/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Other.Algebra.DeRham.KaehlerWedge
public import Mathlib.Data.Complex.Basic

/-!
# Alternation and balancing for wedges of Kähler differentials

The Kähler wedge constructed from the generators-and-relations de Rham model is alternating
and balanced over the coefficient algebra.  These properties are useful when a cotangent module
is generated by one differential.
-/

@[expose] public noncomputable section

namespace Algebra.DeRham

universe u

variable (R A : Type u) [CommRing R] [CommRing A] [Algebra R A]

/-- Swapping the two differential entries of a degree-two symbol changes its sign. -/
theorem mk_two_swap (a b d : A) :
    mk R A 2 a ![b, d] = -mk R A 2 a ![d, b] := by
  have h := mk_alt R A 2 a ![b + d, b + d] (0 : Fin 2) (1 : Fin 2)
    (by simp) (by decide)
  simp only [show ![b + d, b + d] =
      Function.update (![0, b + d] : Fin 2 → A) 0 (b + d) by
        funext i; fin_cases i <;> simp,
    mk_diff_add] at h
  have hb : Function.update (![0, b + d] : Fin 2 → A) 0 b = ![b, b + d] := by
    funext i
    fin_cases i <;> simp
  have hd : Function.update (![0, b + d] : Fin 2 → A) 0 d = ![d, b + d] := by
    funext i
    fin_cases i <;> simp
  rw [hb, hd] at h
  rw [show ![b, b + d] =
      Function.update (![b, 0] : Fin 2 → A) 1 (b + d) by
        funext i; fin_cases i <;> simp,
    mk_diff_add] at h
  rw [show ![d, b + d] =
      Function.update (![d, 0] : Fin 2 → A) 1 (b + d) by
        funext i; fin_cases i <;> simp,
    mk_diff_add] at h
  have hbb' : Function.update (![b, 0] : Fin 2 → A) 1 b = ![b, b] := by
    funext i
    fin_cases i <;> simp
  have hbd : Function.update (![b, 0] : Fin 2 → A) 1 d = ![b, d] := by
    funext i
    fin_cases i <;> simp
  have hdb : Function.update (![d, 0] : Fin 2 → A) 1 b = ![d, b] := by
    funext i
    fin_cases i <;> simp
  have hdd' : Function.update (![d, 0] : Fin 2 → A) 1 d = ![d, d] := by
    funext i
    fin_cases i <;> simp
  rw [hbb', hbd, hdb, hdd'] at h
  have hbb : mk R A 2 a ![b, b] = 0 :=
    mk_alt R A 2 a ![b, b] (0 : Fin 2) (1 : Fin 2) (by simp) (by decide)
  have hdd : mk R A 2 a ![d, d] = 0 :=
    mk_alt R A 2 a ![d, d] (0 : Fin 2) (1 : Fin 2) (by simp) (by decide)
  rw [hbb, hdd, zero_add, add_zero] at h
  exact eq_neg_of_add_eq_zero_left h

/-- The Kähler wedge is balanced over the coefficient algebra. -/
theorem kaehlerWedge_balance (a : A) (w z : KaehlerDifferential R A) :
    kaehlerWedge R A (a • w) z = kaehlerWedge R A w (a • z) := by
  obtain ⟨v, rfl⟩ := KaehlerDifferential.linearCombination_surjective R A w
  obtain ⟨u, rfl⟩ := KaehlerDifferential.linearCombination_surjective R A z
  induction v using Finsupp.induction with
  | zero => simp
  | single_add b c v hb hc ih =>
      simp only [map_add, smul_add, ih, LinearMap.add_apply]
      congr 1
      clear ih
      induction u using Finsupp.induction with
      | zero => simp
      | single_add d e u hd he ih' =>
          simp only [map_add, smul_add, ih']
          congr 1
          simp only [Finsupp.linearCombination_single]
          rw [smul_smul, smul_smul,
            kaehlerWedge_smul_D_smul_D,
            kaehlerWedge_smul_D_smul_D]
          congr 1
          ring

/-- The Kähler wedge is skew-symmetric. -/
theorem kaehlerWedge_swap (w z : KaehlerDifferential R A) :
    kaehlerWedge R A w z = -kaehlerWedge R A z w := by
  obtain ⟨v, rfl⟩ := KaehlerDifferential.linearCombination_surjective R A w
  obtain ⟨u, rfl⟩ := KaehlerDifferential.linearCombination_surjective R A z
  induction v using Finsupp.induction with
  | zero => simp
  | single_add b a v hb ha ih =>
      simp only [map_add, LinearMap.add_apply, ih, neg_add_rev]
      rw [add_comm]
      congr 1
      clear ih
      induction u using Finsupp.induction with
      | zero => simp
      | single_add d c u hd hc ih' =>
          simp only [map_add, LinearMap.add_apply, ih', neg_add_rev]
          rw [add_comm]
          congr 1
          simp only [Finsupp.linearCombination_single]
          rw [kaehlerWedge_smul_D_smul_D,
            kaehlerWedge_smul_D_smul_D, mul_comm]
          exact mk_two_swap R A (c * a) b d

set_option maxHeartbeats 600000 in
/-- Over the complex numbers, two coefficient multiples of the same Kähler differential have
zero wedge. -/
theorem complex_kaehlerWedge_smul_self
    (B : Type) [CommRing B] [Algebra ℂ B]
    (a b : B) (w : KaehlerDifferential ℂ B) :
    kaehlerWedge ℂ B (a • w) (b • w) = 0 := by
  let y := kaehlerWedge ℂ B ((b * a) • w) w
  have hxy : kaehlerWedge ℂ B (a • w) (b • w) = y := by
    rw [← kaehlerWedge_balance ℂ B b (a • w) w, smul_smul]
  have hy : y = -y := by
    have hs := kaehlerWedge_swap ℂ B ((b * a) • w) w
    have hb := kaehlerWedge_balance ℂ B (b * a) w w
    exact hs.trans (congrArg Neg.neg hb.symm)
  have htwo : (2 : ℂ) • y = 0 := by
    calc
      (2 : ℂ) • y = y + y := two_smul ℂ y
      _ = -y + y := congrArg (fun q ↦ q + y) hy
      _ = 0 := neg_add_cancel y
  have hhalf := congrArg (fun q ↦ ((2 : ℂ)⁻¹) • q) htwo
  have hyzero : y = 0 := by
    simpa [smul_smul] using hhalf
  rw [hxy, hyzero]

/-- If the Kähler differential module of a complex algebra is generated by one element, every
degree-two form in the generators-and-relations de Rham model vanishes. -/
theorem complex_twoForm_eq_zero_of_cotangent_generator
    (B : Type) [CommRing B] [Algebra ℂ B]
    (ω : KaehlerDifferential ℂ B)
    (hgen : ∀ w : KaehlerDifferential ℂ B, ∃ a : B, a • ω = w)
    (η : Form ℂ B 2) : η = 0 := by
  obtain ⟨r, rfl⟩ := Submodule.mkQ_surjective (relations ℂ B 2) η
  induction r using Finsupp.induction with
  | zero => rfl
  | single_add g c r hg hc ih =>
      rw [map_add, ih, add_zero]
      change Submodule.Quotient.mk (Finsupp.single g c) = 0
      rw [show Finsupp.single g c = c • Finsupp.single g 1 by simp,
        Submodule.Quotient.mk_smul]
      apply smul_eq_zero.mpr
      right
      change mk ℂ B 2 g.1 g.2 = 0
      have hv : g.2 = ![g.2 0, g.2 1] := by
        funext i
        fin_cases i <;> rfl
      rw [hv]
      have hkw := kaehlerWedge_smul_D_smul_D ℂ B g.1 (g.2 0) 1 (g.2 1)
      rw [mul_one] at hkw
      rw [← hkw]
      obtain ⟨a, ha⟩ := hgen (KaehlerDifferential.D ℂ B (g.2 0))
      obtain ⟨b, hb⟩ := hgen (KaehlerDifferential.D ℂ B (g.2 1))
      rw [← ha, ← hb, smul_smul, one_smul]
      exact complex_kaehlerWedge_smul_self B (g.1 * a) b ω

end Algebra.DeRham
