/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module  -- shake: keep-all --deprecated_module: ignore

public import HodgeConjecture.Definitions
public import HodgeConjecture.Definitions.Algebra.DeRham.Basic
public import HodgeConjecture.Definitions.AlgebraicGeometry.AlgebraicCycleSupport
public import HodgeConjecture.Definitions.AlgebraicGeometry.AnalyticDifferentialForms
public import HodgeConjecture.Definitions.AlgebraicGeometry.ChowGroup
public import HodgeConjecture.Definitions.AlgebraicGeometry.CohomologyWithSupport
public import HodgeConjecture.Definitions.AlgebraicGeometry.ComplexAnalyticSheaf
public import HodgeConjecture.Definitions.AlgebraicGeometry.CycleClass
public import HodgeConjecture.Definitions.AlgebraicGeometry.HodgeFiltration
public import HodgeConjecture.Definitions.AlgebraicGeometry.HolomorphicDeRham
public import HodgeConjecture.Definitions.AlgebraicGeometry.Points
public import HodgeConjecture.Definitions.AlgebraicGeometry.ProjectiveSpace
public import HodgeConjecture.Definitions.AlgebraicTopology.SingularCohomology
public import HodgeConjecture.Definitions.LinearAlgebra.HodgeStructure
public import HodgeConjecture.Lemmas
public import HodgeConjecture.Lemmas.Algebra.Homology.ShiftedExact
public import HodgeConjecture.Lemmas.Algebra.Homology.StupidTruncation
public import HodgeConjecture.Lemmas.AlgebraicGeometry.ComplexAffineScheme
public import HodgeConjecture.Lemmas.AlgebraicGeometry.ComplexAffineSpace
public import HodgeConjecture.Lemmas.AlgebraicGeometry.ComplexEtale
public import HodgeConjecture.Lemmas.AlgebraicGeometry.ComplexLocalization
public import HodgeConjecture.Lemmas.AlgebraicGeometry.ComplexManifold
public import HodgeConjecture.Lemmas.AlgebraicGeometry.ComplexOpen
public import HodgeConjecture.Lemmas.AlgebraicGeometry.ComplexStandardEtale
public import HodgeConjecture.Lemmas.AlgebraicGeometry.HolomorphicPoincare
public import HodgeConjecture.Lemmas.AlgebraicGeometry.OrderOfVanishing
public import HodgeConjecture.Lemmas.AlgebraicGeometry.SmoothComplexCoordinates
public import HodgeConjecture.Lemmas.AlgebraicGeometry.SmoothLocus
public import HodgeConjecture.Lemmas.AlgebraicTopology.ChartLocalFundamentalClass
public import HodgeConjecture.Lemmas.AlgebraicTopology.ComplexOrientation
public import HodgeConjecture.Lemmas.AlgebraicTopology.LocalFundamentalClass
public import HodgeConjecture.Lemmas.Analysis.Calculus.DifferentialForm.Poincare
public import HodgeConjecture.Mathlib.Algebra.Category.Grp.Basic
public import HodgeConjecture.Mathlib.Algebra.Category.ModuleCat.Basic
public import HodgeConjecture.Mathlib.Algebra.Category.Ring.Basic
public import HodgeConjecture.Mathlib.CategoryTheory.ConcreteCategory.Notation
public import HodgeConjecture.Mathlib.Topology.Category.TopCat.Basic
public import HodgeConjecture.Other
public import HodgeConjecture.Other.Algebra.Category.ModuleCat.Presheaf.ExteriorPower
public import HodgeConjecture.Other.Algebra.DeRham.Complex
public import HodgeConjecture.Other.Algebra.Homology.DualExact
public import HodgeConjecture.Other.Algebra.PolynomialCatenary
public import HodgeConjecture.Other.AlgebraicGeometry.BettiCohomologyWithSupportComparison
public import HodgeConjecture.Other.AlgebraicGeometry.BettiGlobalSectionsAdditivity
public import HodgeConjecture.Other.AlgebraicGeometry.BettiGlobalSectionsComparison
public import HodgeConjecture.Other.AlgebraicGeometry.BettiSheafComparison
public import HodgeConjecture.Other.AlgebraicGeometry.BettiSupportConeComparison
public import HodgeConjecture.Other.AlgebraicGeometry.BettiSupportSingularComparison
public import HodgeConjecture.Other.AlgebraicGeometry.BettiSupportSingularGlobalComparison
public import HodgeConjecture.Other.AlgebraicGeometry.BettiSupportSingularHypercohomologyComparison
public import HodgeConjecture.Other.AlgebraicGeometry.BettiSupportSingularNaturality
public import HodgeConjecture.Other.AlgebraicGeometry.ComplexAnalyticMaps
public import HodgeConjecture.Other.AlgebraicGeometry.ComplexSingularComparison
public import HodgeConjecture.Other.AlgebraicGeometry.CycleClassDimension
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentAnalyticEmbedding
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentClosedPointDimension
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentDimension
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentLocalGenerator
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentMaximalCodimensionPurity
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentNormalCoordinates
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentNormalGeometry
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentPointPurity
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentPurity
public import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentRegularImmersion
public import HodgeConjecture.Other.AlgebraicGeometry.HodgeCodimensionZero
public import HodgeConjecture.Other.AlgebraicGeometry.ProjectiveAnalytification
public import HodgeConjecture.Other.AlgebraicGeometry.ProjectiveAnalytificationConnected
public import HodgeConjecture.Other.AlgebraicGeometry.ProjectiveAnalytificationHausdorff
public import HodgeConjecture.Other.AlgebraicGeometry.ProjectiveAnalytificationLocallyContractible
public import HodgeConjecture.Other.AlgebraicGeometry.ProjectiveAnalytificationParacompact
public import HodgeConjecture.Other.AlgebraicGeometry.ProjectiveAnalytificationSecondCountable
public import HodgeConjecture.Other.AlgebraicGeometry.ProjectiveSingularCoefficientBaseChange
public import HodgeConjecture.Other.AlgebraicGeometry.RationalCohomologyZero
public import HodgeConjecture.Other.AlgebraicGeometry.SingularCycleClass
public import HodgeConjecture.Other.AlgebraicGeometry.SmoothCatenaryDimension
public import HodgeConjecture.Other.AlgebraicGeometry.SmoothDimensionFormula
public import HodgeConjecture.Other.AlgebraicGeometry.SmoothPointwiseDimension
public import HodgeConjecture.Other.AlgebraicGeometry.SmoothRegularLocal
public import HodgeConjecture.Other.AlgebraicTopology.BoundedBelowFlasqueComplex
public import HodgeConjecture.Other.AlgebraicTopology.CechNerveEvaluation
public import HodgeConjecture.Other.AlgebraicTopology.ChartLocalFundamentalClassGenerator
public import HodgeConjecture.Other.AlgebraicTopology.ConstantSheafDegreeZero
public import HodgeConjecture.Other.AlgebraicTopology.EuclideanLocalHomology
public import HodgeConjecture.Other.AlgebraicTopology.FiniteGoodCoverHomology
public import HodgeConjecture.Other.AlgebraicTopology.FiniteGoodCoverNerveHomology
public import HodgeConjecture.Other.AlgebraicTopology.FirstQuadrantColumnFiltration
public import HodgeConjecture.Other.AlgebraicTopology.FirstQuadrantColumnFiltrationQuotient
public import HodgeConjecture.Other.AlgebraicTopology.FirstQuadrantColumnFiltrationShortExact
public import HodgeConjecture.Other.AlgebraicTopology.FirstQuadrantRowwiseTotalization
public import HodgeConjecture.Other.AlgebraicTopology.FirstQuadrantTotalComplex
public import HodgeConjecture.Other.AlgebraicTopology.FlasqueAcyclic
public import HodgeConjecture.Other.AlgebraicTopology.FlasqueQuasiIsoGlobalSections
public import HodgeConjecture.Other.AlgebraicTopology.GlobalSingularRestriction
public import HodgeConjecture.Other.AlgebraicTopology.HorizontalTotalHomotopy
public import HodgeConjecture.Other.AlgebraicTopology.InjectiveFlasque
public import HodgeConjecture.Other.AlgebraicTopology.IntegralCechTotalAugmentation
public import HodgeConjecture.Other.AlgebraicTopology.LocalFundamentalClassGenerator
public import HodgeConjecture.Other.AlgebraicTopology.MappingConeQuasiIso
public import HodgeConjecture.Other.AlgebraicTopology.OpenCoverOrderedCechBicomplex
public import HodgeConjecture.Other.AlgebraicTopology.OrderedCechNormalization
public import HodgeConjecture.Other.AlgebraicTopology.OrderedCechRealization
public import HodgeConjecture.Other.AlgebraicTopology.OrderedCechTupleAlgebra
public import HodgeConjecture.Other.AlgebraicTopology.PuncturedEuclideanFundamentalClass
public import HodgeConjecture.Other.AlgebraicTopology.RelativeCochainCone
public import HodgeConjecture.Other.AlgebraicTopology.RelativePairExcision
public import HodgeConjecture.Other.AlgebraicTopology.SingularAffineSubdivision
public import HodgeConjecture.Other.AlgebraicTopology.SingularAffineSubdivisionIteration
public import HodgeConjecture.Other.AlgebraicTopology.SingularAffineSubdivisionMesh
public import HodgeConjecture.Other.AlgebraicTopology.SingularAffineSubdivisionPrism
public import HodgeConjecture.Other.AlgebraicTopology.SingularAffineSubdivisionRelativeMesh
public import HodgeConjecture.Other.AlgebraicTopology.SingularAffineSubdivisionSmall
public import HodgeConjecture.Other.AlgebraicTopology.SingularAffineSubdivisionSmallPrism
public import HodgeConjecture.Other.AlgebraicTopology.SingularAffineSubdivisionSupport
public import HodgeConjecture.Other.AlgebraicTopology.SingularBarycentricAllDegrees
public import HodgeConjecture.Other.AlgebraicTopology.SingularBarycentricChains
public import HodgeConjecture.Other.AlgebraicTopology.SingularBarycentricHomotopy
public import HodgeConjecture.Other.AlgebraicTopology.SingularBarycentricOuterFaces
public import HodgeConjecture.Other.AlgebraicTopology.SingularCochainCohomology
public import HodgeConjecture.Other.AlgebraicTopology.SingularCochainFlasque
public import HodgeConjecture.Other.AlgebraicTopology.SingularCochainSheaf
public import HodgeConjecture.Other.AlgebraicTopology.SingularCochainSheafFlasque
public import HodgeConjecture.Other.AlgebraicTopology.SingularCoefficientBaseChange
public import HodgeConjecture.Other.AlgebraicTopology.SingularCohomologyZero
public import HodgeConjecture.Other.AlgebraicTopology.SingularCohomologyZeroConnectedness
public import HodgeConjecture.Other.AlgebraicTopology.SingularContractible
public import HodgeConjecture.Other.AlgebraicTopology.SingularContractibleMapQuasiIso
public import HodgeConjecture.Other.AlgebraicTopology.SingularCoverSmall
public import HodgeConjecture.Other.AlgebraicTopology.SingularCoverSmallPresentation
public import HodgeConjecture.Other.AlgebraicTopology.SingularCoverSmallProjective
public import HodgeConjecture.Other.AlgebraicTopology.SingularCoverSmallQuasiIso
public import HodgeConjecture.Other.AlgebraicTopology.SingularExcisionField
public import HodgeConjecture.Other.AlgebraicTopology.SingularExcisionOpenCover
public import HodgeConjecture.Other.AlgebraicTopology.SingularOpenCoverLebesgue
public import HodgeConjecture.Other.AlgebraicTopology.SingularOpenCoverSmallChains
public import HodgeConjecture.Other.AlgebraicTopology.SingularStandardSimplexCone
public import HodgeConjecture.Other.AlgebraicTopology.SingularSubdivision
public import HodgeConjecture.Other.AlgebraicTopology.SingularSubdivisionCochainSheaf
public import HodgeConjecture.Other.AlgebraicTopology.SingularSubdivisionIteration
public import HodgeConjecture.Other.AlgebraicTopology.StandardSimplexSingularComparison
public import HodgeConjecture.Other.AlgebraicTopology.StandardSphereAffineBoundary
public import HodgeConjecture.Other.AlgebraicTopology.StandardSphereSimplicialHomology
public import HodgeConjecture.Other.CommutativeAlgebra.RegularLocalQuotientKernel
public import HodgeConjecture.Statement
