name = "HodgeConjecture"
keywords = ["math", "algebraic-geometry", "hodge-theory"]
defaultTargets = ["HodgeConjecture", "Other"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.33.0"

[[lean_lib]]
name = "HodgeConjecture"

[[lean_lib]]
name = "Other"

[[lean_lib]]
name = "Challenge"
roots = ["Challenge.Constructed"]

[[lean_lib]]
name = "HodgeGuide"

[[lean_exe]]
name = "hodge-guide"
root = "HodgeGuideMain"
