/-
Copyright 2026 The Formal Conjectures Authors.
Licensed under the Apache License, Version 2.0.
-/
module

public import HodgeConjecture.Definitions.AlgebraicGeometry.Cycle.ClassSpan
public import Other.AlgebraicGeometry.Hodge.Filtration

/-!
# The codimension-zero comparison line

The previous conclusions in this file depended on a degree-zero computation formulated through
the obsolete SmallShiftedHom presentation. Only the representation-independent comparison line
is retained.
-/

@[expose] public noncomputable section

open CategoryTheory

namespace AlgebraicGeometry.ComplexPoint

variable (X : Over (Spec ↧ℂ))

/-- The comparison line generated by the degree-zero rational cohomology unit. -/
def codimensionZeroCycleClassSpan : Submodule ℚ (H^0(X; ℚ)) :=
  Submodule.span ℚ {fieldCohomologyUnit ℚ X}

/-- The codimension-zero comparison span is the unit line. -/
lemma codimensionZeroCycleClassSpan_eq_span_unit :
    codimensionZeroCycleClassSpan X = Submodule.span ℚ {fieldCohomologyUnit ℚ X} :=
  rfl

end AlgebraicGeometry.ComplexPoint
