/-
Copyright 2026 The Formal Conjectures Authors.
Licensed under the Apache License, Version 2.0.
-/
module

public import HodgeConjecture.Definitions.AlgebraicGeometry.Cycle.ClassSpan
import Other.AlgebraicGeometry.Cycle.Codimension
public import Other.AlgebraicGeometry.Hodge.CodimensionZero
public import Other.AlgebraicGeometry.Cycle.FundamentalClass

/-!
# Representation-independent codimension-zero cycle calculations

The comparison with the cohomological unit is deferred until degree-zero hypercohomology is
computed through derived global sections.
-/

@[expose] public noncomputable section

open CategoryTheory Order TopologicalSpace

namespace AlgebraicGeometry.ComplexPoint

open Point

variable (X : Over (Spec ↧ℂ)) [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom]

local instance : QuasiSeparatedSpace X.left :=
  quasiSeparatedSpace_of_quasiSeparated X.hom

omit [Smooth X.hom] [IsProjective X.hom] in
/-- The codimension-zero coheight certificate of the generic point. -/
theorem coheight_genericPoint_eq_zero :
    coheight (genericPoint X.left) = ((0 : ℕ) : ℕ∞) := by
  rw [Nat.cast_zero]
  exact Order.IsMax.coheight_eq_zero isMax_top

/-- The constructed codimension-zero algebraic cycle-class span is generated by the generic
point: no other point of an integral scheme has coheight zero. -/
theorem algebraicCycleClassSpan_zero_eq_span_genericPoint :
    algebraicCycleClassSpan X 0 =
      Submodule.span ℚ {cycleComponentSheafClass X (genericPoint X.left)
        (coheight_genericPoint_eq_zero X)} := by
  unfold algebraicCycleClassSpan
  refine le_antisymm (iSup_le fun x ↦ iSup_le fun hx ↦ ?_)
    (le_iSup_of_le (genericPoint X.left)
      (le_iSup_of_le (coheight_genericPoint_eq_zero X) le_rfl))
  obtain rfl := eq_genericPoint_of_coheight_zero x (by simpa using hx)
  exact le_rfl

end AlgebraicGeometry.ComplexPoint
