/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.CategoryTheory.Sites.SheafCohomology.Basic
public import Mathlib.CategoryTheory.Sites.MayerVietorisSquare
public import Mathlib.CategoryTheory.Abelian.CommSq
public import Mathlib.CategoryTheory.Abelian.DiagramLemmas.KernelCokernelComp
public import Mathlib.Algebra.Homology.DerivedCategory.Ext.ExactSequences

/-!
# Sheaf cohomology of a pair

Let `f : U ⟶ V` be a monomorphism in a site `(C, J)`, and let `ℤ[U] ⟶ ℤ[V]` be the induced
morphism of free abelian sheaves. The cohomology of the pair `(V, U)` with coefficients in an
abelian sheaf `F` is `Ext (ℤ[V, U]) F n`, where `ℤ[V, U]` is the cokernel of `ℤ[U] ⟶ ℤ[V]`.
The short exact sequence `0 → ℤ[U] → ℤ[V] → ℤ[V, U] → 0` gives the long exact sequence
`… → H^n(V, U; F) → H^n(V; F) → H^n(U; F) → H^(n+1)(V, U; F) → …`.
-/

@[expose] public noncomputable section

open CategoryTheory Limits Abelian Opposite

universe w v u

namespace CategoryTheory.Sheaf

variable {C : Type u} [Category.{v} C] (J : GrothendieckTopology C)
  [HasSheafify J AddCommGrpCat.{v}]

/-- `U ↦ ℤ[U]`, the free abelian sheaf generated by the presheaf of sets represented by `U`. -/
def freeAbelianSheaf : C ⥤ Sheaf J AddCommGrpCat.{v} :=
  yoneda ⋙ (Functor.whiskeringRight _ _ _).obj AddCommGrpCat.free ⋙ presheafToSheaf J _

instance {U V : C} (f : U ⟶ V) [Mono f] : Mono ((freeAbelianSheaf J).map f) := by
  dsimp [freeAbelianSheaf]; infer_instance

variable {J}

/-- The section `[𝟙 U]` of `ℤ[U]` over `U`. -/
def freeAbelianSheafGenerator (U : C) : ((freeAbelianSheaf J).obj U).obj.obj (op U) :=
  (toSheafify J (yoneda.obj U ⋙ AddCommGrpCat.free)).app (op U) (FreeAbelianGroup.of (𝟙 U))

/-- A morphism `ℤ[U] ⟶ F` is determined by the image of `[𝟙 U]`, a section of `F` over `U`. -/
def freeAbelianSheafHomAddEquiv (U : C) (F : Sheaf J AddCommGrpCat.{v}) :
    ((freeAbelianSheaf J).obj U ⟶ F) ≃+ F.obj.obj (op U) where
  toEquiv := ((sheafificationAdjunction J _).homEquiv _ _).trans <|
    ((Adjunction.whiskerRight Cᵒᵖ AddCommGrpCat.adj).homEquiv _ _).trans yonedaEquiv
  map_add' _ _ := rfl

lemma freeAbelianSheafHomAddEquiv_apply (U : C) (F : Sheaf J AddCommGrpCat.{v})
    (φ : (freeAbelianSheaf J).obj U ⟶ F) :
    freeAbelianSheafHomAddEquiv U F φ = φ.hom.app (op U) (freeAbelianSheafGenerator U) := rfl

lemma freeAbelianSheafHomAddEquiv_comp {U : C} {F G : Sheaf J AddCommGrpCat.{v}}
    (φ : (freeAbelianSheaf J).obj U ⟶ F) (g : F ⟶ G) :
    freeAbelianSheafHomAddEquiv U G (φ ≫ g) =
      g.hom.app (op U) (freeAbelianSheafHomAddEquiv U F φ) := rfl

lemma freeAbelianSheafHomAddEquiv_map_comp {U V : C} (f : U ⟶ V) (F : Sheaf J AddCommGrpCat.{v})
    (φ : (freeAbelianSheaf J).obj V ⟶ F) :
    freeAbelianSheafHomAddEquiv U F ((freeAbelianSheaf J).map f ≫ φ) =
      F.obj.map f.op (freeAbelianSheafHomAddEquiv V F φ) := by
  have e1 := Adjunction.homEquiv_naturality_left (sheafificationAdjunction J AddCommGrpCat.{v})
    (((Functor.whiskeringRight _ _ _).obj AddCommGrpCat.free).map (yoneda.map f)) φ
  have e2 := Adjunction.homEquiv_naturality_left (Adjunction.whiskerRight Cᵒᵖ AddCommGrpCat.adj)
    (yoneda.map f) ((sheafificationAdjunction J _).homEquiv _ _ φ)
  have e3 := yonedaEquiv_naturality
    ((Adjunction.whiskerRight Cᵒᵖ AddCommGrpCat.adj).homEquiv _ _
      ((sheafificationAdjunction J _).homEquiv _ _ φ)) f
  exact (congrArg yonedaEquiv ((congrArg _ e1).trans e2)).trans e3.symm

/-- `ℤ[V, U]`, the cokernel of `ℤ[U] ⟶ ℤ[V]` for a monomorphism `f : U ⟶ V`. -/
abbrev pairSheaf {U V : C} (f : U ⟶ V) : Sheaf J AddCommGrpCat.{v} :=
  cokernel ((freeAbelianSheaf J).map f)

/-- The short complex `ℤ[U] ⟶ ℤ[V] ⟶ ℤ[V, U]`. -/
def pairShortComplex {U V : C} (f : U ⟶ V) : ShortComplex (Sheaf J AddCommGrpCat.{v}) :=
  ShortComplex.cokernelSequence ((freeAbelianSheaf J).map f)

lemma pairShortComplex_shortExact {U V : C} (f : U ⟶ V) [Mono f] :
    (pairShortComplex (J := J) f).ShortExact where
  exact := ShortComplex.cokernelSequence_exact _
  mono_f := by
    change Mono ((freeAbelianSheaf J).map f)
    infer_instance
  epi_g := by dsimp [pairShortComplex]; infer_instance

/-- A morphism `ℤ[V, U] ⟶ G` is a section of `G` over `V` whose restriction to `U` is zero. -/
def pairSheafHomAddEquiv {U V : C} (f : U ⟶ V) (G : Sheaf J AddCommGrpCat.{v}) :
    (pairSheaf (J := J) f ⟶ G) ≃+ (G.obj.map f.op).hom.ker where
  toFun φ := ⟨freeAbelianSheafHomAddEquiv V G (cokernel.π _ ≫ φ), by
    rw [AddMonoidHom.mem_ker, ← freeAbelianSheafHomAddEquiv_map_comp, cokernel.condition_assoc,
      zero_comp, map_zero]⟩
  invFun s := cokernel.desc _ ((freeAbelianSheafHomAddEquiv V G).symm s.1) (by
    apply (freeAbelianSheafHomAddEquiv U G).injective
    rw [freeAbelianSheafHomAddEquiv_map_comp, AddEquiv.apply_symm_apply, map_zero]
    exact s.2)
  left_inv φ := by
    apply (cancel_epi (cokernel.π ((freeAbelianSheaf J).map f))).1
    rw [cokernel.π_desc, AddEquiv.symm_apply_apply]
  right_inv s := by
    ext
    simp only [cokernel.π_desc, AddEquiv.apply_symm_apply]
  map_add' φ ψ := by
    ext
    simp only [Preadditive.comp_add, map_add, AddSubgroup.coe_add]

/-- The map `ℤ[V', U'] ⟶ ℤ[V, U]` induced by a commutative square `U' ⟶ U`, `V' ⟶ V`. -/
def pairSheafMap {U V U' V' : C} (f : U ⟶ V) (f' : U' ⟶ V') (a : U' ⟶ U) (b : V' ⟶ V)
    (w : f' ≫ b = a ≫ f) : pairSheaf (J := J) f' ⟶ pairSheaf (J := J) f :=
  cokernel.map _ _ ((freeAbelianSheaf J).map a) ((freeAbelianSheaf J).map b)
    (by rw [← Functor.map_comp, ← Functor.map_comp, w])

lemma pairSheafHomAddEquiv_pairSheafMap_comp {U V U' V' : C} (f : U ⟶ V) (f' : U' ⟶ V')
    (a : U' ⟶ U) (b : V' ⟶ V) (w : f' ≫ b = a ≫ f) (G : Sheaf J AddCommGrpCat.{v})
    (φ : pairSheaf (J := J) f ⟶ G) :
    (pairSheafHomAddEquiv f' G (pairSheafMap f f' a b w ≫ φ) : G.obj.obj (op V')) =
      G.obj.map b.op (pairSheafHomAddEquiv f G φ) := by
  change freeAbelianSheafHomAddEquiv V' G (cokernel.π _ ≫ pairSheafMap f f' a b w ≫ φ) =
    G.obj.map b.op (freeAbelianSheafHomAddEquiv V G (cokernel.π _ ≫ φ))
  rw [pairSheafMap, cokernel.π_desc_assoc, Category.assoc, freeAbelianSheafHomAddEquiv_map_comp]

def pairNestedShortComplex {W U V : C} (f : W ⟶ U) (g : U ⟶ V) :
    ShortComplex (Sheaf J AddCommGrpCat.{v}) :=
  ShortComplex.mk
    (pairSheafMap (J := J) (f ≫ g) f (𝟙 _) g (by simp))
    (pairSheafMap (J := J) g (f ≫ g) f (𝟙 _) (by simp))
    (by
      apply (cancel_epi (cokernel.π ((freeAbelianSheaf J).map f))).1
      dsimp [pairSheafMap, cokernel.map]
      simp)

set_option maxHeartbeats 800000 in
set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency.types false in
lemma pairNestedShortComplex_shortExact {W U V : C} (f : W ⟶ U) (g : U ⟶ V)
    [Mono f] [Mono g] :
    (pairNestedShortComplex (J := J) f g).ShortExact := by
  let F := freeAbelianSheaf J
  have hmono : Mono (cokernel.map (F.map f) (F.map f ≫ F.map g) (𝟙 _) (F.map g)
      (by simp)) := by
    apply Abelian.mono_cokernel_map_of_isPullback
    refine IsPullback.of_vert_isIso_mono (fst := F.map f) (snd := 𝟙 _)
      (f := F.map g) (g := F.map f ≫ F.map g) ?_
    exact ⟨by simp⟩
  have hepi : Epi (cokernel.map (F.map f ≫ F.map g) (F.map g) (F.map f) (𝟙 _)
      (by simp)) := by
    dsimp [cokernel.map]
    apply cokernel.desc_epi
  let S : ShortComplex (Sheaf J AddCommGrpCat.{v}) := ShortComplex.mk
    (cokernel.map (F.map f) (F.map f ≫ F.map g) (𝟙 _) (F.map g) (by simp))
    (cokernel.map (F.map f ≫ F.map g) (F.map g) (F.map f) (𝟙 _) (by simp))
    (by
      apply (cancel_epi (cokernel.π (F.map f))).1
      dsimp [cokernel.map]
      simp)
  let h : F.map f ≫ F.map g = F.map (f ≫ g) := (F.map_comp f g).symm
  let e₂ : cokernel (F.map f ≫ F.map g) ≅ cokernel (F.map (f ≫ g)) := cokernelIsoOfEq h
  let e : S ≅
      pairNestedShortComplex (J := J) f g :=
    ShortComplex.isoMk (Iso.refl _) e₂ (Iso.refl _) (by
      apply (cancel_epi (cokernel.π (F.map f))).1
      dsimp [S, pairNestedShortComplex, e₂, h, pairSheafMap, cokernel.map]
      dsimp [F]
      simp only [Category.id_comp]
      rw [cokernel.π_desc, cokernel.π_desc_assoc]
      simp [Category.assoc, π_comp_cokernelIsoOfEq_hom]) (by
      apply (cancel_epi (cokernel.π (F.map f ≫ F.map g))).1
      dsimp [S, pairNestedShortComplex, e₂, h, pairSheafMap, cokernel.map]
      dsimp [F]
      simp [Category.assoc, cokernelIsoOfEq_hom_comp_desc h])
  exact ShortComplex.shortExact_of_iso e
    { exact := (kernelCokernelCompSequence_exact (F.map f) (F.map g)).exact 3 (by omega)
      mono_f := hmono
      epi_g := hepi }

variable [HasExt.{w} (Sheaf J AddCommGrpCat.{v})]

/-- `H^n(V, U; F)`, the cohomology of the pair `(V, U)` with coefficients in `F`. -/
abbrev relH (F : Sheaf J AddCommGrpCat.{v}) (n : ℕ) {U V : C} (f : U ⟶ V) : Type w :=
  Ext (pairSheaf (J := J) f) F n

namespace relH

variable (F : Sheaf J AddCommGrpCat.{v}) {U V : C} (f : U ⟶ V)

/-- The map `H^n(V, U; F) → H^n(V; F)`. -/
def forget (n : ℕ) : relH F n f →+ F.H' n V :=
  (Ext.mk₀ (cokernel.π ((freeAbelianSheaf J).map f))).precomp F (zero_add n)

/-- The connecting map `H^n(U; F) → H^(n+1)(V, U; F)`. -/
def δ [Mono f] (n₀ n₁ : ℕ) (h : 1 + n₀ = n₁) : F.H' n₀ U →+ relH F n₁ f :=
  (pairShortComplex_shortExact f).extClass.precomp F h

/-- The map on cohomology of the pair induced by a morphism of sheaves. -/
def map {F G : Sheaf J AddCommGrpCat.{v}} (g : F ⟶ G) (n : ℕ) : relH F n f →+ relH G n f :=
  (Ext.mk₀ g).postcomp _ (add_zero n)

/-- The map `H^n(V, U; F) → H^n(V', U'; F)` induced by a map of pairs `(V', U') → (V, U)`. -/
def restrict {U' V' : C} (f' : U' ⟶ V') (a : U' ⟶ U) (b : V' ⟶ V) (w : f' ≫ b = a ≫ f) (n : ℕ) :
    relH F n f →+ relH F n f' :=
  (Ext.mk₀ (pairSheafMap f f' a b w)).precomp F (zero_add n)

/-- The long exact sequence of the pair `(V, U)`. -/
lemma sequence_exact [Mono f] (n₀ n₁ : ℕ) (h : 1 + n₀ = n₁) :
    (Ext.contravariantSequence (pairShortComplex_shortExact (J := J) f) F n₀ n₁ h).Exact :=
  Ext.contravariantSequence_exact _ _ _ _ _

lemma nestedSequence_exact {W U V : C} (f : W ⟶ U) (g : U ⟶ V) [Mono f] [Mono g]
    (n₀ n₁ : ℕ) (h : 1 + n₀ = n₁) :
    (Ext.contravariantSequence (pairNestedShortComplex_shortExact (J := J) f g) F n₀ n₁ h).Exact :=
  Ext.contravariantSequence_exact _ _ _ _ _

end relH

section Terminal

variable {T : C} (hT : IsTerminal T)

/-- `ℤ[T] ≅ ℤ` for a terminal object `T`. -/
def freeAbelianSheafTerminalIso :
    (freeAbelianSheaf J).obj T ≅
      (constantSheaf J AddCommGrpCat.{v}).obj (AddCommGrpCat.of (ULift ℤ)) :=
  (presheafToSheaf J _).mapIso <| NatIso.ofComponents
    (fun U =>
      letI : Unique (U.unop ⟶ T) := ⟨⟨hT.from _⟩, fun _ => hT.hom_ext _ _⟩
      ((FreeAbelianGroup.uniqueEquiv (U.unop ⟶ T)).trans AddEquiv.ulift.symm).toAddCommGrpIso)
    (by
      intro U V g
      apply AddCommGrpCat.hom_ext
      apply FreeAbelianGroup.lift_ext
      intro h
      first
        | rfl
        | simp [FreeAbelianGroup.uniqueEquiv, AddCommGrpCat.free_map_coe, FreeAbelianGroup.map_of])

/-- Precomposition with an isomorphism is an additive equivalence of `Ext` groups. -/
def _root_.CategoryTheory.Abelian.Ext.precompAddEquiv {A B : Sheaf J AddCommGrpCat.{v}} (e : A ≅ B)
    (F : Sheaf J AddCommGrpCat.{v}) (n : ℕ) : Ext B F n ≃+ Ext A F n where
  toFun := (Ext.mk₀ e.hom).precomp F (zero_add n)
  invFun := (Ext.mk₀ e.inv).precomp F (zero_add n)
  left_inv x := by simp
  right_inv x := by simp
  map_add' x y := by simp

/-- `H^n(T; F) ≃ H^n(F)` for a terminal object `T`. -/
def H'.addEquivTerminal (F : Sheaf J AddCommGrpCat.{v}) (n : ℕ) : F.H' n T ≃+ F.H n :=
  Ext.precompAddEquiv (freeAbelianSheafTerminalIso hT).symm F n

end Terminal

end CategoryTheory.Sheaf

end
