/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import FormalConjecturesForMathlib.AlgebraicGeometry.ProjectiveSpace
public import FormalConjecturesForMathlib.AlgebraicTopology.SingularCohomology
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
public import Mathlib.AlgebraicGeometry.Noetherian
public import Mathlib.Topology.Instances.Complex
public import Mathlib.Topology.Order

/-!
# Complex points and Betti cohomology

For a scheme over `ℂ`, a complex point is a morphism `Spec ℂ ⟶ X` over `Spec ℂ`. This file
constructs its analytic topology from local regular functions. On an open subscheme `U`, every
section of `𝒪_X(U)` evaluates in `ℂ` at every complex point lying in `U`; these evaluation maps
generate the topology.

Betti homology is then Mathlib's singular homology of this constructed topological space. Betti
cohomology over a field is its linear dual.
-/

@[expose] public section

open CategoryTheory Topology

namespace AlgebraicGeometry

/-- A complex point of `X` over its given structure morphism to `Spec ℂ`. -/
abbrev ComplexPoint (X : Scheme) (structureMap : X ⟶ Spec (.of ℂ)) :=
  {z : Spec (.of ℂ) ⟶ X // z ≫ structureMap = 𝟙 _}

namespace ComplexPoint

variable {X : Scheme} {structureMap : X ⟶ Spec (.of ℂ)}

/-- The scheme point and residue-field embedding corresponding to a complex point. -/
noncomputable def residueData (z : ComplexPoint X structureMap) :
    Σ x : X, X.residueField x ⟶ .of ℂ :=
  Scheme.SpecToEquivOfField ℂ X z.1

/-- The underlying point of the scheme. -/
noncomputable def underlying (z : ComplexPoint X structureMap) : X := z.residueData.1

/-- The complex points whose underlying scheme point lies in `U`. -/
noncomputable def overOpen (U : X.Opens) : Set (ComplexPoint X structureMap) :=
  {z | z.underlying ∈ U}

/-- A complex point whose underlying scheme point lies in `U`.

Using this subtype is preferable whenever a local regular function is evaluated: it records the
domain condition in the type instead of assigning an arbitrary value outside `U`. -/
abbrev OverOpen (U : X.Opens) := {z : ComplexPoint X structureMap // z.underlying ∈ U}

/-- Evaluation of a local regular function on its actual domain. -/
noncomputable def evaluateOnOpen (U : X.Opens) (s : Γ(X, U))
    (z : OverOpen (structureMap := structureMap) U) : ℂ :=
  z.1.residueData.2 (X.evaluation U z.1.residueData.1 z.2 s)

/--
Evaluation of a local regular function at a complex point. Outside the function's domain this is
defined to be zero; all uses in the analytic topology are restricted to `overOpen U`.
-/
noncomputable def evaluate (U : X.Opens) (s : Γ(X, U))
    (z : ComplexPoint X structureMap) : ℂ := by
  classical
  exact if hz : z.residueData.1 ∈ U then
      z.residueData.2 (X.evaluation U z.residueData.1 hz s)
    else 0

lemma evaluate_eq_evaluateOnOpen (U : X.Opens) (s : Γ(X, U))
    (z : OverOpen (structureMap := structureMap) U) :
    evaluate U s z.1 = evaluateOnOpen U s z := by
  have hz : z.1.residueData.1 ∈ U := by
    simpa only [underlying] using z.2
  rw [evaluate, dif_pos hz]
  rfl

/-- Sets obtained by restricting an inverse image of a complex open set to the domain of a local
regular function. -/
noncomputable def analyticSubbasis : Set (Set (ComplexPoint X structureMap)) :=
  {W | ∃ (U : X.Opens) (s : Γ(X, U)) (V : Set ℂ), IsOpen V ∧
    W = overOpen U ∩ evaluate U s ⁻¹' V}

/-- The analytic topology on complex points, generated by evaluation of local regular functions. -/
@[instance_reducible]
noncomputable def analyticTopology : TopologicalSpace (ComplexPoint X structureMap) :=
  TopologicalSpace.generateFrom analyticSubbasis

/-- A defining subbasic set is open in the analytic topology. -/
lemma isOpen_overOpen_inter_preimage (U : X.Opens) (s : Γ(X, U))
    (V : Set ℂ) (hV : IsOpen V) :
    @IsOpen (ComplexPoint X structureMap) analyticTopology
      (overOpen U ∩ evaluate U s ⁻¹' V) :=
  TopologicalSpace.isOpen_generateFrom_of_mem ⟨U, s, V, hV, rfl⟩

/-- The complex points over a scheme open form an analytic open set. -/
lemma isOpen_overOpen (U : X.Opens) :
    @IsOpen (ComplexPoint X structureMap) analyticTopology (overOpen U) := by
  apply TopologicalSpace.isOpen_generateFrom_of_mem
  refine ⟨U, 0, Set.univ, isOpen_univ, ?_⟩
  simp

/-- The map on complex points induced by a morphism over `Spec ℂ`. -/
noncomputable def map {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap) :
    ComplexPoint X structureMap → ComplexPoint Y structureMapY :=
  fun z ↦ ⟨z.1 ≫ f, by rw [Category.assoc, hf, z.2]⟩

/-- The identity scheme morphism induces the identity on complex points. -/
@[simp]
lemma map_id (h : 𝟙 X ≫ structureMap = structureMap) (z : ComplexPoint X structureMap) :
    map (𝟙 X) h z = z := by
  apply Subtype.ext
  simp [map]

/-- Composition of scheme morphisms agrees with composition on complex points. -/
@[simp]
lemma map_comp_apply {Y Z : Scheme}
    {structureMapY : Y ⟶ Spec (.of ℂ)} {structureMapZ : Z ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (g : Y ⟶ Z)
    (hf : f ≫ structureMapY = structureMap) (hg : g ≫ structureMapZ = structureMapY)
    (hfg : (f ≫ g) ≫ structureMapZ = structureMap) (z : ComplexPoint X structureMap) :
    map (f ≫ g) hfg z = map g hg (map f hf z) := by
  apply Subtype.ext
  simp [map, Category.assoc]

/-- The residue-field description of the image of a complex point. Both the underlying point and
its residue-field embedding are obtained functorially. -/
lemma residueData_map {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    (map f hf z).residueData =
      ⟨f z.residueData.1, f.residueFieldMap z.residueData.1 ≫ z.residueData.2⟩ := by
  apply Sigma.ext
  · simp [map, residueData, Scheme.SpecToEquivOfField]
    rfl
  · dsimp [map, residueData, Scheme.SpecToEquivOfField]
    rw [Scheme.descResidueField_stalkClosedPointTo_comp]

@[simp]
lemma residueData_map_fst {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    (map f hf z).residueData.1 = f z.residueData.1 := by
  rw [residueData_map]

lemma residueData_map_snd {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    (map f hf z).residueData.2 =
      f.residueFieldMap z.residueData.1 ≫ z.residueData.2 := by
  dsimp [map, residueData, Scheme.SpecToEquivOfField]
  rw [Scheme.descResidueField_stalkClosedPointTo_comp]

@[simp]
lemma underlying_map {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    (map f hf z).underlying = f z.underlying :=
  residueData_map_fst f hf z

/-- Pulling back a scheme open commutes with passage to complex points. -/
lemma mem_overOpen_map_iff {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) (U : Y.Opens) :
    map f hf z ∈ overOpen U ↔ z ∈ overOpen (f ⁻¹ᵁ U) := by
  simp [overOpen]

/-- Evaluation of a pulled-back regular function agrees with evaluation after mapping the point. -/
lemma evaluate_map {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (U : Y.Opens) (s : Γ(Y, U)) (z : ComplexPoint X structureMap) :
    evaluate U s (map f hf z) = evaluate (f ⁻¹ᵁ U) (f.app U s) z := by
  classical
  simp only [evaluate]
  rw [residueData_map]
  by_cases hx : z.residueData.1 ∈ f ⁻¹ᵁ U
  · have hy : f z.residueData.1 ∈ U := by simpa using hx
    rw [dif_pos hy, dif_pos hx]
    have hnat := Scheme.evaluation_naturality_apply f z.residueData.1 hy s
    change z.residueData.2
      (f.residueFieldMap z.residueData.1
        (Y.evaluation U (f z.residueData.1) _ s)) = _
    simpa using congrArg (fun a ↦ z.residueData.2 a) hnat
  · have hy : f z.residueData.1 ∉ U := by simpa using hx
    rw [dif_neg hy, dif_neg hx]

/-- Every morphism over `Spec ℂ` induces a continuous map on complex points for the topology
generated by regular-function evaluations. -/
lemma continuous_map {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap) :
    @Continuous (ComplexPoint X structureMap) (ComplexPoint Y structureMapY)
      analyticTopology analyticTopology (map f hf) := by
  rw [continuous_generateFrom_iff]
  rintro W ⟨U, s, V, hV, rfl⟩
  rw [Set.preimage_inter, Set.preimage_preimage]
  have hover : map f hf ⁻¹' overOpen U = overOpen (f ⁻¹ᵁ U) := by
    ext z
    exact mem_overOpen_map_iff f hf z U
  have heval : (fun z ↦ evaluate U s (map f hf z)) =
      evaluate (f ⁻¹ᵁ U) (f.app U s) := by
    funext z
    exact evaluate_map f hf U s z
  rw [hover, heval]
  exact isOpen_overOpen_inter_preimage _ _ _ hV

/-- A morphism over `Spec ℂ`, bundled as a continuous map on complex points. -/
noncomputable def continuousMap {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap) :
    @ContinuousMap (ComplexPoint X structureMap) (ComplexPoint Y structureMapY)
      analyticTopology analyticTopology :=
  @ContinuousMap.mk _ _ analyticTopology analyticTopology (map f hf) (continuous_map f hf)

/-- An isomorphism of schemes over `Spec ℂ` induces a homeomorphism on complex points. -/
noncomputable def isoMapHomeomorph {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (e : X ≅ Y) (h : e.hom ≫ structureMapY = structureMap) :
    @Homeomorph (ComplexPoint X structureMap) (ComplexPoint Y structureMapY)
      analyticTopology analyticTopology := by
  let _ : TopologicalSpace (ComplexPoint X structureMap) := analyticTopology
  let _ : TopologicalSpace (ComplexPoint Y structureMapY) := analyticTopology
  exact
    { toFun := map e.hom h
      invFun := map e.inv (by
        rw [← h, ← Category.assoc, e.inv_hom_id, Category.id_comp])
      left_inv z := by
        apply Subtype.ext
        simp [map, Category.assoc]
      right_inv z := by
        apply Subtype.ext
        simp [map, Category.assoc]
      continuous_toFun := continuous_map e.hom h
      continuous_invFun := continuous_map e.inv (by
        rw [← h, ← Category.assoc, e.inv_hom_id, Category.id_comp]) }

@[simp]
lemma isoMapHomeomorph_apply {Y : Scheme} {structureMapY : Y ⟶ Spec (.of ℂ)}
    (e : X ≅ Y) (h : e.hom ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    isoMapHomeomorph e h z = map e.hom h z :=
  rfl

end ComplexPoint

/-- Analytification of schemes over `Spec ℂ` as a functor to topological spaces.

This is the canonical home for functorial complex points.  In particular, consumers need not
package their own morphism records or reprove identity and composition laws. -/
noncomputable def complexAnalytification :
    CategoryTheory.Functor (Over (Spec (.of ℂ))) TopCat where
  obj X := @TopCat.of (ComplexPoint X.left X.hom) ComplexPoint.analyticTopology
  map f := @TopCat.ofHom _ _ ComplexPoint.analyticTopology ComplexPoint.analyticTopology
    (ComplexPoint.continuousMap f.left (Over.w f))
  map_id X := by
    ext z
    simp [ComplexPoint.continuousMap, ComplexPoint.map]
  map_comp f g := by
    ext z
    simp [ComplexPoint.continuousMap, ComplexPoint.map, Category.assoc]

/-- An integral projective algebraic variety over `ℂ`. Projectivity is witnessed by an explicit
closed embedding into a finite-dimensional projective space. -/
structure IntegralProjectiveComplexVariety where
  /-- The underlying scheme. -/
  scheme : Scheme
  [isIntegral : IsIntegral scheme]
  /-- The structure morphism to `Spec ℂ`. -/
  structureMap : scheme ⟶ Spec (.of ℂ)
  /-- An explicit finite-dimensional projective presentation. -/
  projective : ProjectiveSpace.IsProjective structureMap

namespace IntegralProjectiveComplexVariety

/-- The integral structure carried by an integral projective complex variety. -/
instance (V : IntegralProjectiveComplexVariety) : IsIntegral V.scheme := V.isIntegral

/-- The structure morphism of an integral projective complex variety is proper. -/
noncomputable instance (V : IntegralProjectiveComplexVariety) :
    IsProper V.structureMap := V.projective.isProper

/-- An integral projective complex variety is Noetherian. -/
noncomputable instance (V : IntegralProjectiveComplexVariety) : IsNoetherian V.scheme where
  toIsLocallyNoetherian :=
    LocallyOfFiniteType.isLocallyNoetherian V.structureMap
  toCompactSpace :=
    QuasiCompact.compactSpace_of_compactSpace V.structureMap

/-- The variety regarded as the corresponding object over `Spec ℂ`. -/
noncomputable abbrev over (V : IntegralProjectiveComplexVariety) : Over (Spec (.of ℂ)) :=
  Over.mk V.structureMap

/-- The complex points of an integral projective complex variety. -/
abbrev analyticPoint (V : IntegralProjectiveComplexVariety) :=
  ComplexPoint V.scheme V.structureMap

noncomputable instance (V : IntegralProjectiveComplexVariety) :
    TopologicalSpace V.analyticPoint :=
  ComplexPoint.analyticTopology

/-- The analytification as a topological space. -/
noncomputable def analytification (V : IntegralProjectiveComplexVariety) : TopCat :=
  complexAnalytification.obj V.over

end IntegralProjectiveComplexVariety

/-- A nonsingular projective algebraic variety over `ℂ`. Projectivity is an explicit closed
embedding into a finite-dimensional projective space. -/
structure SmoothProjectiveComplexVariety where
  /-- The underlying scheme. -/
  scheme : Scheme
  [isIntegral : IsIntegral scheme]
  /-- The structure morphism to `Spec ℂ`. -/
  structureMap : scheme ⟶ Spec (.of ℂ)
  [smooth : Smooth structureMap]
  /-- An explicit finite-dimensional projective presentation. -/
  projective : ProjectiveSpace.IsProjective structureMap

namespace SmoothProjectiveComplexVariety

/-- The integral structure carried by a smooth projective complex variety. -/
instance (V : SmoothProjectiveComplexVariety) : IsIntegral V.scheme := V.isIntegral

/-- The structure morphism of a smooth projective complex variety is proper. -/
noncomputable instance (V : SmoothProjectiveComplexVariety) :
    IsProper V.structureMap := V.projective.isProper

/-- A smooth projective complex variety is Noetherian. -/
noncomputable instance (V : SmoothProjectiveComplexVariety) : IsNoetherian V.scheme where
  toIsLocallyNoetherian :=
    LocallyOfFiniteType.isLocallyNoetherian V.structureMap
  toCompactSpace :=
    QuasiCompact.compactSpace_of_compactSpace V.structureMap

/-- The variety regarded as the corresponding object over `Spec ℂ`. -/
noncomputable abbrev over (V : SmoothProjectiveComplexVariety) : Over (Spec (.of ℂ)) :=
  Over.mk V.structureMap

/-- Forget smoothness while retaining the integral projective variety. -/
def toIntegralProjective (V : SmoothProjectiveComplexVariety) :
    IntegralProjectiveComplexVariety where
  scheme := V.scheme
  isIntegral := V.isIntegral
  structureMap := V.structureMap
  projective := V.projective

/-- The complex points of a smooth projective complex variety. -/
abbrev analyticPoint (V : SmoothProjectiveComplexVariety) :=
  ComplexPoint V.scheme V.structureMap

noncomputable instance (V : SmoothProjectiveComplexVariety) :
    TopologicalSpace V.analyticPoint :=
  ComplexPoint.analyticTopology

/-- The analytification as an object of the category of topological spaces. -/
noncomputable def analytification (V : SmoothProjectiveComplexVariety) : TopCat :=
  complexAnalytification.obj V.over

/-- Singular homology of the analytification with coefficients in a field `R`. -/
noncomputable abbrev bettiHomology (R : Type) [Field R]
    (V : SmoothProjectiveComplexVariety) (n : ℕ) : ModuleCat R :=
  AlgebraicTopology.Singular.Homology R V.analytification n

/-- Betti cohomology over a field, constructed as the linear dual of singular homology. -/
noncomputable abbrev bettiCohomology (R : Type) [Field R]
    (V : SmoothProjectiveComplexVariety) (n : ℕ) :=
  AlgebraicTopology.Singular.Cohomology R V.analytification n

/-- A morphism of smooth projective complex varieties. Its underlying scheme morphism is required
to commute with the structure morphisms to `Spec ℂ`. -/
@[ext]
structure Hom (V W : SmoothProjectiveComplexVariety) where
  /-- The underlying scheme morphism. -/
  toSchemeHom : V.scheme ⟶ W.scheme
  /-- Compatibility with the two structure morphisms. -/
  commutes : toSchemeHom ≫ W.structureMap = V.structureMap

namespace Hom

/-- The ordinary morphism in the over-category underlying a variety morphism. -/
noncomputable def toOverHom {V W : SmoothProjectiveComplexVariety} (f : Hom V W) :
    V.over ⟶ W.over :=
  Over.homMk f.toSchemeHom f.commutes

/-- The identity morphism of a smooth projective complex variety. -/
@[refl]
def id (V : SmoothProjectiveComplexVariety) : Hom V V where
  toSchemeHom := 𝟙 V.scheme
  commutes := Category.id_comp _

/-- Composition of morphisms of smooth projective complex varieties. -/
def comp {U V W : SmoothProjectiveComplexVariety} (f : Hom U V) (g : Hom V W) : Hom U W where
  toSchemeHom := f.toSchemeHom ≫ g.toSchemeHom
  commutes := by rw [Category.assoc, g.commutes, f.commutes]

end Hom

/-- The continuous map on analytifications induced by a morphism of varieties. -/
noncomputable def analyticMap {V W : SmoothProjectiveComplexVariety} (f : Hom V W) :
    V.analytification ⟶ W.analytification :=
  complexAnalytification.map f.toOverHom

/-- The map on singular homology induced by a morphism of varieties. -/
noncomputable def homologyMap (R : Type) [Field R]
    {V W : SmoothProjectiveComplexVariety} (n : ℕ) (f : Hom V W) :
    bettiHomology R V n →ₗ[R] bettiHomology R W n :=
  AlgebraicTopology.Singular.homologyMap R n (analyticMap f)

/-- Pullback on Betti cohomology induced by a morphism of varieties. -/
noncomputable def cohomologyMap (R : Type) [Field R]
    {V W : SmoothProjectiveComplexVariety} (n : ℕ) (f : Hom V W) :
    bettiCohomology R W n →ₗ[R] bettiCohomology R V n :=
  AlgebraicTopology.Singular.cohomologyMap R n (analyticMap f)

@[simp]
lemma cohomologyMap_apply (R : Type) [Field R]
    {V W : SmoothProjectiveComplexVariety} (n : ℕ) (f : Hom V W)
    (α : bettiCohomology R W n) (z : bettiHomology R V n) :
    cohomologyMap R n f α z = α (homologyMap R n f z) :=
  rfl

@[simp]
lemma analyticMap_id (V : SmoothProjectiveComplexVariety) :
    analyticMap (Hom.id V) = 𝟙 V.analytification := by
  ext z
  rfl

@[simp]
lemma analyticMap_comp {U V W : SmoothProjectiveComplexVariety}
    (f : Hom U V) (g : Hom V W) :
    analyticMap (Hom.comp f g) = analyticMap f ≫ analyticMap g := by
  ext z
  rfl

@[simp]
lemma homologyMap_id (R : Type) [Field R] (V : SmoothProjectiveComplexVariety) (n : ℕ) :
    homologyMap R n (Hom.id V) = LinearMap.id := by
  simp [homologyMap]

@[simp]
lemma homologyMap_comp (R : Type) [Field R]
    {U V W : SmoothProjectiveComplexVariety} (n : ℕ) (f : Hom U V) (g : Hom V W) :
    homologyMap R n (Hom.comp f g) =
      (homologyMap R n g).comp (homologyMap R n f) := by
  simp [homologyMap]

@[simp]
lemma cohomologyMap_id (R : Type) [Field R]
    (V : SmoothProjectiveComplexVariety) (n : ℕ) :
    cohomologyMap R n (Hom.id V) = LinearMap.id := by
  simp [cohomologyMap]

@[simp]
lemma cohomologyMap_comp (R : Type) [Field R]
    {U V W : SmoothProjectiveComplexVariety} (n : ℕ) (f : Hom U V) (g : Hom V W) :
    cohomologyMap R n (Hom.comp f g) =
      (cohomologyMap R n f).comp (cohomologyMap R n g) := by
  simp [cohomologyMap]

end SmoothProjectiveComplexVariety

end AlgebraicGeometry
