/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import FormalConjecturesForMathlib.AlgebraicGeometry.BettiSupportSingularHypercohomologyComparison
public import FormalConjecturesForMathlib.AlgebraicGeometry.CycleClass
public import FormalConjecturesForMathlib.AlgebraicGeometry.CycleComponentPointPurity
public import FormalConjecturesForMathlib.AlgebraicGeometry.ProjectiveAnalytificationParacompact

/-!
# Maximal-codimension component purity

The analytification of a maximal-codimension component is a point. Its rational singular
cohomology with support is generated by the chart-local coclass. The additive Betti comparison
transports this generator to rational constant-sheaf cohomology with support. Its image after
forgetting support therefore generates the complete supported image, which proves the guarded
component fundamental-class proposition in maximal codimension.

This does not prove Thom--Gysin purity for positive-dimensional supports or compatibility of the
Betti comparison with forgetting support.
-/

@[expose] public noncomputable section

open CategoryTheory Order TopologicalSpace

namespace AlgebraicGeometry.ComplexPoint.DimensionedSmoothProjectiveComplexVariety

private lemma span_singleton_image_eq_span_range_of_span_eq_top
    {M N : Type*} [AddCommGroup M] [Module ℚ M] [AddCommGroup N] [Module ℚ N]
    (f : M →+ N) (x : M) (hx : Submodule.span ℚ {x} = ⊤) :
    Submodule.span ℚ {f x} = Submodule.span ℚ (Set.range f) := by
  apply le_antisymm
  · apply Submodule.span_mono
    exact fun y hy ↦ ⟨x, Set.mem_singleton_iff.mp hy ▸ rfl⟩
  · apply Submodule.span_le.mpr
    rintro y ⟨z, rfl⟩
    obtain ⟨q, rfl⟩ := (Submodule.span_singleton_eq_top_iff ℚ x).mp hx z
    rw [map_rat_smul]
    exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))

private lemma span_addEquiv_apply_eq_top
    {M N : Type*} [AddCommGroup M] [Module ℚ M] [AddCommGroup N] [Module ℚ N]
    (e : M ≃+ N) (x : M) (hx : Submodule.span ℚ {x} = ⊤) :
    Submodule.span ℚ {e x} = ⊤ := by
  apply top_unique
  intro y _
  obtain ⟨q, hq⟩ :=
    (Submodule.span_singleton_eq_top_iff ℚ x).mp hx (e.symm y)
  rw [← e.apply_symm_apply y, ← hq, map_rat_smul]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))

/-- A component of maximal codimension satisfies rational component cycle-class purity in
constant-sheaf cohomology. The supported generator is constructed in the proof and the public
conclusion records only the resulting equality of the fundamental-class line and supported
image. -/
theorem rationalComponentCycleClassPurity_of_coheight_eq_dimension
    (V : DimensionedSmoothProjectiveComplexVariety) (x : V.scheme)
    (hx : coheight x = V.dimension) :
    RationalComponentCycleClassPurity
      V.toSmoothProjectiveComplexVariety V.dimension x := by
  unfold RationalComponentCycleClassPurity
  rw [show 2 * (V.dimension : ℤ) = ((2 * V.dimension : ℕ) : ℤ) by omega]
  let W := V.toSmoothProjectiveComplexVariety
  let Z := cycleComponentSupport W x
  have hZ : IsClosed Z := isClosed_cycleComponentSupport W x
  let e : RationalCohomologyWithSupport V.structureMap Z
        ((2 * V.dimension : ℕ) : ℤ) ≃+
      AlgebraicTopology.Singular.CohomologyWithSupport ℚ
        (TopCat.of W.analyticPoint) Z (2 * V.dimension) :=
    rationalCohomologyWithSupportAddEquivSingular
      V.structureMap V.dimension Z hZ (2 * V.dimension)
  let _ : Module ℚ (RationalCohomologyWithSupport V.structureMap Z
      ((2 * V.dimension : ℕ) : ℤ)) := e.module ℚ
  obtain ⟨β, hβ⟩ :=
    exists_singularComponentSupportedGenerator_of_coheight_eq_dimension V x hx
  let γ : RationalCohomologyWithSupport V.structureMap Z
      ((2 * V.dimension : ℕ) : ℤ) := e.symm β
  have hγ : Submodule.span ℚ {γ} = ⊤ := by
    change Submodule.span ℚ {e.symm β} = ⊤
    exact span_addEquiv_apply_eq_top e.symm β hβ
  let α := forgetSupport V.structureMap Z ((2 * V.dimension : ℕ) : ℤ) γ
  have hα : IsRationalComponentCycleClass W V.dimension x α := by
    constructor
    · exact Submodule.subset_span ⟨γ, rfl⟩
    · exact span_singleton_image_eq_span_range_of_span_eq_top
        (forgetSupport V.structureMap Z ((2 * V.dimension : ℕ) : ℤ)) γ hγ
  exact (rationalComponentCycleClassLine_eq_span W V.dimension x α hα).trans hα.2

end AlgebraicGeometry.ComplexPoint.DimensionedSmoothProjectiveComplexVariety
