/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import HodgeConjecture.Mathlib.Algebra.Category.Ring.Basic
public import HodgeConjecture.Definitions.AlgebraicGeometry.ProjectiveSpace
public import HodgeConjecture.Mathlib.Topology.Category.TopCat.Basic
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
public import Mathlib.AlgebraicGeometry.Noetherian
public import Mathlib.Topology.Instances.Complex
public import Mathlib.Topology.Order

/-!
# Complex points and analytification

For a scheme over `ℂ`, a complex point is a morphism `Spec ℂ ⟶ X` over `Spec ℂ`. This file
constructs its analytic topology from local regular functions. On an open subscheme `U`, every
section of `𝒪_X(U)` evaluates in `ℂ` at every complex point lying in `U`; these evaluation maps
generate the topology.

Analytification is then packaged as a functor from schemes over `Spec ℂ` to topological spaces,
so that Betti (co)homology of a complex variety is Mathlib's singular (co)homology of the
resulting space.

A nonsingular projective complex variety is not bundled into a structure. Its data travel as
an integral scheme `X`, a structure morphism to `Spec ℂ`, and the instance hypotheses `Smooth`
and `ProjectiveSpace.IsProjective` on that morphism, matching how the rest of this development
states its results.
-/

@[expose] public section

open CategoryTheory Topology

namespace AlgebraicGeometry

/-- A complex point of `X` over its given structure morphism to `Spec ℂ`. -/
abbrev ComplexPoint (X : Scheme) (structureMap : X ⟶ Spec ↧ℂ) :=
  {z : Spec ↧ℂ ⟶ X // z ≫ structureMap = 𝟙 _}

namespace ComplexPoint

variable {X : Scheme} {structureMap : X ⟶ Spec ↧ℂ}

/-- The scheme point and residue-field embedding corresponding to a complex point. -/
noncomputable def residueData (z : ComplexPoint X structureMap) :
    Σ x : X, X.residueField x ⟶ ↧ℂ :=
  Scheme.SpecToEquivOfField ℂ X z.1

/-- The underlying point of the scheme. -/
noncomputable def underlying (z : ComplexPoint X structureMap) : X := z.residueData.1

/-- The complex points whose underlying scheme point lies in `U`. -/
noncomputable def overOpen (U : X.Opens) : Set (ComplexPoint X structureMap) :=
  {z | z.underlying ∈ U}

/-- A complex point whose underlying scheme point lies in `U`.

Using this subtype is preferable whenever a local regular function is evaluated: it records the
domain condition in the type instead of assigning an arbitrary value outside `U`. -/
abbrev OverOpen (U : X.Opens) := {z : ComplexPoint X structureMap // z.underlying ∈ U}

/-- Evaluation of a local regular function on its actual domain. -/
noncomputable def evaluateOnOpen (U : X.Opens) (s : Γ(X, U))
    (z : OverOpen (structureMap := structureMap) U) : ℂ :=
  z.1.residueData.2 (X.evaluation U z.1.residueData.1 z.2 s)

/--
Evaluation of a local regular function at a complex point. Outside the function's domain this is
defined to be zero; all uses in the analytic topology are restricted to `overOpen U`.
-/
noncomputable def evaluate (U : X.Opens) (s : Γ(X, U))
    (z : ComplexPoint X structureMap) : ℂ := by
  classical
  exact if hz : z.residueData.1 ∈ U then
      z.residueData.2 (X.evaluation U z.residueData.1 hz s)
    else 0

lemma evaluate_eq_evaluateOnOpen (U : X.Opens) (s : Γ(X, U))
    (z : OverOpen (structureMap := structureMap) U) :
    evaluate U s z.1 = evaluateOnOpen U s z := by
  have hz : z.1.residueData.1 ∈ U := by
    simpa only [underlying] using z.2
  rw [evaluate, dif_pos hz]
  rfl

/-- Sets obtained by restricting an inverse image of a complex open set to the domain of a local
regular function. -/
noncomputable def analyticSubbasis : Set (Set (ComplexPoint X structureMap)) :=
  {W | ∃ (U : X.Opens) (s : Γ(X, U)) (V : Set ℂ), IsOpen V ∧
    W = overOpen U ∩ evaluate U s ⁻¹' V}

/-- The analytic topology on complex points, generated by evaluation of local regular functions.

This is the canonical topology on a complex-point space, so it is registered as an instance;
`instance_reducible` lets it unify with the equivalent local instances declared in other files. -/
@[instance_reducible]
noncomputable instance analyticTopology : TopologicalSpace (ComplexPoint X structureMap) :=
  TopologicalSpace.generateFrom analyticSubbasis

/-- A defining subbasic set is open in the analytic topology. -/
lemma isOpen_overOpen_inter_preimage (U : X.Opens) (s : Γ(X, U))
    (V : Set ℂ) (hV : IsOpen V) :
    @IsOpen (ComplexPoint X structureMap) analyticTopology
      (overOpen U ∩ evaluate U s ⁻¹' V) :=
  TopologicalSpace.isOpen_generateFrom_of_mem ⟨U, s, V, hV, rfl⟩

/-- The complex points over a scheme open form an analytic open set. -/
lemma isOpen_overOpen (U : X.Opens) :
    @IsOpen (ComplexPoint X structureMap) analyticTopology (overOpen U) := by
  apply TopologicalSpace.isOpen_generateFrom_of_mem
  refine ⟨U, 0, Set.univ, isOpen_univ, ?_⟩
  simp

/-- The map on complex points induced by a morphism over `Spec ℂ`. -/
noncomputable def map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap) :
    ComplexPoint X structureMap → ComplexPoint Y structureMapY :=
  fun z ↦ ⟨z.1 ≫ f, by rw [Category.assoc, hf, z.2]⟩

/-- The identity scheme morphism induces the identity on complex points. -/
@[simp]
lemma map_id (h : 𝟙 X ≫ structureMap = structureMap) (z : ComplexPoint X structureMap) :
    map (𝟙 X) h z = z := by
  apply Subtype.ext
  simp [map]

/-- Composition of scheme morphisms agrees with composition on complex points. -/
@[simp]
lemma map_comp_apply {Y Z : Scheme}
    {structureMapY : Y ⟶ Spec ↧ℂ} {structureMapZ : Z ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (g : Y ⟶ Z)
    (hf : f ≫ structureMapY = structureMap) (hg : g ≫ structureMapZ = structureMapY)
    (hfg : (f ≫ g) ≫ structureMapZ = structureMap) (z : ComplexPoint X structureMap) :
    map (f ≫ g) hfg z = map g hg (map f hf z) := by
  apply Subtype.ext
  simp [map, Category.assoc]

/-- The residue-field description of the image of a complex point. Both the underlying point and
its residue-field embedding are obtained functorially. -/
lemma residueData_map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    (map f hf z).residueData =
      ⟨f z.residueData.1, f.residueFieldMap z.residueData.1 ≫ z.residueData.2⟩ := by
  apply Sigma.ext
  · simp [map, residueData, Scheme.SpecToEquivOfField]
    rfl
  · dsimp [map, residueData, Scheme.SpecToEquivOfField]
    rw [Scheme.descResidueField_stalkClosedPointTo_comp]

@[simp]
lemma residueData_map_fst {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    (map f hf z).residueData.1 = f z.residueData.1 := by
  rw [residueData_map]

lemma residueData_map_snd {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    (map f hf z).residueData.2 =
      f.residueFieldMap z.residueData.1 ≫ z.residueData.2 := by
  dsimp [map, residueData, Scheme.SpecToEquivOfField]
  rw [Scheme.descResidueField_stalkClosedPointTo_comp]

@[simp]
lemma underlying_map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    (map f hf z).underlying = f z.underlying :=
  residueData_map_fst f hf z

/-- Pulling back a scheme open commutes with passage to complex points. -/
lemma mem_overOpen_map_iff {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) (U : Y.Opens) :
    map f hf z ∈ overOpen U ↔ z ∈ overOpen (f ⁻¹ᵁ U) := by
  simp [overOpen]

/-- Evaluation of a pulled-back regular function agrees with evaluation after mapping the point. -/
lemma evaluate_map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (U : Y.Opens) (s : Γ(Y, U)) (z : ComplexPoint X structureMap) :
    evaluate U s (map f hf z) = evaluate (f ⁻¹ᵁ U) (f.app U s) z := by
  classical
  simp only [evaluate]
  rw [residueData_map]
  by_cases hx : z.residueData.1 ∈ f ⁻¹ᵁ U
  · have hy : f z.residueData.1 ∈ U := by simpa using hx
    rw [dif_pos hy, dif_pos hx]
    have hnat := Scheme.evaluation_naturality_apply f z.residueData.1 hy s
    change z.residueData.2
      (f.residueFieldMap z.residueData.1
        (Y.evaluation U (f z.residueData.1) _ s)) = _
    simpa using congrArg (fun a ↦ z.residueData.2 a) hnat
  · have hy : f z.residueData.1 ∉ U := by simpa using hx
    rw [dif_neg hy, dif_neg hx]

/-- Every morphism over `Spec ℂ` induces a continuous map on complex points for the topology
generated by regular-function evaluations. -/
lemma continuous_map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap) :
    @Continuous (ComplexPoint X structureMap) (ComplexPoint Y structureMapY)
      analyticTopology analyticTopology (map f hf) := by
  rw [continuous_generateFrom_iff]
  rintro W ⟨U, s, V, hV, rfl⟩
  rw [Set.preimage_inter, Set.preimage_preimage]
  have hover : map f hf ⁻¹' overOpen U = overOpen (f ⁻¹ᵁ U) := by
    ext z
    exact mem_overOpen_map_iff f hf z U
  have heval : (fun z ↦ evaluate U s (map f hf z)) =
      evaluate (f ⁻¹ᵁ U) (f.app U s) := by
    funext z
    exact evaluate_map f hf U s z
  rw [hover, heval]
  exact isOpen_overOpen_inter_preimage _ _ _ hV

/-- A morphism over `Spec ℂ`, bundled as a continuous map on complex points. -/
noncomputable def continuousMap {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap) :
    @ContinuousMap (ComplexPoint X structureMap) (ComplexPoint Y structureMapY)
      analyticTopology analyticTopology :=
  @ContinuousMap.mk _ _ analyticTopology analyticTopology (map f hf) (continuous_map f hf)

/-- An isomorphism of schemes over `Spec ℂ` induces a homeomorphism on complex points. -/
noncomputable def isoMapHomeomorph {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (e : X ≅ Y) (h : e.hom ≫ structureMapY = structureMap) :
    @Homeomorph (ComplexPoint X structureMap) (ComplexPoint Y structureMapY)
      analyticTopology analyticTopology := by
  let _ : TopologicalSpace (ComplexPoint X structureMap) := analyticTopology
  let _ : TopologicalSpace (ComplexPoint Y structureMapY) := analyticTopology
  exact
    { toFun := map e.hom h
      invFun := map e.inv (by
        rw [← h, ← Category.assoc, e.inv_hom_id, Category.id_comp])
      left_inv z := by
        apply Subtype.ext
        simp [map, Category.assoc]
      right_inv z := by
        apply Subtype.ext
        simp [map, Category.assoc]
      continuous_toFun := continuous_map e.hom h
      continuous_invFun := continuous_map e.inv (by
        rw [← h, ← Category.assoc, e.inv_hom_id, Category.id_comp]) }

@[simp]
lemma isoMapHomeomorph_apply {Y : Scheme} {structureMapY : Y ⟶ Spec ↧ℂ}
    (e : X ≅ Y) (h : e.hom ≫ structureMapY = structureMap)
    (z : ComplexPoint X structureMap) :
    isoMapHomeomorph e h z = map e.hom h z :=
  rfl

end ComplexPoint

/-- Analytification of schemes over `Spec ℂ` as a functor to topological spaces.

This is the canonical home for functorial complex points.  In particular, consumers need not
package their own morphism records or reprove identity and composition laws. -/
noncomputable def complexAnalytification :
    CategoryTheory.Functor (Over (Spec ↧ℂ)) TopCat where
  obj X := @TopCat.of (ComplexPoint X.left X.hom) ComplexPoint.analyticTopology
  map f := @TopCat.ofHom _ _ ComplexPoint.analyticTopology ComplexPoint.analyticTopology
    (ComplexPoint.continuousMap f.left (Over.w f))
  map_id X := by
    ext z
    simp [ComplexPoint.continuousMap, ComplexPoint.map]
  map_comp f g := by
    ext z
    simp [ComplexPoint.continuousMap, ComplexPoint.map, Category.assoc]

/-- An integral projective algebraic variety over `ℂ`. Projectivity is witnessed by an explicit
closed embedding into a finite-dimensional projective space. -/
structure IntegralProjectiveComplexVariety where
  /-- The underlying scheme. -/
  scheme : Scheme
  [isIntegral : IsIntegral scheme]
  /-- The structure morphism to `Spec ℂ`. -/
  structureMap : scheme ⟶ Spec ↧ℂ
  [projective : ProjectiveSpace.IsProjective structureMap]

/-- A projective complex scheme is Noetherian. -/
theorem isNoetherian_of_isProjective {X : Scheme} (structureMap : X ⟶ Spec ↧ℂ)
    [ProjectiveSpace.IsProjective structureMap] : IsNoetherian X where
  toIsLocallyNoetherian := LocallyOfFiniteType.isLocallyNoetherian structureMap
  toCompactSpace := QuasiCompact.compactSpace_of_compactSpace structureMap

namespace IntegralProjectiveComplexVariety

/-- The integral structure carried by an integral projective complex variety. -/
instance (V : IntegralProjectiveComplexVariety) : IsIntegral V.scheme := V.isIntegral

/-- The projective presentation carried by an integral projective complex variety. -/
instance (V : IntegralProjectiveComplexVariety) :
    ProjectiveSpace.IsProjective V.structureMap := V.projective

/-- An integral projective complex variety is Noetherian. -/
noncomputable instance (V : IntegralProjectiveComplexVariety) : IsNoetherian V.scheme :=
  isNoetherian_of_isProjective V.structureMap

/-- The variety regarded as the corresponding object over `Spec ℂ`. -/
noncomputable abbrev over (V : IntegralProjectiveComplexVariety) : Over (Spec ↧ℂ) :=
  Over.mk V.structureMap

/-- The complex points of an integral projective complex variety. -/
abbrev analyticPoint (V : IntegralProjectiveComplexVariety) :=
  ComplexPoint V.scheme V.structureMap

noncomputable instance (V : IntegralProjectiveComplexVariety) :
    TopologicalSpace V.analyticPoint :=
  ComplexPoint.analyticTopology

/-- The analytification as a topological space. -/
noncomputable def analytification (V : IntegralProjectiveComplexVariety) : TopCat :=
  complexAnalytification.obj V.over

end IntegralProjectiveComplexVariety

end AlgebraicGeometry
