/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import HodgeConjecture.Mathlib.Algebra.Category.Ring.Basic
public import HodgeConjecture.Definitions.AlgebraicGeometry.ProjectiveSpace
public import HodgeConjecture.Mathlib.Topology.Category.TopCat.Basic
public import Mathlib.Algebra.Category.Ring.Topology
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
public import Mathlib.AlgebraicGeometry.Noetherian
public import Mathlib.Topology.Instances.Complex
public import Mathlib.Topology.Order

/-!
# Points over a field, and analytification

For a scheme `X` over a field `K`, a `K`-point is a morphism `Spec K ⟶ X` over `Spec K`. A
`K`-point lying over an open `U` evaluates every section of `𝒪_X(U)` in `K`, and so induces a ring
homomorphism `Γ(X, U) ⟶ ↧K`. Over an affine open this identifies the `K`-points with a subspace of
that hom set, which carries Mathlib's topology of pointwise convergence; the analytic topology is
the topology glued from these affine charts. It exists as soon as `K` is a topological division
ring whose points are closed, so it applies just as well to `ℝ` or to a `p`-adic field.

`analyticTopology_eq_generateFrom` identifies it with the more elementary description: the
topology generated by the sets on which a local regular function takes values in a prescribed open
subset of `K`.

Complex points are the case `K = ℂ`. Analytification is then packaged as a functor from schemes
over `Spec ℂ` to topological spaces, so that Betti (co)homology of a complex variety is Mathlib's
singular (co)homology of the resulting space.

A nonsingular projective complex variety is not bundled into a structure. Its data travel as
an integral scheme `X`, a structure morphism to `Spec ℂ`, and the instance hypotheses `Smooth`
and `IsProjective` on that morphism, matching how the rest of this development
states its results.
-/

@[expose] public section

open CategoryTheory Topology
open scoped CommRingCat.HomTopology

namespace AlgebraicGeometry

variable (K : Type) [Field K]

/-- A `K`-point of `X` over its given structure morphism to `Spec K`. -/
abbrev Point (X : Scheme) (structureMap : X ⟶ Spec ↧K) :=
  {z : Spec ↧K ⟶ X // z ≫ structureMap = 𝟙 _}

namespace Point

variable {K} {X : Scheme} {structureMap : X ⟶ Spec ↧K}

/-- The scheme point and residue-field embedding corresponding to a `K`-point. -/
noncomputable def residueData (z : Point K X structureMap) :
    Σ x : X, X.residueField x ⟶ ↧K :=
  Scheme.SpecToEquivOfField K X z.1

/-- The underlying point of the scheme. -/
noncomputable def underlying (z : Point K X structureMap) : X := z.residueData.1

/-- The `K`-points whose underlying scheme point lies in `U`. -/
noncomputable def overOpen (U : X.Opens) : Set (Point K X structureMap) :=
  {z | z.underlying ∈ U}

/-- A `K`-point whose underlying scheme point lies in `U`.

Using this subtype is preferable whenever a local regular function is evaluated: it records the
domain condition in the type instead of assigning an arbitrary value outside `U`. -/
abbrev OverOpen (U : X.Opens) := {z : Point K X structureMap // z.underlying ∈ U}

/-- Evaluation of a local regular function on its actual domain. -/
noncomputable def evaluateOnOpen (U : X.Opens) (s : Γ(X, U))
    (z : OverOpen (structureMap := structureMap) U) : K :=
  z.1.residueData.2 (X.evaluation U z.1.residueData.1 z.2 s)

/--
Evaluation of a local regular function at a `K`-point. Outside the function's domain this is
defined to be zero; all uses in the analytic topology are restricted to `overOpen U`.
-/
noncomputable def evaluate (U : X.Opens) (s : Γ(X, U))
    (z : Point K X structureMap) : K := by
  classical
  exact if hz : z.residueData.1 ∈ U then
      z.residueData.2 (X.evaluation U z.residueData.1 hz s)
    else 0

lemma evaluate_eq_evaluateOnOpen (U : X.Opens) (s : Γ(X, U))
    (z : OverOpen (structureMap := structureMap) U) :
    evaluate U s z.1 = evaluateOnOpen U s z := by
  have hz : z.1.residueData.1 ∈ U := by
    simpa only [underlying] using z.2
  rw [evaluate, dif_pos hz]
  rfl

/-- Restricting a regular function does not change its value at a point in the smaller open. -/
lemma evaluate_res {U V : X.Opens} (hVU : V ≤ U) (s : Γ(X, U))
    (z : Point K X structureMap) (hz : z ∈ overOpen V) :
    evaluate U s z = evaluate V (X.presheaf.map (homOfLE hVU).op s) z := by
  rw [evaluate, dif_pos, evaluate, dif_pos]
  · congr 1
    exact congrArg (fun a ↦ X.residue z.residueData.1 a)
      (X.presheaf.germ_res_apply (homOfLE hVU) z.residueData.1 hz s).symm
  · exact hz
  · exact hVU hz

/-- A `K`-point belongs to a principal open exactly when its defining function is nonzero. -/
lemma mem_overOpen_basicOpen_iff_evaluate_ne_zero {U : X.Opens} (s : Γ(X, U))
    (z : Point K X structureMap) (hz : z ∈ overOpen U) :
    z ∈ overOpen (X.basicOpen s) ↔ evaluate U s z ≠ 0 := by
  rw [evaluate, dif_pos (show z.residueData.1 ∈ U from hz)]
  change z.residueData.1 ∈ X.basicOpen s ↔
    z.residueData.2 (X.evaluation U z.residueData.1 hz s) ≠ 0
  rw [← Scheme.evaluation_ne_zero_iff_mem_basicOpen]
  exact (map_ne_zero_iff z.residueData.2.hom z.residueData.2.hom.injective).symm

/-- Evaluation of all regular functions on `U` at a `K`-point lying over `U`, bundled as a
ring homomorphism `Γ(X, U) ⟶ ↧K`.

This is the chart map of the analytic topology: over an affine open it identifies the complex
points with Mathlib's space of ring homomorphisms into `K`. -/
noncomputable def evaluationHom (U : X.Opens)
    (z : OverOpen (structureMap := structureMap) U) : Γ(X, U) ⟶ ↧K :=
  X.evaluation U z.1.residueData.1 z.2 ≫ z.1.residueData.2

@[simp]
lemma evaluationHom_apply (U : X.Opens) (z : OverOpen (structureMap := structureMap) U)
    (s : Γ(X, U)) : evaluationHom U z s = evaluate U s z.1 := by
  rw [evaluate, dif_pos (show z.1.residueData.1 ∈ U from z.2)]
  rfl

/-- The underlying ring homomorphism of `evaluationHom` is evaluation. -/
lemma evaluationHom_hom_apply (U : X.Opens) (z : OverOpen (structureMap := structureMap) U)
    (s : Γ(X, U)) : (evaluationHom U z).hom s = evaluate U s z.1 :=
  evaluationHom_apply U z s

/-- On an affine open, a regular function on a principal open is a quotient of regular functions
on the whole affine open. -/
lemma exists_evaluate_basicOpen_eq_div {U : X.Opens} (hU : IsAffineOpen U) (f : Γ(X, U))
    (t : Γ(X, X.basicOpen f)) :
    ∃ (k : ℕ) (a : Γ(X, U)), ∀ z : Point K X structureMap,
      z ∈ overOpen (X.basicOpen f) →
        evaluate (X.basicOpen f) t z = evaluate U a z / evaluate U f z ^ k := by
  let _ := hU.isLocalization_basicOpen f
  obtain ⟨k, a, hta⟩ := IsLocalization.Away.surj f t
  refine ⟨k, a, ?_⟩
  intro z hz
  have hzU : z ∈ overOpen U := X.basicOpen_le f hz
  have hden : evaluate U f z ≠ 0 :=
    (mem_overOpen_basicOpen_iff_evaluate_ne_zero f z hzU).mp hz
  apply (eq_div_iff (pow_ne_zero k hden)).2
  let ψ : Γ(X, X.basicOpen f) →+* K :=
    z.residueData.2.hom.comp
      (X.evaluation (X.basicOpen f) z.residueData.1 hz).hom
  have hmap := congrArg ψ hta
  have hf := evaluate_res (X.basicOpen_le f) f z hz
  have ha := evaluate_res (X.basicOpen_le f) a z hz
  have hz' : z.residueData.1 ∈ X.basicOpen f := hz
  rw [hf, ha]
  simp only [evaluate, dif_pos hz']
  change ψ t * ψ (algebraMap _ _ f) ^ k = ψ (algebraMap _ _ a)
  simpa using hmap

/-- The map on `K`-points induced by a morphism over `Spec K`. -/
noncomputable def map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap) :
    Point K X structureMap → Point K Y structureMapY :=
  fun z ↦ ⟨z.1 ≫ f, by rw [Category.assoc, hf, z.2]⟩

/-- The identity scheme morphism induces the identity on `K`-points. -/
@[simp]
lemma map_id (h : 𝟙 X ≫ structureMap = structureMap) (z : Point K X structureMap) :
    map (𝟙 X) h z = z := by
  apply Subtype.ext
  simp [map]

/-- Composition of scheme morphisms agrees with composition on `K`-points. -/
@[simp]
lemma map_comp_apply {Y Z : Scheme}
    {structureMapY : Y ⟶ Spec ↧K} {structureMapZ : Z ⟶ Spec ↧K}
    (f : X ⟶ Y) (g : Y ⟶ Z)
    (hf : f ≫ structureMapY = structureMap) (hg : g ≫ structureMapZ = structureMapY)
    (hfg : (f ≫ g) ≫ structureMapZ = structureMap) (z : Point K X structureMap) :
    map (f ≫ g) hfg z = map g hg (map f hf z) := by
  apply Subtype.ext
  simp [map, Category.assoc]

/-- The residue-field description of the image of a `K`-point. Both the underlying point and
its residue-field embedding are obtained functorially. -/
lemma residueData_map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : Point K X structureMap) :
    (map f hf z).residueData =
      ⟨f z.residueData.1, f.residueFieldMap z.residueData.1 ≫ z.residueData.2⟩ := by
  apply Sigma.ext
  · simp [map, residueData, Scheme.SpecToEquivOfField]
    rfl
  · dsimp [map, residueData, Scheme.SpecToEquivOfField]
    rw [Scheme.descResidueField_stalkClosedPointTo_comp]

@[simp]
lemma residueData_map_fst {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : Point K X structureMap) :
    (map f hf z).residueData.1 = f z.residueData.1 := by
  rw [residueData_map]

lemma residueData_map_snd {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : Point K X structureMap) :
    (map f hf z).residueData.2 =
      f.residueFieldMap z.residueData.1 ≫ z.residueData.2 := by
  dsimp [map, residueData, Scheme.SpecToEquivOfField]
  rw [Scheme.descResidueField_stalkClosedPointTo_comp]

@[simp]
lemma underlying_map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : Point K X structureMap) :
    (map f hf z).underlying = f z.underlying :=
  residueData_map_fst f hf z

/-- Pulling back a scheme open commutes with passage to `K`-points. -/
lemma mem_overOpen_map_iff {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (z : Point K X structureMap) (U : Y.Opens) :
    map f hf z ∈ overOpen U ↔ z ∈ overOpen (f ⁻¹ᵁ U) := by
  simp [overOpen]

/-- Evaluation of a pulled-back regular function agrees with evaluation after mapping the point. -/
lemma evaluate_map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap)
    (U : Y.Opens) (s : Γ(Y, U)) (z : Point K X structureMap) :
    evaluate U s (map f hf z) = evaluate (f ⁻¹ᵁ U) (f.app U s) z := by
  classical
  simp only [evaluate]
  rw [residueData_map]
  by_cases hx : z.residueData.1 ∈ f ⁻¹ᵁ U
  · have hy : f z.residueData.1 ∈ U := by simpa using hx
    rw [dif_pos hy, dif_pos hx]
    have hnat := Scheme.evaluation_naturality_apply f z.residueData.1 hy s
    change z.residueData.2
      (f.residueFieldMap z.residueData.1
        (Y.evaluation U (f z.residueData.1) _ s)) = _
    simpa using congrArg (fun a ↦ z.residueData.2 a) hnat
  · have hy : f z.residueData.1 ∉ U := by simpa using hx
    rw [dif_neg hy, dif_neg hx]

section Topology

variable [TopologicalSpace K]

/-- The chart topology on the `K`-points lying over an open subset: the topology of pointwise
convergence, pulled back along `evaluationHom` from Mathlib's topology on `Γ(X, U) ⟶ ↧K`. -/
@[instance_reducible]
noncomputable def chartTopology (U : X.Opens) :
    TopologicalSpace (OverOpen (structureMap := structureMap) U) :=
  .induced (evaluationHom U) inferInstance

/-- Sets obtained by restricting an inverse image of an open subset of `K` to the domain of a local
regular function. -/
noncomputable def analyticSubbasis : Set (Set (Point K X structureMap)) :=
  {W | ∃ (U : X.Opens) (s : Γ(X, U)) (V : Set K), IsOpen V ∧
    W = overOpen U ∩ evaluate U s ⁻¹' V}

/-- The analytic topology on `K`-points: the topology glued from the affine charts, each of
which carries Mathlib's topology of pointwise convergence on `Γ(X, U) ⟶ ↧K`.

This is the canonical topology on a complex-point space, so it is registered as an instance;
`instance_reducible` lets it unify with the equivalent local instances declared in other files. -/
@[instance_reducible]
noncomputable instance analyticTopology : TopologicalSpace (Point K X structureMap) :=
  ⨆ U : X.affineOpens,
    .coinduced (Subtype.val : OverOpen (structureMap := structureMap) U.1 → _) (chartTopology U.1)

/-- A set of `K`-points is analytically open exactly when, in every affine chart, it is cut
out by an open set of ring homomorphisms `Γ(X, U) ⟶ ↧K`. -/
lemma isOpen_analyticTopology_iff {W : Set (Point K X structureMap)} :
    IsOpen W ↔ ∀ U : X.affineOpens,
      ∃ O : Set (Γ(X, U.1) ⟶ ↧K), IsOpen O ∧ evaluationHom U.1 ⁻¹' O = Subtype.val ⁻¹' W := by
  show IsOpen[⨆ U : X.affineOpens, TopologicalSpace.coinduced _ (chartTopology U.1)] W ↔ _
  rw [isOpen_iSup_iff]
  exact forall_congr' fun U ↦ isOpen_coinduced.trans isOpen_induced_iff

variable [IsTopologicalDivisionRing K] [T1Space K]

/-- A defining subbasic set is open in the analytic topology. -/
lemma isOpen_overOpen_inter_preimage (U : X.Opens) (s : Γ(X, U))
    (V : Set K) (hV : IsOpen V) :
    IsOpen (overOpen U ∩ evaluate U s ⁻¹' V : Set (Point K X structureMap)) := by
  rw [isOpen_analyticTopology_iff]
  rintro ⟨W, hW⟩
  refine ⟨⋃ (g : Γ(X, W)) (k : ℕ) (a : Γ(X, W)) (_ : X.basicOpen g ≤ U ⊓ W)
      (_ : ∀ y : Point K X structureMap, y ∈ overOpen (X.basicOpen g) →
        evaluate U s y = evaluate W a y / evaluate W g y ^ k),
      {φ : Γ(X, W) ⟶ ↧K | φ g ≠ 0} ∩ (fun φ : Γ(X, W) ⟶ ↧K ↦ φ a / φ g ^ k) ⁻¹' V,
      ?_, ?_⟩
  · refine isOpen_iUnion fun g ↦ isOpen_iUnion fun k ↦ isOpen_iUnion fun a ↦
      isOpen_iUnion fun _ ↦ isOpen_iUnion fun _ ↦ ?_
    have hg : Continuous fun φ : Γ(X, W) ⟶ ↧K ↦ φ g :=
      CommRingCat.HomTopology.continuous_apply (R := ↧K) g
    have ha : Continuous fun φ : Γ(X, W) ⟶ ↧K ↦ φ a :=
      CommRingCat.HomTopology.continuous_apply (R := ↧K) a
    exact (ha.continuousOn.div (hg.pow k).continuousOn
        fun _ hφ ↦ pow_ne_zero k hφ).isOpen_inter_preimage
      (isOpen_ne_fun hg continuous_const) hV
  · ext z
    have key : ∀ t : Γ(X, W), evaluationHom W z t = evaluate W t z.1 :=
      fun t ↦ evaluationHom_apply W z t
    simp only [Set.mem_preimage, Set.mem_iUnion, Set.mem_ofPred_eq, Set.mem_inter_iff,
      exists_prop, key]
    constructor
    · rintro ⟨g, k, a, hgle, hdiv, hg0, hgV⟩
      have hzg : z.1 ∈ overOpen (X.basicOpen g) :=
        (mem_overOpen_basicOpen_iff_evaluate_ne_zero g z.1 z.2).mpr hg0
      exact ⟨(hgle.trans inf_le_left) hzg, by rw [hdiv z.1 hzg]; exact hgV⟩
    · rintro ⟨hzU, hzV⟩
      obtain ⟨g, hgle, hzg⟩ :=
        hW.exists_basicOpen_le (⟨z.1.underlying, ⟨hzU, z.2⟩⟩ : (U ⊓ W : X.Opens)) z.2
      have hgU : X.basicOpen g ≤ U := hgle.trans inf_le_left
      obtain ⟨k, a, hka⟩ :=
        exists_evaluate_basicOpen_eq_div (structureMap := structureMap) hW g
          (X.presheaf.map (homOfLE hgU).op s)
      have hdiv : ∀ y : Point K X structureMap, y ∈ overOpen (X.basicOpen g) →
          evaluate U s y = evaluate W a y / evaluate W g y ^ k := fun y hy ↦ by
        rw [evaluate_res hgU s y hy]; exact hka y hy
      refine ⟨g, k, a, hgle, hdiv, ?_, ?_⟩
      · exact (mem_overOpen_basicOpen_iff_evaluate_ne_zero g z.1 z.2).mp hzg
      · rw [← hdiv z.1 hzg]; exact hzV

/-- The `K`-points over a scheme open form an analytic open set. -/
lemma isOpen_overOpen (U : X.Opens) :
    IsOpen (overOpen U : Set (Point K X structureMap)) := by
  simpa using isOpen_overOpen_inter_preimage U 0 Set.univ isOpen_univ

/-- The analytic topology is generated by evaluation of local regular functions.

This is the original description of the topology: it is generated by the sets on which a local
regular function takes values in a prescribed open subset of `K`. -/
lemma analyticTopology_eq_generateFrom :
    (analyticTopology : TopologicalSpace (Point K X structureMap)) =
      .generateFrom analyticSubbasis := by
  refine le_antisymm (le_generateFrom ?_) ?_
  · rintro W ⟨U, s, V, hV, rfl⟩
    exact isOpen_overOpen_inter_preimage U s V hV
  · intro W hW
    rw [isOpen_analyticTopology_iff] at hW
    refine (@isOpen_iff_forall_mem_open _
      (.generateFrom (analyticSubbasis (structureMap := structureMap))) _).2 fun z hz ↦ ?_
    obtain ⟨U, hU, hzU, -⟩ :=
      exists_isAffineOpen_mem_and_subset (x := z.underlying) (U := ⊤) trivial
    obtain ⟨O, hO, hWO⟩ := hW ⟨U, hU⟩
    obtain ⟨O', hO', rfl⟩ :=
      (CommRingCat.HomTopology.isEmbedding_hom ↧K Γ(X, U)).isInducing.isOpen_iff.mp hO
    have hzO : ⇑(evaluationHom U ⟨z, hzU⟩).hom ∈ O' := by
      have : (⟨z, hzU⟩ : OverOpen (structureMap := structureMap) U) ∈ Subtype.val ⁻¹' W := hz
      rw [← hWO] at this
      exact this
    obtain ⟨I, u, hu, hIO⟩ := isOpen_pi_iff.mp hO' _ hzO
    refine ⟨overOpen U ∩ ⋂ t ∈ (I : Set Γ(X, U)), (overOpen U ∩ evaluate U t ⁻¹' u t),
      ?_, ?_, ?_⟩
    · rintro y ⟨hyU, hyu⟩
      have hy : ⇑(evaluationHom U ⟨y, hyU⟩).hom ∈ O' :=
        hIO fun t ht ↦ by
          rw [evaluationHom_hom_apply]
          exact (Set.mem_iInter₂.1 hyu t ht).2
      have hmem : (⟨y, hyU⟩ : OverOpen (structureMap := structureMap) U) ∈
          evaluationHom U ⁻¹' ((fun f : Γ(X, U) ⟶ ↧K ↦ ⇑f.hom) ⁻¹' O') := hy
      rw [hWO] at hmem
      exact hmem
    · exact @IsOpen.inter _ (.generateFrom _) _ _
        (TopologicalSpace.isOpen_generateFrom_of_mem ⟨U, 0, Set.univ, isOpen_univ, by simp⟩)
        (@Set.Finite.isOpen_biInter _ _ (.generateFrom _) _ _ I.finite_toSet fun t ht ↦
          TopologicalSpace.isOpen_generateFrom_of_mem ⟨U, t, u t, (hu t ht).1, rfl⟩)
    · refine ⟨hzU, Set.mem_iInter₂.2 fun t ht ↦ ⟨hzU, ?_⟩⟩
      have h2 := (hu t ht).2
      rw [evaluationHom_hom_apply] at h2
      exact h2

/-- Continuity of a map into the `K`-points is tested on the defining subbasis. -/
lemma continuous_iff_analyticSubbasis {Z : Type*} [TopologicalSpace Z]
    {g : Z → Point K X structureMap} :
    Continuous g ↔ ∀ W ∈ analyticSubbasis (structureMap := structureMap), IsOpen (g ⁻¹' W) := by
  rw [analyticTopology_eq_generateFrom]
  exact continuous_generateFrom_iff

/-- Every morphism over `Spec K` induces a continuous map on `K`-points for the topology
generated by regular-function evaluations. -/
lemma continuous_map {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap) :
    @Continuous (Point K X structureMap) (Point K Y structureMapY)
      analyticTopology analyticTopology (map f hf) := by
  rw [continuous_iff_analyticSubbasis]
  rintro W ⟨U, s, V, hV, rfl⟩
  rw [Set.preimage_inter, Set.preimage_preimage]
  have hover : map f hf ⁻¹' overOpen U = overOpen (f ⁻¹ᵁ U) := by
    ext z
    exact mem_overOpen_map_iff f hf z U
  have heval : (fun z ↦ evaluate U s (map f hf z)) =
      evaluate (f ⁻¹ᵁ U) (f.app U s) := by
    funext z
    exact evaluate_map f hf U s z
  rw [hover, heval]
  exact isOpen_overOpen_inter_preimage _ _ _ hV

/-- A morphism over `Spec K`, bundled as a continuous map on `K`-points. -/
noncomputable def continuousMap {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (f : X ⟶ Y) (hf : f ≫ structureMapY = structureMap) :
    @ContinuousMap (Point K X structureMap) (Point K Y structureMapY)
      analyticTopology analyticTopology :=
  @ContinuousMap.mk _ _ analyticTopology analyticTopology (map f hf) (continuous_map f hf)

/-- An isomorphism of schemes over `Spec K` induces a homeomorphism on `K`-points. -/
noncomputable def isoMapHomeomorph {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (e : X ≅ Y) (h : e.hom ≫ structureMapY = structureMap) :
    @Homeomorph (Point K X structureMap) (Point K Y structureMapY)
      analyticTopology analyticTopology := by
  let _ : TopologicalSpace (Point K X structureMap) := analyticTopology
  let _ : TopologicalSpace (Point K Y structureMapY) := analyticTopology
  exact
    { toFun := map e.hom h
      invFun := map e.inv (by
        rw [← h, ← Category.assoc, e.inv_hom_id, Category.id_comp])
      left_inv z := by
        apply Subtype.ext
        simp [map, Category.assoc]
      right_inv z := by
        apply Subtype.ext
        simp [map, Category.assoc]
      continuous_toFun := continuous_map e.hom h
      continuous_invFun := continuous_map e.inv (by
        rw [← h, ← Category.assoc, e.inv_hom_id, Category.id_comp]) }

@[simp]
lemma isoMapHomeomorph_apply {Y : Scheme} {structureMapY : Y ⟶ Spec ↧K}
    (e : X ≅ Y) (h : e.hom ≫ structureMapY = structureMap)
    (z : Point K X structureMap) :
    isoMapHomeomorph e h z = map e.hom h z :=
  rfl

end Topology

end Point

/-- A complex point of `X` over its given structure morphism to `Spec ℂ`. -/
abbrev ComplexPoint (X : Scheme) (structureMap : X ⟶ Spec ↧ℂ) := Point ℂ X structureMap

/-- Analytification of schemes over `Spec ℂ` as a functor to topological spaces.

This is the canonical home for functorial complex points.  In particular, consumers need not
package their own morphism records or reprove identity and composition laws. -/
noncomputable def complexAnalytification :
    CategoryTheory.Functor (Over (Spec ↧ℂ)) TopCat where
  obj X := @TopCat.of (ComplexPoint X.left X.hom) Point.analyticTopology
  map f := @TopCat.ofHom _ _ Point.analyticTopology Point.analyticTopology
    (Point.continuousMap f.left (Over.w f))
  map_id X := by
    ext z
    simp [Point.continuousMap, Point.map]
  map_comp f g := by
    ext z
    simp [Point.continuousMap, Point.map, Category.assoc]

/-- An integral projective algebraic variety over `ℂ`. Projectivity is witnessed by an explicit
closed embedding into a finite-dimensional projective space. -/
structure IntegralProjectiveComplexVariety where
  /-- The underlying scheme. -/
  scheme : Scheme
  [isIntegral : IsIntegral scheme]
  /-- The structure morphism to `Spec ℂ`. -/
  structureMap : scheme ⟶ Spec ↧ℂ
  [projective : IsProjective structureMap]

/-- A projective complex scheme is Noetherian. -/
theorem isNoetherian_of_isProjective {X : Scheme} (structureMap : X ⟶ Spec ↧ℂ)
    [IsProjective structureMap] : IsNoetherian X where
  toIsLocallyNoetherian := LocallyOfFiniteType.isLocallyNoetherian structureMap
  toCompactSpace := QuasiCompact.compactSpace_of_compactSpace structureMap

namespace IntegralProjectiveComplexVariety

/-- The integral structure carried by an integral projective complex variety. -/
instance (V : IntegralProjectiveComplexVariety) : IsIntegral V.scheme := V.isIntegral

/-- The projective presentation carried by an integral projective complex variety. -/
instance (V : IntegralProjectiveComplexVariety) :
    IsProjective V.structureMap := V.projective

/-- An integral projective complex variety is Noetherian. -/
noncomputable instance (V : IntegralProjectiveComplexVariety) : IsNoetherian V.scheme :=
  isNoetherian_of_isProjective V.structureMap

/-- The variety regarded as the corresponding object over `Spec ℂ`. -/
noncomputable abbrev over (V : IntegralProjectiveComplexVariety) : Over (Spec ↧ℂ) :=
  Over.mk V.structureMap

/-- The complex points of an integral projective complex variety. -/
abbrev analyticPoint (V : IntegralProjectiveComplexVariety) :=
  ComplexPoint V.scheme V.structureMap

noncomputable instance (V : IntegralProjectiveComplexVariety) :
    TopologicalSpace V.analyticPoint :=
  Point.analyticTopology

/-- The analytification as a topological space. -/
noncomputable def analytification (V : IntegralProjectiveComplexVariety) : TopCat :=
  complexAnalytification.obj V.over

end IntegralProjectiveComplexVariety

end AlgebraicGeometry
