/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Other.AlgebraicTopology.IntegralSingularHomologyFinite
public import Mathlib.Analysis.Convex.Contractible
public import Mathlib.Analysis.Normed.Module.Convex

import Mathlib.Algebra.Category.Grp.EpiMono
import Mathlib.Algebra.EuclideanDomain.Int
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# Finiteness of integral singular homology for compact retracts of open sets

A compact space which is a retract of an open subset of a real normed space has finitely
generated integral singular homology in every degree.

The compact image is covered by finitely many open balls contained in the open neighbourhood;
their union has a finite good cover by those balls (finite intersections of balls are convex,
hence contractible), so its integral singular homology is finitely generated by
`FiniteGoodCover.integralSingularHomology_module_finite`.  The retraction exhibits the homology
of the compact space as a direct summand, hence as a submodule of a finitely generated
`ℤ`-module.
-/

@[expose] public noncomputable section

open CategoryTheory CategoryTheory.Limits Metric Set

namespace AlgebraicTopology.Singular

section BallCover

variable {E : Type} [NormedAddCommGroup E] [NormedSpace ℝ E]

omit [NormedSpace ℝ E] in
/-- A compact subset of an open subset of a normed space is covered by finitely many open balls
contained in the open subset. -/
theorem exists_finite_ball_cover_subset {W S : Set E} (hW : IsOpen W) (hS : IsCompact S)
    (hSW : S ⊆ W) :
    ∃ (m : ℕ) (c : Fin m → E) (ε : Fin m → ℝ),
      S ⊆ ⋃ j, ball (c j) (ε j) ∧ ∀ j, ball (c j) (ε j) ⊆ W := by
  have hε : ∀ x : E, ∃ ε : ℝ, 0 < ε ∧ (x ∈ W → ball x ε ⊆ W) := by
    intro x
    by_cases hx : x ∈ W
    · obtain ⟨ε, hε, hball⟩ := Metric.isOpen_iff.1 hW x hx
      exact ⟨ε, hε, fun _ ↦ hball⟩
    · exact ⟨1, one_pos, fun h ↦ (hx h).elim⟩
  choose ε hεpos hεW using hε
  obtain ⟨t, htS, hcover⟩ :=
    hS.elim_nhds_subcover (fun x ↦ ball x (ε x)) fun x _ ↦ ball_mem_nhds x (hεpos x)
  refine ⟨t.card, fun j ↦ (t.equivFin.symm j : E), fun j ↦ ε (t.equivFin.symm j : E), ?_, ?_⟩
  · intro x hx
    obtain ⟨y, hyt, hxy⟩ := mem_iUnion₂.1 (hcover hx)
    refine mem_iUnion.2 ⟨t.equivFin ⟨y, hyt⟩, ?_⟩
    simpa using hxy
  · intro j
    exact hεW _ (hSW (htS _ (t.equivFin.symm j).2))

variable {ι : Type} [LinearOrder ι] [Finite ι] (c : ι → E) (ε : ι → ℝ)

/-- The union of a family of open balls, as a topological space. -/
abbrev ballUnion : TopCat := TopCat.of (⋃ j, ball (c j) (ε j))

/-- The open cover of the union of a family of balls by the balls themselves. -/
def ballUnionCover (j : ι) : Set (ballUnion c ε) :=
  (Subtype.val : (⋃ j, ball (c j) (ε j)) → E) ⁻¹' ball (c j) (ε j)

/-- A nonempty finite intersection of members of the ball cover is homeomorphic to the
corresponding intersection of balls in the ambient normed space. -/
def ballUnionCoverIntersectionHomeomorph (s : Finset ι) (hs : s.Nonempty) :
    openCoverIntersection (ballUnion c ε) (ballUnionCover c ε) s ≃ₜ
      (⋂ j ∈ s, ball (c j) (ε j) : Set E) where
  toFun u := ⟨u.1.1, mem_iInter₂.2 fun j hj ↦
    (mem_openCoverIntersection_iff _ _ _ _).1 u.2 j hj⟩
  invFun x := ⟨⟨x.1, hs.elim fun j hj ↦ mem_iUnion.2 ⟨j, mem_iInter₂.1 x.2 j hj⟩⟩,
    (mem_openCoverIntersection_iff _ _ _ _).2 fun j hj ↦ mem_iInter₂.1 x.2 j hj⟩
  left_inv _ := rfl
  right_inv _ := rfl
  continuous_toFun := (continuous_subtype_val.comp continuous_subtype_val).subtype_mk _
  continuous_invFun := (continuous_subtype_val.subtype_mk _).subtype_mk _

omit [LinearOrder ι] in
/-- The balls form a finite good cover of their union. -/
theorem ballUnion_finiteGoodCover :
    FiniteGoodCover (ballUnion c ε) (ballUnionCover c ε) where
  finite_index := inferInstance
  isOpen_openSet j := isOpen_ball.preimage continuous_subtype_val
  iUnion_openSet := by
    simp only [ballUnionCover, ← preimage_iUnion]
    exact Subtype.coe_preimage_self _
  contractible_intersection s hs hne := by
    have hconv : Convex ℝ (⋂ j ∈ s, ball (c j) (ε j)) :=
      convex_iInter₂ fun j _ ↦ convex_ball (c j) (ε j)
    have hne' : (⋂ j ∈ s, ball (c j) (ε j)).Nonempty :=
      ⟨_, (ballUnionCoverIntersectionHomeomorph c ε s hs ⟨hne.some, hne.some_mem⟩).2⟩
    have := hconv.contractibleSpace hne'
    exact (ballUnionCoverIntersectionHomeomorph c ε s hs).contractibleSpace

/-- The union of finitely many balls has finitely generated integral singular homology. -/
theorem ballUnion_integralSingularHomology_module_finite (n : ℕ) :
    Module.Finite ℤ ((IntegralSingularChainComplexObj (ballUnion c ε)).homology n) :=
  (ballUnion_finiteGoodCover c ε).integralSingularHomology_module_finite n

end BallCover

section Retract

/-- If `i : K → X` and `r : X → K` are continuous with `r ∘ i = id`, then the integral singular
homology of `K` embeds into that of `X`; hence it is finitely generated whenever that of `X`
is. -/
theorem module_finite_homology_of_retract_topCat {K X : TopCat} (i : K ⟶ X) (r : X ⟶ K)
    (hr : i ≫ r = 𝟙 K) (n : ℕ)
    [Module.Finite ℤ ((IntegralSingularChainComplexObj X).homology n)] :
    Module.Finite ℤ ((IntegralSingularChainComplexObj K).homology n) := by
  have hcomp : HomologicalComplex.homologyMap (integralSingularChainMapObj i) n ≫
      HomologicalComplex.homologyMap (integralSingularChainMapObj r) n = 𝟙 _ := by
    rw [← HomologicalComplex.homologyMap_comp, integralSingularChainMapObj,
      integralSingularChainMapObj, ← CategoryTheory.Functor.map_comp, hr,
      CategoryTheory.Functor.map_id,
      HomologicalComplex.homologyMap_id]
  have hinj : Function.Injective
      (HomologicalComplex.homologyMap (integralSingularChainMapObj i) n).hom := by
    refine Function.LeftInverse.injective
      (g := (HomologicalComplex.homologyMap (integralSingularChainMapObj r) n).hom) fun x ↦ ?_
    have := congrArg (fun φ ↦ φ.hom x) hcomp
    simpa using this
  have : IsNoetherian ℤ ((IntegralSingularChainComplexObj X).homology n) :=
    isNoetherian_of_isNoetherianRing_of_finite ℤ _
  exact Module.Finite.of_injective
    (HomologicalComplex.homologyMap (integralSingularChainMapObj i) n).hom.toIntLinearMap hinj

variable {E : Type} [NormedAddCommGroup E] [NormedSpace ℝ E]
variable {K : Type} [TopologicalSpace K] [CompactSpace K]

/-- A compact space which is a retract of an open subset of a real normed space has finitely
generated integral singular homology in every degree (for the `AddCommGrpCat`-valued singular
chain complex). -/
theorem module_finite_homology_of_retract (i : C(K, E)) {W : Set E} (hWopen : IsOpen W)
    (hW : Set.range i ⊆ W) (r : C(W, K)) (hr : ∀ k, r ⟨i k, hW (Set.mem_range_self k)⟩ = k)
    (n : ℕ) :
    Module.Finite ℤ ((IntegralSingularChainComplexObj (TopCat.of K)).homology n) := by
  obtain ⟨m, c, ε, hcover, hballW⟩ :=
    exists_finite_ball_cover_subset hWopen (isCompact_range i.continuous) hW
  have hUW : (⋃ j, ball (c j) (ε j)) ⊆ W := iUnion_subset hballW
  let i' : TopCat.of K ⟶ ballUnion c ε :=
    TopCat.ofHom ⟨fun k ↦ ⟨i k, hcover (Set.mem_range_self k)⟩, i.continuous.subtype_mk _⟩
  let r' : ballUnion c ε ⟶ TopCat.of K :=
    TopCat.ofHom ⟨fun u ↦ r ⟨u.1, hUW u.2⟩,
      r.continuous.comp (continuous_subtype_val.subtype_mk _)⟩
  have hir : i' ≫ r' = 𝟙 _ := by
    ext k
    exact hr k
  have := ballUnion_integralSingularHomology_module_finite c ε n
  exact module_finite_homology_of_retract_topCat i' r' hir n

/-- A compact space which is a retract of an open subset of a real normed space has finitely
generated integral singular homology in every degree (for the `ModuleCat ℤ`-valued singular
chain complex). -/
theorem module_finite_scalarHomology_of_retract (i : C(K, E)) {W : Set E} (hWopen : IsOpen W)
    (hW : Set.range i ⊆ W) (r : C(W, K)) (hr : ∀ k, r ⟨i k, hW (Set.mem_range_self k)⟩ = k)
    (n : ℕ) :
    Module.Finite ℤ
      (((TopCat.toSSet.obj (TopCat.of K)).chainComplex (ModuleCat.of ℤ ℤ)).homology n) :=
  module_finite_scalarHomology_of_module_finite_integralHomology _ n
    (module_finite_homology_of_retract i hWopen hW r hr n)

end Retract

end AlgebraicTopology.Singular
