/-
Copyright (c) 2026 Bhargav Mehta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bhavik Mehta
-/
module

public import Mathlib.FieldTheory.PrimitiveElement
public import Mathlib.RingTheory.Adjoin.FG
public import Mathlib.RingTheory.Localization.Integral
public import Mathlib.RingTheory.Localization.Finiteness

@[expose] public section

namespace Algebra

variable (R K L : Type*) [CommRing R] [IsDomain R] [Field K] [Field L]
  [Algebra R K] [IsFractionRing R K] [Algebra K L] [Algebra R L]
  [IsScalarTower R K L] [FiniteDimensional K L] [Algebra.IsSeparable K L]

/-- A finite separable extension of the fraction field admits an integral primitive generator. -/
theorem exists_integral_primitive_element :
    ∃ y : L, IsIntegral R y ∧ Algebra.adjoin K {y} = ⊤ := by
  let b := Field.powerBasisOfFiniteOfSeparable K L
  obtain ⟨m, hm⟩ := (b.isIntegral_gen).exists_multiple_integral_of_isLocalization
    (R := R) (nonZeroDivisors R) b.gen
  refine ⟨m • b.gen, hm, ?_⟩
  apply top_unique
  rw [← b.adjoin_gen_eq_top]
  apply Algebra.adjoin_le
  intro x hx
  obtain rfl : x = b.gen := Set.mem_singleton_iff.mp hx
  have hmem := (Algebra.adjoin K {m • b.gen}).smul_mem
    (Algebra.subset_adjoin (Set.mem_singleton _))
    ((algebraMap R K (m : R))⁻¹)
  have hne : algebraMap R K (m : R) ≠ 0 :=
    by
      rw [← map_zero (algebraMap R K)]
      exact (IsFractionRing.injective R K).ne (nonZeroDivisors.ne_zero m.property)
  have hy : m • b.gen = (algebraMap R K (m : R)) • b.gen := by
    rw [Submonoid.smul_def]
    exact (IsScalarTower.algebraMap_smul K (m : R) b.gen).symm
  rw [hy] at hmem ⊢
  simp only [smul_smul, inv_mul_cancel₀ hne, one_smul] at hmem
  exact hmem

omit [IsDomain R] [FiniteDimensional K L] [Algebra.IsSeparable K L] in
/-- Finitely many elements admit a common denominator into an order whose generator is
primitive over the fraction field. -/
theorem exists_common_denominator_of_adjoin_eq_top (y : L)
    (hy : Algebra.adjoin K {y} = ⊤) (s : Finset L) :
    ∃ r : nonZeroDivisors R, ∀ x ∈ s, r • x ∈ Algebra.adjoin R {y} := by
  classical
  induction s using Finset.induction with
  | empty =>
      exact ⟨1, by simp⟩
  | @insert a s ha ih =>
      obtain ⟨ra, hra⟩ := multiple_mem_adjoin_of_mem_localization_adjoin
        (nonZeroDivisors R) K {y} a (by rw [hy]; trivial)
      obtain ⟨rs, hrs⟩ := ih
      refine ⟨ra * rs, fun x hx ↦ ?_⟩
      rw [Finset.mem_insert] at hx
      rcases hx with rfl | hx
      · rw [Submonoid.smul_def, Submonoid.coe_mul, mul_comm, mul_smul]
        apply (Algebra.adjoin R {y}).smul_mem
        simpa only [Submonoid.smul_def] using hra
      · rw [Submonoid.smul_def, Submonoid.coe_mul, mul_smul]
        apply (Algebra.adjoin R {y}).smul_mem
        simpa only [Submonoid.smul_def] using hrs x hx


/-- The integral primitive generator can be chosen so that every element of the extension
can be cleared into the order it generates over the base domain. -/
theorem exists_integral_primitive_element_and_denominators :
    ∃ y : L, IsIntegral R y ∧ Algebra.adjoin K {y} = ⊤ ∧
      ∀ x : L, ∃ r : nonZeroDivisors R, r • x ∈ Algebra.adjoin R {y} := by
  obtain ⟨y, hy_int, hy⟩ := exists_integral_primitive_element R K L
  refine ⟨y, hy_int, hy, fun x ↦ ?_⟩
  apply multiple_mem_adjoin_of_mem_localization_adjoin (nonZeroDivisors R) K {y} x
  rw [hy]
  trivial

omit [FiniteDimensional K L] [Algebra.IsSeparable K L] in
/-- If a finitely generated order contains a primitive element, then after inverting one
nonzero element of the base it is equal to the order generated by that primitive element.

Both localizations are represented as subalgebras of the common fraction field: adjoining
the inverse of the denominator has the same effect as localizing at its powers. -/
theorem exists_adjoin_inverse_eq_of_fg (S : Subalgebra R L) (hS : S.FG) (y : L)
    (hy : y ∈ S) (hy_primitive : Algebra.adjoin K {y} = ⊤) :
    ∃ r : nonZeroDivisors R,
      Algebra.adjoin R ((S : Set L) ∪ {(algebraMap R L (r : R))⁻¹}) =
        Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹}) := by
  classical
  obtain ⟨s, hs⟩ := hS
  obtain ⟨r, hr⟩ := exists_common_denominator_of_adjoin_eq_top R K L y hy_primitive s
  refine ⟨r, le_antisymm ?_ ?_⟩
  · apply Algebra.adjoin_le
    intro x hx
    rcases hx with hx | hx
    · rw [← hs] at hx
      induction hx using Algebra.adjoin_induction with
      | mem x hx =>
          have hrx : r • x ∈ Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹}) :=
            Algebra.adjoin_mono Set.subset_union_left (hr x hx)
          have hinv : (algebraMap R L (r : R))⁻¹ ∈
              Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹}) :=
            Algebra.subset_adjoin (Set.mem_union_right _ (Set.mem_singleton _))
          have hne : algebraMap R L (r : R) ≠ 0 := by
            rw [IsScalarTower.algebraMap_apply R K L]
            exact (map_ne_zero (algebraMap K L)).2 <|
              by
                rw [← map_zero (algebraMap R K)]
                exact (IsFractionRing.injective R K).ne (nonZeroDivisors.ne_zero r.property)
          have := (Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹})).mul_mem hinv hrx
          change x ∈ Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹})
          simpa only [Submonoid.smul_def, Algebra.smul_def, ← mul_assoc,
            inv_mul_cancel₀ hne, one_mul] using this
      | algebraMap r => exact (Algebra.adjoin R _).algebraMap_mem r
      | add x z _ _ hx hz => exact add_mem hx hz
      | mul x z _ _ hx hz =>
          exact (Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹})).mul_mem hx hz
    · exact Algebra.subset_adjoin (Set.mem_union_right _ hx)
  · apply Algebra.adjoin_le
    intro x hx
    rcases hx with hx | hx
    · rw [Set.mem_singleton_iff] at hx
      subst x
      exact Algebra.subset_adjoin (Set.mem_union_left _ hy)
    · exact Algebra.subset_adjoin (Set.mem_union_right _ hx)

end Algebra
