/-
Copyright (c) 2026 Bhavik Mehta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bhavik Mehta
-/
module

public import Mathlib.FieldTheory.PrimitiveElement
public import Mathlib.RingTheory.MvPolynomial.Basic
public import Mathlib.FieldTheory.Perfect
public import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
public import Mathlib.Data.Complex.Basic
public import Mathlib.RingTheory.Adjoin.FG
public import Mathlib.RingTheory.Localization.Integral
public import Mathlib.RingTheory.Localization.Finiteness
public import Mathlib.RingTheory.NoetherNormalization

@[expose] public section

namespace Algebra

variable (R K L : Type*) [CommRing R] [IsDomain R] [Field K] [Field L]
  [Algebra R K] [IsFractionRing R K] [Algebra K L] [Algebra R L]
  [IsScalarTower R K L] [FiniteDimensional K L] [Algebra.IsSeparable K L]

/-- A finite separable extension of the fraction field admits an integral primitive generator. -/
theorem exists_integral_primitive_element :
    ∃ y : L, IsIntegral R y ∧ Algebra.adjoin K {y} = ⊤ := by
  let b := Field.powerBasisOfFiniteOfSeparable K L
  obtain ⟨m, hm⟩ := (b.isIntegral_gen).exists_multiple_integral_of_isLocalization
    (R := R) (nonZeroDivisors R) b.gen
  refine ⟨m • b.gen, hm, ?_⟩
  apply top_unique
  rw [← b.adjoin_gen_eq_top]
  apply Algebra.adjoin_le
  intro x hx
  obtain rfl : x = b.gen := Set.mem_singleton_iff.mp hx
  have hmem := (Algebra.adjoin K {m • b.gen}).smul_mem
    (Algebra.subset_adjoin (Set.mem_singleton _))
    ((algebraMap R K (m : R))⁻¹)
  have hne : algebraMap R K (m : R) ≠ 0 :=
    by
      rw [← map_zero (algebraMap R K)]
      exact (IsFractionRing.injective R K).ne (nonZeroDivisors.ne_zero m.property)
  have hy : m • b.gen = (algebraMap R K (m : R)) • b.gen := by
    rw [Submonoid.smul_def]
    exact (IsScalarTower.algebraMap_smul K (m : R) b.gen).symm
  rw [hy] at hmem ⊢
  simp only [smul_smul, inv_mul_cancel₀ hne, one_smul] at hmem
  exact hmem

/-- Multiplying a primitive generator by a nonzero base-field scalar preserves the field
it generates. -/
lemma adjoin_smul_eq_top_of_ne {K L : Type*} [Field K] [Field L] [Algebra K L]
    (y : L) (hy : Algebra.adjoin K {y} = ⊤) (c : K) (hc : c ≠ 0) :
    Algebra.adjoin K {c • y} = ⊤ := by
  apply top_unique
  rw [← hy]
  apply Algebra.adjoin_le
  intro x hx
  rw [Set.mem_singleton_iff] at hx
  subst x
  have hmem := (Algebra.adjoin K {c • y}).smul_mem
    (Algebra.subset_adjoin (Set.mem_singleton _)) c⁻¹
  have : y ∈ Algebra.adjoin K {c • y} := by
    simpa only [smul_smul, inv_mul_cancel₀ hc, one_smul] using hmem
  exact this

omit [IsDomain R] [FiniteDimensional K L] [Algebra.IsSeparable K L] in
/-- Finitely many elements admit a common denominator into an order whose generator is
primitive over the fraction field. -/
theorem exists_common_denominator_of_adjoin_eq_top (y : L)
    (hy : Algebra.adjoin K {y} = ⊤) (s : Finset L) :
    ∃ r : nonZeroDivisors R, ∀ x ∈ s, r • x ∈ Algebra.adjoin R {y} := by
  classical
  induction s using Finset.induction with
  | empty =>
      exact ⟨1, by simp⟩
  | @insert a s ha ih =>
      obtain ⟨ra, hra⟩ := multiple_mem_adjoin_of_mem_localization_adjoin
        (nonZeroDivisors R) K {y} a (by rw [hy]; trivial)
      obtain ⟨rs, hrs⟩ := ih
      refine ⟨ra * rs, fun x hx ↦ ?_⟩
      rw [Finset.mem_insert] at hx
      rcases hx with rfl | hx
      · rw [Submonoid.smul_def, Submonoid.coe_mul, mul_comm, mul_smul]
        apply (Algebra.adjoin R {y}).smul_mem
        simpa only [Submonoid.smul_def] using hra
      · rw [Submonoid.smul_def, Submonoid.coe_mul, mul_smul]
        apply (Algebra.adjoin R {y}).smul_mem
        simpa only [Submonoid.smul_def] using hrs x hx


/-- The integral primitive generator can be chosen so that every element of the extension
can be cleared into the order it generates over the base domain. -/
theorem exists_integral_primitive_element_and_denominators :
    ∃ y : L, IsIntegral R y ∧ Algebra.adjoin K {y} = ⊤ ∧
      ∀ x : L, ∃ r : nonZeroDivisors R, r • x ∈ Algebra.adjoin R {y} := by
  obtain ⟨y, hy_int, hy⟩ := exists_integral_primitive_element R K L
  refine ⟨y, hy_int, hy, fun x ↦ ?_⟩
  apply multiple_mem_adjoin_of_mem_localization_adjoin (nonZeroDivisors R) K {y} x
  rw [hy]
  trivial

omit [FiniteDimensional K L] [Algebra.IsSeparable K L] in
/-- If a finitely generated order contains a primitive element, then after inverting one
nonzero element of the base it is equal to the order generated by that primitive element.

Both localizations are represented as subalgebras of the common fraction field: adjoining
the inverse of the denominator has the same effect as localizing at its powers. -/
theorem exists_adjoin_inverse_eq_of_fg (S : Subalgebra R L) (hS : S.FG) (y : L)
    (hy : y ∈ S) (hy_primitive : Algebra.adjoin K {y} = ⊤) :
    ∃ r : nonZeroDivisors R,
      Algebra.adjoin R ((S : Set L) ∪ {(algebraMap R L (r : R))⁻¹}) =
        Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹}) := by
  classical
  obtain ⟨s, hs⟩ := hS
  obtain ⟨r, hr⟩ := exists_common_denominator_of_adjoin_eq_top R K L y hy_primitive s
  refine ⟨r, le_antisymm ?_ ?_⟩
  · apply Algebra.adjoin_le
    intro x hx
    rcases hx with hx | hx
    · rw [← hs] at hx
      induction hx using Algebra.adjoin_induction with
      | mem x hx =>
          have hrx : r • x ∈ Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹}) :=
            Algebra.adjoin_mono Set.subset_union_left (hr x hx)
          have hinv : (algebraMap R L (r : R))⁻¹ ∈
              Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹}) :=
            Algebra.subset_adjoin (Set.mem_union_right _ (Set.mem_singleton _))
          have hne : algebraMap R L (r : R) ≠ 0 := by
            rw [IsScalarTower.algebraMap_apply R K L]
            exact (map_ne_zero (algebraMap K L)).2 <|
              by
                rw [← map_zero (algebraMap R K)]
                exact (IsFractionRing.injective R K).ne (nonZeroDivisors.ne_zero r.property)
          have := (Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹})).mul_mem hinv hrx
          change x ∈ Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹})
          simpa only [Submonoid.smul_def, Algebra.smul_def, ← mul_assoc,
            inv_mul_cancel₀ hne, one_mul] using this
      | algebraMap r => exact (Algebra.adjoin R _).algebraMap_mem r
      | add x z _ _ hx hz => exact add_mem hx hz
      | mul x z _ _ hx hz =>
          exact (Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹})).mul_mem hx hz
    · exact Algebra.subset_adjoin (Set.mem_union_right _ hx)
  · apply Algebra.adjoin_le
    intro x hx
    rcases hx with hx | hx
    · rw [Set.mem_singleton_iff] at hx
      subst x
      exact Algebra.subset_adjoin (Set.mem_union_left _ hy)
    · exact Algebra.subset_adjoin (Set.mem_union_right _ hx)

omit [FiniteDimensional K L] [Algebra.IsSeparable K L] in
/-- A finite order containing an integral primitive element becomes monogenic after one
localization, and its monogenic model is the quotient by the monic minimal polynomial. -/
theorem exists_adjoin_inverse_eq_and_minpoly_quotient_of_finite
    [IsIntegrallyClosed R] [Module.IsTorsionFree R L]
    (S : Subalgebra R L) [Module.Finite R S] (y : L)
    (hy : y ∈ S) (hy_integral : IsIntegral R y)
    (hy_primitive : Algebra.adjoin K {y} = ⊤) :
    ∃ r : nonZeroDivisors R,
      Algebra.adjoin R ((S : Set L) ∪ {(algebraMap R L (r : R))⁻¹}) =
          Algebra.adjoin R ({y} ∪ {(algebraMap R L (r : R))⁻¹}) ∧
        (minpoly R y).Monic ∧
        Nonempty (AdjoinRoot (minpoly R y) ≃ₐ[R] Algebra.adjoin R ({y} : Set L)) := by
  have hS : S.FG := (Subalgebra.fg_top S).mp <|
    Subalgebra.fg_of_submodule_fg (Module.Finite.fg_top (R := R) (M := S))
  obtain ⟨r, hr⟩ := exists_adjoin_inverse_eq_of_fg R K L S hS y hy hy_primitive
  exact ⟨r, hr, minpoly.monic hy_integral, ⟨minpoly.equivAdjoin hy_integral⟩⟩

end Algebra

namespace Algebra

/-- A Noether-normalization map for a finite-type integral complex algebra, together with
the finiteness datum used to transport the algebra structure downstream. -/
structure ComplexNoetherNormalization (A : Type*) [CommRing A] [Algebra ℂ A] where
  dimension : ℕ
  hom : MvPolynomial (Fin dimension) ℂ →ₐ[ℂ] A
  injective : Function.Injective hom
  finite : hom.Finite

variable (A : Type*) [CommRing A] [IsDomain A] [Algebra ℂ A]
  [Algebra.FiniteType ℂ A]

/-- Every finite-type integral complex algebra has a polynomial subalgebra over which it is
finite. The bundled result retains both the chosen map and its injectivity, which are needed
when passing to fraction fields. -/
theorem exists_complexNoetherNormalization : Nonempty (ComplexNoetherNormalization A) := by
  obtain ⟨n, g, hinj, hfinite⟩ := exists_finite_inj_algHom_of_fg ℂ A
  exact ⟨⟨n, g, hinj, hfinite⟩⟩

end Algebra
namespace Algebra
variable (A : Type*) [CommRing A] [IsDomain A] [Algebra ℂ A]

@[instance_reducible] noncomputable def ComplexNoetherNormalization.fractionFieldAlgebra
    (N : ComplexNoetherNormalization A) :
    Algebra (FractionRing (MvPolynomial (Fin N.dimension) ℂ)) (FractionRing A) := by
  let P := MvPolynomial (Fin N.dimension) ℂ
  letI : Algebra P A := N.hom.toAlgebra
  letI : Module.Finite P A := N.finite
  letI : FaithfulSMul P A :=
    (faithfulSMul_iff_algebraMap_injective P A).mpr N.injective
  letI : SMul P (FractionRing A) :=
    (Algebra.compHom (FractionRing A) N.hom.toRingHom).toSMul
  letI : Algebra P (FractionRing A) :=
    Algebra.compHom (FractionRing A) N.hom.toRingHom
  letI : FaithfulSMul P (FractionRing A) :=
    (faithfulSMul_iff_algebraMap_injective P (FractionRing A)).mpr
      ((FaithfulSMul.algebraMap_injective A (FractionRing A)).comp N.injective)
  exact FractionRing.liftAlgebra P (FractionRing A)

theorem ComplexNoetherNormalization.finiteDimensionalFractionFields
    (N : ComplexNoetherNormalization A) :
    @FiniteDimensional (FractionRing (MvPolynomial (Fin N.dimension) ℂ)) (FractionRing A)
      _ _ N.fractionFieldAlgebra.toModule := by
  let P := MvPolynomial (Fin N.dimension) ℂ
  let : Algebra P A := N.hom.toAlgebra
  let : Module.Finite P A := N.finite
  let : FaithfulSMul P A :=
    (faithfulSMul_iff_algebraMap_injective P A).mpr N.injective
  let : SMul P (FractionRing A) :=
    (Algebra.compHom (FractionRing A) N.hom.toRingHom).toSMul
  let : Algebra P (FractionRing A) :=
    Algebra.compHom (FractionRing A) N.hom.toRingHom
  let : FaithfulSMul P (FractionRing A) :=
    (faithfulSMul_iff_algebraMap_injective P (FractionRing A)).mpr
      ((FaithfulSMul.algebraMap_injective A (FractionRing A)).comp N.injective)
  let : Algebra (FractionRing P) (FractionRing A) :=
    FractionRing.liftAlgebra P (FractionRing A)
  exact (inferInstance : @FiniteDimensional (FractionRing P) (FractionRing A) _ _
    (FractionRing.liftAlgebra P (FractionRing A)).toModule)
end Algebra
namespace Algebra
variable (A : Type*) [CommRing A] [IsDomain A] [Algebra ℂ A]

theorem ComplexNoetherNormalization.separableFractionFields
    (N : ComplexNoetherNormalization A) :
    @Algebra.IsSeparable (FractionRing (MvPolynomial (Fin N.dimension) ℂ)) (FractionRing A)
      _ _ N.fractionFieldAlgebra := by
  let P := MvPolynomial (Fin N.dimension) ℂ
  let : Algebra P A := N.hom.toAlgebra
  let : Module.Finite P A := N.finite
  let : FaithfulSMul P A := (faithfulSMul_iff_algebraMap_injective P A).mpr N.injective
  let : SMul P (FractionRing A) := (Algebra.compHom (FractionRing A) N.hom.toRingHom).toSMul
  let : Algebra P (FractionRing A) := Algebra.compHom (FractionRing A) N.hom.toRingHom
  let : FaithfulSMul P (FractionRing A) := (faithfulSMul_iff_algebraMap_injective P (FractionRing A)).mpr ((FaithfulSMul.algebraMap_injective A (FractionRing A)).comp N.injective)
  let : Algebra (FractionRing P) (FractionRing A) := FractionRing.liftAlgebra P (FractionRing A)
  let : FiniteDimensional (FractionRing P) (FractionRing A) := N.finiteDimensionalFractionFields
  let : Module.Finite (FractionRing P) (FractionRing A) := inferInstance
  let : CharZero P := by infer_instance
  let : CharZero (FractionRing P) := IsFractionRing.charZero P
  let : PerfectField (FractionRing P) := PerfectField.ofCharZero
  let : Algebra.IsAlgebraic (FractionRing P) (FractionRing A) := Algebra.IsAlgebraic.of_finite _ _
  exact inferInstance

/-- A complex Noether normalization admits a primitive numerator in the original algebra.
After inverting one nonzero polynomial, the image of the algebra in its fraction field is
the order generated by this numerator; that order is presented by its monic minimal
polynomial. -/
theorem ComplexNoetherNormalization.exists_primitive_numerator_localized_presentation
    (N : ComplexNoetherNormalization A) :
    let P := MvPolynomial (Fin N.dimension) ℂ
    let K := FractionRing P
    let L := FractionRing A
    letI : Algebra P A := N.hom.toAlgebra
    letI : Algebra P L := Algebra.compHom L N.hom.toRingHom
    letI : Algebra K L := N.fractionFieldAlgebra
    let f : A →ₐ[P] L :=
      { algebraMap A L with commutes' := fun _ ↦ rfl }
    let S : Subalgebra P L := f.range
    ∃ (a : A) (y : L) (r : nonZeroDivisors P),
      y = algebraMap A L a ∧ IsIntegral P y ∧ Algebra.adjoin K {y} = ⊤ ∧ y ∈ S ∧
      Algebra.adjoin P ((S : Set L) ∪ {(algebraMap P L (r : P))⁻¹}) =
        Algebra.adjoin P ({y} ∪ {(algebraMap P L (r : P))⁻¹}) ∧
      (minpoly P y).Monic ∧
      Nonempty (AdjoinRoot (minpoly P y) ≃ₐ[P] Algebra.adjoin P ({y} : Set L)) := by
  let P := MvPolynomial (Fin N.dimension) ℂ
  let K := FractionRing P
  let L := FractionRing A
  let : Algebra P A := N.hom.toAlgebra
  let : Module.Finite P A := N.finite
  let : FaithfulSMul P A :=
    (faithfulSMul_iff_algebraMap_injective P A).mpr N.injective
  let : SMul P L := (Algebra.compHom L N.hom.toRingHom).toSMul
  let : Algebra P L := Algebra.compHom L N.hom.toRingHom
  let : FaithfulSMul P L :=
    (faithfulSMul_iff_algebraMap_injective P L).mpr
      ((FaithfulSMul.algebraMap_injective A L).comp N.injective)
  let : Algebra K L := N.fractionFieldAlgebra
  let : FiniteDimensional K L := N.finiteDimensionalFractionFields
  let : Algebra.IsSeparable K L := N.separableFractionFields
  let b := Field.powerBasisOfFiniteOfSeparable K L
  obtain ⟨a, s, h⟩ := IsLocalization.exists_mk'_eq
    (Algebra.algebraMapSubmonoid A (nonZeroDivisors P)) b.gen
  obtain ⟨r, hr, hrs⟩ := s.property
  change N.hom r = (s : A) at hrs
  have hmul : algebraMap P L r * b.gen = algebraMap A L a := by
    rw [← h]
    change algebraMap A L (N.hom r) * IsLocalization.mk' L a s = algebraMap A L a
    rw [hrs]
    exact IsLocalization.mk'_spec' L a s
  have hr0 : r ≠ 0 := nonZeroDivisors.ne_zero hr
  have hscalar : (algebraMap P K r) • b.gen = algebraMap A L a := by
    rw [Algebra.smul_def]
    simpa only [IsScalarTower.algebraMap_apply P K L] using hmul
  have hprim : Algebra.adjoin K {algebraMap A L a} = ⊤ := by
    rw [← hscalar]
    exact adjoin_smul_eq_top_of_ne b.gen b.adjoin_gen_eq_top (algebraMap P K r)
      (by
        intro hzero
        apply hr0
        apply IsFractionRing.injective P K
        simpa using hzero)
  have ha : IsIntegral P a := Algebra.IsIntegral.isIntegral a
  obtain ⟨q, hq_monic, hq⟩ := ha
  change Polynomial.eval₂ N.hom.toRingHom a q = 0 at hq
  have hcomp : (algebraMap A L).comp N.hom.toRingHom = algebraMap P L := rfl
  have hint : IsIntegral P (algebraMap A L a) := by
    refine ⟨q, hq_monic, ?_⟩
    rw [← hcomp]
    rw [← Polynomial.hom_eval₂]
    rw [hq, map_zero]
  let f : A →ₐ[P] L :=
    { algebraMap A L with
      commutes' := fun _ ↦ rfl }
  let S : Subalgebra P L := f.range
  let : Module.Finite P S :=
    Module.Finite.of_surjective f.rangeRestrict.toLinearMap f.rangeRestrict_surjective
  have hmem : algebraMap A L a ∈ S := ⟨a, rfl⟩
  obtain ⟨r', hr'eq, hr'monic, hr'equiv⟩ :=
    exists_adjoin_inverse_eq_and_minpoly_quotient_of_finite P K L S
      (algebraMap A L a) hmem hint hprim
  exact ⟨a, algebraMap A L a, r', rfl, hint, hprim, hmem, hr'eq, hr'monic, hr'equiv⟩
end Algebra
