/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import Mathlib.RingTheory.Ideal.Height
public import Mathlib.RingTheory.Regular.RegularSequence

import Mathlib.RingTheory.Ideal.UFD
import Mathlib.RingTheory.KrullDimension.Regular

/-!
# Quotient kernels in regular local rings

This file records two commutative-algebra facts needed to study kernels of maps between regular
local rings. First, the drop in finite Krull dimension is bounded by the minimal number of ideal
generators. Second, a height-one prime in a local unique factorization domain is generated by a
regular sequence of minimal length, and quotienting by it lowers Krull dimension by one.

The corresponding statement for an arbitrary prime whose quotient is regular local needs the
theory that regular local rings are Cohen--Macaulay (or the Auslander--Buchsbaum formula). That
theory is not yet available in Mathlib, so no general complete-intersection claim is made here.
-/

@[expose] public noncomputable section

open IsLocalRing

namespace Ideal

variable {R : Type*} [CommRing R]

/-- In a Noetherian local ring of finite natural dimension, the drop in Krull dimension after
quotienting by a proper ideal is at most the minimal number of generators of that ideal. -/
lemma natCast_ringKrullDim_sub_le_spanFinrank [IsNoetherianRing R] [IsLocalRing R]
    (I : Ideal R) (hI : I ≠ ⊤) {d e : ℕ}
    (hR : ringKrullDim R = d) (hquot : ringKrullDim (R ⧸ I) = e) :
    ((d - e : ℕ) : ℕ∞) ≤ I.spanFinrank := by
  by_cases hed : e ≤ d
  · have hle := ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank I (by
      rw [IsLocalRing.ringJacobson_eq_maximalIdeal]
      exact IsLocalRing.le_maximalIdeal hI)
    rw [hR, hquot] at hle
    have hle' : (d : ℕ∞) ≤ (e : ℕ∞) + I.spanFinrank :=
      WithBot.coe_le_coe.mp hle
    have hdecomp : (d : ℕ∞) = (e : ℕ∞) + ((d - e : ℕ) : ℕ∞) := by
      exact_mod_cast (Nat.add_sub_of_le hed).symm
    rw [hdecomp] at hle'
    exact (ENat.add_le_add_iff_left (ENat.natCast_ne_top e)).mp hle'
  · rw [Nat.sub_eq_zero_of_le (Nat.le_of_not_ge hed)]
    exact bot_le

/-- A nonzero proper principal ideal in a local domain is generated by a regular sequence whose
length is its minimal number of generators. -/
lemma exists_isRegular_of_isPrincipal [IsDomain R] [IsLocalRing R]
    (I : Ideal R) [I.IsPrincipal] (hbot : I ≠ ⊥) (htop : I ≠ ⊤) :
    ∃ rs : List R, Ideal.ofList rs = I ∧ rs.length = I.spanFinrank ∧
      RingTheory.Sequence.IsRegular R rs := by
  let r := Submodule.IsPrincipal.generator I
  have hr0 : r ≠ 0 := by rwa [ne_eq, ← Submodule.IsPrincipal.eq_bot_iff_generator_eq_zero]
  have hrI : r ∈ I := Submodule.IsPrincipal.generator_mem I
  have hrmax : r ∈ maximalIdeal R := IsLocalRing.le_maximalIdeal htop hrI
  have hfinrank : I.spanFinrank = 1 :=
    (Submodule.spanFinrank_eq_one_iff I).2 ⟨inferInstance, hbot⟩
  refine ⟨[r], (Ideal.ofList_singleton r).trans
      (Submodule.IsPrincipal.span_singleton_generator I), by simp [hfinrank], ?_⟩
  rw [IsLocalRing.isRegular_iff_isWeaklyRegular_of_subset_maximalIdeal]
  · exact (RingTheory.Sequence.isWeaklyRegular_singleton_iff R r).2
      (IsRegular.of_ne_zero hr0).isSMulRegular
  · intro x hx
    simp only [List.mem_singleton] at hx
    subst x
    exact hrmax

/-- A height-one prime in a local unique factorization domain is generated by a regular sequence
of minimal length. -/
lemma exists_isRegular_of_isPrime_height_eq_one [IsDomain R] [IsLocalRing R]
    [UniqueFactorizationMonoid R] (I : Ideal R) [I.IsPrime] (hheight : I.height = 1) :
    ∃ rs : List R, Ideal.ofList rs = I ∧ rs.length = I.spanFinrank ∧
      RingTheory.Sequence.IsRegular R rs := by
  let : I.IsPrincipal :=
    UniqueFactorizationMonoid.isPrincipal_of_height_eq_one hheight
  exact I.exists_isRegular_of_isPrincipal (I.ne_bot_of_height_eq_one hheight)
    (Ideal.IsPrime.ne_top (inferInstance : I.IsPrime))

/-- Quotienting a Noetherian local unique factorization domain by a height-one prime lowers its
Krull dimension by one. -/
lemma ringKrullDim_quotient_add_one_eq_of_isPrime_height_eq_one
    [IsDomain R] [IsNoetherianRing R] [IsLocalRing R] [UniqueFactorizationMonoid R]
    (I : Ideal R) [I.IsPrime] (hheight : I.height = 1) :
    ringKrullDim (R ⧸ I) + 1 = ringKrullDim R := by
  let : I.IsPrincipal :=
    UniqueFactorizationMonoid.isPrincipal_of_height_eq_one hheight
  obtain ⟨rs, hrs, hrslen, hregular⟩ :=
    I.exists_isRegular_of_isPrime_height_eq_one hheight
  have hfinrank : I.spanFinrank = 1 :=
    (Submodule.spanFinrank_eq_one_iff I).2
      ⟨inferInstance, I.ne_bot_of_height_eq_one hheight⟩
  have hrslen_one : rs.length = 1 := hrslen.trans hfinrank
  rw [← hrs]
  simpa [hrslen_one] using
    ringKrullDim_add_length_eq_ringKrullDim_of_isRegular rs hregular

end Ideal
