/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import HodgeConjecture.Lemmas.AlgebraicGeometry.Cycle.Support
public import HodgeConjecture.Definitions.AlgebraicGeometry.Cycle.Component.SmoothLocus
public import Mathlib.RingTheory.RegularLocalRing.Defs

import HodgeConjecture.Lemmas.AlgebraicGeometry.Smooth.PointwiseDimension
import HodgeConjecture.Lemmas.AlgebraicGeometry.Cycle.Component.ClosedPointDimension
import HodgeConjecture.Lemmas.AlgebraicGeometry.Cycle.Component.NormalGeometry
import Other.AlgebraicGeometry.Smooth.RegularLocal
public import Other.AlgebraicGeometry.Cycle.Component.ClosedPointDimension
public import Other.AlgebraicGeometry.Cycle.Component.NormalGeometry

/-!
# Local rings of cycle-component immersions

At a smooth point of a reduced cycle component, both the component stalk and its ambient stalk
are regular local rings. The closed-immersion stalk map is surjective, so its quotient by the
kernel is again regular local. The kernel is a finitely generated prime ideal.

This file also proves that the kernel needs at least as many generators as the geometric
codimension. The converse bound, and the theorem that a kernel of this kind is generated by a
regular sequence, are not available in the current commutative-algebra API. Consequently this
file does not assert that the closed immersion is regular or a local complete intersection.
-/

@[expose] public noncomputable section

open CategoryTheory Topology

namespace AlgebraicGeometry

variable (X : Over (Spec ↧ℂ)) [IsIntegral X.left] [Smooth X.hom]
  [IsProjective X.hom] (x : X.left)

omit [IsIntegral X.left] in
/-- The component stalk at a point in the component's smooth locus is regular local. -/
lemma cycleComponent_stalk_isRegularLocalRing_of_mem_smoothLocus
    (z : X.left.pointClosure x)
    (hz : z ∈ cycleComponentSmoothLocus X x) :
    IsRegularLocalRing ((X.left.pointClosure x).presheaf.stalk z) := by
  let c : X.left.pointClosure x ⟶ Spec ↧ℂ :=
    X.left.pointClosureι x ≫ X.hom
  let U : (X.left.pointClosure x).Opens := c.smoothLocus
  let g : U.toScheme ⟶ Spec ↧ℂ := U.ι ≫ c
  let : Smooth g := c.smooth_restrict_smoothLocus
  let zu : U.toScheme := ⟨z, hz⟩
  have hregular : IsRegularLocalRing (U.toScheme.presheaf.stalk zu) :=
    Smooth.isRegularLocalRing_stalk_complex (f := g) zu
  exact @IsRegularLocalRing.of_ringEquiv (U.toScheme.presheaf.stalk zu) _ hregular
    ((X.left.pointClosure x).presheaf.stalk z) _
    (U.stalkIso zu).commRingCatIsoToRingEquiv

omit [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] in
/-- The ambient stalk at a point of a cycle component in a smooth complex variety is regular
local. -/
lemma cycleComponent_ambient_stalk_isRegularLocalRing
    {d : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : X.left.pointClosure x) :
    IsRegularLocalRing
      (X.left.presheaf.stalk (X.left.pointClosureι x z)) :=
  SmoothOfRelativeDimension.isRegularLocalRing_stalk_complex
    (d := d) (f := X.hom) (X.left.pointClosureι x z)

omit [IsIntegral X.left] in
/-- At a smooth component point, the quotient of the ambient stalk by the kernel of the
closed-immersion stalk map is regular local. -/
lemma cycleComponent_stalkMap_quotient_isRegularLocalRing_of_mem_smoothLocus
    (z : X.left.pointClosure x)
    (hz : z ∈ cycleComponentSmoothLocus X x) :
    IsRegularLocalRing
      (X.left.presheaf.stalk (X.left.pointClosureι x z) ⧸
        RingHom.ker ((X.left.pointClosureι x).stalkMap z).hom) := by
  have hsurj := (X.left.pointClosureι x).stalkMap_surjective z
  have hregular := cycleComponent_stalk_isRegularLocalRing_of_mem_smoothLocus X x z hz
  exact @IsRegularLocalRing.of_ringEquiv
    ((X.left.pointClosure x).presheaf.stalk z) _ hregular _ _
    (RingHom.quotientKerEquivOfSurjective hsurj).symm

omit [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] in
/-- The kernel of the cycle-component stalk map is finitely generated. -/
lemma cycleComponent_stalkMap_ker_fg
    {d : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : X.left.pointClosure x) :
    (RingHom.ker ((X.left.pointClosureι x).stalkMap z).hom).FG := by
  have _ : IsRegularLocalRing
      (X.left.presheaf.stalk (X.left.pointClosureι x z)) :=
    cycleComponent_ambient_stalk_isRegularLocalRing (d := d) X x z
  exact (RingHom.ker
    ((X.left.pointClosureι x).stalkMap z).hom).fg_of_isNoetherianRing

/-- The kernel of the cycle-component stalk map is prime. -/
lemma cycleComponent_stalkMap_ker_isPrime {X : Scheme} (x : X) (z : X.pointClosure x) :
    (RingHom.ker ((X.pointClosureι x).stalkMap z).hom).IsPrime :=
  RingHom.ker_isPrime _

/-- At a complex point of a codimension-`p` component in a smooth complex `d`-fold, the quotient
of the ambient stalk by the stalk-map kernel has Krull dimension `d - p`. -/
lemma ringKrullDim_cycleComponent_stalkMap_quotient
    {d p : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : ComplexPoint (cycleComponentOver X x))
    (hx : Order.coheight x = p) :
    ringKrullDim
      (X.left.presheaf.stalk (X.left.pointClosureι x z.underlying) ⧸
        RingHom.ker ((X.left.pointClosureι x).stalkMap z.underlying).hom) =
      d - p := by
  have hsurj := (X.left.pointClosureι x).stalkMap_surjective z.underlying
  calc
    ringKrullDim
        (X.left.presheaf.stalk (X.left.pointClosureι x z.underlying) ⧸
          RingHom.ker ((X.left.pointClosureι x).stalkMap z.underlying).hom) =
        ringKrullDim ((X.left.pointClosure x).presheaf.stalk z.underlying) :=
      ringKrullDim_eq_of_ringEquiv (RingHom.quotientKerEquivOfSurjective hsurj)
    _ = Order.coheight z.underlying := ringKrullDim_stalk_eq_coheight z.underlying
    _ = d - p := congrArg (fun n : ℕ∞ ↦ (↑n : WithBot ℕ∞))
      (cycleComponent_complexPoint_coheight_eq_sub
        (d := d) (p := p) X x z hx)

/-- The ambient stalk at the image of a complex component point has Krull dimension `d`. -/
lemma ringKrullDim_cycleComponent_ambient_stalk
    {d : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : ComplexPoint (cycleComponentOver X x)) :
    ringKrullDim
      (X.left.presheaf.stalk (X.left.pointClosureι x z.underlying)) = d := by
  rw [ringKrullDim_stalk_eq_coheight]
  have hclosed := cycleComponent_complexPoint_ambient_underlying_isClosed X x z
  have hsum := SmoothOfRelativeDimension.height_add_coheight_eq_of_isClosed
    (f := X.hom) (d := d)
    (X.left.pointClosureι x z.underlying) hclosed
  have hmin : IsMin (X.left.pointClosureι x z.underlying) := by
    intro y hy
    have hy' : y ∈ closure {X.left.pointClosureι x z.underlying} := by
      rw [← specializes_iff_mem_closure, ← Scheme.le_iff_specializes]
      exact hy
    rw [hclosed.closure_eq] at hy'
    exact (Set.mem_singleton_iff.mp hy').ge
  have hheight : Order.height (X.left.pointClosureι x z.underlying) = 0 :=
    Order.IsMin.height_eq_zero hmin
  rw [hheight, zero_add] at hsum
  exact_mod_cast hsum

/-- The minimal number of generators of the stalk-map kernel is at least the geometric
codimension `p`. -/
lemma cycleComponent_codimension_le_stalkMap_ker_spanFinrank
    {d p : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : ComplexPoint (cycleComponentOver X x))
    (hx : Order.coheight x = p) :
    (p : ℕ∞) ≤ Submodule.spanFinrank
      (RingHom.ker ((X.left.pointClosureι x).stalkMap z.underlying).hom) := by
  let R := X.left.presheaf.stalk (X.left.pointClosureι x z.underlying)
  let I : Ideal R :=
    RingHom.ker ((X.left.pointClosureι x).stalkMap z.underlying).hom
  let : IsRegularLocalRing R :=
    cycleComponent_ambient_stalk_isRegularLocalRing (d := d) X x z.underlying
  have hI : I ≤ Ring.jacobson R := by
    rw [IsLocalRing.ringJacobson_eq_maximalIdeal]
    exact IsLocalRing.le_maximalIdeal (RingHom.ker_ne_top _)
  have hle := ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank I hI
  rw [ringKrullDim_cycleComponent_ambient_stalk (d := d) X x z,
    ringKrullDim_cycleComponent_stalkMap_quotient
      (d := d) (p := p) X x z hx] at hle
  have hle' : (d : ℕ∞) ≤ ((d - p : ℕ) : ℕ∞) + I.spanFinrank := WithBot.coe_le_coe.mp hle
  have hp : p ≤ d := cycleComponent_codimension_le X x hx
  have hdecomp : (d : ℕ∞) = ((d - p : ℕ) : ℕ∞) + (p : ℕ∞) := by
    exact_mod_cast (Nat.sub_add_cancel hp).symm
  rw [hdecomp] at hle'
  exact (ENat.add_le_add_iff_left (ENat.natCast_ne_top (d - p))).mp hle'

/-- The stalk-map kernel has a finite generating set of minimal size, and that size is at least
the geometric codimension. -/
lemma exists_cycleComponent_stalkMap_ker_generators
    {d p : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : ComplexPoint (cycleComponentOver X x))
    (hx : Order.coheight x = p) :
    ∃ s : Finset (X.left.presheaf.stalk
        (X.left.pointClosureι x z.underlying)),
      Ideal.span (s : Set _) =
          RingHom.ker ((X.left.pointClosureι x).stalkMap z.underlying).hom ∧
        s.card = Submodule.spanFinrank
          (RingHom.ker ((X.left.pointClosureι x).stalkMap z.underlying).hom) ∧
        p ≤ s.card := by
  obtain ⟨s, hcard, hspan⟩ :=
    Submodule.FG.exists_span_finset_card_eq_spanFinrank
      (cycleComponent_stalkMap_ker_fg (d := d) X x z.underlying)
  refine ⟨s, ?_, hcard, ?_⟩
  · rwa [← Ideal.submodule_span_eq]
  · have hle := cycleComponent_codimension_le_stalkMap_ker_spanFinrank
      (d := d) (p := p) X x z hx
    rw [← hcard] at hle
    exact_mod_cast hle

end AlgebraicGeometry
