/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import HodgeConjecture.Lemmas.AlgebraicGeometry.Cycle.Support
public import Mathlib.RingTheory.RegularLocalRing.Defs

import HodgeConjecture.Lemmas.AlgebraicGeometry.Smooth.PointwiseDimension
import HodgeConjecture.Lemmas.AlgebraicGeometry.Smooth.Locus
import HodgeConjecture.Lemmas.AlgebraicGeometry.Cycle.Component.ClosedPointDimension
import HodgeConjecture.Lemmas.AlgebraicGeometry.Cycle.Component.NormalGeometry
import Other.AlgebraicGeometry.Smooth.RegularLocal
public import Other.AlgebraicGeometry.Cycle.Component.ClosedPointDimension
public import Other.AlgebraicGeometry.Cycle.Component.NormalGeometry

/-!
# Local rings of cycle-component immersions

At a smooth point of a reduced cycle component, both the component stalk and its ambient stalk
are regular local rings. The closed-immersion stalk map is surjective, so its quotient by the
kernel is again regular local. The kernel is a finitely generated prime ideal.

This file also proves that the kernel needs at least as many generators as the geometric
codimension. The converse bound, and the theorem that a kernel of this kind is generated by a
regular sequence, are not available in the current commutative-algebra API. Consequently this
file does not assert that the closed immersion is regular or a local complete intersection.
-/

@[expose] public noncomputable section

open CategoryTheory Topology

namespace AlgebraicGeometry

variable {X Y : Over (Spec ↧ℂ)} (i : Y ⟶ X) [IsIntegral X.left] [Smooth X.hom]
  [IsProjective X.hom] [IsIntegral Y.left] [IsClosedImmersion i.left]

omit [IsIntegral X.left] [IsProjective X.hom] [IsIntegral Y.left] in
/-- The stalk of the source at a point of its smooth locus is regular local. -/
lemma closedEmbedding_stalk_isRegularLocalRing_of_mem_smoothLocus
    (z : Y.left)
    (hz : z ∈ (i.left ≫ X.hom).smoothLocus) :
    IsRegularLocalRing ((Y.left).presheaf.stalk z) := by
  let c : Y.left ⟶ Spec ↧ℂ :=
    i.left ≫ X.hom
  let U : (Y.left).Opens := c.smoothLocus
  let g : U.toScheme ⟶ Spec ↧ℂ := U.ι ≫ c
  let : Smooth g := (i.left ≫ X.hom).smooth_restrict_smoothLocus
  let zu : U.toScheme := ⟨z, hz⟩
  have hregular : IsRegularLocalRing (U.toScheme.presheaf.stalk zu) :=
    Smooth.isRegularLocalRing_stalk_complex (f := g) zu
  exact @IsRegularLocalRing.of_ringEquiv (U.toScheme.presheaf.stalk zu) _ hregular
    ((Y.left).presheaf.stalk z) _
    (U.stalkIso zu).commRingCatIsoToRingEquiv

omit [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] [IsIntegral Y.left]
  [IsClosedImmersion i.left] in
/-- The ambient stalk at the image of a point of the source in a smooth complex variety is
regular local. -/
lemma closedEmbedding_ambient_stalk_isRegularLocalRing
    {d : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : Y.left) :
    IsRegularLocalRing
      (X.left.presheaf.stalk (i.left z)) :=
  SmoothOfRelativeDimension.isRegularLocalRing_stalk_complex
    (d := d) (f := X.hom) (i.left z)

omit [IsIntegral X.left] [IsProjective X.hom] [IsIntegral Y.left] in
/-- At a smooth component point, the quotient of the ambient stalk by the kernel of the
closed-immersion stalk map is regular local. -/
lemma closedEmbedding_stalkMap_quotient_isRegularLocalRing_of_mem_smoothLocus
    (z : Y.left)
    (hz : z ∈ (i.left ≫ X.hom).smoothLocus) :
    IsRegularLocalRing
      (X.left.presheaf.stalk (i.left z) ⧸
        RingHom.ker ((i.left).stalkMap z).hom) := by
  have hsurj := (i.left).stalkMap_surjective z
  have hregular := closedEmbedding_stalk_isRegularLocalRing_of_mem_smoothLocus i z hz
  exact @IsRegularLocalRing.of_ringEquiv
    ((Y.left).presheaf.stalk z) _ hregular _ _
    (RingHom.quotientKerEquivOfSurjective hsurj).symm

omit [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] [IsIntegral Y.left]
  [IsClosedImmersion i.left] in
/-- The kernel of the stalk map of a closed embedding is finitely generated. -/
lemma closedEmbedding_stalkMap_ker_fg
    {d : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : Y.left) :
    (RingHom.ker ((i.left).stalkMap z).hom).FG := by
  have _ : IsRegularLocalRing
      (X.left.presheaf.stalk (i.left z)) :=
    closedEmbedding_ambient_stalk_isRegularLocalRing (d := d) i z
  exact (RingHom.ker
    ((i.left).stalkMap z).hom).fg_of_isNoetherianRing

/-- The kernel of the stalk map of a closed immersion is prime. -/
lemma closedImmersion_stalkMap_ker_isPrime {X Z : Scheme} (f : Z ⟶ X) [IsIntegral Z] (z : Z) :
    (RingHom.ker (f.stalkMap z).hom).IsPrime :=
  RingHom.ker_isPrime _

/-- At a complex point of a codimension-`p` closed subvariety in a smooth complex `d`-fold, the quotient
of the ambient stalk by the stalk-map kernel has Krull dimension `d - p`. -/
lemma ringKrullDim_closedEmbedding_stalkMap_quotient
    {d p : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : ComplexPoint (Y))
    (hi : Order.coheight (closedEmbeddingGenericPoint i) = p) :
    ringKrullDim
      (X.left.presheaf.stalk (i.left z.underlying) ⧸
        RingHom.ker ((i.left).stalkMap z.underlying).hom) =
      d - p := by
  have hsurj := (i.left).stalkMap_surjective z.underlying
  calc
    ringKrullDim
        (X.left.presheaf.stalk (i.left z.underlying) ⧸
          RingHom.ker ((i.left).stalkMap z.underlying).hom) =
        ringKrullDim ((Y.left).presheaf.stalk z.underlying) :=
      ringKrullDim_eq_of_ringEquiv (RingHom.quotientKerEquivOfSurjective hsurj)
    _ = Order.coheight z.underlying := ringKrullDim_stalk_eq_coheight z.underlying
    _ = d - p := congrArg (fun n : ℕ∞ ↦ (↑n : WithBot ℕ∞))
      (closedEmbedding_complexPoint_coheight_eq_sub
        (d := d) (p := p) i z hi)

/-- The ambient stalk at the image of a complex point of the source has Krull dimension `d`. -/
lemma ringKrullDim_closedEmbedding_ambient_stalk
    {d : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : ComplexPoint (Y)) :
    ringKrullDim
      (X.left.presheaf.stalk (i.left z.underlying)) = d := by
  rw [ringKrullDim_stalk_eq_coheight]
  have hclosed := closedEmbedding_complexPoint_ambient_underlying_isClosed i z
  have hsum := SmoothOfRelativeDimension.height_add_coheight_eq_of_isClosed
    (f := X.hom) (d := d)
    (i.left z.underlying) hclosed
  have hmin : IsMin (i.left z.underlying) := by
    intro y hy
    have hy' : y ∈ closure {i.left z.underlying} := by
      rw [← specializes_iff_mem_closure, ← Scheme.le_iff_specializes]
      exact hy
    rw [hclosed.closure_eq] at hy'
    exact (Set.mem_singleton_iff.mp hy').ge
  have hheight : Order.height (i.left z.underlying) = 0 :=
    Order.IsMin.height_eq_zero hmin
  rw [hheight, zero_add] at hsum
  exact_mod_cast hsum

/-- The minimal number of generators of the stalk-map kernel is at least the geometric
codimension `p`. -/
lemma closedEmbedding_codimension_le_stalkMap_ker_spanFinrank
    {d p : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : ComplexPoint (Y))
    (hi : Order.coheight (closedEmbeddingGenericPoint i) = p) :
    (p : ℕ∞) ≤ Submodule.spanFinrank
      (RingHom.ker ((i.left).stalkMap z.underlying).hom) := by
  let R := X.left.presheaf.stalk (i.left z.underlying)
  let I : Ideal R :=
    RingHom.ker ((i.left).stalkMap z.underlying).hom
  let : IsRegularLocalRing R :=
    closedEmbedding_ambient_stalk_isRegularLocalRing (d := d) i z.underlying
  have hI : I ≤ Ring.jacobson R := by
    rw [IsLocalRing.ringJacobson_eq_maximalIdeal]
    exact IsLocalRing.le_maximalIdeal (RingHom.ker_ne_top _)
  have hle := ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank I hI
  rw [ringKrullDim_closedEmbedding_ambient_stalk (d := d) i z,
    ringKrullDim_closedEmbedding_stalkMap_quotient
      (d := d) (p := p) i z hi] at hle
  have hle' : (d : ℕ∞) ≤ ((d - p : ℕ) : ℕ∞) + I.spanFinrank := WithBot.coe_le_coe.mp hle
  have hp : p ≤ d := closedEmbedding_codimension_le i hi
  have hdecomp : (d : ℕ∞) = ((d - p : ℕ) : ℕ∞) + (p : ℕ∞) := by
    exact_mod_cast (Nat.sub_add_cancel hp).symm
  rw [hdecomp] at hle'
  exact (ENat.add_le_add_iff_left (ENat.natCast_ne_top (d - p))).mp hle'

/-- The stalk-map kernel has a finite generating set of minimal size, and that size is at least
the geometric codimension. -/
lemma exists_closedEmbedding_stalkMap_ker_generators
    {d p : ℕ} [SmoothOfRelativeDimension d X.hom]
    (z : ComplexPoint (Y))
    (hi : Order.coheight (closedEmbeddingGenericPoint i) = p) :
    ∃ s : Finset (X.left.presheaf.stalk
        (i.left z.underlying)),
      Ideal.span (s : Set _) =
          RingHom.ker ((i.left).stalkMap z.underlying).hom ∧
        s.card = Submodule.spanFinrank
          (RingHom.ker ((i.left).stalkMap z.underlying).hom) ∧
        p ≤ s.card := by
  obtain ⟨s, hcard, hspan⟩ :=
    Submodule.FG.exists_span_finset_card_eq_spanFinrank
      (closedEmbedding_stalkMap_ker_fg (d := d) i z.underlying)
  refine ⟨s, ?_, hcard, ?_⟩
  · rwa [← Ideal.submodule_span_eq]
  · have hle := closedEmbedding_codimension_le_stalkMap_ker_spanFinrank
      (d := d) (p := p) i z hi
    rw [← hcard] at hle
    exact_mod_cast hle

end AlgebraicGeometry
