/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import HodgeConjecture.Statement
public import Mathlib.CategoryTheory.Monoidal.Grp

/-!
# Special cases of the Hodge conjecture

This file states (but does not prove!) special cases of the Hodge conjecture. Three of them
are theorems: the Lefschetz (1,1) theorem, the case of varieties of dimension three or less,
and the case of abelian varieties of dimension five or less. The case of all abelian varieties
is open.

## References

* [P. Deligne, *The Hodge Conjecture*](https://www.claymath.org/wp-content/uploads/2022/02/MPPc.pdf)
* [B. Moonen and Yu. Zarhin, *Hodge classes on abelian varieties of low
  dimension*](https://arxiv.org/abs/math/9901113)
* [E. Markman, *Cycles on abelian 2n-folds of Weil type from secant sheaves on abelian
  n-folds*](https://arxiv.org/abs/2502.03415)
-/

@[expose] public section

open CategoryTheory AlgebraicGeometry ComplexPoint TopologicalSpace

/-- Statement of the **Lefschetz (1,1) theorem**: the Hodge conjecture in codimension one.

This is a theorem. -/
def LefschetzOneOne : Prop :=
  ∀ (X : Over (Spec ↧ℂ)) [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom],
    Hdg^1(X; ℚ) ≤ algebraicCycleClassSpan X 1

/-- Statement of the **Hodge conjecture in dimension at most `n`**.

This is a theorem for `n ≤ 3`. It follows from the Lefschetz (1,1) theorem and the hard
Lefschetz theorem. -/
def HodgeConjectureInDimensionLE (n : ℕ) : Prop :=
  ∀ (X : Over (Spec ↧ℂ)) [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom],
    dim X.left ≤ n → ∀ p : ℕ, Hdg^p(X; ℚ) ≤ algebraicCycleClassSpan X p

/-- Statement of the **Hodge conjecture for abelian varieties**. An abelian variety over `ℂ` is
an integral smooth projective group object over `Spec ℂ`.

This is open. -/
def HodgeConjectureForAbelianVarieties : Prop :=
  ∀ (X : Over (Spec ↧ℂ)) [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] [GrpObj X]
    (p : ℕ),
    Hdg^p(X; ℚ) ≤ algebraicCycleClassSpan X p

/-- Statement of the **Hodge conjecture for abelian varieties of dimension at most `n`**.

This is a theorem for `n ≤ 5`. Moonen and Zarhin showed that the Hodge ring of an abelian
variety of dimension five or less is generated by divisor classes and Weil classes, and Markman
showed that the Weil classes on an abelian fourfold of Weil type are algebraic. -/
def HodgeConjectureForAbelianVarietiesInDimensionLE (n : ℕ) : Prop :=
  ∀ (X : Over (Spec ↧ℂ)) [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] [GrpObj X],
    dim X.left ≤ n → ∀ p : ℕ, Hdg^p(X; ℚ) ≤ algebraicCycleClassSpan X p

end
