/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Other.AlgebraicGeometry.Cycle.Codimension
public import Other.AlgebraicGeometry.DivisorOfRationalSection
public import Mathlib.GroupTheory.QuotientGroup.Defs
public import Mathlib.LinearAlgebra.TensorProduct.Basic

/-!
# Chow groups of schemes

This file defines rational equivalence and Chow groups. A generator of rational equivalence in
codimension `p` is the proper pushforward of the divisor of a nonzero rational function on an
integral Noetherian closed subscheme of codimension `p - 1`.
-/

@[expose] public noncomputable section

open CategoryTheory Order

universe u

namespace AlgebraicGeometry

/-- Data defining one generator of rational equivalence in codimension `p`. -/
structure PrincipalDivisor (X : Scheme.{u}) (p : ℕ) where
  /-- The integral closed subscheme carrying the rational function. -/
  carrier : Scheme.{u}
  /-- Its closed immersion into the ambient scheme. -/
  inclusion : carrier ⟶ X
  [isClosedImmersion : IsClosedImmersion inclusion]
  [isIntegral : IsIntegral carrier]
  [isNoetherian : IsNoetherian carrier]
  /-- The nonzero rational function whose divisor generates the relation. -/
  rationalFunction : carrier.functionField
  rationalFunction_ne_zero : rationalFunction ≠ 0
  /-- The carrier has codimension `p - 1` in the ambient scheme. -/
  genericPoint_codimension : Order.coheight (inclusion (genericPoint carrier)) + 1 = p

namespace PrincipalDivisor

variable {X : Scheme.{u}} {p : ℕ} (D : PrincipalDivisor X p)

/-- The divisor of the rational function as an algebraic cycle on its carrier. -/
def divisor : AlgebraicCycle D.carrier ℤ := by
  let := D.isIntegral
  let := D.isNoetherian
  exact (D.carrier.principalCodimensionOneDivisor D.rationalFunction).1

/-- The proper pushforward of the principal divisor to the ambient scheme. -/
def pushforwardCycle : AlgebraicCycle X ℤ := by
  let := D.isClosedImmersion
  exact AlgebraicCycle.map D.inclusion (fun _ : D.carrier ↦ ()) (fun _ : X ↦ ()) D.divisor

/-- A pushed-forward principal divisor, bundled as a pure codimension-`p` cycle once its purity
has been proved. -/
def pushforward
    (h : ∀ y, D.pushforwardCycle y ≠ 0 → Order.coheight y = p) :
    codimensionCycleSubgroup X p :=
  ⟨D.pushforwardCycle, h⟩

/-- A codimension-zero integral closed carrier in an integral scheme is the whole scheme. -/
theorem inclusion_isIso_of_codimension_one [IsIntegral X] (D : PrincipalDivisor X 1) :
    IsIso D.inclusion := by
  let _ := D.isClosedImmersion
  let _ := D.isIntegral
  have hcodim : Order.coheight (D.inclusion (genericPoint D.carrier)) = 0 := by
    simpa using D.genericPoint_codimension
  have hgeneric : D.inclusion (genericPoint D.carrier) = genericPoint X :=
    eq_genericPoint_of_coheight_zero _ hcodim
  have hrange : Set.range D.inclusion = Set.univ := by
    apply Set.eq_univ_of_forall
    intro x
    have hclosure : closure ({genericPoint X} : Set X) ⊆ Set.range D.inclusion :=
      D.inclusion.isClosedEmbedding.isClosed_range.closure_subset_iff.mpr <| by
        rintro y rfl
        exact ⟨genericPoint D.carrier, hgeneric⟩
    rw [genericPoint_closure X] at hclosure
    exact hclosure trivial
  let _ : Surjective D.inclusion := ⟨Set.range_eq_univ.mp hrange⟩
  exact isIso_of_isClosedImmersion_of_surjective D.inclusion

end PrincipalDivisor

/-- The subgroup generated by proper pushforwards of principal divisors whose carriers have
codimension `p - 1`. -/
def principalDivisorSubgroup (X : Scheme.{u}) (p : ℕ) :
    AddSubgroup (AlgebraicCycle X ℤ) :=
  AddSubgroup.closure (Set.range fun D : PrincipalDivisor X p ↦ D.pushforwardCycle)

/-- Rational equivalences among codimension-`p` cycles. -/
def rationalEquivalenceSubgroup (X : Scheme.{u}) (p : ℕ) :
    AddSubgroup (codimensionCycleSubgroup X p) :=
  (principalDivisorSubgroup X p).comap (codimensionCycleInclusion X p)

lemma mem_rationalEquivalenceSubgroup_iff {X : Scheme.{u}} {p : ℕ}
    (c : codimensionCycleSubgroup X p) :
    c ∈ rationalEquivalenceSubgroup X p ↔ c.1 ∈ principalDivisorSubgroup X p :=
  Iff.rfl

/-- There are no principal-divisor generators in codimension zero. -/
@[simp]
lemma principalDivisorSubgroup_zero (X : Scheme.{u}) :
    principalDivisorSubgroup X 0 = ⊥ := by
  rw [eq_bot_iff]
  unfold principalDivisorSubgroup
  rw [AddSubgroup.closure_le]
  rintro _ ⟨D, rfl⟩
  have h := D.genericPoint_codimension
  simp at h

/-- Rational equivalence is trivial in codimension zero. -/
@[simp]
lemma rationalEquivalenceSubgroup_zero (X : Scheme.{u}) :
    rationalEquivalenceSubgroup X 0 = ⊥ := by
  ext c
  simp only [rationalEquivalenceSubgroup, principalDivisorSubgroup_zero,
    AddSubgroup.mem_comap, AddSubgroup.mem_bot]
  constructor
  · exact fun h ↦ Subtype.ext h
  · rintro rfl
    rfl

/-- The codimension-`p` Chow group: cycles modulo rational equivalence. -/
abbrev ChowGroup (X : Scheme.{u}) (p : ℕ) :=
  codimensionCycleSubgroup X p ⧸ rationalEquivalenceSubgroup X p

/-- The codimension-`p` Chow group with rational coefficients. -/
noncomputable abbrev RationalChowGroup (X : Scheme.{u}) (p : ℕ) :=
  TensorProduct ℤ ℚ (ChowGroup X p)

namespace ChowGroup

variable {X : Scheme.{u}} {p : ℕ}

/-- The class of a codimension-`p` cycle in the Chow group. -/
def mk (c : codimensionCycleSubgroup X p) : ChowGroup X p :=
  QuotientAddGroup.mk c

@[simp]
lemma mk_eq_zero_iff (c : codimensionCycleSubgroup X p) :
    mk c = 0 ↔ c ∈ rationalEquivalenceSubgroup X p :=
  QuotientAddGroup.eq_zero_iff c

end ChowGroup

end AlgebraicGeometry
