import HodgeConjecture.Other.AlgebraicGeometry.SmoothClosedSupportLocalHomology

open AlgebraicTopology.Singular AlgebraicGeometry.ComplexPoint

#check @exists_small_open_supportCohomology_concentrated
#check @smoothClosedSupportCochainConeHomology_isZero_of_ne
#check @smoothClosedSupportNormalCoclass_unique

#print axioms neighborhoodSupportComplementPair
#print axioms univBall_normal_eq_zero_iff
#print axioms exists_flattenedSupportRadius
#print axioms flattenedSupportRadius
#print axioms flattenedSupportRadius_pos
#print axioms ball_flattenedSupportRadius_subset
#print axioms flattenedSupportEmbedding
#print axioms flattenedSupportEmbedding_source
#print axioms flattenedSupportEmbedding_zero
#print axioms flattenedSupportNeighborhood
#print axioms mem_flattenedSupportNeighborhood
#print axioms flattenedSupportNeighborhood_subset_source
#print axioms flattenedSupportHomeomorph
#print axioms flattenedSupportHomeomorph_apply
#print axioms flattenedSupportHomeomorph_coordinates
#print axioms flattenedSupportHomeomorph_mem_support_iff
#print axioms flattenedSupportComplementHomeomorph
#print axioms flattenedSupportPairIso
#print axioms flattenedSupportRelativeHomologyIso
#print axioms flattenedSupportRelativeHomology_isZero_of_ne
#print axioms flattenedSupportNormalClass
#print axioms flattenedSupportNormalClass_normalization
#print axioms flattenedSupportRelativeCohomologyEquiv
#print axioms flattenedSupportRelativeCohomology_isZero_of_ne

#print axioms smoothClosedSupportRestrictionChart
#print axioms smoothClosedSupportRestrictionChart_mem_source
#print axioms smoothClosedSupportRestrictionChart_center
#print axioms smoothClosedSupportRestrictionChart_mem_range_iff
#print axioms smoothClosedSupportNeighborhood
#print axioms mem_smoothClosedSupportNeighborhood
#print axioms smoothClosedSupportNeighborhood_le
#print axioms smoothClosedSupportNeighborhoodPair
#print axioms smoothClosedSupportNeighborhoodPairIso
#print axioms smoothClosedSupportRelativeHomologyIso
#print axioms smoothClosedSupportRelativeHomology_isZero_of_ne
#print axioms smoothClosedSupportNormalClass
#print axioms smoothClosedSupportNormalClass_normalization
#print axioms smoothClosedSupportRelativeCohomologyEquiv
#print axioms smoothClosedSupportNormalCoclass
#print axioms smoothClosedSupportNormalCoclass_apply_class
#print axioms smoothClosedSupportNormalClass_ne_zero
#print axioms span_smoothClosedSupportNormalClass_eq_top
#print axioms smoothClosedSupportNormalCoclass_unique
#print axioms smoothClosedSupportRelativeCohomology_isZero_of_ne
#print axioms smoothClosedSupportCochainConeHomology_isZero_of_ne
#print axioms exists_small_open_supportCohomology_concentrated
