import HodgeConjecture.Other.AlgebraicTopology.SingularChainSheafPushforward

open AlgebraicTopology.Singular

#print axioms stalkPushforward_naturality_additive
#print axioms pushforward_stalk_isZero_of_not_mem_range
#print axioms pushforwardSheafificationComparison
#print axioms pushforwardSheafificationComparison_unit
#print axioms pushforwardSheafificationComparison_naturality
#print axioms pushforward_sheafificationUnit_stalk_isIso_on_range
#print axioms pushforward_sheafificationUnit_stalk_isIso
#print axioms pushforwardSheafificationComparison_isIso
#print axioms closedEmbeddingSheafificationIso

#print axioms singularChain_presheafPushforward_additive
#print axioms singularChain_sheafPushforward_additive
#print axioms openComplementPairPushforward
#print axioms openRelativeSingularChainPushforward
#print axioms singularChainPresheafPushforward
#print axioms singularChainPresheafPushforward_app
#print axioms singularChainPresheafPushforward_boundary
#print axioms singularChainPresheafPushforwardComplex
#print axioms relativeSingularChains_emptySupport_isZero
#print axioms singularChainPresheaf_empty_isZero
#print axioms singularChainPushforwardSheafificationComparison
#print axioms singularChainPushforwardSheafificationComparison_isIso
#print axioms singularChainPushforwardSheafificationIso
#print axioms singularChainSheafPushforward
#print axioms singularChainSheafPushforward_comparison
#print axioms singularChainSheafPushforward_unit
#print axioms singularChainSheafPushforward_unit_app
#print axioms singularChainSheafPushforward_unit_germ
#print axioms singularChainSheafPushforwardRegraded
