import HodgeConjecture.Other.AlgebraicGeometry.ComplexSupportedOrdinaryComparison

#print axioms HomologicalComplex.mapExtendCanonicalIso_eq_bettiMapExtendIso
#print axioms AlgebraicTopology.Singular.topOpenIntersectionPairIso
#print axioms AlgebraicTopology.Singular.topOpenNeighborhoodSupportPairIso
#print axioms AlgebraicTopology.Singular.supportedSingularSupportComplementEquiv_apply
#print axioms AlgebraicTopology.Singular.globalRawCochainIso_comp_topOpenDual
#print axioms AlgebraicTopology.Singular.globalRawCochainIntIso_comp_topOpenDual
#print axioms AlgebraicTopology.Singular.openRawRelativeCochainClass_top
#print axioms AlgebraicTopology.Singular.openRawToSingularCochainSheafComplex_top
#print axioms AlgebraicGeometry.ComplexPoint.complexOpenRawToSheafTop_eq_global
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportedSingularTop_inclusion_of_relative
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveSectionCohomologyEquiv_symm_top
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportedSingularInjectiveHomologyIso_inclusion
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveSectionCohomologyEquiv_inclusion_positive
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveSectionCohomologyEquiv_inclusion_eq_neg_legacy

#check @AlgebraicGeometry.ComplexPoint.complexSupportInjectiveSectionCohomologyEquiv_inclusion_positive
#check @AlgebraicGeometry.ComplexPoint.complexSupportInjectiveSectionCohomologyEquiv_inclusion_eq_neg_legacy
