import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentSingularClosedFiltration

#print axioms topologicalKrullDim_lt_of_isClosed_of_dense_compl

namespace AlgebraicGeometry

#print axioms smoothOfRelativeDimension_resLE_of_isStandardSmooth
#print axioms smoothOfRelativeDimension_affineOpen_of_isStandardSmooth
#print axioms reducedSmoothClosedFiltration
#print axioms reducedSmoothClosedFiltration_zero
#print axioms reducedSmoothClosedFiltration_succ
#print axioms reducedSmoothClosedFiltration_succ_start
#print axioms reducedClosedSingularRemainder_bot
#print axioms reducedSmoothClosedFiltration_bot
#print axioms reducedSmoothClosedFiltration_succ_le
#print axioms reducedSmoothClosedFiltration_antitone
#print axioms reducedSmoothClosedFiltration_le
#print axioms reducedSmoothClosedFiltration_layer
#print axioms reducedSmoothClosedFiltration_succ_lt
#print axioms reducedSmoothClosedFiltration_length
#print axioms reducedSmoothClosedFiltration_eq_bot_of_length_le
#print axioms reducedSmoothClosedFiltration_mem
#print axioms topologicalKrullDim_reducedSingularLocus_lt_of_isReduced
#print axioms topologicalKrullDim_reducedClosedSingularRemainder_eq
#print axioms topologicalKrullDim_reducedClosedSingularRemainder_lt
#print axioms topologicalKrullDim_reducedSmoothClosedFiltration_succ_lt
#print axioms cycleComponentSingularClosedFiltration
#print axioms cycleComponentSingularFiltrationLength
#print axioms cycleComponentSingularClosedFiltration_length
#print axioms cycleComponentSingularFiltrationStratum
#print axioms cycleComponentSingularFiltrationStratumι
#print axioms cycleComponentSingularFiltrationStratumι_isImmersion
#print axioms cycleComponentSingularFiltrationStratum_smooth
#print axioms cycleComponentSingularAmbientClosedFiltration
#print axioms cycleComponentSingularAmbientClosedFiltration_antitone
#print axioms cycleComponentSingularAmbientClosedFiltration_length
#print axioms cycleComponentSingularAmbientClosedFiltration_layer
#print axioms cycleComponentSingularStratumAmbientOpen
#print axioms cycleComponentSingularStratumClosedLift
#print axioms cycleComponentSingularStratumClosedLift_ι
#print axioms range_cycleComponentSingularStratumClosedLift
#print axioms cycleComponentSingularStratumClosedLift_isClosedImmersion
#print axioms cycleComponentSingularStratumAmbientOpen_smoothOfRelativeDimension
#print axioms cycleComponentSingularStratumClosedLift_smooth
#print axioms cycleComponentSingularClosedFiltration_dimension_lt
#print axioms cycleComponentSingularFiltrationStratum_dimension_lt
#print axioms cycleComponentSingularFiltrationStratum_exists_affine_normalCodimension_ge
#print axioms cycleComponentSingularFiltrationStratum_exists_smooth_relativeDimension
#print axioms ComplexPoint.cycleComponentSingularAnalyticClosedFiltration
#print axioms ComplexPoint.cycleComponentSingularAnalyticClosedFiltration_antitone
#print axioms ComplexPoint.cycleComponentSingularAnalyticClosedFiltration_length
#print axioms ComplexPoint.cycleComponentSingularAnalyticClosedFiltration_layer
#print axioms ComplexPoint.cycleComponentSingularStratumClosedLift_complexPoints_range
#print axioms ComplexPoint.cycleComponentSmoothLocus_complexPoints_range_eq_support_sdiff_boundary

#check @cycleComponentSingularFiltrationStratum_exists_smooth_relativeDimension
#check @ComplexPoint.cycleComponentSingularAnalyticClosedFiltration_length
#check @ComplexPoint.cycleComponentSingularAnalyticClosedFiltration_layer

end AlgebraicGeometry
