import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentSupportExtension

open AlgebraicGeometry.ComplexPoint

#print axioms TopCat.Sheaf.toSheafSectionsBetweenOpens_global_comparison
#print axioms TopCat.Sheaf.nestedSupportRestrictionLastComplexIso_g
#print axioms cycleComponentSingularFiltrationSectionCohomology_isZero_of_lt
#print axioms cycleComponentSingularBoundarySectionCohomology_isZero_of_lt
#print axioms cycleComponentSingularBoundarySectionCohomology_isZero_cycleDegree
#print axioms cycleComponentSingularBoundarySectionCohomology_isZero_cycleDegree_succ
#print axioms cycleComponentSingularBoundary_le_support
#print axioms cycleComponentSupportComplement_le_smoothAmbientOpen
#print axioms cycleComponentSupportSectionRestriction
#print axioms cycleComponentSupportSectionRestriction_homology_isIso
#print axioms cycleComponentSupportExtensionIso
#print axioms cycleComponentSupportExtensionIso_hom

#check @cycleComponentSupportExtensionIso
#check @cycleComponentSingularBoundarySectionCohomology_isZero_of_lt
