import HodgeConjecture.Other.AlgebraicGeometry.SmoothClosedCycleClassRationalComparison

open AlgebraicGeometry.ComplexPoint

#print axioms smoothClosedRationalCycleClassMap
#print axioms smoothClosedRationalCycleClass
#print axioms smoothClosedRationalCycleClass_eq_borelMoore
#print axioms smoothClosedRationalCycleClassMap_apply
#print axioms smoothClosedRationalCycleClassMapInCodimension
#print axioms smoothClosedRationalCycleClassInCodimension
#print axioms smoothClosedRationalCycleClassMapInCodimension_apply

-- The public signatures, not only their axiom lists, expose every geometric hypothesis.
#check @smoothClosedRationalCycleClassMap
#check @smoothClosedRationalCycleClassInCodimension
