import HodgeConjecture.Other.AlgebraicGeometry.SingularFiltrationLocalSupportVanishing

#print axioms AlgebraicGeometry.closedImmersionSourceOpenTarget
#print axioms AlgebraicGeometry.closedImmersionSourceOpenTarget_preimage
#print axioms AlgebraicGeometry.closedImmersionSourceOpenLift
#print axioms AlgebraicGeometry.closedImmersionSourceOpenLift_ι
#print axioms AlgebraicGeometry.range_closedImmersionSourceOpenLift
#print axioms AlgebraicGeometry.closedImmersionSourceOpenLift_isClosedImmersion
#print axioms AlgebraicGeometry.ComplexPoint.range_map_of_isImmersion_of_comm
#print axioms AlgebraicTopology.Singular.neighborhoodSupportComplementImageHomeomorph
#print axioms AlgebraicTopology.Singular.neighborhoodSupportPairImageIso
#print axioms AlgebraicTopology.Singular.neighborhoodSupportPairImageCohomologyEquiv
#print axioms AlgebraicGeometry.ComplexPoint.exists_smoothClosedSupportImageNeighborhood
#print axioms AlgebraicGeometry.ComplexPoint.exists_smoothClosedSourceOpenNeighborhood
#print axioms AlgebraicGeometry.ComplexPoint.exists_smoothClosedSourceOpenImageNeighborhood
#print axioms TopCat.Sheaf.openRestriction_homology_isZero_of_cofinal_sections
#print axioms TopCat.Sheaf.sectionCohomology_isZero_of_cofinal_lower_vanishing
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSingularLayer_exists_relativeCohomology_vanishing
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSingularLayer_exists_supportedInjectiveSection_vanishing
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSingularLayerSectionCohomology_isZero_of_lt

#check @AlgebraicGeometry.ComplexPoint.cycleComponentSingularLayerSectionCohomology_isZero_of_lt
#check @AlgebraicGeometry.ComplexPoint.exists_smoothClosedSourceOpenNeighborhood
