import HodgeConjecture.Other.AlgebraicGeometry.HolomorphicClosedImmersionCharts

open AlgebraicTopology.Singular AlgebraicGeometry.ComplexPoint

#check @closedImmersionHolomorphicFlatteningChart
#check @closedImmersionNormalTransitionDerivativeEquiv
#check @exists_open_closedImmersionNormalTransition_coclass_invariance

#print axioms normalBlock
#print axioms normalBlock_apply
#print axioms normal_tangent_derivative_eq_zero
#print axioms normalBlock_leftInverse
#print axioms normalTransition_center_normal
#print axioms normalTransition_tangent_derivative
#print axioms normalTransition_inverse_tangent_derivative
#print axioms normalTransition_derivative_leftInverse
#print axioms normalTransition_derivative_rightInverse
#print axioms normalTransitionDerivativeEquiv
#print axioms normalTransitionDerivativeEquiv_apply
#print axioms normalTransition_hasFDerivAt
#print axioms normalTransitionMap
#print axioms normalTransitionDomain
#print axioms normalTransitionDomain_isOpen
#print axioms normalTransitionMap_zero
#print axioms normalTransitionMap_continuousOn
#print axioms exists_open_normalTransition_localClass_invariance
#print axioms exists_open_normalTransition_relativeHomologyMap_eq
#print axioms exists_open_normalTransition_relativeCohomologyMap_eq

#print axioms OpenPartialHomeomorph.biAnalyticLocus
#print axioms OpenPartialHomeomorph.biAnalyticLocus_isOpen
#print axioms OpenPartialHomeomorph.biAnalyticRestrict
#print axioms OpenPartialHomeomorph.biAnalyticRestrict_apply
#print axioms OpenPartialHomeomorph.biAnalyticRestrict_symm_apply
#print axioms OpenPartialHomeomorph.biAnalyticRestrict_mem_source_iff
#print axioms closedImmersionNormalCoordinatesLinearEquiv
#print axioms closedImmersionNormalCoordinateChange
#print axioms closedImmersionNormalCoordinateChange_mem_source
#print axioms closedImmersionNormalCoordinateChange_center
#print axioms analyticAt_closedImmersionNormalCoordinateChange
#print axioms analyticAt_closedImmersionNormalCoordinateChange_symm
#print axioms closedImmersionHolomorphicFlatteningChart
#print axioms closedImmersionHolomorphicFlatteningChart_apply
#print axioms closedImmersionHolomorphicFlatteningChart_symm_apply
#print axioms closedImmersionHolomorphicFlatteningChart_mem_source
#print axioms closedImmersionHolomorphicFlatteningChart_center
#print axioms closedImmersionHolomorphicFlatteningChart_mem_range_iff
#print axioms closedImmersionHolomorphicFlatteningChart_analytic
#print axioms closedImmersionNormalCoordinateChange_symm_at_chart
#print axioms closedImmersionNormalTransition
#print axioms analyticAt_closedImmersionNormalTransition
#print axioms closedImmersionNormalTransition_preserves_support
#print axioms analyticAt_closedImmersionNormalTransition_symm
#print axioms closedImmersionNormalTransitionDerivativeEquiv
#print axioms closedImmersionNormalTransitionDerivativeEquiv_apply
#print axioms exists_open_closedImmersionNormalTransition_coclass_invariance
