import HodgeConjecture.Other.AlgebraicTopology.SingularChainSheafClosedSupport

open AlgebraicTopology.Singular

#print axioms closedEmbeddingSupport
#print axioms pushforward_openRestriction_closedImage_isZero
#print axioms mapFromPushforward_restrict_closedImage_zero
#print axioms mapFromPushforwardWithClosedSupport
#print axioms mapFromPushforwardWithClosedSupport_inclusion
#print axioms singularChainClosedSupportInclusion
#print axioms singularChainSheafPushforward_restrict_zero
#print axioms singularChainSheafPushforwardWithClosedSupport
#print axioms singularChainSheafPushforwardWithClosedSupport_f_inclusion
#print axioms singularChainSheafPushforwardWithClosedSupport_inclusion
#print axioms singularChainSheafPushforwardWithClosedSupport_unique
#print axioms singularChainSheafPushforwardWithClosedSupport_homology
#print axioms singularChainSheafPushforwardWithClosedSupport_unit
#print axioms singularChainSheafPushforwardWithClosedSupportRegraded
#print axioms singularChainSheafPushforwardWithClosedSupportRegraded_inclusion
