import HodgeConjecture.Other.AlgebraicGeometry.ComplexPointCoclassOrientationComparison

#print axioms AlgebraicGeometry.ComplexPoint.analyticPointLocalHomologyClass_eq_complexLocalOrientation
#print axioms AlgebraicGeometry.ComplexPoint.analyticPointLocalCoclass_apply_complexLocalOrientation
#print axioms AlgebraicGeometry.ComplexPoint.analyticPointLocalCoclass_apply_smul_complexLocalOrientation
#print axioms AlgebraicGeometry.ComplexPoint.eq_analyticPointLocalCoclass_iff
#print axioms AlgebraicGeometry.ComplexPoint.complexOrientationHomologySheafIso_stalk_pointCoclass
