import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentSmoothSupportCoclassSection

/-! Actual open-embedding transport and normalized original-ambient section audit. -/

#print axioms AlgebraicTopology.Singular.neighborhoodSupportPairImageIso_naturality
#print axioms AlgebraicTopology.Singular.neighborhoodSupportPairImageCohomologyEquiv_apply
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologyPresheafOpenIso
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologyPresheafOpenIso_inv_app
#print axioms AlgebraicTopology.Singular.supportOpenEmbeddingSheafificationIso
#print axioms AlgebraicTopology.Singular.supportOpenEmbeddingSheafificationIso_unit
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySheafOpenIso
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySheafOpenIso_unit
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySectionOpenImage
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySectionOpenImage_restrict
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySheafOpenIso_unit_apply
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySectionOnOpen
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySectionOnOpen_restrict
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportOpenImageCoclassSection
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportOpenImageCoclassSection_restrict_chart
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftStructureMap
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftStructureMap_smoothOfRelativeDimension
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLift_codimension
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftCoclassSection
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftAmbientMap
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftAmbientMap_isOpenEmbedding
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftAmbientMap_support
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftAmbientMap_imageOpen
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportCoclassSection
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportCoclassSection_restrict

#check @AlgebraicTopology.Singular.supportRelativeCohomologySheafOpenIso
#check @AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportCoclassSection
#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportOpenImageCoclassSection_restrict_chart
