import HodgeConjecture.Other.AlgebraicGeometry.SheafBorelMoorePointClass

#print axioms TopCat.Sheaf.termwiseToDerivedClosedSupport
#print axioms TopCat.Sheaf.termwiseToDerivedClosedSupport_truncation
#print axioms AlgebraicTopology.Singular.pointChainSource
#print axioms AlgebraicTopology.Singular.pointChainEmbedding
#print axioms AlgebraicTopology.Singular.pointChainEmbedding_isClosedEmbedding
#print axioms AlgebraicTopology.Singular.pointChainEmbedding_support
#print axioms AlgebraicTopology.Singular.pointChainSourceSimplex
#print axioms AlgebraicTopology.Singular.pointChainSourceRelativeSection
#print axioms AlgebraicTopology.Singular.pointChainSourceSheafSection
#print axioms AlgebraicTopology.Singular.pointSupportedChainSection
#print axioms AlgebraicTopology.Singular.pointSupportedChainSection_inclusion
#print axioms AlgebraicTopology.Singular.pointSupportedChainCocycle
#print axioms AlgebraicTopology.Singular.pointSupportedChainCocycle_f_zero
#print axioms AlgebraicGeometry.ComplexPoint.sheafBorelMoorePointSupport
#print axioms AlgebraicGeometry.ComplexPoint.sheafBorelMoorePointSupport_coe
#print axioms AlgebraicGeometry.ComplexPoint.sheafBorelMoorePointMorphism
#print axioms AlgebraicGeometry.ComplexPoint.sheafBorelMoorePointMorphism_underlying
#print axioms AlgebraicGeometry.ComplexPoint.sheafBorelMoorePointClassMap
#print axioms AlgebraicGeometry.ComplexPoint.sheafBorelMoorePointClass
#print axioms AlgebraicGeometry.ComplexPoint.sheafBorelMoorePointSupportedCohomologyClass
