import HodgeConjecture.Other.AlgebraicGeometry.ComplexSheafBorelMoore

#print axioms CategoryTheory.NatTrans.commShift_of_whiskerLeft
#print axioms CategoryTheory.NatTrans.commShift_of_whiskerRight
#print axioms CategoryTheory.NatTrans.mapCochainComplexCommShift
#print axioms CategoryTheory.NatTrans.mapHomotopyCategoryCommShift
#print axioms CategoryTheory.NatTrans.mapHomotopyCategoryPlusCommShift
#print axioms CategoryTheory.NatTrans.rightDerivedFunctorPlus_onInjectives
#print axioms CategoryTheory.NatTrans.rightDerivedFunctorPlusCommShift
#print axioms TopCat.Sheaf.derivedClosedSupportSectionsMap_commShift
#print axioms TopCat.Sheaf.derivedClosedSupportSectionsMap_shift
#print axioms AlgebraicGeometry.ComplexPoint.complexDerivedSupportedCohomologySupportMap
#print axioms AlgebraicGeometry.ComplexPoint.complexAmbientSheafBorelMooreOrientationIso_naturality
#print axioms AlgebraicGeometry.ComplexPoint.complexAmbientSheafBorelMooreHomologyIso_naturality
