import HodgeConjecture.Other.AlgebraicGeometry.ComplexSheafBorelMoore

open AlgebraicGeometry.ComplexPoint

#print axioms complexChainSheafCohomology_concentrated
#print axioms complexChainSheafPlusObject
#print axioms complexChainSheafPlusObject_obj
#print axioms complexAmbientSheafBorelMooreObject
#print axioms ComplexAmbientSheafBorelMooreHomology
#print axioms complexAmbientSheafBorelMooreSupportMap
#print axioms complexAmbientSheafBorelMooreSupportMap_refl
#print axioms complexAmbientSheafBorelMooreSupportMap_comp
#print axioms complexAmbientSheafBorelMooreForgetSupport
#print axioms complexConstantRationalSheafPlusObject
#print axioms ComplexDerivedSupportedCohomology
#print axioms complexChainSheafPlusIsoOfOrientation
#print axioms complexAmbientSheafBorelMooreIsoOfOrientation
#print axioms complexAmbientSheafBorelMooreHomologyIsoOfOrientation
#print axioms complexAmbientSheafBorelMooreCycleDegreeIsoOfOrientation
#print axioms complexOrientationHomologySheafIso
#print axioms complexOrientationHomologySheafIso_stalk_one
#print axioms complexChainSheafDerivedSingleOrientationIso
#print axioms complexChainSheafDerivedSingleOrientationIso_homology
#print axioms complexChainSheafPlusOrientationIso
#print axioms complexAmbientSheafBorelMooreOrientationIso
#print axioms complexAmbientSheafBorelMooreHomologyIso
#print axioms complexAmbientSheafBorelMooreCycleDegreeIso
#print axioms complexDerivedSupportedCohomologySupportMap
#print axioms complexAmbientSheafBorelMooreOrientationIso_naturality
#print axioms complexAmbientSheafBorelMooreHomologyIso_naturality
