import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentSmoothSupportPurity

#print axioms AlgebraicGeometry.cycleComponentSmoothLocusAmbientOpen
#print axioms AlgebraicGeometry.cycleComponentSmoothLocusAmbientOpen_eq_sourceOpenTarget
#print axioms AlgebraicGeometry.cycleComponentSmoothLocusClosedLift
#print axioms AlgebraicGeometry.cycleComponentSmoothLocusClosedLift_isClosedImmersion
#print axioms AlgebraicGeometry.cycleComponentSmoothLocusClosedLift_ι
#print axioms AlgebraicGeometry.range_cycleComponentSmoothLocusClosedLift
#print axioms AlgebraicGeometry.cycleComponentSmoothLocus_smoothOfRelativeDimension
#print axioms AlgebraicGeometry.cycleComponentSmoothLocusAmbientOpen_smoothOfRelativeDimension
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentAnalyticClosedSupport
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothLocusAmbientOpen_analytic_image
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothLocusClosedLift_complexPoints_range
#print axioms TopCat.Sheaf.openRestrictionTopOpen_eq
#print axioms TopCat.Sheaf.openRestrictionTopSectionsIso
#print axioms TopCat.Sheaf.openRestrictionTopSectionComplexIso
#print axioms TopCat.Sheaf.openRestrictionHomologyTopSectionsIso
#print axioms TopCat.Sheaf.openRestrictedLowestSectionCohomologyIso
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportAmbientOpen
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupport_exists_relativeCohomology_vanishing
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupport_exists_supportedInjectiveSection_vanishing
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothRestrictedInjectiveComplex
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothRestrictedInjectiveComplex_isStrictlyGE
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothRestrictedInjectiveComplex_isFlasque
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothRestrictedInjective_homology_isZero_of_ne
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothRestrictedInjective_isGE
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothRestrictedInjective_isLE
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportLowestSectionCohomologyIso
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportLowestSectionCohomologyIso_hom
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportSectionCohomology_isZero_of_lt

#check @AlgebraicGeometry.cycleComponentSmoothLocus_smoothOfRelativeDimension
#check @AlgebraicGeometry.ComplexPoint.cycleComponentSmoothRestrictedInjective_homology_isZero_of_ne
#check @AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportLowestSectionCohomologyIso
