import HodgeConjecture.Other.AlgebraicGeometry.SmoothClosedSupportCohomologySheaf

#print axioms TopCat.Sheaf.supportEvaluationRestriction
#print axioms TopCat.Sheaf.sectionComplexRestriction
#print axioms TopCat.Sheaf.sectionComplexRestriction_extend
#print axioms TopCat.Sheaf.sectionComplexRestrictionExtendConeIso
#print axioms TopCat.Sheaf.supportRestrictionSectionsIntersectionIso
#print axioms TopCat.Sheaf.supportRestrictionSectionsIntersectionIso_restriction
#print axioms TopCat.Sheaf.supportRestrictionSectionsConeIso
#print axioms TopCat.Sheaf.supportedSectionHomologyIsoRestrictionCone
#print axioms TopCat.Sheaf.supportedOutsideSections_isZero_of_le
#print axioms AlgebraicTopology.Singular.openIntersectionSupportComplementHomeomorph
#print axioms AlgebraicTopology.Singular.openIntersectionPairIsoSupportComplement
#print axioms AlgebraicTopology.Singular.supportedRationalSingularSectionCohomologyEquivRelative
#print axioms AlgebraicTopology.Singular.supportedRationalSingularSectionCohomologyEquivSupportComplement
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveComplex
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveComplex_isStrictlyGE
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveSectionCohomologyEquiv
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveComplex_homology_isZero_negative
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveComplex_homology_stalk_isZero_of_not_mem
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedAnalyticSupport
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportInjective_homology_stalk_isZero_of_ne
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportInjective_homology_isZero_of_ne
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportInjective_isGE
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportInjective_isLE

#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportInjective_homology_isZero_of_ne
#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportInjective_isGE
#check @AlgebraicGeometry.ComplexPoint.complexSupportInjectiveSectionCohomologyEquiv
