import HodgeConjecture.Other.AlgebraicTopology.SupportedSingularOrdinaryComparison

#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionConeIsoRelative_connecting
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionCone_signed_inclusion
#print axioms AlgebraicTopology.Singular.openRawRelativeCochainClass
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionCone_connecting_of_relative
#print axioms AlgebraicTopology.Singular.openSingularSheafRestrictionConeCohomologyEquivRelative_symm
#print axioms AlgebraicTopology.Singular.openSingularSheafRestrictionCone_connecting_of_relative
#print axioms TopCat.Sheaf.sectionComplexRestrictionExtendConeIso_connecting
#print axioms AlgebraicTopology.Singular.supportedRationalSingularSectionCohomologyEquivRelative_inclusion
