import HodgeConjecture.Other.AlgebraicGeometry.ComplexLocalHomologyVanishing

#print axioms SSet.chainComplexXZeroIsoCyclesZero
#print axioms SSet.homology₀ε_naturality
#print axioms SSet.homology₀ε_epi_of_vertex
#print axioms TopCat.singularHomology₀ε_naturality
#print axioms TopCat.singularHomology₀ε_epi
#print axioms TopCat.singularHomologyMap_zero_epi
#print axioms TopCat.singularHomologyMap_zero_isIso

open AlgebraicTopology.Singular

#print axioms standardSphereSucc_normalizedChains_exactAt_of_lt
#print axioms standardPuncturedHomology_isZero_of_lt
#print axioms standardPuncturedHomology_isZero_of_dimension_le
#print axioms standardLocalHomology_isZero_of_dimension_lt
#print axioms standardPuncturedPair_nonempty
#print axioms standardPuncturedPair_pathConnectedSpace
#print axioms relativeHomology_zero_isZero_of_pathConnected
#print axioms standardLocalHomology_zero_isZero
#print axioms standardLocalHomology_one_isZero
#print axioms standardLocalHomology_isZero_of_ne
#print axioms chartModelEmbedding_relativeHomologyMap_bijective_degree
#print axioms chartModelEmbeddingRelativeHomologyIso
#print axioms standardComplexLocalHomology_isZero_of_ne
#print axioms localHomology_isZero_of_complexChart
#print axioms AlgebraicGeometry.ComplexPoint.localHomology_isZero_of_ne
#print axioms AlgebraicGeometry.ComplexPoint.singularChainHomologySheaf_isZero_of_ne
