import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentPointCoclassSectionNormalization

/-! Audit of exact point normalization of the GENERAL component section. -/

#print axioms AlgebraicGeometry.cycleComponentSingularClosedFiltration_eq_bot_of_coheight_eq_dimension
#print axioms AlgebraicGeometry.cycleComponentSingularAmbientClosedFiltration_eq_bot_of_coheight_eq_dimension
#print axioms AlgebraicGeometry.cycleComponentSmoothLocusAmbientOpen_eq_top_of_coheight_eq_dimension
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSingularAnalyticClosedFiltration_eq_bot_of_coheight_eq_dimension
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportAmbientOpen_eq_top_of_coheight_eq_dimension
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothLocusAmbientOpen_ι_isIso_of_coheight_eq_dimension
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothLocusAmbientOpen_isProjective_of_coheight_eq_dimension
#print axioms AlgebraicTopology.Singular.pointComplementHomeomorphPairMap
#print axioms AlgebraicTopology.Singular.mem_homeomorphTransportedChart
#print axioms AlgebraicTopology.Singular.chartRadius_homeomorphTransport
#print axioms AlgebraicTopology.Singular.chartModelEmbeddingPair_homeomorphTransport
#print axioms AlgebraicTopology.Singular.localClassOfChart_homeomorphTransport
#print axioms AlgebraicGeometry.ComplexPoint.complexSchemeIsoPointPairMap
#print axioms AlgebraicGeometry.ComplexPoint.complexSchemeIsoPointPairMap_localClass
#print axioms AlgebraicGeometry.ComplexPoint.analyticPointLocalCoclass_schemeIso_pullback
#print axioms AlgebraicGeometry.ComplexPoint.analyticPointCoclassSupportSection
#print axioms AlgebraicGeometry.ComplexPoint.analyticPointCoclassSupportSection_restrict
#print axioms AlgebraicGeometry.ComplexPoint.complexSchemeIsoTopMap
#print axioms AlgebraicGeometry.ComplexPoint.complexSchemeIsoTopMap_isOpenEmbedding
#print axioms AlgebraicGeometry.ComplexPoint.neighborhoodSupportPairImageIso_inv_to_point
#print axioms AlgebraicGeometry.ComplexPoint.analyticPointCoclassSupportSection_schemeIso_transport
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftPointImage
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftPointImage_mem_support
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSupport_eq_singleton_smoothClosedLiftPointImage
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLift_range_eq_singleton
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentPointClosedLift_smoothOfRelativeDimension_zero
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothClosedLiftCoclassSection_eq_oldPoint
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportCoclassSection_eq_point_at_lift
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportCoclassSection_eq_analyticPointCoclass
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportCoclassSection_global_point_normalization

#check @AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportCoclassSection_global_point_normalization
#check @AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupportCoclassSection_eq_analyticPointCoclass
#check @AlgebraicGeometry.ComplexPoint.complexSchemeIsoPointPairMap_localClass
