import HodgeConjecture.Other.AlgebraicTopology.NestedSheafSupportLocalization

open CategoryTheory TopCat.Sheaf

#print axioms kernelCompositionShortComplex
#print axioms kernelCompositionShortComplex_exact
#print axioms kernelCompositionShortComplex_shortExact
#print axioms kernelFactorizationShortComplex
#print axioms kernelCompositionFactorizationIso
#print axioms kernelFactorizationShortComplex_shortExact
#print axioms kernelFactorizationShortComplexMapIso
#print axioms kernelFactorizationShortComplex_map_shortExact
#print axioms sheafSectionsBetweenOpens
#print axioms sheafSectionsBetweenOpensOnOpenIso
#print axioms sheafSectionsBetweenOpensOnOpenIso_hom_ι
#print axioms toSheafSectionsBetweenOpens
#print axioms sheafSectionsSupportedOutsideMap_toBetween
#print axioms nestedSupportRestrictionShortComplex
#print axioms nestedSupportRestrictionShortComplex_eq
#print axioms nestedSupportRestrictionShortComplex_shortExact
#print axioms nestedSupportRestrictionSectionsShortComplex_shortExact
#print axioms nestedSupportRestrictionComplexShortComplex
#print axioms nestedSupportRestrictionComplexShortComplex_shortExact
#print axioms nestedSupportRestrictionSectionsComplexShortComplex
#print axioms nestedSupportRestrictionSectionsComplexShortComplex_shortExact
#print axioms nestedSupportRestrictionToFiber
#print axioms nestedSupportRestrictionToFiber_quasiIso
#print axioms nestedSupportRestrictionToFiber_fst
#print axioms nestedSupportRestriction_homologyMap_isIso_of_vanishing
#print axioms nestedSupportRestrictionHomologyIsoOfVanishing
#print axioms nestedSupportRestrictionHomologyIsoOfVanishing_hom
