import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentPointClassNormalization

#print axioms TopCat.Sheaf.sectionCohomologyToSheafSection_restriction
#print axioms TopCat.Sheaf.sectionCohomologyToSheafSection_restriction_assoc
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveCohomologySheafIsoRelative_restriction_section
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSupportedClassNormalizationIso_hom
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointRelativeCoclass
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointSupportedInjectiveCoclass
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointPositiveKernelClass
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointSupportedInjectiveCoclass_relative
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointRelativeCoclass_toSheaf
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointSupportedInjectiveCoclass_section_normalization
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSupportedInjectiveClass_point_normalization
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_point_normalization
#print axioms AlgebraicGeometry.ComplexPoint.sheafCycleClassOnCycles_single_point_normalization
#print axioms AlgebraicGeometry.ComplexPoint.sheafCycleClassOnCycles_sum_single_point_normalization
#print axioms AlgebraicGeometry.ComplexPoint.rationalSheafCycleClassOnCycles_tmul_single_point_normalization
#print axioms AlgebraicGeometry.ComplexPoint.rationalSheafCycleClassOnCycles_sum_tmul_single_point_normalization

#check @AlgebraicGeometry.ComplexPoint.cycleComponentSupportedInjectiveClass_point_normalization
#check @AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_point_normalization
