import HodgeConjecture.Other.AlgebraicGeometry.BettiSupportedOrdinaryConeComparison

#print axioms CochainComplex.exists_homotopyLift_of_quasiIso_to_isKInjective
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyAddEquivGlobalSectionsOfResolution_map
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyAddEquivGlobalSectionsOfResolution_naturality_to_kInjective
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyAddEquivGlobalSections_naturality_to_kInjective
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyAddEquivGlobalSections_shifted_naturality_to_kInjective
#print axioms AlgebraicGeometry.ComplexPoint.rationalToSingular_comp_complexSingularToAmbientInjective
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportConeToNaturalSingularCone_ambient_connecting
#print axioms AlgebraicGeometry.ComplexPoint.rationalCohomologyAmbient_forgetSupport_naturalSingularCone
