/- Run after `lake build HodgeConjecture.Other.AlgebraicTopology.SingularChainSheaf`. -/
import HodgeConjecture.Other.AlgebraicTopology.SingularChainSheaf

open AlgebraicTopology.Singular

#print axioms openComplementPairFunctor
#print axioms openRelativeSingularChainComplexFunctor
#print axioms singularChainPresheaf
#print axioms singularChainPresheaf_map
#print axioms singularChainBoundary
#print axioms singularChainBoundary_naturality
#print axioms singularChainBoundary_comp
#print axioms singularChainPresheafComplex
#print axioms singularChainPresheafComplex_d
#print axioms singularChainSheaf
#print axioms singularChainSheafBoundary
#print axioms singularChainSheafComplex
#print axioms singularChainSheafComplex_d
#print axioms singularChainSheafificationUnit
#print axioms singularChainSheafificationUnit_stalk_isIso
#print axioms singularChainSheafificationStalkIso
#print axioms singularChainSheafCochainComplex
#print axioms singularChainSheafCochainComplexXIso
#print axioms singularChainSheafCochainComplex_d
#print axioms singularChainSheafCochainComplex_isStrictlyLE
