import HodgeConjecture.Other.AlgebraicGeometry.BettiSupportedOrdinarySign
import HodgeConjecture.Other.AlgebraicTopology.SupportedSectionConeConnecting

#print axioms CochainComplex.mappingCone.homotopyCofiber_mapArrowHom_eq
#print axioms CochainComplex.mappingCone.homotopyCofiber_mapArrowIso_connecting
#print axioms AlgebraicTopology.Singular.globalRawSingularRestrictionConeIsoRelative_connecting
#print axioms AlgebraicTopology.Singular.globalRawSingularRestrictionCone_signed_inclusion
#print axioms AlgebraicTopology.Singular.globalRawRelativeCochainClass
#print axioms AlgebraicTopology.Singular.globalRawSingularRestrictionCone_connecting_of_relative
#print axioms TopCat.Sheaf.supportRestrictionSectionsConeIso_connecting
#print axioms TopCat.Sheaf.supportedSectionHomologyIsoRestrictionCone_connecting
#print axioms AlgebraicGeometry.ComplexPoint.rationalCohomologyAmbient_forgetSupport_of_singular_signed
