import HodgeConjecture.Other.AlgebraicGeometry.SmoothClosedSupportCoclassSection

/-! Audit of the literal relative-cohomology presheaf and actual normalized global gluing.
Run with `lake env lean scripts/audit_smooth_support_coclass_section.lean`. -/

#print axioms AlgebraicTopology.Singular.neighborhoodSupportInclusionPairMap_id
#print axioms AlgebraicTopology.Singular.neighborhoodSupportInclusionPairMap_comp
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologyPresheaf
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologyPresheaf_map_apply
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySheaf
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologyToSheaf
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologyGerm
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologyGerm_restrict
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologyGerm_eq_of_restrict_eq
#print axioms AlgebraicTopology.Singular.neighborhoodSupportRelativeChains_isZero
#print axioms AlgebraicTopology.Singular.neighborhoodSupportRelativeCohomology_subsingleton
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologyGerm_eq_zero_of_not_mem
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportChartOpen
#print axioms AlgebraicGeometry.ComplexPoint.mem_smoothClosedSupportChartOpen
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSheaf
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportChartSheafSection
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportChartCoclassGerm
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportChartCoclassGerm_eq
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportChartCoclassGerm_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassStalk
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassStalk_eq_chartGerm
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassStalk_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassStalk_locallyRepresentable
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_germ
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_germ_eq_chart
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_restrict_chart
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_germ_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_unique
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_germ_eq_normalCoclass
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_unique_of_normalization

#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection
#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_germ_eq_normalCoclass
#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_unique_of_normalization
