import HodgeConjecture.Other.AlgebraicGeometry.SmoothClosedSupportCoclassOverlap

/-! Exhaustive principal-declaration axiom and signature audit for the ambient normal-coclass
compatibility tranche. Run with `lake env lean scripts/audit_normal_projection_overlap.lean`. -/

#print axioms AlgebraicTopology.Singular.neighborhoodSupportInclusionPairMap
#print axioms AlgebraicTopology.Singular.chartNormalProjectionPair
#print axioms AlgebraicTopology.Singular.neighborhoodSupportInclusion_comp_chartNormalProjection
#print axioms AlgebraicTopology.Singular.chartNormalProjectionCoclass
#print axioms AlgebraicTopology.Singular.chartNormalProjectionCoclass_restrict
#print axioms AlgebraicTopology.Singular.univBall_zero_tangent_normal
#print axioms AlgebraicTopology.Singular.normalFiber_comp_chartNormalProjection
#print axioms AlgebraicTopology.Singular.flattenedSupportNormalClass_eq_normalFiber
#print axioms AlgebraicTopology.Singular.chartNormalProjection_normalClass
#print axioms AlgebraicTopology.Singular.chartNormalProjectionCoclass_apply_normalClass
#print axioms AlgebraicTopology.Singular.span_flattenedSupportNormalClass_eq_top
#print axioms AlgebraicTopology.Singular.chartNormalProjection_relativeHomologyMap_injective
#print axioms AlgebraicTopology.Singular.chartNormalProjectionCoclass_unique
#print axioms AlgebraicTopology.Singular.exists_open_normalTransition_localClass_invariance_within
#print axioms AlgebraicTopology.Singular.chartNormalFiberPair
#print axioms AlgebraicTopology.Singular.chartNormalFiber_comp_projection
#print axioms AlgebraicTopology.Singular.chartNormalFiber_comp_other_projection
#print axioms AlgebraicTopology.Singular.supportChartTransition_preserves_plane
#print axioms AlgebraicTopology.Singular.chartNormalProjectionCoclass_eq_on_flattenedNeighborhood
#print axioms AlgebraicTopology.Singular.exists_open_chartNormalProjectionCoclass_eq
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportChartCoclass
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportChartCoclass_restrict
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportNormalCoclass_eq_projection
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportNormalCoclass_restrict_eq_chart
#print axioms AlgebraicGeometry.ComplexPoint.exists_open_smoothClosedSupportChartCoclass_eq
#print axioms AlgebraicGeometry.ComplexPoint.exists_open_smoothClosedSupportChartCoclass_eq_within
#print axioms AlgebraicGeometry.ComplexPoint.exists_open_smoothClosedSupportNormalCoclass_restrict_eq

#check @AlgebraicTopology.Singular.exists_open_chartNormalProjectionCoclass_eq
#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportChartCoclass
#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportChartCoclass_restrict
#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportNormalCoclass_eq_projection
#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportNormalCoclass_restrict_eq_chart
#check @AlgebraicGeometry.ComplexPoint.exists_open_smoothClosedSupportChartCoclass_eq
#check @AlgebraicGeometry.ComplexPoint.exists_open_smoothClosedSupportChartCoclass_eq_within
#check @AlgebraicGeometry.ComplexPoint.exists_open_smoothClosedSupportNormalCoclass_restrict_eq
