import HodgeConjecture.Other.AlgebraicGeometry.SmoothClosedPointCoclassSectionNormalization

/-! Exact point comparison audit: all new principal declarations. -/

#print axioms AlgebraicTopology.Singular.neighborhoodSupportToPointPairMap
#print axioms AlgebraicTopology.Singular.neighborhoodSupportInclusionPairMap_toPoint
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedOldPointCoclassSection
#print axioms AlgebraicGeometry.ComplexPoint.neighborhoodSupportToPointPairMap_eq_smoothClosedPointNeighborhoodPairMap
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedOldPointCoclassSection_germ_eq_normalCoclass
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedOldPointCoclassSection_germ_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_eq_oldPoint_of_singleton
#print axioms AlgebraicGeometry.ComplexPoint.complexSpecIdentityPoint
#print axioms AlgebraicGeometry.ComplexPoint.complexSpecPoint_eq_identity
#print axioms AlgebraicGeometry.ComplexPoint.complexPoint_isClosedImmersion
#print axioms AlgebraicGeometry.ComplexPoint.map_complexSpecIdentityPoint
#print axioms AlgebraicGeometry.ComplexPoint.range_map_complexPoint
#print axioms AlgebraicGeometry.ComplexPoint.complexPointSmoothSupportCoclassSection
#print axioms AlgebraicGeometry.ComplexPoint.analyticPointLocalCoclassSheafSection
#print axioms AlgebraicGeometry.ComplexPoint.complexPointSmoothSupportCoclassSection_eq_analyticPointLocalCoclassSheafSection

#check @AlgebraicGeometry.ComplexPoint.smoothClosedSupportCoclassSection_eq_oldPoint_of_singleton
#check @AlgebraicGeometry.ComplexPoint.complexPointSmoothSupportCoclassSection_eq_analyticPointLocalCoclassSheafSection
#check @AlgebraicGeometry.ComplexPoint.complexPoint_isClosedImmersion
#check @AlgebraicGeometry.ComplexPoint.range_map_complexPoint
