import HodgeConjecture.Other.AlgebraicGeometry.CycleComponentPointOrdinarySign

#print axioms AlgebraicTopology.Singular.enlargeSupport_eq_cast_of_eq
#print axioms AlgebraicTopology.Singular.topOpenNeighborhoodSupportPairIso_toPoint
#print axioms AlgebraicGeometry.cycleClassOnCyclesOfComponents_neg
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentPointOrdinarySignParacompact
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointGlobalRelativeCoclass
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointGlobalRelativeCoclass_top
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointPositiveKernelClass_raw_positive
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointPositiveKernelClass_eq_neg_legacy
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_point_raw_positive
#print axioms AlgebraicGeometry.ComplexPoint.analyticComponentPointGlobalRelativeCoclass_eq_maximalCodimensionSupportedGenerator
#print axioms AlgebraicGeometry.ComplexPoint.maximalCodimensionComponentClass_eq_directLegacyPoint
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_eq_neg_maximalCodimensionComponentClass
#print axioms AlgebraicGeometry.ComplexPoint.sheafCycleClassOnCycles_eq_neg_pointCycleClassOnCycles
#print axioms AlgebraicGeometry.ComplexPoint.rationalSheafCycleClassOnCycles_eq_neg_rationalPointCycleClassOnCycles
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_closedPoint_positiveKernel
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_closedPoint_eq_neg_legacy

#check @AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_point_raw_positive
#check @AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_eq_neg_maximalCodimensionComponentClass
#check @AlgebraicGeometry.ComplexPoint.rationalSheafCycleClassOnCycles_eq_neg_rationalPointCycleClassOnCycles
#check @AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_closedPoint_eq_neg_legacy
