import HodgeConjecture.Other.AlgebraicGeometry.ComplexSupportedSingularModel
import HodgeConjecture.Other.AlgebraicGeometry.ComplexSheafBorelMooreRationalComparison

open AlgebraicTopology.Singular AlgebraicGeometry.ComplexPoint

#print axioms rationalSingularCochainComplex
#print axioms rationalConstantInjectiveComplex
#print axioms rationalSingularCochainComplex_isStrictlyGE
#print axioms rationalConstantInjectiveComplex_isStrictlyGE
#print axioms rationalConstantInjectiveComplex_injective
#print axioms singularToConstantInjectiveResolution
#print axioms constants_comp_singularToConstantInjectiveResolution
#print axioms singularToConstantInjectiveResolution_quasiIso
#print axioms singularToConstantInjectiveComplex
#print axioms singularToConstantInjectiveComplex_quasiIso
#print axioms supportedRationalSingularCochainComplex
#print axioms supportedSingularToInjectiveComplex
#print axioms rationalSingularCochainComplex_isFlasque
#print axioms supportedSingularToInjectiveComplex_quasiIso
#print axioms supportedSingularToInjectiveComplex_onOpen_quasiIso
#print axioms supportedSingularInjectiveHomologyIso
#print axioms complexSingularToAmbientInjective
#print axioms complexSingularToAmbientInjective_quasiIso
#print axioms complexSupportedSingularToAmbientInjective
#print axioms complexSupportedSingularToAmbientInjective_quasiIso
#print axioms complexSupportedSingularToAmbientInjective_onOpen_quasiIso
#print axioms complexSupportedSingularInjectiveHomologyIso
#print axioms complexAmbientSheafBorelMooreToFieldCohomology_eq_derivedForget

#check @complexSupportedSingularToAmbientInjective_quasiIso
#check @complexSupportedSingularToAmbientInjective_onOpen_quasiIso
#check @complexSupportedSingularInjectiveHomologyIso
#check @complexAmbientSheafBorelMooreToFieldCohomology_eq_derivedForget
