import HodgeConjecture.Other.AlgebraicGeometry.ClosedImmersionNormalCoordinates

open AlgebraicGeometry AlgebraicGeometry.ComplexPoint

#check @Scheme.Hom.exists_affine_local_section_lifts
#check @exists_analytic_localLeftInverse_of_isClosedImmersion
#check @injective_fderiv_inclusionInComplexCharts
#check @closedImmersionStandardFlatteningChart
#check @closedImmersionStandardFlatteningChart_mem_range_iff
#check @analyticAt_closedImmersionNormalChart_symm

#print axioms Scheme.Hom.exists_affine_local_section_lifts
#print axioms inclusionInComplexCharts
#print axioms inclusionInComplexCharts_at_center
#print axioms analyticAt_inclusionInComplexCharts
#print axioms exists_analytic_localLeftInverse_of_isClosedImmersion
#print axioms exists_leftInverse_fderiv_inclusionInComplexCharts
#print axioms injective_fderiv_inclusionInComplexCharts

#print axioms ContinuousLinearMap.splitKernelEquiv
#print axioms ContinuousLinearMap.splitKernelEquiv_apply
#print axioms ContinuousLinearMap.splitKernelEquiv_symm_fst
#print axioms HasStrictFDerivAt.add_kernel
#print axioms HasStrictFDerivAt.normalChart
#print axioms HasStrictFDerivAt.normalChart_apply
#print axioms HasStrictFDerivAt.normalChart_mem_source
#print axioms HasStrictFDerivAt.normalChart_mem_target
#print axioms HasStrictFDerivAt.normalChart_symm_apply
#print axioms HasStrictFDerivAt.normalChart_normal_eq_zero_iff

#print axioms closedImmersionDerivativeProjection
#print axioms closedImmersionDerivativeProjection_leftInverse
#print axioms closedImmersionNormalChart
#print axioms closedImmersionNormalChart_apply
#print axioms closedImmersionNormalChart_mem_source
#print axioms closedImmersionNormalChart_mem_target
#print axioms closedImmersionNormalChart_symm_center
#print axioms closedImmersionNormalKernel_finrank
#print axioms analyticAt_closedImmersionNormalChart
#print axioms analyticAt_closedImmersionNormalChart_symm
#print axioms eventually_mem_range_iff_normal_eq_zero
#print axioms exists_open_normalCriterion
#print axioms closedImmersionFlatteningChart
#print axioms closedImmersionFlatteningChart_apply
#print axioms closedImmersionFlatteningChart_mem_source
#print axioms closedImmersionFlatteningChart_center
#print axioms closedImmersionFlatteningChart_mem_range_iff
#print axioms closedImmersionNormalKernelEquiv
#print axioms closedImmersionStandardFlatteningChart
#print axioms closedImmersionStandardFlatteningChart_apply
#print axioms closedImmersionStandardFlatteningChart_source
#print axioms closedImmersionStandardFlatteningChart_mem_source
#print axioms closedImmersionStandardFlatteningChart_center
#print axioms closedImmersionStandardFlatteningChart_mem_range_iff
