import HodgeConjecture.Other.AlgebraicGeometry.SmoothClosedPointPurityNormalization

#print axioms AlgebraicTopology.Singular.centeredComplexLinear_preserves_standardComplexLocalClass
#print axioms AlgebraicTopology.Singular.chartTargetInverseAtSourcePairMap
#print axioms AlgebraicTopology.Singular.radialTargetPointPairMap_chartTargetInverseAtSource
#print axioms AlgebraicTopology.Singular.chartTargetPointPairMap_localClass
#print axioms AlgebraicGeometry.ComplexPoint.closedImmersionPointNormalLinearMap
#print axioms AlgebraicGeometry.ComplexPoint.closedImmersionPointNormalLinearMap_injective
#print axioms AlgebraicGeometry.ComplexPoint.closedImmersionPointNormalChart_apply
#print axioms AlgebraicGeometry.ComplexPoint.closedImmersionPointStandardFlatteningChart_symm
#print axioms AlgebraicGeometry.ComplexPoint.closedImmersionPointStandardFlatteningChart_coordinates
#print axioms AlgebraicGeometry.ComplexPoint.univBall_zeroTangent_apply
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNeighborhoodPairMap
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalModelPairMap
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalRadius
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalRadius_pos
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalModelPairMap_apply
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalModelPairMap_mem_chartSource
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalModelPairMap_coordinates
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalTargetPairMap
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalTargetPairMap_inverseChart
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalTargetPairMap_comp_inclusion
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalModelPairMap_localClass
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalClass_to_analyticPointLocalHomologyClass
#print axioms AlgebraicGeometry.ComplexPoint.analyticPointLocalCoclass_apply_smoothClosedPointNormalClass
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalCoclass_eq_analyticPointLocalCoclass
#print axioms AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalCoclass_smul_eq_analyticPointLocalCoclass

#check @AlgebraicGeometry.ComplexPoint.smoothClosedPointNormalCoclass_eq_analyticPointLocalCoclass
