import Other.AlgebraicGeometry.GAGAStatement
import Other.AlgebraicGeometry.AffineSpaceHolomorphicChart
import Other.AlgebraicGeometry.AffineSpaceSmooth
import Other.AlgebraicGeometry.AnalyticLineBundleFiniteAtlas
import Other.AlgebraicGeometry.AnalyticSerreGeneration
import Other.AlgebraicGeometry.AnalytificationRestriction
import Other.AlgebraicGeometry.AnalytificationReflectsStalkRankOne
import Other.AlgebraicGeometry.ComplexPointClosedPointEquiv
import Other.AlgebraicGeometry.FiniteFreeAnalytification
import Other.AlgebraicGeometry.FiniteSumHomSurjective
import Other.AlgebraicGeometry.GAGACoherentReduction
import Other.AlgebraicGeometry.GAGAProper
import Other.AlgebraicGeometry.GAGALineBundles
import Other.AlgebraicGeometry.GAGASerreReduction
import Other.AlgebraicGeometry.GAGATwistPresentation
import Other.AlgebraicGeometry.GAGAtoLefschetz
import Other.AlgebraicGeometry.HolomorphicLocallyRingedSpace
import Other.AlgebraicGeometry.HolomorphicMultiplierTransition
import Other.AlgebraicGeometry.HomogeneousEntireFunctions
import Other.AlgebraicGeometry.InvertibleSheafCoherent
import Other.AlgebraicGeometry.InvertiblePullback
import Other.AlgebraicGeometry.MvPolynomialHomogenisation
import Other.AlgebraicGeometry.MvPolynomialStandardSmooth
import Other.AlgebraicGeometry.PointEvaluationApp
import Other.AlgebraicGeometry.PolynomialGrowthLiouville
import Other.AlgebraicGeometry.ProjAwayEvaluation
import Other.AlgebraicGeometry.ProjectiveAnalytificationCharts
import Other.AlgebraicGeometry.ProjectiveAnalytificationHomeomorph
import Other.AlgebraicGeometry.ProjectiveChartFormComparison
import Other.AlgebraicGeometry.ProjectiveChartHolomorphic
import Other.AlgebraicGeometry.ProjectiveChartIso
import Other.AlgebraicGeometry.ProjectiveChartLocality
import Other.AlgebraicGeometry.ProjectiveChartMultiplierGrowth
import Other.AlgebraicGeometry.ProjectiveHolomorphicFunctions
import Other.AlgebraicGeometry.ProjectiveHomogeneousRatioEvaluation
import Other.AlgebraicGeometry.ProjectivePresentationTwist
import Other.AlgebraicGeometry.ProjectiveSpaceNegativeTwist
import Other.AlgebraicGeometry.ProjectiveSpaceSmooth
import Other.AlgebraicGeometry.ProjectiveSpectrumNegativeTwist
import Other.AlgebraicGeometry.ProjectiveSpectrumTwistFrames
import Other.AlgebraicGeometry.ProjectiveSpectrumTwistMultiply
import Other.AlgebraicGeometry.ProjectiveTwistAnalyticFrames
import Other.AlgebraicGeometry.ProjectiveTwistCanonicalFrames
import Other.AlgebraicGeometry.ProjectiveTwistCanonicalMultipliers
import Other.AlgebraicGeometry.ProjectiveTwistChartFrames
import Other.AlgebraicGeometry.ProjectiveTwistDegreeZero
import Other.AlgebraicGeometry.ProjectiveTwistDegreeZeroRelations
import Other.AlgebraicGeometry.ProjectiveTwistMultipliers
import Other.AlgebraicGeometry.ProjectiveTwistMultiplyTransport
import Other.AlgebraicGeometry.ProjectiveTwistNegativeVanishing
import Other.AlgebraicGeometry.ProjectiveTwistObligations
import Other.AlgebraicGeometry.ProjectiveTwistRatioPower
import Other.AlgebraicGeometry.ProjectiveTwistRelationObligations
import Other.AlgebraicGeometry.PullbackSectionNaturality
import Other.AlgebraicGeometry.SchemePullbackGenerates
import Other.AlgebraicGeometry.SchemePullbackSection
import Other.AlgebraicGeometry.TwistRelationsFromRankOne
import Other.AlgebraicGeometry.UnitEndomorphismComparison
import Other.RingTheory.FaithfullyFlatRankOne
import Other.TauCeti.SheafOfModules.CechTransition
import Other.TauCeti.SheafOfModules.FiniteLocalTriviality
import Other.TauCeti.SheafOfModules.JacobsonLocalTriviality

/- Representative axiom checks for the completed proper-GAGA comparison and its supporting
development.
Run: lake env lean scripts/gaga_axiom_audit.lean
See docs/GAGA_HANDOFF.md for the proof route. -/

#print axioms AlgebraicGeometry.ComplexPoint.comparisonToCanonical_isLocalIso
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicAnalytificationπ_isAnalytification
#print axioms AlgebraicGeometry.ComplexPoint.faithfullyFlat_stalkMap_holomorphicAnalytificationπ
#print axioms ComplexAnalytic.coherent_algebraizes_of_isAnalytification
#print axioms AlgebraicGeometry.ComplexPoint.analyticCoherentSheavesAlgebraize
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize
#print axioms AlgebraicGeometry.ComplexPoint.rationalSheafCycleClassOnCycles_mem_algebraicCycleClassSpan
#print axioms RationalLefschetzOneOne.to_lefschetzOneOne
#print axioms rationalLefschetzOneOne
#print axioms lefschetzOneOne

#print axioms AlgebraicGeometry.ComplexPoint.holomorphicStalk_isLocalRing
#print axioms AlgebraicGeometry.ComplexPoint.analytification_stalkMap_comp_evaluation
#print axioms AlgebraicGeometry.ComplexPoint.analytificationToAlgebraic
#print axioms AlgebraicGeometry.ComplexPoint.hasAlgebraicModel_of_analyticLineBundlesAlgebraize
#print axioms RationalLefschetzOneOne.of_algebraicModel
#print axioms RationalLefschetzOneOne.of_analyticLineBundlesAlgebraize
#print axioms Module.basisPUnitOfLinearEquivSelf
#print axioms Module.exists_linearEquiv_self_of_faithfullyFlat_baseChange
#print axioms Module.exists_linearEquiv_self_of_faithfullyFlat_extendScalars
#print axioms AlgebraicGeometry.ComplexPoint.exists_algebraicStalkLinearEquiv_of_analytification
#print axioms AlgebraicGeometry.ComplexPoint.exists_algebraicStalkLinearEquiv_of_analytificationIso
#print axioms AlgebraicGeometry.ComplexPoint.exists_algebraicStalkLinearEquiv_of_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.exists_algebraicStalkLinearEquiv_of_isInvertible_closedPoint
#print axioms AlgebraicGeometry.ComplexPoint.algebraic_isInvertible_of_analytificationIso
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_coherent
#print axioms RationalLefschetzOneOne.of_coherentGAGA
#print axioms AlgebraicGeometry.ComplexPoint.Euclidean.contMDiff_omega_iff_okaAnalytic
#print axioms AlgebraicGeometry.ComplexPoint.Euclidean.complexSpaceIso
#print axioms AlgebraicGeometry.ComplexPoint.localChartLocallyRingedSpaceIso
#print axioms AlgebraicGeometry.ComplexPoint.localChartLocallyRingedSpaceIso_isCLinear
#print axioms AlgebraicGeometry.ComplexPoint.isLocalModel_localChartRestriction
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicAnalyticSpace
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicLocallyRingedSpace_hasLocalRelations
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicLocallyRingedSpace_isCoherentStructureSheaf
#print axioms AlgebraicGeometry.LocallyRingedSpace.nonempty_stalkLinearEquiv_of_isInvertible
#print axioms AlgebraicGeometry.LocallyRingedSpace.isCoherent_of_isInvertible
#print axioms ComplexAnalytic.AnalyticSpace.isCoherentStructureSheaf
#print axioms ComplexAnalytic.AnalyticSpace.isCoherent_of_isInvertible
#print axioms AlgebraicGeometry.LocallyRingedSpace.finite_stalk_of_isFiniteType
#print axioms AlgebraicGeometry.LocallyRingedSpace.exists_restrictModules_iso_free_of_basis
#print axioms TauCeti.SheafOfModules.LocalTrivializations.ofClosedPoints
#print axioms AlgebraicGeometry.LocallyRingedSpace.isInvertible_of_isCoherent_of_basis_closedPoints
#print axioms AlgebraicGeometry.ComplexPoint.complexPointEquivClosedPoint
#print axioms AlgebraicGeometry.ComplexPoint.pointEquivOfRangeClosedPoints
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundle_algebraizes_of_iso_unit
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_subsingleton
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_dimension_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundle_isFinitePresentation
#print axioms AlgebraicGeometry.ComplexPoint.algebraicLineBundle_isFinitePresentation
#print axioms AlgebraicGeometry.ComplexPoint.analyticOpen_coversTop
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationFreePUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationIsoOfFreePUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.regularToHolomorphicRingSheafOver
#print axioms AlgebraicGeometry.ComplexPoint.localModuleAnalytificationFreePUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationOverIso
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytification_isInvertible
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.sheafOfModules
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.DegreeZero.unitIso
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.HomogeneousShift.basicOpenUnitIso
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.isInvertible_of_basicOpenCover
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.schemeSheafOfModules_isInvertible_of_basicOpenCover
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.universalNegativeTwist_isInvertible
#print axioms AlgebraicGeometry.Scheme.Modules.pullback_isInvertible
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.complexProjectiveNegativeTwist_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.algebraic_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analytic_isInvertible
#print axioms TauCeti.SheafOfModules.LocalTrivializations.finiteIndexSet_isOpenCover
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundleFiniteTrivializations_coversTop
#print axioms TauCeti.SheafOfModules.LocalTrivializations.transitionIsoOver_trans
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.sumAnalytificationIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.IsSerreGenerated.of_epi
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.AlgebraicTwistPresentation.algebraicModelAnalytificationIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.AlgebraicTwistPresentation.algebraizes
#print axioms AlgebraicGeometry.ComplexPoint.globalHolomorphic_range_finite
#print axioms AlgebraicGeometry.ComplexPoint.regularFunctionsToHolomorphic_top_surjective
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.DegreeZero.schemeUnitIso
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.negativeTwistZeroIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.algebraicZeroIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analyticZeroIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.epiIsCokernelOfKernelGenerators
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.exists_algebraicTwistPresentationOfSerreData
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_serreData
#print axioms AlgebraicGeometry.ComplexPoint.unitEndomorphism_analytification_surjective
#print axioms SheafOfModules.ιFree_matrix_πFree
#print axioms AlgebraicGeometry.ComplexPoint.unitFreeAnalytificationIso_hom_πFree
#print axioms AlgebraicGeometry.ComplexPoint.finiteFreeHom_analytification_surjective
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analyticTwistRelationsAlgebraize_zero
#print axioms Complex.PolynomialGrowth.exists_isHomogeneous_eval_eq_diag
#print axioms Complex.PolynomialGrowth.iteratedDeriv_line_eq_zero
#print axioms Complex.PolynomialGrowth.exists_isHomogeneous_sum_eq
#print axioms Complex.PolynomialGrowth.exists_mvPolynomial_eq_of_growth
#print axioms Complex.PolynomialGrowth.analyticOnNhd_and_growth_iff
#print axioms Complex.PolynomialGrowth.exists_mvPolynomial_eq_of_contMDiff_of_growth
#print axioms Complex.PolynomialGrowth.exists_mvPolynomial_eq_of_homogeneous_of_bounded_sphere
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.projectivizationHomeomorph
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.isOpenQuotientMap_projMk
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartHomeomorph
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.iUnion_chartSet
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.complexPointChartHomeomorph
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.iUnion_complexPointChartSet
#print axioms Complex.PolynomialGrowth.iteratedDeriv_line_eq_zero_of_lt
#print axioms Complex.PolynomialGrowth.exists_bound_of_homogeneous
#print axioms Complex.PolynomialGrowth.exists_isHomogeneous_eq_of_homogeneous
#print axioms Complex.PolynomialGrowth.analyticOnNhd_homogeneous_iff
#print axioms Complex.PolynomialGrowth.eq_zero_of_homogeneous_neg
#print axioms Other.MvPolynomialStandardSmooth.isStandardSmoothOfRelativeDimension
#print axioms Other.ProjectiveChart.eval₂_mul_of_isHomogeneous
#print axioms Other.ProjectiveChart.chartHom_surjective
#print axioms Other.ProjectiveChart.chartHom_injective
#print axioms Other.ProjectiveChart.chartRingEquiv
#print axioms Other.ProjectiveChart.isStandardSmoothOfRelativeDimension_fromZeroRingHom
#print axioms Other.ProjectiveChart.irrelevant_le_span_X
#print axioms Other.ProjectiveChart.smoothOfRelativeDimension_toSpecZero
#print axioms Other.ProjectiveChart.smoothOfRelativeDimension_projectiveSpaceToBase
#print axioms Other.AffineSpaceSmooth.smoothOfRelativeDimension_affineSpace
#print axioms AlgebraicGeometry.ComplexPoint.analyticAt_evaluate_affineSpaceEquiv_symm
#print axioms AlgebraicGeometry.ComplexPoint.contMDiff_affineSpaceEquiv_symm
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.contMDiff_projectivizationToComplexPoint_chartPoint
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.analyticOnNhd_comp_chartPoint
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.isProjective_projectiveSpace
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.exists_mvPolynomial_of_growth
#print axioms Other.ProjectiveChart.deh_homogenise
#print axioms Other.ProjectiveChart.isHomogeneous_homogenise
#print axioms Other.ProjectiveChart.eq_zero_of_deh_eq_zero
#print axioms Other.ProjectiveChart.existsUnique_isHomogeneous_deh_eq
#print axioms Other.ProjectiveChart.totalDegree_deh_le
#print axioms Other.ProjectiveChart.existsUnique_isHomogeneous_of_growth
#print axioms Other.ProjectiveChart.existsUnique_isHomogeneous_of_chart_growth
#print axioms Other.ProjectiveChart.algebraizes_of_serreData_proj
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.overOpen_projectiveSpaceBasicOpen_X
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.twistTrivializations
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.twistChartFramesProj
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.holomorphicGenerates_analyticChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.existsUnique_chartMultiplier
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.contMDiff_chartPointIn
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.analyticOnNhd_comp_chartPointIn
#print axioms AlgebraicGeometry.ComplexPoint.multiplier_transition
#print axioms AlgebraicGeometry.ComplexPoint.multiplier_eq_of_same_transition
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartMultiplier_eq_on_overlap
#print axioms AlgebraicGeometry.Scheme.Modules.pullbackSection_smul_res
#print axioms AlgebraicGeometry.Scheme.Modules.generates_pullbackSection
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.generates_projFrame
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.projRatio_smul_projFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.generates_algChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.holomorphicGenerates_anChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.spaceRatio_smul_algChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.analyticFunction_spaceRatio_smul_anChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.existsUnique_canonicalChartMultiplier
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.canonicalChartMultiplier_transition
#print axioms CategoryTheory.Limits.exists_sumMatrix_of_hom_surjective
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analyticTwistRelationsAlgebraize_of_rankOne
#print axioms Other.ProjectiveChart.twistRelationsAlgebraizeProj_of_parts
#print axioms AlgebraicGeometry.ComplexPoint.evaluate_eq_appLE_top
#print axioms AlgebraicGeometry.ComplexPoint.evaluate_app_eq_appLE_top
#print axioms AlgebraicGeometry.Proj.awayι_eq_SpecMap_fromSpec
#print axioms AlgebraicGeometry.Proj.ΓSpecIso_appLE_top_awayToSection
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.spaceRatio_pow
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.homogeneousRatioEvaluation
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartRatioEvaluation
#print axioms AlgebraicGeometry.Scheme.Modules.pullbackSection_map
#print axioms AlgebraicGeometry.ComplexPoint.analyticSection_map
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartMultiplierGrowth
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.surjective_chartPointIn
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.holSection_ext
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.hom_eq_zero_of_anChartFrame
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.multiplyShiftHom
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.multiplyShiftHom_projFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.algMulHom_algChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.analytified_algMulHom_anChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartMultiplier_decay
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.twistRankOneVanishesNeg_of_pos
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.twistRankOneAlgebraizesNeg_of_pos
