/- Representative axiom checks for the incomplete Lefschetz development.
Run: lake env lean scripts/lefschetz_axiom_audit.lean
See docs/LEFSCHETZ_HANDOFF.md for the full goal and remaining obligations. -/
import Other.Algebra.Homology.RationalCochainDenominators
import Other.AlgebraicGeometry.HolomorphicLocallyRingedSpace
import Other.AlgebraicGeometry.AnalytificationModules
import Other.AlgebraicGeometry.HolomorphicLineBundleInvertible
import Other.AlgebraicGeometry.LefschetzOneOne
import Other.AlgebraicGeometry.LefschetzOneOneReduction
import Other.AlgebraicGeometry.BettiScalarComparison
import Other.AlgebraicGeometry.IntegralDenominatorClearing
import Other.AlgebraicGeometry.ProjectiveFiniteHomology
import Other.AlgebraicGeometry.DivisorObligations
import Other.AlgebraicGeometry.GAGALineBundles
import Other.AlgebraicGeometry.ProjectiveSpectrumNegativeTwist
import Other.AlgebraicGeometry.ProjectiveSpaceNegativeTwist
import Other.AlgebraicGeometry.ProjectivePresentationTwist
import Other.AlgebraicGeometry.AnalyticLineBundleFiniteAtlas
import Other.AlgebraicGeometry.AnalyticSerreGeneration
import Other.AlgebraicGeometry.GAGATwistPresentation
import Other.AlgebraicGeometry.GAGASerreReduction
import Other.AlgebraicGeometry.ProjectiveHolomorphicFunctions
import Other.AlgebraicGeometry.ProjectiveTwistDegreeZero
import Other.AlgebraicGeometry.UnitEndomorphismComparison
import Other.AlgebraicGeometry.FiniteFreeAnalytification
import Other.AlgebraicGeometry.ProjectiveTwistDegreeZeroRelations
import Other.TauCeti.SheafOfModules.FiniteLocalTriviality
import Other.TauCeti.SheafOfModules.CechTransition
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.localCoordinateEquiv
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.sectionSheafOfModules_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.contMDiffAt_evaluate
#print axioms AlgebraicGeometry.ComplexPoint.regularToHolomorphicSheaf
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationAdjunction
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.exists_holomorphicUnitExtension_of_integral_hodgeClass
#print axioms HodgeConjecture.rationalLefschetzOneOne
#print axioms HodgeConjecture.rationalLefschetzOneOne_direct
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicStalk_isLocalRing
#print axioms AlgebraicGeometry.ComplexPoint.analytification_stalkMap_comp_evaluation
#print axioms AlgebraicGeometry.ComplexPoint.analytificationToAlgebraic
#print axioms LinearMap.exists_integer_multiple_isInteger
#print axioms LinearMap.exists_integer_multiple
#print axioms CategoryTheory.ShortComplex.homologyMap_exists_integer_multiple
#print axioms AlgebraicGeometry.ComplexPoint.exists_rationalSheafCycleClassOnCycles_eq_of_obligations
#print axioms RationalLefschetzOneOne.of_obligations
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorOfUnitExtension_of_algebraicModel
#print axioms AlgebraicGeometry.ComplexPoint.hasAlgebraicModel_of_analyticLineBundlesAlgebraize
#print axioms AlgebraicGeometry.ComplexPoint.integralCohomologyEquivOrdinarySingularCohomology
#print axioms AlgebraicGeometry.ComplexPoint.hasIntegralDenominatorClearing_of_hasFiniteGoodCover
#print axioms RationalLefschetzOneOne.of_finiteGoodCover_of_divisor
#print axioms SSet.exists_integer_multiple_of_finite_homology
#print axioms AlgebraicGeometry.ComplexPoint.scalarCohomologyEquivOrdinarySingularCohomology_coefficientChange
#print axioms RationalLefschetzOneOne.of_finiteSecondHomology_of_divisor
#print axioms AlgebraicGeometry.ComplexPoint.hasIntegralDenominatorClearing
#print axioms RationalLefschetzOneOne.of_divisor
#print axioms AlgebraicTopology.Singular.module_finite_homology_of_compactSpace_isManifold
#print axioms exists_retraction_of_compact_embedding
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorOfAlgebraicModel_of_divisorClass
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundle_algebraizes_of_iso_unit
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_subsingleton
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_dimension_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundle_isFinitePresentation
#print axioms AlgebraicGeometry.ComplexPoint.algebraicLineBundle_isFinitePresentation
#print axioms AlgebraicGeometry.ComplexPoint.analyticOpen_coversTop
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationFreePUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationIsoOfFreePUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.regularToHolomorphicRingSheafOver
#print axioms AlgebraicGeometry.ComplexPoint.localModuleAnalytificationFreePUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationOverIso
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytification_isInvertible
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.sheafOfModules
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.DegreeZero.unitIso
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.HomogeneousShift.basicOpenUnitIso
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.isInvertible_of_basicOpenCover
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.schemeSheafOfModules_isInvertible_of_basicOpenCover
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.universalNegativeTwist_isInvertible
#print axioms AlgebraicGeometry.Scheme.Modules.pullback_isInvertible
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.complexProjectiveNegativeTwist_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.algebraic_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analytic_isInvertible
#print axioms TauCeti.SheafOfModules.LocalTrivializations.finiteIndexSet_isOpenCover
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundleFiniteTrivializations_coversTop
#print axioms TauCeti.SheafOfModules.LocalTrivializations.transitionIsoOver_trans
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.sumAnalytificationIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.IsSerreGenerated.of_epi
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.AlgebraicTwistPresentation.algebraicModelAnalytificationIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.AlgebraicTwistPresentation.algebraizes
#print axioms AlgebraicGeometry.ComplexPoint.globalHolomorphic_range_finite
#print axioms AlgebraicGeometry.ComplexPoint.regularFunctionsToHolomorphic_top_surjective
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.DegreeZero.schemeUnitIso
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.negativeTwistZeroIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.algebraicZeroIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analyticZeroIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.epiIsCokernelOfKernelGenerators
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.exists_algebraicTwistPresentationOfSerreData
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_serreData
#print axioms AlgebraicGeometry.ComplexPoint.unitEndomorphism_analytification_surjective
#print axioms SheafOfModules.ιFree_matrix_πFree
#print axioms AlgebraicGeometry.ComplexPoint.unitFreeAnalytificationIso_hom_πFree
#print axioms AlgebraicGeometry.ComplexPoint.finiteFreeHom_analytification_surjective
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analyticTwistRelationsAlgebraize_zero
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.instPathConnectedSpace
