import Other.AlgebraicGeometry.RelativeChernLocalBoundary
import Other.AlgebraicTopology.CohomologySheafSectionDerivedVanishing
import Other.AlgebraicGeometry.CocycleGlobalSectionNaturality
import Other.AlgebraicGeometry.CartierWindingChartVanishing
/- Representative axiom checks for the incomplete Lefschetz development.
Run: lake env lean scripts/lefschetz_axiom_audit.lean
See docs/LEFSCHETZ_HANDOFF.md for the full goal and remaining obligations. -/
import Other.AlgebraicGeometry.ChernWindingRawBoundary
import Other.AlgebraicGeometry.RelativeChernFrameVariation
import Other.AlgebraicGeometry.RelativeChernFrameWinding
import Other.AlgebraicGeometry.HolomorphicExponentialIntrinsicWindingClass
import Other.AlgebraicGeometry.CocycleGlobalSections
import Other.AlgebraicGeometry.HolomorphicExponentialSingularSectionClass
import Other.AlgebraicTopology.SupportedSingularBoundaryRelative
import Other.AlgebraicTopology.OpenRawBoundaryComparison
import Other.AlgebraicGeometry.ChernWindingCohomologyNaturality
import Other.AlgebraicGeometry.ChernWindingSupportedBoundary
import Other.AlgebraicGeometry.RationalSupportBoundaryRelative
import Other.AlgebraicGeometry.HolomorphicExponentialSingularSections
import Other.Algebra.Homology.RationalCochainDenominators
import Other.AlgebraicGeometry.RawComplementResolutionComparison
import Other.AlgebraicGeometry.SupportedInjectiveBoundaryNormalization
import Other.AlgebraicGeometry.ActualSingularSupportBoundary
import Other.AlgebraicGeometry.HolomorphicLocallyRingedSpace
import Other.AlgebraicGeometry.AnalytificationModules
import Other.AlgebraicGeometry.HolomorphicLineBundleInvertible
import Other.AlgebraicGeometry.LefschetzOneOne
import Other.AlgebraicGeometry.LefschetzOneOneReduction
import Other.AlgebraicGeometry.BettiScalarComparison
import Other.AlgebraicGeometry.IntegralDenominatorClearing
import Other.AlgebraicGeometry.ProjectiveFiniteHomology
import Other.AlgebraicGeometry.DivisorObligations
import Other.AlgebraicGeometry.GAGALineBundles
import Other.AlgebraicGeometry.ProjectiveSpectrumNegativeTwist
import Other.AlgebraicGeometry.ProjectiveSpaceNegativeTwist
import Other.AlgebraicGeometry.ProjectivePresentationTwist
import Other.AlgebraicGeometry.ProjectiveTwistRelationObligations
import Other.AlgebraicGeometry.ProjectiveHomogeneousRatioEvaluation
import Other.AlgebraicGeometry.ProjectiveTwistNegativeVanishing
import Other.AlgebraicGeometry.ProjectiveTwistMultiplyTransport
import Other.AlgebraicGeometry.PullbackSectionNaturality
import Other.AlgebraicGeometry.AnalyticLineBundleFiniteAtlas
import Other.AlgebraicGeometry.AnalyticSerreGeneration
import Other.AlgebraicGeometry.GAGATwistPresentation
import Other.AlgebraicGeometry.PolynomialGrowthLiouville
import Other.AlgebraicGeometry.ProjectiveAnalytificationHomeomorph
import Other.AlgebraicGeometry.ProjectiveAnalytificationCharts
import Other.AlgebraicGeometry.HomogeneousEntireFunctions
import Other.AlgebraicGeometry.MvPolynomialStandardSmooth
import Other.AlgebraicGeometry.ProjectiveChartIso
import Other.AlgebraicGeometry.ProjectiveSpaceSmooth
import Other.AlgebraicGeometry.AffineSpaceSmooth
import Other.AlgebraicGeometry.AffineSpaceHolomorphicChart
import Other.AlgebraicGeometry.ProjectiveChartHolomorphic
import Other.AlgebraicGeometry.MvPolynomialHomogenisation
import Other.AlgebraicGeometry.ProjectiveChartFormComparison
import Other.AlgebraicGeometry.ProjectiveTwistObligations
import Other.AlgebraicGeometry.ProjectiveTwistChartFrames
import Other.AlgebraicGeometry.ProjectiveTwistAnalyticFrames
import Other.AlgebraicGeometry.HolomorphicMultiplierTransition
import Other.AlgebraicGeometry.ProjectiveTwistMultipliers
import Other.AlgebraicGeometry.GAGASerreReduction
import Other.AlgebraicGeometry.ProjectiveHolomorphicFunctions
import Other.AlgebraicGeometry.ProjectiveTwistDegreeZero
import Other.AlgebraicGeometry.UnitEndomorphismComparison
import Other.AlgebraicGeometry.FiniteFreeAnalytification
import Other.AlgebraicGeometry.ProjectiveTwistDegreeZeroRelations
import Other.TauCeti.SheafOfModules.FiniteLocalTriviality
import Other.TauCeti.SheafOfModules.CechTransition
import Other.AlgebraicGeometry.AnalytificationGenerates
import Other.AlgebraicGeometry.UnitExtensionClassOfSectionSheaf
import Other.AlgebraicGeometry.CohomologyWithSupportExact
import Other.AlgebraicGeometry.ChernClassRestrictionVanishing
import Other.AlgebraicGeometry.ChernLocalModel
import Other.AlgebraicGeometry.CartierLocalForm
import Other.AlgebraicGeometry.ClosedSupportCoheightDimension
import Other.AlgebraicGeometry.CycleComponentRestrictionInjective
import Other.AlgebraicGeometry.ChernLocalModelWinding
import Other.AlgebraicGeometry.ChernRelativeClassNaturality
import Other.AlgebraicGeometry.ChernWindingChartPeriods
import Other.AlgebraicGeometry.ChernWindingStandardTriangle
import Other.AlgebraicGeometry.ChernWindingLocalFormObstruction
import Other.AlgebraicGeometry.ChernWindingHolomorphicLog
import Other.AlgebraicGeometry.ChernWindingNormalChartExistence
import Other.AlgebraicGeometry.ChernWindingGenericChartExistence
import Other.AlgebraicGeometry.ChernWindingNormalChartTransport
import Other.AlgebraicGeometry.ComplementFrame
import Other.AlgebraicGeometry.ComplementFrameGeneric
import Other.AlgebraicGeometry.ChernRelativeClassGeneric
import Other.AlgebraicGeometry.SupportEnlargementCodimTwo
import Other.Algebra.Homology.MappingConeCocycle
import Other.AlgebraicGeometry.ChernRelativeChartFormula
import Other.AlgebraicGeometry.ChernRelativeChartFormulaSplitting
import Other.AlgebraicGeometry.ChernWindingChartCoclassRestrict
import Other.AlgebraicGeometry.HolomorphicExponentialSingularCochain
import Other.Algebra.Homology.SingleCocycleFactorization
import Other.AlgebraicGeometry.HolomorphicExponentialSingularClass
import Other.AlgebraicTopology.RelativeCochainConeBoundaryComparison
import Other.AlgebraicGeometry.ChernWindingConnecting
import Other.AlgebraicTopology.LinearDualConnecting
import Other.Algebra.Homology.ExtendConnecting
import Other.AlgebraicGeometry.HolomorphicExponentialSingularRestriction
import Other.AlgebraicGeometry.HolomorphicFrameLift
import Other.AlgebraicGeometry.CartierFrameLift
import Other.AlgebraicGeometry.CartierLocalFormUnit
import Other.AlgebraicGeometry.CartierWindingChartUnit
import Other.AlgebraicGeometry.CartierWindingChartFrame

#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.localCoordinateEquiv
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.sectionSheafOfModules_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.contMDiffAt_evaluate
#print axioms AlgebraicGeometry.ComplexPoint.regularToHolomorphicSheaf
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationAdjunction
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.exists_holomorphicUnitExtension_of_integral_hodgeClass
#print axioms HodgeConjecture.rationalLefschetzOneOne
#print axioms HodgeConjecture.rationalLefschetzOneOne_direct
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicStalk_isLocalRing
#print axioms AlgebraicGeometry.ComplexPoint.analytification_stalkMap_comp_evaluation
#print axioms AlgebraicGeometry.ComplexPoint.analytificationToAlgebraic
#print axioms LinearMap.exists_integer_multiple_isInteger
#print axioms LinearMap.exists_integer_multiple
#print axioms CategoryTheory.ShortComplex.homologyMap_exists_integer_multiple
#print axioms AlgebraicGeometry.ComplexPoint.exists_rationalSheafCycleClassOnCycles_eq_of_obligations
#print axioms RationalLefschetzOneOne.of_obligations
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorOfUnitExtension_of_algebraicModel
#print axioms AlgebraicGeometry.ComplexPoint.hasAlgebraicModel_of_analyticLineBundlesAlgebraize
#print axioms AlgebraicGeometry.ComplexPoint.integralCohomologyEquivOrdinarySingularCohomology
#print axioms AlgebraicGeometry.ComplexPoint.hasIntegralDenominatorClearing_of_hasFiniteGoodCover
#print axioms RationalLefschetzOneOne.of_finiteGoodCover_of_divisor
#print axioms SSet.exists_integer_multiple_of_finite_homology
#print axioms AlgebraicGeometry.ComplexPoint.scalarCohomologyEquivOrdinarySingularCohomology_coefficientChange
#print axioms RationalLefschetzOneOne.of_finiteSecondHomology_of_divisor
#print axioms AlgebraicGeometry.ComplexPoint.hasIntegralDenominatorClearing
#print axioms RationalLefschetzOneOne.of_divisor
#print axioms AlgebraicTopology.Singular.module_finite_homology_of_compactSpace_isManifold
#print axioms exists_retraction_of_compact_embedding
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorOfAlgebraicModel_of_divisorClass
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundle_algebraizes_of_iso_unit
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_subsingleton
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_dimension_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundle_isFinitePresentation
#print axioms AlgebraicGeometry.ComplexPoint.algebraicLineBundle_isFinitePresentation
#print axioms AlgebraicGeometry.ComplexPoint.analyticOpen_coversTop
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationFreePUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationIsoOfFreePUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.regularToHolomorphicRingSheafOver
#print axioms AlgebraicGeometry.ComplexPoint.localModuleAnalytificationFreePUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationOverIso
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytification_isInvertible
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.sheafOfModules
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.DegreeZero.unitIso
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.HomogeneousShift.basicOpenUnitIso
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.isInvertible_of_basicOpenCover
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.schemeSheafOfModules_isInvertible_of_basicOpenCover
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.universalNegativeTwist_isInvertible
#print axioms AlgebraicGeometry.Scheme.Modules.pullback_isInvertible
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.complexProjectiveNegativeTwist_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.algebraic_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analytic_isInvertible
#print axioms TauCeti.SheafOfModules.LocalTrivializations.finiteIndexSet_isOpenCover
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundleFiniteTrivializations_coversTop
#print axioms TauCeti.SheafOfModules.LocalTrivializations.transitionIsoOver_trans
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.sumAnalytificationIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.IsSerreGenerated.of_epi
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.AlgebraicTwistPresentation.algebraicModelAnalytificationIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.AlgebraicTwistPresentation.algebraizes
#print axioms AlgebraicGeometry.ComplexPoint.globalHolomorphic_range_finite
#print axioms AlgebraicGeometry.ComplexPoint.regularFunctionsToHolomorphic_top_surjective
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.DegreeZero.schemeUnitIso
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.negativeTwistZeroIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.algebraicZeroIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analyticZeroIso
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.epiIsCokernelOfKernelGenerators
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.exists_algebraicTwistPresentationOfSerreData
#print axioms AlgebraicGeometry.ComplexPoint.analyticLineBundlesAlgebraize_of_serreData
#print axioms AlgebraicGeometry.ComplexPoint.unitEndomorphism_analytification_surjective
#print axioms SheafOfModules.ιFree_matrix_πFree
#print axioms AlgebraicGeometry.ComplexPoint.unitFreeAnalytificationIso_hom_πFree
#print axioms AlgebraicGeometry.ComplexPoint.finiteFreeHom_analytification_surjective
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analyticTwistRelationsAlgebraize_zero
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.instPathConnectedSpace
#print axioms AlgebraicGeometry.ComplexPoint.analytificationGenerates
#print axioms AlgebraicGeometry.ComplexPoint.sectionSheafDeterminesClass
#print axioms AlgebraicGeometry.ComplexPoint.exact_forgetSupport_restrictToComplement
#print axioms Complex.PolynomialGrowth.exists_isHomogeneous_eval_eq_diag
#print axioms Complex.PolynomialGrowth.iteratedDeriv_line_eq_zero
#print axioms Complex.PolynomialGrowth.exists_isHomogeneous_sum_eq
#print axioms Complex.PolynomialGrowth.exists_mvPolynomial_eq_of_growth
#print axioms Complex.PolynomialGrowth.analyticOnNhd_and_growth_iff
#print axioms Complex.PolynomialGrowth.exists_mvPolynomial_eq_of_contMDiff_of_growth
#print axioms Complex.PolynomialGrowth.exists_mvPolynomial_eq_of_homogeneous_of_bounded_sphere
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.projectivizationHomeomorph
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.isOpenQuotientMap_projMk
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartHomeomorph
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.iUnion_chartSet
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.complexPointChartHomeomorph
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.iUnion_complexPointChartSet
#print axioms Complex.PolynomialGrowth.iteratedDeriv_line_eq_zero_of_lt
#print axioms Complex.PolynomialGrowth.exists_bound_of_homogeneous
#print axioms Complex.PolynomialGrowth.exists_isHomogeneous_eq_of_homogeneous
#print axioms Complex.PolynomialGrowth.analyticOnNhd_homogeneous_iff
#print axioms Complex.PolynomialGrowth.eq_zero_of_homogeneous_neg
#print axioms Other.MvPolynomialStandardSmooth.isStandardSmoothOfRelativeDimension
#print axioms Other.ProjectiveChart.eval₂_mul_of_isHomogeneous
#print axioms Other.ProjectiveChart.chartHom_surjective
#print axioms Other.ProjectiveChart.chartHom_injective
#print axioms Other.ProjectiveChart.chartRingEquiv
#print axioms Other.ProjectiveChart.isStandardSmoothOfRelativeDimension_fromZeroRingHom
#print axioms Other.ProjectiveChart.irrelevant_le_span_X
#print axioms Other.ProjectiveChart.smoothOfRelativeDimension_toSpecZero
#print axioms Other.ProjectiveChart.smoothOfRelativeDimension_projectiveSpaceToBase
#print axioms Other.AffineSpaceSmooth.smoothOfRelativeDimension_affineSpace
#print axioms AlgebraicGeometry.ComplexPoint.analyticAt_evaluate_affineSpaceEquiv_symm
#print axioms AlgebraicGeometry.ComplexPoint.contMDiff_affineSpaceEquiv_symm
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.contMDiff_projectivizationToComplexPoint_chartPoint
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.analyticOnNhd_comp_chartPoint
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.isProjective_projectiveSpace
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.exists_mvPolynomial_of_growth
#print axioms Other.ProjectiveChart.deh_homogenise
#print axioms Other.ProjectiveChart.isHomogeneous_homogenise
#print axioms Other.ProjectiveChart.eq_zero_of_deh_eq_zero
#print axioms Other.ProjectiveChart.existsUnique_isHomogeneous_deh_eq
#print axioms Other.ProjectiveChart.totalDegree_deh_le
#print axioms Other.ProjectiveChart.existsUnique_isHomogeneous_of_growth
#print axioms Other.ProjectiveChart.existsUnique_isHomogeneous_of_chart_growth
#print axioms Other.ProjectiveChart.algebraizes_of_serreData_proj
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.overOpen_projectiveSpaceBasicOpen_X
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.twistTrivializations
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.twistChartFramesProj
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.holomorphicGenerates_analyticChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.existsUnique_chartMultiplier
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.contMDiff_chartPointIn
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.analyticOnNhd_comp_chartPointIn
#print axioms AlgebraicGeometry.ComplexPoint.restrictedChernClassVanishes
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_localModel
#print axioms AlgebraicGeometry.Scheme.CartierData.exists_localForm
#print axioms AlgebraicGeometry.ComplexPoint.multiplier_transition
#print axioms AlgebraicGeometry.ComplexPoint.multiplier_eq_of_same_transition
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartMultiplier_eq_on_overlap
#print axioms AlgebraicGeometry.ComplexPoint.hasComponentSupportDecomposition_unconditional
#print axioms AlgebraicGeometry.ComplexPoint.hasCodimensionTwoSupportedVanishing
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_supportedChernLift_of_localModel
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupport_restriction_injective
#print axioms AlgebraicGeometry.ComplexPoint.hasChernLocalModel_of_winding
#print axioms AlgebraicGeometry.ComplexPoint.hasNormalizedWindingCharts_of_forall
#print axioms AlgebraicGeometry.Scheme.Modules.pullbackSection_smul_res
#print axioms AlgebraicGeometry.Scheme.Modules.generates_pullbackSection
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.generates_projFrame
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.projRatio_smul_projFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.generates_algChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.holomorphicGenerates_anChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.spaceRatio_smul_algChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.analyticFunction_spaceRatio_smul_anChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.existsUnique_canonicalChartMultiplier
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.canonicalChartMultiplier_transition
#print axioms CategoryTheory.Limits.exists_sumMatrix_of_hom_surjective
#print axioms AlgebraicGeometry.ComplexPoint.ProjectiveTwist.analyticTwistRelationsAlgebraize_of_rankOne
#print axioms Other.ProjectiveChart.twistRelationsAlgebraizeProj_of_parts
#print axioms AlgebraicGeometry.ComplexPoint.evaluate_eq_appLE_top
#print axioms AlgebraicGeometry.ComplexPoint.evaluate_app_eq_appLE_top
#print axioms AlgebraicGeometry.Proj.awayι_eq_SpecMap_fromSpec
#print axioms AlgebraicGeometry.Proj.ΓSpecIso_appLE_top_awayToSection
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.spaceRatio_pow
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.homogeneousRatioEvaluation
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartRatioEvaluation
#print axioms AlgebraicGeometry.Scheme.Modules.pullbackSection_map
#print axioms AlgebraicGeometry.ComplexPoint.analyticSection_map
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeCohomologyClass_comp_relativeUnitConeδ
#print axioms AlgebraicGeometry.ComplexPoint.nonempty_relativeChernComparison
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.forgetSupport_relativeChernClass
#print axioms AlgebraicGeometry.ComplexPoint.supportedInjectiveToAmbient_relativeChernSupportedClass
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_relativeChernChartFormula
#print axioms AlgebraicGeometry.ComplexPoint.exists_holomorphicExponential_of_simplyConnected
#print axioms ChernWinding.hasRationalWindingPeriod
#print axioms AlgebraicGeometry.ComplexPoint.hasWindingPeriods
#print axioms AlgebraicGeometry.ComplexPoint.hasNormalizedWindingCharts_of_geometricWindingCharts
#print axioms ChernWinding.windingPeriod_standardPuncturedBoundaryClass
#print axioms AlgebraicGeometry.ComplexPoint.exists_chernWindingChart_imp_divisor_eq_zero
#print axioms AlgebraicTopology.Singular.relativeSingularBoundary_naturality
#print axioms AlgebraicTopology.Singular.relativeSingularBoundary_standardComplexLocalClass
#print axioms ChernWinding.windingPeriod_flattenedNormalClass
#print axioms ChernWinding.windingClass_eq_chartNormalProjectionCoclass
#print axioms AlgebraicGeometry.ComplexPoint.exists_holomorphicExponential_flattenedSupportNeighborhood
#print axioms AlgebraicGeometry.ComplexPoint.NormalWindingChartData.normalizesCoclass
#print axioms AlgebraicGeometry.ComplexPoint.exists_closed_normalizedWindingCharts
#print axioms ChernWinding.windingClass_eq_chartNormalProjectionCoclass_of_unit
#print axioms AlgebraicGeometry.ComplexPoint.GenericWindingChartData.normalizesCoclass
#print axioms AlgebraicGeometry.ComplexPoint.hasGeometricWindingCharts_of_genericFlatteningCharts
#print axioms AlgebraicGeometry.ComplexPoint.hasNormalizedWindingCharts_of_genericFlatteningCharts
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySheaf_eq_toSheaf_of_germ
#print axioms AlgebraicGeometry.ComplexPoint.coclass_restrict_of_germ
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartMultiplierGrowth
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.surjective_chartPointIn
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.holSection_ext
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.hom_eq_zero_of_anChartFrame
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.multiplyShiftHom
#print axioms AlgebraicGeometry.ProjectiveSpectrum.NegativeTwist.multiplyShiftHom_projFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.algMulHom_algChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.analytified_algMulHom_anChartFrame
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.chartMultiplier_decay
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.twistRankOneVanishesNeg_of_pos
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.twistRankOneAlgebraizesNeg_of_pos
#print axioms AlgebraicGeometry.ComplexPoint.hasComplementFrame_of_unitOffDivisor
#print axioms AlgebraicGeometry.ComplexPoint.hasComplementFrame_of_stalkUnit
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_unitOffDivisor
#print axioms AlgebraicGeometry.ComplexPoint.hasComplementFrameOffCodimTwo
#print axioms TopCat.Sheaf.supportedSectionsEnlarge_bijective_of_vanishing
#print axioms AlgebraicGeometry.ComplexPoint.exists_closeds_sup_of_codimTwo
#print axioms AlgebraicGeometry.ComplexPoint.enlargeSupportedInjectiveHomology_bijective_of_codimTwo
#print axioms AlgebraicGeometry.ComplexPoint.exists_enlarge_eq_of_codimTwo
#print axioms AlgebraicGeometry.ComplexPoint.supportedInjectiveToAmbient_relativeChernSupportedClassOnClosed
#print axioms AlgebraicGeometry.ComplexPoint.hasChernWindingNaturality_of_generic
#print axioms AlgebraicGeometry.ComplexPoint.hasChernWindingNaturality_of_enlargeSurjective
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_enlargeSurjective
#print axioms AlgebraicGeometry.ComplexPoint.enlargeSurjectiveCodimTwo
#print axioms AlgebraicGeometry.ComplexPoint.hasChernWindingNaturality_of_relativeChernChartFormulaGeneric
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_relativeChernChartFormulaGeneric

-- Divisor–Chern comparison: restriction, normalized cochains, and cone signs.
#print axioms CochainComplex.mappingCone.map_sub_map_of_eq_add
#print axioms CochainComplex.mappingCone.inv_map_descShortComplex_comp_map_sub
#print axioms CochainComplex.mappingCone.cocycleClass_precomp_descShortComplex_eq
#print axioms CochainComplex.mappingCone.quotient_map_descShortComplex_comp_cocycle_eq_neg
#print axioms AlgebraicGeometry.ComplexPoint.injective_smallShiftedHom_precomp
#print axioms AlgebraicGeometry.ComplexPoint.bijective_comp_restrictionUnit
#print axioms AlgebraicGeometry.ComplexPoint.RelativeChernComparison.restrictionClass_eq
#print axioms AlgebraicGeometry.ComplexPoint.nonempty_relativeChernComparison
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.exists_relativeConeMap_sub_eq
#print axioms ChernWinding.iCycles_comp_windingCochain_retraction
#print axioms ChernWinding.rationalWindingCochain_eq_d_comp_rationalFunctionCochain
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicUnitToSingularOneSheaf_comp_coboundary
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicExponential_comp_toSingularOneSheaf
#print axioms AlgebraicGeometry.ComplexPoint.integerConstantsToHolomorphicSheaf_comp_toSingularZeroSheaf
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfCartierData_of_chartFormulaExists

#print axioms CochainComplex.HomComplex.Cocycle.exists_precomp_single_eq
#print axioms AlgebraicGeometry.ComplexPoint.integerSingularZeroCocycle_homOf
#print axioms AlgebraicGeometry.ComplexPoint.exponential_cone_comp_extClass
#print axioms AlgebraicGeometry.ComplexPoint.rationalChernShiftedHom_comp_singularAugmentation
#print axioms AlgebraicTopology.Singular.relativeDualShiftIsoCochainCone_inr_inv
#print axioms AlgebraicTopology.Singular.relativeCochainConeHomologyIsoDualRelativeInt_boundary

#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCocycle_precomp
#print axioms AlgebraicGeometry.ComplexPoint.restrictedRationalChernShiftedHom_eq_singularCocycle
#print axioms AlgebraicGeometry.ComplexPoint.RelativeChernComparison.boundary_eq_singular
#print axioms CochainComplex.homology_shiftMap_homOfDegreewiseSplit_eq_δ
#print axioms AlgebraicTopology.Singular.relativeCochainConeHomologyIsoDualRelativeInt_boundary_eq_δ

#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.restrictionFactorisation_comp_inclusion
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.restrictionFactorisation_sub_comp_inclusion
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.exists_relativeConeMap_sub_eq_with_liftHom

#print axioms TopCat.Sheaf.constHomOfSection_integerOne_apply
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.liftHom_integerOneSection
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.liftHom_difference_section_eq_neg_unit

#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicGenerates.isUnit_smul
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.frameLiftUnit_unique
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.projection_frameLift
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.frameLift_smul_unit
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.frameLift_restrict
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.frameLift_eq
#print axioms AlgebraicGeometry.ComplexPoint.localLift_eq_frameLift
#print axioms AlgebraicGeometry.ComplexPoint.UnitDatum.holomorphicGenerates_regularFrame
#print axioms AlgebraicGeometry.ComplexPoint.UnitDatum.analyticFrame_eq_smul_regularFrame
#print axioms AlgebraicGeometry.ComplexPoint.localLift_eq_regularFrameLift_add_unit
#print axioms AlgebraicGeometry.ComplexPoint.exists_lift_of_goodLocus_with_localFormula
#print axioms AlgebraicGeometry.Scheme.CartierData.LocalForm.equationUnit_val
#print axioms AlgebraicGeometry.Scheme.CartierData.LocalForm.germ_cartierUnit
#print axioms AlgebraicGeometry.Scheme.CartierData.LocalForm.toUnitDatum
#print axioms AlgebraicGeometry.ComplexPoint.analyticUnitHom_restrict
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.punctured_le_basicOpen
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.equationUnit_eq_coord
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.cartierUnit_eq
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.winding_cartierUnit
#print axioms AlgebraicGeometry.ComplexPoint.UnitDatum.regularFrame_eq_restrict
#print axioms AlgebraicGeometry.ComplexPoint.analyticUnit_toUnitDatum
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.holomorphicGenerates_regularFrame
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.regularFrame_restrict_unitDatum
#print axioms AlgebraicGeometry.ComplexPoint.IsCartierComplementLift.restrict_chart
#print axioms AlgebraicGeometry.ComplexPoint.IsCartierComplementLift.restrict_chart_eq_restrict_regularLift_add
#print axioms AlgebraicGeometry.ComplexPoint.IsCartierComplementLift.chart_liftHom_difference_section

#print axioms CochainComplex.mappingCocone.inrHomotopyHomOfDegreewiseSplit
#print axioms CochainComplex.mappingCocone.homologyMap_inr_comp_shortExactHomologyIsoCone_inv
#print axioms AlgebraicTopology.Singular.relativeCochainCone_legacy_canonical_boundary
#print axioms AlgebraicTopology.Singular.relativeCochainConeCohomologyEquiv_eq_canonical_of_boundary
#print axioms HomologicalComplex.linearDualHomologyEquiv_homologyπ_apply
#print axioms CategoryTheory.ShortComplex.linearDualChain_shortExact
#print axioms CategoryTheory.ShortComplex.linearDualChain_connecting_pairing
#print axioms HomologicalComplex.extendOpcyclesIso_hom_opcyclesToCycles
#print axioms HomologicalComplex.extendSnakeInputMap
#print axioms HomologicalComplex.extend_connecting
#print axioms ChernWinding.iCycles_rationalWindingCocycle
#print axioms ChernWinding.linearDualHomologyEquiv_rationalWindingCohomologyClass
#print axioms ChernWinding.rationalWindingCohomologyClass_connecting
#print axioms ChernWinding.relativeCochainConeCohomologyEquiv_boundary_rationalWinding

-- Actual complement resolutions and the supported-injective boundary sign.
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportConeToAmbientInjectiveCone_inr
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportAddEquivAmbientInjectiveConeGlobalSections_boundary
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportHypercohomologyAddEquivNaturalSingularConeGlobalSections_boundary
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportAmbientInjective_of_naturalSingular_boundary
#print axioms HomologicalComplex.comp_descOfPrecompBijective
#print axioms HomologicalComplex.homotopyOfPrecompBijective
#print axioms CochainComplex.homotopyOfPrecompQuasiIso
#print axioms AlgebraicGeometry.ComplexPoint.complementResolution_precomp_bijective
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularRestriction_comp_naturalOutsideResolutionComparison
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularRestriction_comp_ambientOutsideResolutionComparison
#print axioms AlgebraicGeometry.ComplexPoint.naturalSingularResolutionRestrictionHomotopy
#print axioms AlgebraicGeometry.ComplexPoint.naturalSingularOutsideResolutionComparisonHomotopy
#print axioms AlgebraicGeometry.ComplexPoint.naturalSingularOutsideResolutionComparison_homologyMap
#print axioms AlgebraicTopology.Singular.globalRawSingularRestrictionInt_epi
#print axioms AlgebraicTopology.Singular.globalRawSingularRestrictionInt_comp_topOpen
#print axioms AlgebraicGeometry.ComplexPoint.globalRawSingularRestrictionInt_comp_actualSingularOutside
#print axioms AlgebraicGeometry.ComplexPoint.globalRawComplementToActualSingularOutside_comp_natural
#print axioms AlgebraicGeometry.ComplexPoint.globalRawComplementToActualSingularOutside_comp_ambient_homologyMap
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportAddEquivSupportedInjectiveHomology_eq_neg
#print axioms AlgebraicGeometry.ComplexPoint.actualSupportConeToAmbientInjectiveGlobalCone_inr
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportAddEquivSupportedInjectiveHomology_boundary
#print axioms CochainComplex.mappingCocone.shortExactHomologyIsoCone_inv_inr_naturality
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularToInjectiveOutside_comp_resolution
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularSupportBoundary_comp_injective
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportAddEquivSupportedInjectiveHomology_raw_boundary

-- Literal local relative normalization and the actual restricted winding coefficient.
#print axioms CochainComplex.mappingCone.inr_mapArrowIso
#print axioms TopCat.Sheaf.supportRestrictionSectionsConeIso_inr
#print axioms TopCat.Sheaf.sectionComplexRestrictionExtendConeIso_inr
#print axioms AlgebraicTopology.Singular.openRawToSupportedSingularOutside_boundary
#print axioms AlgebraicTopology.Singular.supportedSingularSectionCohomologyEquivRelative_boundary
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionConeIsoRelative_inr
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionConeCohomologyEquivRelative_boundary
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionConeCohomologyEquivRelative_boundary_legacy
#print axioms AlgebraicTopology.Singular.openRawCochainHomologyEquivDual_restriction
#print axioms AlgebraicTopology.Singular.relativeCochainConeCohomologyEquivCanonical_boundary_naturality
#print axioms ChernWinding.rationalWindingCocycle_naturality
#print axioms ChernWinding.rationalWindingCohomologyClass_naturality
#print axioms ChernWinding.rationalWindingIntCohomologyClass_naturality
#print axioms ChernWinding.openRawRationalWindingClass_restriction
#print axioms ChernWinding.supportedSingularSectionCohomologyEquivSupportComplement_winding_boundary
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveSectionCohomologyEquiv_supported_singular
#print axioms AlgebraicGeometry.ComplexPoint.globalRawComplementToActualSingularOutside_eq_topOpen
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportAddEquivSupportedInjectiveHomology_raw_boundary_relative
#print axioms AlgebraicGeometry.ComplexPoint.restrictionUnit_comp_restrictedSingularOneCoefficient
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularRestriction_comp_naturalOutsideResolutionComparisonOnOpen
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_eq_restricted_winding
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_apply
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_comp_d
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicSingularOneCoefficient_apply_raw
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_apply_raw
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_apply_on_open
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_apply_on_open_raw

-- Actual winding cycle representatives under the fixed complement hypercohomology map.
#print axioms TopCat.Sheaf.integerConstantHomEquivGlobalSections_id
#print axioms TopCat.Sheaf.integerConstantHomEquivGlobalSections_constHomOfSection
#print axioms TopCat.Sheaf.homComplexSingleIntegerIsoGlobalSections_precomp_constHom
#print axioms TopCat.Sheaf.iCycles_integerCocycleGlobalSection
#print axioms TopCat.Sheaf.iCycles_integerCocycleGlobalSection_precomp_constHom
#print axioms CochainComplex.HomComplex.homologyAddEquiv_symm_mk
#print axioms AlgebraicGeometry.ComplexPoint.derivedHomAddEquivGlobalSectionsKInjective_cocycle
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyAddEquivGlobalSections_eq_kInjective
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyAddEquivGlobalSectionsKInjective_mk_cocycle
#print axioms AlgebraicGeometry.ComplexPoint.iCycles_restrictedSingularOneGlobalCocycle
#print axioms AlgebraicGeometry.ComplexPoint.derivedHomAddEquivGlobalSections_restrictedSingularOneCocycle
#print axioms AlgebraicGeometry.ComplexPoint.complementRationalHypercohomology_restrictedSingularOneCocycle
#print axioms AlgebraicGeometry.ComplexPoint.naturalSingularOutsideResolutionComparisonOnOpen_eq_canonical

-- Normalized raw representatives and the actual exponential/winding class equality.
#print axioms HomologicalComplex.mapExtendCanonicalIso_inv_f
#print axioms HomologicalComplex.mapExtendIso_hom_f
#print axioms AlgebraicTopology.Singular.openRawSingularCochainComplexIntIsoDual_inv_f
#print axioms CategoryTheory.ShortComplex.homologyπ_mapHomologyIso_hom
#print axioms ChernWinding.homologyπ_rationalWindingIntCocycle
#print axioms ChernWinding.iCycles_rationalWindingIntCocycle
#print axioms ChernWinding.homologyπ_openRawRationalWindingCocycle
#print axioms ChernWinding.iCycles_openRawRationalWindingCocycle
#print axioms AlgebraicGeometry.ComplexPoint.openRawToComplementResolutionOnOpen_f
#print axioms AlgebraicGeometry.ComplexPoint.cyclesMap_openRawToComplementResolutionOnOpen_winding
#print axioms AlgebraicGeometry.ComplexPoint.homologyMap_openRawToComplementResolutionOnOpen_winding
#print axioms AlgebraicGeometry.ComplexPoint.complementRationalHypercohomology_restrictedSingularOneCocycle_eq_rawWinding

-- Literal intrinsic-complement presentation of the actual exponential winding class.
#print axioms AlgebraicTopology.Singular.globalRawComplementToTopOpenCochains_isIso
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionInt_epi
#print axioms AlgebraicTopology.Singular.openRawSingularRestriction_comp
#print axioms AlgebraicGeometry.ComplexPoint.openRawRestriction_comp_complementResolutionOnOpen
#print axioms AlgebraicGeometry.ComplexPoint.openRawRestriction_comp_intrinsicComplement
#print axioms AlgebraicGeometry.ComplexPoint.openRawToComplementResolutionOnOpen_eq_intrinsic
#print axioms AlgebraicGeometry.ComplexPoint.openRawToIntrinsicComplement_comp_topOpen
#print axioms AlgebraicGeometry.ComplexPoint.complementRationalHypercohomology_restrictedSingularOneCocycle_eq_intrinsicWinding

-- The actual relative Chern class and its concrete frame-change boundary.
#print axioms ChernWinding.openRawRelative_winding_boundary
#print axioms AlgebraicGeometry.ComplexPoint.RelativeChernComparison.boundary_eq_singular_on_section
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyEquiv_sub
#print axioms AlgebraicGeometry.ComplexPoint.constantIntegerMorphism_eq_constHomOfSection
#print axioms AlgebraicGeometry.ComplexPoint.restrictedIntegerMorphism_eq_constHomOfSection
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_equiv
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_sub_of_cone_difference
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.exists_relativeChernClass_sub_eq_singular_boundary
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.exists_relativeChernClass_sub_eq_unit_boundary
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_sub_eq_neg_unit_boundary

-- The actual frame variation under the fixed support-to-winding comparison.
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportBoundary_restrictedSingularOneCocycle_eq_winding
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportBoundary_restrictedSingularOneCocycle_eq_windingHom
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_sub_eq_winding

#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_sub_eq_windingSheaf

-- Actual restriction and local vanishing for an extending reference frame.
#print axioms CochainComplex.mappingCone.mapHomotopyZeroOfFactorization
#print axioms CochainComplex.mappingCone.homotopyToZeroOfIsIso
#print axioms CochainComplex.mappingCone.mapHomologicalComplexConeHomotopyZero
#print axioms AlgebraicGeometry.ComplexPoint.openRestrictionTopEval_inv_naturality_open
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.liftHom_restrict
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.projection_restrict_lift
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.restrictionFactorisation_restrict
#print axioms AlgebraicGeometry.ComplexPoint.relativeUnitConeRestriction
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeConeMap_restrict
#print axioms AlgebraicGeometry.ComplexPoint.isIso_restrictToOpen_single_restrictionUnit
#print axioms AlgebraicGeometry.ComplexPoint.relativeUnitCone_restrict_self_homotopyZero
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeConeMap_restrict_homotopyZero
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeConeMap_restrict_mapDerivedCategory_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.regularFrame_relativeChernClass_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_local_eq_neg_unit_boundary

-- Derived vanishing and the actual cocycle-to-cohomology-sheaf normalization.
#print axioms HomologicalComplex.homologyMap_eq_zero_of_Q_map_eq_zero
#print axioms CategoryTheory.Functor.Q_map_mapHomologicalComplex_eq_zero_of_mapDerivedCategory_eq_zero
#print axioms CategoryTheory.Functor.homologyMap_mapHomologicalComplex_eq_zero_of_mapDerivedCategory_eq_zero
#print axioms TopCat.Sheaf.sectionCohomologyToSheafSection_map_eq_zero_of_Q_map_eq_zero
#print axioms TopCat.Sheaf.homologyMap_onOpen_eq_zero_of_derived_restriction_eq_zero
#print axioms TopCat.Sheaf.sectionCohomologyToSheafSection_map_eq_zero_of_derived_restriction_eq_zero
#print axioms TopCat.Sheaf.integerCocycleGlobalSection_postcomp
#print axioms TopCat.Sheaf.homologyπ_integerCocycleGlobalSection_postcomp
#print axioms TopCat.Sheaf.sectionCohomology_integerCocycleGlobalSection_postcomp
#print axioms TopCat.Sheaf.sectionCohomology_integerCocycleGlobalSection_postcomp_onOpen_eq_zero
#print axioms TopCat.Sheaf.sectionCohomology_integerCocycleGlobalSection_ofHom_onOpen_eq_zero
