import Other.AlgebraicTopology.Sheaf.CohomologySectionNaturality
import Other.AlgebraicTopology.Sheaf.CohomologySectionShiftTransport
import Other.AlgebraicTopology.Sheaf.CohomologySectionShiftTop
import Other.AlgebraicTopology.Sheaf.CohomologySectionArbitraryDegreeVanishing
import Other.AlgebraicGeometry.RelativeChernLocalBoundary
import Other.AlgebraicGeometry.RelativeChernOriginalRestriction
import Other.AlgebraicTopology.CohomologySheafSectionDerivedVanishing
import Other.AlgebraicGeometry.CocycleGlobalSectionNaturality
import Other.AlgebraicGeometry.CartierWindingChartVanishing
import Other.AlgebraicGeometry.CartierChernLocalWinding
import Other.AlgebraicGeometry.CartierWindingChartNormalizedVanishing
import Other.AlgebraicGeometry.CartierWindingChartCoefficient
import Other.AlgebraicGeometry.ChernRelativeCanonicalLift
import Other.AlgebraicGeometry.ChernComponentLocalIsolation
import Other.AlgebraicGeometry.CartierLocalIdeal
import Other.AlgebraicGeometry.CartierLocalDerivative
import Other.AlgebraicGeometry.CartierLocalDerivativePointJet
import Other.AlgebraicGeometry.ChernWindingGenericChartAssembly
import Other.AlgebraicGeometry.ChernWindingGenericChartConditional
import Other.AlgebraicGeometry.ChernWindingGenericChartCanonical
import Other.AlgebraicGeometry.ChernWindingGenericChartAlgebraic
import Other.AlgebraicGeometry.SupportedInjectiveSectionNaturality
import Other.AlgebraicGeometry.Cohomology.SupportSheafConeComparison
import Other.AlgebraicGeometry.Cohomology.SupportSheafConeQuasiIso
import Other.AlgebraicGeometry.Cohomology.SupportSheafConeNormalization
import Other.AlgebraicGeometry.Cohomology.SupportSheafConeLocalVanishing
import Other.AlgebraicTopology.Sheaf.FlasquePushforwardQuasiIso
import Other.AlgebraicGeometry.ChernRelativeChartFormulaGenericLocal
import Other.Analysis.Complex.NormalDivision
import Other.Analysis.Complex.NormalDivisionChart
import Other.Analysis.Complex.NormalDivisionFinOne
import Other.RingTheory.RegularLocalEquation
import Other.RingTheory.CotangentDetection
import Other.AlgebraicGeometry.PointJetDerivation
import Other.AlgebraicGeometry.PointJetDetection
import Other.AlgebraicGeometry.PointJetSectionGerm
import Other.AlgebraicTopology.Sheaf.CohomologyShiftDerivedVanishing
import Other.AlgebraicGeometry.ClosedImmersion.HolomorphicChartsAnalytic
/- Representative axiom checks for the incomplete Lefschetz development.
Run: lake env lean scripts/lefschetz_axiom_audit.lean
See docs/LEFSCHETZ_HANDOFF.md for the full goal and remaining obligations. -/
import Other.AlgebraicGeometry.ChernWindingRawBoundary
import Other.AlgebraicGeometry.RelativeChernFrameVariation
import Other.AlgebraicGeometry.RelativeChernFrameWinding
import Other.AlgebraicGeometry.HolomorphicExponentialIntrinsicWindingClass
import Other.AlgebraicGeometry.CocycleGlobalSections
import Other.AlgebraicGeometry.HolomorphicExponentialSingularSectionClass
import Other.AlgebraicTopology.SupportedSingularBoundaryRelative
import Other.AlgebraicTopology.OpenRawBoundaryComparison
import Other.AlgebraicGeometry.ChernWindingCohomologyNaturality
import Other.AlgebraicGeometry.ChernWindingSupportedBoundary
import Other.AlgebraicGeometry.RationalSupportBoundaryRelative
import Other.AlgebraicGeometry.HolomorphicExponentialSingularSections
import Other.Algebra.Homology.RationalCochainDenominators
import Other.AlgebraicGeometry.RawComplementResolutionComparison
import Other.AlgebraicGeometry.SupportedInjectiveBoundaryNormalization
import Other.AlgebraicGeometry.ActualSingularSupportBoundary
import Other.AlgebraicGeometry.AnalytificationModules
import Other.AlgebraicGeometry.HolomorphicLineBundleInvertible
import Other.AlgebraicGeometry.LefschetzOneOne
import Other.AlgebraicGeometry.LefschetzOneOneReduction
import Other.AlgebraicGeometry.BettiScalarComparison
import Other.AlgebraicGeometry.IntegralDenominatorClearing
import Other.AlgebraicGeometry.ProjectiveFiniteHomology
import Other.AlgebraicGeometry.DivisorObligations
import Other.AlgebraicGeometry.AnalytificationGenerates
import Other.AlgebraicGeometry.UnitExtensionClassOfSectionSheaf
import Other.AlgebraicGeometry.CohomologyWithSupportExact
import Other.AlgebraicGeometry.ChernClassRestrictionVanishing
import Other.AlgebraicGeometry.ChernLocalModel
import Other.AlgebraicGeometry.CartierLocalForm
import Other.AlgebraicGeometry.ClosedSupportCoheightDimension
import Other.AlgebraicGeometry.CycleComponentRestrictionInjective
import Other.AlgebraicGeometry.ChernLocalModelWinding
import Other.AlgebraicGeometry.ChernRelativeClassNaturality
import Other.AlgebraicGeometry.ChernWindingChartPeriods
import Other.AlgebraicGeometry.ChernWindingStandardTriangle
import Other.AlgebraicGeometry.ChernWindingLocalFormObstruction
import Other.AlgebraicGeometry.ChernWindingHolomorphicLog
import Other.AlgebraicGeometry.ChernWindingNormalChartExistence
import Other.AlgebraicGeometry.ChernWindingGenericChartExistence
import Other.AlgebraicGeometry.ChernWindingNormalChartTransport
import Other.AlgebraicGeometry.ComplementFrame
import Other.AlgebraicGeometry.ComplementFrameGeneric
import Other.AlgebraicGeometry.ChernRelativeClassGeneric
import Other.AlgebraicGeometry.SupportEnlargementCodimTwo
import Other.Algebra.Homology.MappingConeCocycle
import Other.AlgebraicGeometry.ChernRelativeChartFormula
import Other.AlgebraicGeometry.ChernRelativeChartFormulaSplitting
import Other.AlgebraicGeometry.ChernWindingChartCoclassRestrict
import Other.AlgebraicGeometry.HolomorphicExponentialSingularCochain
import Other.Algebra.Homology.SingleCocycleFactorization
import Other.AlgebraicGeometry.HolomorphicExponentialSingularClass
import Other.AlgebraicTopology.RelativeCochainConeBoundaryComparison
import Other.AlgebraicGeometry.ChernWindingConnecting
import Other.AlgebraicTopology.LinearDualConnecting
import Other.Algebra.Homology.ExtendConnecting
import Other.AlgebraicGeometry.HolomorphicExponentialSingularRestriction
import Other.AlgebraicGeometry.HolomorphicFrameLift
import Other.AlgebraicGeometry.CartierFrameLift
import Other.AlgebraicGeometry.CartierLocalFormUnit
import Other.AlgebraicGeometry.CartierWindingChartUnit
import Other.AlgebraicGeometry.CartierWindingChartFrame

#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.localCoordinateEquiv
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.sectionSheafOfModules_isInvertible
#print axioms AlgebraicGeometry.ComplexPoint.contMDiffAt_evaluate
#print axioms AlgebraicGeometry.ComplexPoint.regularToHolomorphicSheaf
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationAdjunction
#print axioms AlgebraicGeometry.ComplexPoint.moduleAnalytificationUnitIso
#print axioms AlgebraicGeometry.ComplexPoint.exists_holomorphicUnitExtension_of_integral_hodgeClass
#print axioms HodgeConjecture.rationalLefschetzOneOne
#print axioms HodgeConjecture.rationalLefschetzOneOne_direct
#print axioms LinearMap.exists_integer_multiple_isInteger
#print axioms LinearMap.exists_integer_multiple
#print axioms CategoryTheory.ShortComplex.homologyMap_exists_integer_multiple
#print axioms AlgebraicGeometry.ComplexPoint.exists_rationalSheafCycleClassOnCycles_eq_of_obligations
#print axioms RationalLefschetzOneOne.of_obligations
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorOfUnitExtension_of_algebraicModel
#print axioms AlgebraicGeometry.ComplexPoint.integralCohomologyEquivOrdinarySingularCohomology
#print axioms AlgebraicGeometry.ComplexPoint.hasIntegralDenominatorClearing_of_hasFiniteGoodCover
#print axioms RationalLefschetzOneOne.of_finiteGoodCover_of_divisor
#print axioms SSet.exists_integer_multiple_of_finite_homology
#print axioms AlgebraicGeometry.ComplexPoint.scalarCohomologyEquivOrdinarySingularCohomology_coefficientChange
#print axioms RationalLefschetzOneOne.of_finiteSecondHomology_of_divisor
#print axioms AlgebraicGeometry.ComplexPoint.hasIntegralDenominatorClearing
#print axioms RationalLefschetzOneOne.of_divisor
#print axioms AlgebraicTopology.Singular.module_finite_homology_of_compactSpace_isManifold
#print axioms exists_retraction_of_compact_embedding
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorOfAlgebraicModel_of_divisorClass
#print axioms AlgebraicGeometry.ComplexProjectiveSpace.instPathConnectedSpace
#print axioms AlgebraicGeometry.ComplexPoint.analytificationGenerates
#print axioms AlgebraicGeometry.ComplexPoint.sectionSheafDeterminesClass
#print axioms AlgebraicGeometry.ComplexPoint.exact_forgetSupport_restrictToComplement
#print axioms AlgebraicGeometry.ComplexPoint.restrictedChernClassVanishes
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_localModel
#print axioms AlgebraicGeometry.Scheme.CartierData.exists_localForm
#print axioms AlgebraicGeometry.ComplexPoint.hasComponentSupportDecomposition_unconditional
#print axioms AlgebraicGeometry.ComplexPoint.hasCodimensionTwoSupportedVanishing
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_supportedChernLift_of_localModel
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSmoothSupport_restriction_injective
#print axioms AlgebraicGeometry.ComplexPoint.hasChernLocalModel_of_winding
#print axioms AlgebraicGeometry.ComplexPoint.hasNormalizedWindingCharts_of_forall
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeCohomologyClass_comp_relativeUnitConeδ
#print axioms AlgebraicGeometry.ComplexPoint.nonempty_relativeChernComparison
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.forgetSupport_relativeChernClass
#print axioms AlgebraicGeometry.ComplexPoint.supportedInjectiveToAmbient_relativeChernSupportedClass
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_relativeChernChartFormula
#print axioms AlgebraicGeometry.ComplexPoint.exists_holomorphicExponential_of_simplyConnected
#print axioms ChernWinding.hasRationalWindingPeriod
#print axioms AlgebraicGeometry.ComplexPoint.hasWindingPeriods
#print axioms AlgebraicGeometry.ComplexPoint.hasNormalizedWindingCharts_of_geometricWindingCharts
#print axioms ChernWinding.windingPeriod_standardPuncturedBoundaryClass
#print axioms AlgebraicGeometry.ComplexPoint.exists_chernWindingChart_imp_divisor_eq_zero
#print axioms AlgebraicTopology.Singular.relativeSingularBoundary_naturality
#print axioms AlgebraicTopology.Singular.relativeSingularBoundary_standardComplexLocalClass
#print axioms ChernWinding.windingPeriod_flattenedNormalClass
#print axioms ChernWinding.windingClass_eq_chartNormalProjectionCoclass
#print axioms AlgebraicGeometry.ComplexPoint.exists_holomorphicExponential_flattenedSupportNeighborhood
#print axioms AlgebraicGeometry.ComplexPoint.NormalWindingChartData.normalizesCoclass
#print axioms AlgebraicGeometry.ComplexPoint.exists_closed_normalizedWindingCharts
#print axioms ChernWinding.windingClass_eq_chartNormalProjectionCoclass_of_unit
#print axioms AlgebraicGeometry.ComplexPoint.GenericWindingChartData.normalizesCoclass
#print axioms AlgebraicGeometry.ComplexPoint.hasGeometricWindingCharts_of_genericFlatteningCharts
#print axioms AlgebraicGeometry.ComplexPoint.hasNormalizedWindingCharts_of_genericFlatteningCharts
#print axioms AlgebraicTopology.Singular.supportRelativeCohomologySheaf_eq_toSheaf_of_germ
#print axioms AlgebraicGeometry.ComplexPoint.coclass_restrict_of_germ
#print axioms AlgebraicGeometry.ComplexPoint.hasComplementFrame_of_unitOffDivisor
#print axioms AlgebraicGeometry.ComplexPoint.hasComplementFrame_of_stalkUnit
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_unitOffDivisor
#print axioms AlgebraicGeometry.ComplexPoint.hasComplementFrameOffCodimTwo
#print axioms TopCat.Sheaf.supportedSectionsEnlarge_bijective_of_vanishing
#print axioms AlgebraicGeometry.ComplexPoint.exists_closeds_sup_of_codimTwo
#print axioms AlgebraicGeometry.ComplexPoint.enlargeSupportedInjectiveHomology_bijective_of_codimTwo
#print axioms AlgebraicGeometry.ComplexPoint.exists_enlarge_eq_of_codimTwo
#print axioms AlgebraicGeometry.ComplexPoint.supportedInjectiveToAmbient_relativeChernSupportedClassOnClosed
#print axioms AlgebraicGeometry.ComplexPoint.hasChernWindingNaturality_of_generic
#print axioms AlgebraicGeometry.ComplexPoint.hasChernWindingNaturality_of_enlargeSurjective
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_enlargeSurjective
#print axioms AlgebraicGeometry.ComplexPoint.enlargeSurjectiveCodimTwo
#print axioms AlgebraicGeometry.ComplexPoint.hasChernWindingNaturality_of_relativeChernChartFormulaGeneric
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfSomeCartierData_of_relativeChernChartFormulaGeneric

-- Divisor–Chern comparison: restriction, normalized cochains, and cone signs.
#print axioms CochainComplex.mappingCone.map_sub_map_of_eq_add
#print axioms CochainComplex.mappingCone.inv_map_descShortComplex_comp_map_sub
#print axioms CochainComplex.mappingCone.cocycleClass_precomp_descShortComplex_eq
#print axioms CochainComplex.mappingCone.quotient_map_descShortComplex_comp_cocycle_eq_neg
#print axioms AlgebraicGeometry.ComplexPoint.injective_smallShiftedHom_precomp
#print axioms AlgebraicGeometry.ComplexPoint.bijective_comp_restrictionUnit
#print axioms AlgebraicGeometry.ComplexPoint.RelativeChernComparison.restrictionClass_eq
#print axioms AlgebraicGeometry.ComplexPoint.nonempty_relativeChernComparison
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.exists_relativeConeMap_sub_eq
#print axioms ChernWinding.iCycles_comp_windingCochain_retraction
#print axioms ChernWinding.rationalWindingCochain_eq_d_comp_rationalFunctionCochain
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicUnitToSingularOneSheaf_comp_coboundary
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicExponential_comp_toSingularOneSheaf
#print axioms AlgebraicGeometry.ComplexPoint.integerConstantsToHolomorphicSheaf_comp_toSingularZeroSheaf
#print axioms AlgebraicGeometry.ComplexPoint.hasDivisorClassOfCartierData_of_chartFormulaExists
#print axioms AlgebraicGeometry.ComplexPoint.cycleComponentSheafClass_eq_injectiveModel

#print axioms CochainComplex.HomComplex.Cocycle.exists_precomp_single_eq
#print axioms AlgebraicGeometry.ComplexPoint.integerSingularZeroCocycle_homOf
#print axioms AlgebraicGeometry.ComplexPoint.exponential_cone_comp_extClass
#print axioms AlgebraicGeometry.ComplexPoint.rationalChernShiftedHom_comp_singularAugmentation
#print axioms AlgebraicTopology.Singular.relativeDualShiftIsoCochainCone_inr_inv
#print axioms AlgebraicTopology.Singular.relativeCochainConeHomologyIsoDualRelativeInt_boundary

#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCocycle_precomp
#print axioms AlgebraicGeometry.ComplexPoint.restrictedRationalChernShiftedHom_eq_singularCocycle
#print axioms AlgebraicGeometry.ComplexPoint.RelativeChernComparison.boundary_eq_singular
#print axioms CochainComplex.homology_shiftMap_homOfDegreewiseSplit_eq_δ
#print axioms AlgebraicTopology.Singular.relativeCochainConeHomologyIsoDualRelativeInt_boundary_eq_δ

#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.restrictionFactorisation_comp_inclusion
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.restrictionFactorisation_sub_comp_inclusion
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.exists_relativeConeMap_sub_eq_with_liftHom

#print axioms TopCat.Sheaf.constHomOfSection_integerOne_apply
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.liftHom_integerOneSection
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.liftHom_difference_section_eq_neg_unit

#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicGenerates.isUnit_smul
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.frameLiftUnit_unique
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.projection_frameLift
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.frameLift_smul_unit
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.frameLift_restrict
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.frameLift_eq
#print axioms AlgebraicGeometry.ComplexPoint.localLift_eq_frameLift
#print axioms AlgebraicGeometry.ComplexPoint.UnitDatum.holomorphicGenerates_regularFrame
#print axioms AlgebraicGeometry.ComplexPoint.UnitDatum.analyticFrame_eq_smul_regularFrame
#print axioms AlgebraicGeometry.ComplexPoint.localLift_eq_regularFrameLift_add_unit
#print axioms AlgebraicGeometry.ComplexPoint.exists_lift_of_goodLocus_with_localFormula
#print axioms AlgebraicGeometry.Scheme.CartierData.LocalForm.equationUnit_val
#print axioms AlgebraicGeometry.Scheme.CartierData.LocalForm.germ_cartierUnit
#print axioms AlgebraicGeometry.Scheme.CartierData.LocalForm.toUnitDatum
#print axioms AlgebraicGeometry.ComplexPoint.analyticUnitHom_restrict
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.punctured_le_basicOpen
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.equationUnit_eq_coord
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.cartierUnit_eq
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.winding_cartierUnit
#print axioms AlgebraicGeometry.ComplexPoint.UnitDatum.regularFrame_eq_restrict
#print axioms AlgebraicGeometry.ComplexPoint.analyticUnit_toUnitDatum
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.holomorphicGenerates_regularFrame
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.regularFrame_restrict_unitDatum
#print axioms AlgebraicGeometry.ComplexPoint.IsCartierComplementLift.restrict_chart
#print axioms AlgebraicGeometry.ComplexPoint.IsCartierComplementLift.restrict_chart_eq_restrict_regularLift_add
#print axioms AlgebraicGeometry.ComplexPoint.IsCartierComplementLift.chart_liftHom_difference_section

#print axioms CochainComplex.mappingCocone.inrHomotopyHomOfDegreewiseSplit
#print axioms CochainComplex.mappingCocone.homologyMap_inr_comp_shortExactHomologyIsoCone_inv
#print axioms AlgebraicTopology.Singular.relativeCochainCone_legacy_canonical_boundary
#print axioms AlgebraicTopology.Singular.relativeCochainConeCohomologyEquiv_eq_canonical_of_boundary
#print axioms HomologicalComplex.linearDualHomologyEquiv_homologyπ_apply
#print axioms CategoryTheory.ShortComplex.linearDualChain_shortExact
#print axioms CategoryTheory.ShortComplex.linearDualChain_connecting_pairing
#print axioms HomologicalComplex.extendOpcyclesIso_hom_opcyclesToCycles
#print axioms HomologicalComplex.extendSnakeInputMap
#print axioms HomologicalComplex.extend_connecting
#print axioms ChernWinding.iCycles_rationalWindingCocycle
#print axioms ChernWinding.linearDualHomologyEquiv_rationalWindingCohomologyClass
#print axioms ChernWinding.rationalWindingCohomologyClass_connecting
#print axioms ChernWinding.relativeCochainConeCohomologyEquiv_boundary_rationalWinding

-- Actual complement resolutions and the supported-injective boundary sign.
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportConeToAmbientInjectiveCone_inr
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportAddEquivAmbientInjectiveConeGlobalSections_boundary
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportHypercohomologyAddEquivNaturalSingularConeGlobalSections_boundary
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportAmbientInjective_of_naturalSingular_boundary
#print axioms HomologicalComplex.comp_descOfPrecompBijective
#print axioms HomologicalComplex.homotopyOfPrecompBijective
#print axioms CochainComplex.homotopyOfPrecompQuasiIso
#print axioms AlgebraicGeometry.ComplexPoint.complementResolution_precomp_bijective
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularRestriction_comp_naturalOutsideResolutionComparison
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularRestriction_comp_ambientOutsideResolutionComparison
#print axioms AlgebraicGeometry.ComplexPoint.naturalSingularResolutionRestrictionHomotopy
#print axioms AlgebraicGeometry.ComplexPoint.naturalSingularOutsideResolutionComparisonHomotopy
#print axioms AlgebraicGeometry.ComplexPoint.naturalSingularOutsideResolutionComparison_homologyMap
#print axioms AlgebraicTopology.Singular.globalRawSingularRestrictionInt_epi
#print axioms AlgebraicTopology.Singular.globalRawSingularRestrictionInt_comp_topOpen
#print axioms AlgebraicGeometry.ComplexPoint.globalRawSingularRestrictionInt_comp_actualSingularOutside
#print axioms AlgebraicGeometry.ComplexPoint.globalRawComplementToActualSingularOutside_comp_natural
#print axioms AlgebraicGeometry.ComplexPoint.globalRawComplementToActualSingularOutside_comp_ambient_homologyMap
#print axioms AlgebraicGeometry.ComplexPoint.coneSupportAddEquivSupportedInjectiveHomology_eq_neg
#print axioms AlgebraicGeometry.ComplexPoint.actualSupportConeToAmbientInjectiveGlobalCone_inr
#print axioms AlgebraicGeometry.ComplexPoint.coneSupportAddEquivSupportedInjectiveHomology_boundary
#print axioms CochainComplex.mappingCocone.shortExactHomologyIsoCone_inv_inr_naturality
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularToInjectiveOutside_comp_resolution
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularSupportBoundary_comp_injective
#print axioms AlgebraicGeometry.ComplexPoint.coneSupportAddEquivSupportedInjectiveHomology_raw_boundary

-- Literal local relative normalization and the actual restricted winding coefficient.
#print axioms CochainComplex.mappingCone.inr_mapArrowIso
#print axioms TopCat.Sheaf.supportRestrictionSectionsConeIso_inr
#print axioms TopCat.Sheaf.sectionComplexRestrictionExtendConeIso_inr
#print axioms AlgebraicTopology.Singular.openRawToSupportedSingularOutside_boundary
#print axioms AlgebraicTopology.Singular.supportedSingularSectionCohomologyEquivRelative_boundary
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionConeIsoRelative_inr
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionConeCohomologyEquivRelative_boundary
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionConeCohomologyEquivRelative_boundary_legacy
#print axioms AlgebraicTopology.Singular.openRawCochainHomologyEquivDual_restriction
#print axioms AlgebraicTopology.Singular.relativeCochainConeCohomologyEquivCanonical_boundary_naturality
#print axioms ChernWinding.rationalWindingCocycle_naturality
#print axioms ChernWinding.rationalWindingCohomologyClass_naturality
#print axioms ChernWinding.rationalWindingIntCohomologyClass_naturality
#print axioms ChernWinding.openRawRationalWindingClass_restriction
#print axioms ChernWinding.supportedSingularSectionCohomologyEquivSupportComplement_winding_boundary
#print axioms AlgebraicGeometry.ComplexPoint.complexSupportInjectiveSectionCohomologyEquiv_supported_singular
#print axioms AlgebraicGeometry.ComplexPoint.globalRawComplementToActualSingularOutside_eq_topOpen
#print axioms AlgebraicGeometry.ComplexPoint.coneSupportAddEquivSupportedInjectiveHomology_raw_boundary_relative
#print axioms AlgebraicGeometry.ComplexPoint.restrictionUnit_comp_restrictedSingularOneCoefficient
#print axioms AlgebraicGeometry.ComplexPoint.actualSingularRestriction_comp_naturalOutsideResolutionComparisonOnOpen
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_eq_restricted_winding
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_apply
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_comp_d
#print axioms AlgebraicGeometry.ComplexPoint.holomorphicSingularOneCoefficient_apply_raw
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_apply_raw
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_apply_on_open
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSingularOneCoefficient_apply_on_open_raw

-- Actual winding cycle representatives under the fixed complement hypercohomology map.
#print axioms TopCat.Sheaf.integerConstantHomEquivGlobalSections_id
#print axioms TopCat.Sheaf.integerConstantHomEquivGlobalSections_constHomOfSection
#print axioms TopCat.Sheaf.homComplexSingleIntegerIsoGlobalSections_precomp_constHom
#print axioms TopCat.Sheaf.iCycles_integerCocycleGlobalSection
#print axioms TopCat.Sheaf.iCycles_integerCocycleGlobalSection_precomp_constHom
#print axioms CochainComplex.HomComplex.homologyAddEquiv_symm_mk
#print axioms AlgebraicGeometry.ComplexPoint.derivedHomAddEquivGlobalSectionsKInjective_cocycle
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyAddEquivGlobalSections_eq_kInjective
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyAddEquivGlobalSectionsKInjective_mk_cocycle
#print axioms AlgebraicGeometry.ComplexPoint.iCycles_restrictedSingularOneGlobalCocycle
#print axioms AlgebraicGeometry.ComplexPoint.derivedHomAddEquivGlobalSections_restrictedSingularOneCocycle
#print axioms AlgebraicGeometry.ComplexPoint.complementRationalHypercohomology_restrictedSingularOneCocycle
#print axioms AlgebraicGeometry.ComplexPoint.naturalSingularOutsideResolutionComparisonOnOpen_eq_canonical

-- Normalized raw representatives and the actual exponential/winding class equality.
#print axioms HomologicalComplex.mapExtendCanonicalIso_inv_f
#print axioms HomologicalComplex.mapExtendCanonicalIso_hom_f
#print axioms AlgebraicTopology.Singular.openRawSingularCochainComplexIntIsoDual_inv_f
#print axioms CategoryTheory.ShortComplex.homologyπ_mapHomologyIso_hom
#print axioms ChernWinding.homologyπ_rationalWindingIntCocycle
#print axioms ChernWinding.iCycles_rationalWindingIntCocycle
#print axioms ChernWinding.homologyπ_openRawRationalWindingCocycle
#print axioms ChernWinding.iCycles_openRawRationalWindingCocycle
#print axioms AlgebraicGeometry.ComplexPoint.openRawToComplementResolutionOnOpen_f
#print axioms AlgebraicGeometry.ComplexPoint.cyclesMap_openRawToComplementResolutionOnOpen_winding
#print axioms AlgebraicGeometry.ComplexPoint.homologyMap_openRawToComplementResolutionOnOpen_winding
#print axioms AlgebraicGeometry.ComplexPoint.complementRationalHypercohomology_restrictedSingularOneCocycle_eq_rawWinding

-- Literal intrinsic-complement presentation of the actual exponential winding class.
#print axioms AlgebraicTopology.Singular.globalRawComplementToTopOpenCochains_isIso
#print axioms AlgebraicTopology.Singular.openRawSingularRestrictionInt_epi
#print axioms AlgebraicTopology.Singular.openRawSingularRestriction_comp
#print axioms AlgebraicGeometry.ComplexPoint.openRawRestriction_comp_complementResolutionOnOpen
#print axioms AlgebraicGeometry.ComplexPoint.openRawRestriction_comp_intrinsicComplement
#print axioms AlgebraicGeometry.ComplexPoint.openRawToComplementResolutionOnOpen_eq_intrinsic
#print axioms AlgebraicGeometry.ComplexPoint.openRawToIntrinsicComplement_comp_topOpen
#print axioms AlgebraicGeometry.ComplexPoint.complementRationalHypercohomology_restrictedSingularOneCocycle_eq_intrinsicWinding

-- The actual relative Chern class and its concrete frame-change boundary.
#print axioms ChernWinding.openRawRelative_winding_boundary
#print axioms AlgebraicGeometry.ComplexPoint.RelativeChernComparison.boundary_eq_singular_on_section
#print axioms AlgebraicGeometry.ComplexPoint.hypercohomologyEquiv_sub
#print axioms AlgebraicGeometry.ComplexPoint.constantIntegerMorphism_eq_constHomOfSection
#print axioms AlgebraicGeometry.ComplexPoint.restrictedIntegerMorphism_eq_constHomOfSection
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_equiv
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_sub_of_cone_difference
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.exists_relativeChernClass_sub_eq_singular_boundary
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.exists_relativeChernClass_sub_eq_unit_boundary
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_sub_eq_neg_unit_boundary

-- The actual frame variation under the fixed support-to-winding comparison.
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportBoundary_restrictedSingularOneCocycle_eq_winding
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportBoundary_restrictedSingularOneCocycle_eq_windingHom
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_sub_eq_winding

#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_sub_eq_windingSheaf

-- Actual restriction and local vanishing for an extending reference frame.
#print axioms CochainComplex.mappingCone.mapHomotopyZeroOfFactorization
#print axioms CochainComplex.mappingCone.homotopyToZeroOfIsIso
#print axioms CochainComplex.mappingCone.mapHomologicalComplexConeHomotopyZero
#print axioms AlgebraicGeometry.ComplexPoint.openRestrictionTopEval_inv_naturality_open
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.liftHom_restrict
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.projection_restrict_lift
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.restrictionFactorisation_restrict
#print axioms AlgebraicGeometry.ComplexPoint.relativeUnitConeRestriction
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeConeMap_restrict
#print axioms AlgebraicGeometry.ComplexPoint.isIso_restrictToOpen_single_restrictionUnit
#print axioms AlgebraicGeometry.ComplexPoint.relativeUnitCone_restrict_self_homotopyZero
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeConeMap_restrict_homotopyZero
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeConeMap_restrict_mapDerivedCategory_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.regularFrame_relativeChernClass_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.HolomorphicUnitExtension.relativeChernClass_local_eq_neg_unit_boundary

-- Derived vanishing and the actual cocycle-to-cohomology-sheaf normalization.
#print axioms HomologicalComplex.homologyMap_eq_zero_of_Q_map_eq_zero
#print axioms CategoryTheory.Functor.Q_map_mapHomologicalComplex_eq_zero_of_mapDerivedCategory_eq_zero
#print axioms CategoryTheory.Functor.homologyMap_mapHomologicalComplex_eq_zero_of_mapDerivedCategory_eq_zero
#print axioms TopCat.Sheaf.sectionCohomologyToSheafSection_map_eq_zero_of_Q_map_eq_zero
#print axioms TopCat.Sheaf.homologyMap_onOpen_eq_zero_of_derived_restriction_eq_zero
#print axioms TopCat.Sheaf.sectionCohomologyToSheafSection_map_eq_zero_of_derived_restriction_eq_zero
#print axioms TopCat.Sheaf.integerCocycleGlobalSection_postcomp
#print axioms TopCat.Sheaf.homologyπ_integerCocycleGlobalSection_postcomp
#print axioms TopCat.Sheaf.sectionCohomology_integerCocycleGlobalSection_postcomp
#print axioms TopCat.Sheaf.sectionCohomology_integerCocycleGlobalSection_postcomp_onOpen_eq_zero
#print axioms TopCat.Sheaf.sectionCohomology_integerCocycleGlobalSection_ofHom_onOpen_eq_zero
#print axioms TopCat.Sheaf.integerConstantHomAddEquivGlobalSections_freeAbelianTerminal
#print axioms TopCat.Sheaf.homComplexPairSheafIsoSupportedSections_forget
#print axioms AlgebraicGeometry.ComplexPoint.rationalCohomologyAddEquivAmbientInjectiveHomology_eq_extModel
#print axioms AlgebraicGeometry.ComplexPoint.rationalSupportAddEquivSupportedInjectiveHomology_forgetSupport
#print axioms AlgebraicGeometry.Scheme.CartierData.LocalForm.exists_away_eq_component_with_exceptional
#print axioms AlgebraicGeometry.ComplexPoint.IsCartierComplementLift.relativeChernClass_sub_eq_windingSheaf_cartier
#print axioms AlgebraicGeometry.ComplexPoint.hasChernLocalModel_of_chartFormulaGenericLocal
#print axioms Ideal.generator_not_mem_square_of_regular_quotient
#print axioms Derivation.cotangentMap_toCotangent
#print axioms Derivation.ne_zero_of_mem_maximalIdeal_of_not_mem_square_of_injective
#print axioms Derivation.ne_zero_of_mem_maximalIdeal_of_not_mem_square
#print axioms AlgebraicGeometry.ComplexPoint.regularPointJet_add
#print axioms AlgebraicGeometry.ComplexPoint.regularPointJet_mul
#print axioms AlgebraicGeometry.ComplexPoint.regularPointJet_ambientCoordinateSection
#print axioms AlgebraicGeometry.ComplexPoint.Affine.ambientSection_evaluate
#print axioms AlgebraicGeometry.ComplexPoint.Affine.pointJetDerivation
#print axioms AlgebraicGeometry.ComplexPoint.Affine.pointJetExtAlgHom
#print axioms AlgebraicGeometry.ComplexPoint.Affine.localizedPointJetAlgHom
#print axioms AlgebraicGeometry.ComplexPoint.Affine.localizedPointJetDerivation
#print axioms AlgebraicGeometry.ComplexPoint.Affine.localizedPointJetAlgHom_comp
#print axioms AlgebraicGeometry.ComplexPoint.Affine.localizedPointJetDerivation_coordinate
#print axioms Complex.continuousOn_normalQuotient
#print axioms Complex.exists_ball_analytic_normalQuotient_factor
#print axioms CategoryTheory.Functor.mapHomologyShift_eq_zero_of_mapDerivedCategory_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.analyticAt_closedImmersionHolomorphicFlatteningChart_normalCoordinateChange
#print axioms AlgebraicGeometry.ComplexPoint.analyticAt_closedImmersionHolomorphicFlatteningChart_evaluate
#print axioms Complex.exists_nhds_normalQuotientFinOne_factor
#print axioms AlgebraicGeometry.cycleComponent_stalkMap_ker_eq_prime_map
#print axioms AlgebraicGeometry.Scheme.CartierData.LocalForm.span_germ_equation_eq_component_stalkMap_ker_of_away
#print axioms AlgebraicGeometry.Scheme.CartierData.LocalForm.germ_equation_not_mem_square_of_component_of_away
#print axioms AlgebraicGeometry.ComplexPoint.FlatteningChartWithCoclass.toGenericWindingChartData
#print axioms AlgebraicGeometry.ComplexPoint.sectionComplexRestriction_comp_supportedInjectiveComplexMap
#print axioms AlgebraicGeometry.ComplexPoint.supportedInjectiveComplexMap_section_apply
#print axioms Complex.exists_restricted_normalDivision_chart
#print axioms AlgebraicGeometry.ComplexPoint.fderiv_closedImmersionHolomorphicFlatteningChart_evaluate
#print axioms AlgebraicGeometry.ComplexPoint.analyticOnNhd_closedImmersionHolomorphicFlatteningChart_restrict_evaluate
#print axioms CochainComplex.mappingCocone.map_shiftedLiftShortComplex
#print axioms AlgebraicGeometry.ComplexPoint.supportSheafToAmbientInjectiveCone_globalSections
#print axioms TopCat.Sheaf.pushforward_map_quasiIso_of_flasque
#print axioms AlgebraicGeometry.ComplexPoint.ambientRationalOpenResolutionComparison_quasiIso
#print axioms AlgebraicGeometry.ComplexPoint.supportSheafToAmbientInjectiveCone_quasiIso
#print axioms Complex.fderiv_comp_symm_ne_zero_of_openPartialHomeomorph
#print axioms Complex.fderiv_eq_zero_on_normal_tangent
#print axioms Complex.normal_deriv_ne_zero_of_fderiv_ne_zero
#print axioms AlgebraicGeometry.ComplexPoint.FlatteningChartWithCoclass.exists_genericWindingChartData_of_fderiv_ne_zero
#print axioms AlgebraicGeometry.ComplexPoint.fderiv_closedImmersionHolomorphicFlatteningChart_evaluate_ne_zero

#print axioms AlgebraicGeometry.ComplexPoint.supportSheafToAmbientInjectiveCone_globalSections_quasiIso
#print axioms AlgebraicGeometry.ComplexPoint.coneSupportAddEquivSupportedInjectiveHomology_supportSheaf
#print axioms AlgebraicGeometry.ComplexPoint.coneSupportAddEquivSupportedInjectiveHomology_eq_supportSheaf

#print axioms AlgebraicGeometry.ComplexPoint.analyticOnNhd_openEmbeddingTransportChart_restrict_evaluate
#print axioms AlgebraicGeometry.ComplexPoint.exists_genericWindingChartData_of_component_canonical

#print axioms AlgebraicGeometry.ComplexPoint.Affine.localizedPointJetDerivation_ne_zero_of_not_mem_square
#print axioms AlgebraicGeometry.ComplexPoint.Affine.residueAlgHom_ker_eq_residuePrimeIdeal
#print axioms AlgebraicGeometry.ComplexPoint.Affine.localizedPointJetDerivation_ne_zero_of_not_mem_square_coordinate
#print axioms TopCat.Sheaf.sectionCohomologyPresheafShiftMap_toSheaf
#print axioms TopCat.Sheaf.sectionCohomologyToSheafSection_shift_naturality
#print axioms TopCat.Sheaf.sectionCohomologyPresheafShiftShortComplex_top_homology
#print axioms TopCat.Sheaf.derivedHomAddEquivGlobalSectionsKInjective_cocycle
#print axioms TopCat.Sheaf.globalSections_homology_cocycle_rightUnshift
#print axioms TopCat.Sheaf.sectionCohomology_integerCocycleGlobalSection_ofHom_shift_onOpen_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.restrictedConeSection_comp_coneToInteger
#print axioms AlgebraicGeometry.ComplexPoint.restrictedConeSection_comp_relativeConeMap
#print axioms RingEquiv.mem_maximalIdeal_pow_iff
#print axioms AlgebraicGeometry.ComplexPoint.Affine.ambientSection_germ_stalkIso
#print axioms AlgebraicGeometry.ComplexPoint.regularPointJet_eq_of_germ_eq
#print axioms AlgebraicGeometry.ComplexPoint.Affine.regularPointJet_ne_zero_of_germ_mem_maximalIdeal_of_not_mem_square
#print axioms AlgebraicGeometry.ComplexPoint.supportAmbientDerivedClass_topDerivedHom
#print axioms AlgebraicGeometry.ComplexPoint.supportAmbientDerivedClass_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.supportSection_restrict_eq_zero_of_cocycle
#print axioms AlgebraicGeometry.ComplexPoint.supportAmbientSection_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.sectionCohomologyToSheafSection_restrict_eq_zero_of_quasiIso
#print axioms AlgebraicGeometry.ComplexPoint.sectionCohomologyShift_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.supportSheafSection_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.coneSupportSection_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.restrictedOverlapSection
#print axioms AlgebraicGeometry.ComplexPoint.restrictedFrameFactorisation
#print axioms AlgebraicGeometry.ComplexPoint.restrictedOverlapUnitHom
#print axioms AlgebraicGeometry.ComplexPoint.restrictedSection_integerOne
#print axioms AlgebraicGeometry.ComplexPoint.restrictedConstantMap_eq_constHomOfSection
#print axioms AlgebraicGeometry.ComplexPoint.Affine.openInclusion_stalk_germ_eq
#print axioms AlgebraicGeometry.ComplexPoint.Affine.regularPointJet_ne_zero_of_open_restriction_of_germ
#print axioms AlgebraicGeometry.ComplexPoint.Affine.regularPointJet_ne_zero_of_component_equation
#print axioms AlgebraicGeometry.ComplexPoint.Affine.fderiv_ne_zero_of_component_equation
#print axioms AlgebraicGeometry.ComplexPoint.Affine.fderiv_ne_zero_of_smooth_locus_component_equation
#print axioms AlgebraicGeometry.ComplexPoint.Affine.fderiv_ne_zero_of_smooth_locus_component_equation_of_ambient_membership
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.regularFrame_relativeSection_restrict_eq_zero
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.cartier_relativeSection_restrict_eq_windingSheaf
#print axioms AlgebraicGeometry.ComplexPoint.exists_genericWindingChartData_of_component_algebraic
#print axioms AlgebraicGeometry.ComplexPoint.exists_genericWindingChartData_off_component_exceptional
#print axioms AlgebraicGeometry.ComplexPoint.hasGenericFlatteningCharts_of_component_algebraic
#print axioms AlgebraicGeometry.ComplexPoint.hasNormalizedWindingCharts_of_component_algebraic
#print axioms AlgebraicGeometry.ComplexPoint.componentsZariskiSupport_le_badLocus
#print axioms AlgebraicGeometry.ComplexPoint.badLocus_codimension_two_off_components
#print axioms AlgebraicGeometry.ComplexPoint.cycleAnalyticClosedSupport_le_badLocus
#print axioms AlgebraicGeometry.ComplexPoint.exists_compatible_global_lift_and_supported_class
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.puncturedSupportPair_eq
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.punctured_le_goodComplement
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.inf_goodComplement_eq_punctured
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.cartierUnit_winding_eq_divisor_smul_coclass

#print axioms AlgebraicGeometry.ComplexPoint.supportedInjectiveComplexMap_local_isIso
#print axioms AlgebraicGeometry.ComplexPoint.supportedInjectiveHomology_local_map_isIso
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.componentToBadLocusMap_local_isIso
#print axioms AlgebraicGeometry.ComplexPoint.ChernWindingChart.componentToBadLocusHomology_local_map_isIso
