/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
import Lean

/-!
# Minimality audit of a generated challenge file

Usage (after `lake build Challenge`):

    lake env lean --run scripts/SpecAudit.lean Challenge.Constructed HodgeConjecture [drop.json]

The audit loads the compiled challenge module and computes, inside it, the set of constants the
root statement reaches by following definition bodies and types. Since every proof in the file is
a `sorry`, this is exactly the definitional closure of the statement as compiled. Every source
declaration of the file is then classified as needed, needed only because the type ascribed to a
`sorry` mentions it, or unneeded. A minimal file has no unneeded declaration apart from the
notation commands, which are not constants.

The audit also compares, for every declaration, the constants it uses in the compiled file with
the constants its source uses in the repository (`.lake/genspec/source-uses.json`, written by the
generator; proofs excluded). With `import Mathlib` a short name can resolve to a different constant
than in its source module, silently changing what a definition means; such drift is reported.

With a third argument, the names of the unneeded declarations are merged into that JSON file, which
`scripts/GenSpec.lean` reads (`scripts/genspec-state/<root>.drop.json`) to leave them out on its
next run; the repository constants whose shorter names drifted are merged into `<root>.qualify.json`
beside it, and the generator then writes their uses in full.
-/

open Lean Meta

namespace SpecAudit

/-- `sorryAx T _` contributes nothing but its type; strip it to measure what the definitions need
independently of how their proof obligations are stated. -/
def stripSorry (e : Expr) : Expr :=
  e.replace fun sub => if sub.isAppOf ``sorryAx then some (mkConst ``True) else none

def nsUnion (s t : NameSet) : NameSet := t.toList.foldl (init := s) fun s n => s.insert n

/-- Constants a constant refers to, optionally ignoring the types of `sorry`s. -/
def usedConsts (ci : ConstantInfo) (skipSorry : Bool) : NameSet :=
  if !skipSorry then ci.getUsedConstantsAsSet else
    let s := (stripSorry ci.type).getUsedConstantsAsSet
    match ci with
    | .defnInfo v => nsUnion s (stripSorry v.value).getUsedConstantsAsSet
    | .thmInfo v => nsUnion s (stripSorry v.value).getUsedConstantsAsSet
    | .opaqueInfo v => nsUnion s (stripSorry v.value).getUsedConstantsAsSet
    | .inductInfo v => (v.ctors ++ v.all).foldl (init := s) fun s n => s.insert n
    | .ctorInfo v => s.insert v.induct
    | .recInfo v => v.rules.foldl (init := s) fun s r => nsUnion s (stripSorry r.rhs).getUsedConstantsAsSet
    | _ => s

/-- Constants of the audited module reachable from `root`; Mathlib constants are not expanded,
since Mathlib cannot refer back into the file. -/
def reach (env : Environment) (inMod : Name → Bool) (root : Name) (skipSorry : Bool) : NameSet :=
  Id.run do
    let mut seen : NameSet := {}
    let mut stack : Array Name := #[root]
    while !stack.isEmpty do
      let n := stack.back!
      stack := stack.pop
      if seen.contains n then continue
      seen := seen.insert n
      if inMod n then
        if let some ci := env.find? n then
          for m in (usedConsts ci skipSorry).toList do
            if !seen.contains m then stack := stack.push m
    return seen

def kindOf (env : Environment) (n : Name) : String :=
  match env.find? n with
  | some (.defnInfo _) => if isInstanceCore env n then "instance" else "def"
  | some (.thmInfo _) => "theorem"
  | some (.inductInfo _) => "inductive"
  | some (.opaqueInfo _) => "opaque"
  | some (.axiomInfo _) => "axiom"
  | some (.ctorInfo _) => "ctor"
  | some (.recInfo _) => "rec"
  | _ => "?"

/-- Names generated by notation commands, which are syntax rather than definitions. -/
def isNotationAux (n : Name) : Bool :=
  n.components.any fun c =>
    let s := c.toString
    s.startsWith "_aux_" || s.startsWith "«_aux_" || s.startsWith "«term"

structure Report where
  declarations : Nat
  needed : Nat
  core : Nat
  unneededLines : Nat
  sorryOnlyLines : Nat
  drift : Nat
  lines : Array String
  unneeded : Array Name
  qualify : Array Name

def readUses (path : System.FilePath) : IO (Std.HashMap String (Std.HashSet String)) := do
  if !(← path.pathExists) then return {}
  match Json.parse (← IO.FS.readFile path) with
  | .ok j =>
    match j.getObj? with
    | .ok obj => return obj.toList.foldl (init := {}) fun acc (k, v) =>
        acc.insert k (((v.getArr?).toOption.getD #[]).foldl (init := {}) fun s x =>
          match x.getStr? with
          | .ok t => s.insert t
          | _ => s)
    | _ => return {}
  | _ => return {}

def lastComponent : Name → String
  | .str _ s => s
  | _ => ""

def audit (modName root : Name) (uses : Std.HashMap String (Std.HashSet String)) : MetaM Report := do
  let env ← getEnv
  let some idx := env.getModuleIdx? modName | throwError "module {modName} not found"
  let inMod : Name → Bool := fun n => env.getModuleIdxFor? n == some idx
  let names := env.constants.map₁.fold (init := (#[] : Array Name)) fun acc n _ =>
    if inMod n then acc.push n else acc
  unless inMod root do throwError "{root} is not declared in {modName}"
  let needed := reach env inMod root false
  let core := reach env inMod root true
  -- group the constants by source declaration: declaration ranges nest (fields, constructors,
  -- projections inside their structure), and auxiliary constants without a range belong to the
  -- nearest prefix that has one
  let mut ranged : Array (Name × Nat × Nat) := #[]
  let mut unranged : Array Name := #[]
  for n in names do
    match ← findDeclarationRanges? n with
    | some r => ranged := ranged.push (n, r.range.pos.line, r.range.endPos.line)
    | none => unranged := unranged.push n
  let sorted := ranged.qsort fun (_, a1, b1) (_, a2, b2) => a1 < a2 || (a1 == a2 && b1 > b2)
  let mut groups : Array (Name × Nat × Nat × Array Name) := #[]
  for (n, a, b) in sorted do
    if let some (h, ga, gb, ms) := groups.back? then
      if a ≥ ga && b ≤ gb then
        groups := groups.pop.push (h, ga, gb, ms.push n)
        continue
    groups := groups.push (n, a, b, #[n])
  let mut headIdx : Std.HashMap Name Nat := {}
  for i in [0:groups.size] do
    for m in groups[i]!.2.2.2 do headIdx := headIdx.insert m i
  let mut lost : Array Name := #[]
  for n in unranged do
    let mut p := n.getPrefix
    let mut found := false
    while !p.isAnonymous do
      if let some i := headIdx[p]? then
        groups := groups.modify i fun (h, a, b, ms) => (h, a, b, ms.push n)
        found := true
        break
      p := p.getPrefix
    if !found then lost := lost.push n
  let mut nNeeded := 0
  let mut nCore := 0
  let mut unneededLines := 0
  let mut sorryOnlyLines := 0
  let mut drift := 0
  let mut lines : Array String := #[]
  let mut unneeded : Array Name := #[]
  let mut qualify : Array Name := #[]
  let norm (n : Name) : Name := (privateToUserName? n).getD n
  for (h, a, b, ms) in groups do
    if isNotationAux h then continue
    let isNeeded := ms.any needed.contains
    let isCore := ms.any core.contains
    if isNeeded then nNeeded := nNeeded + 1
    if isCore then nCore := nCore + 1
    if !isNeeded then
      unneededLines := unneededLines + (b - a + 1)
      lines := lines.push s!"UNNEEDED   {a}-{b}  {kindOf env h} {h}"
      unneeded := unneeded.push h
    else if !isCore then
      sorryOnlyLines := sorryOnlyLines + (b - a + 1)
      lines := lines.push s!"SORRY-ONLY {a}-{b}  {kindOf env h} {h}"
    -- drift: the data of the declaration (types, and values with every `sorry` removed) uses a
    -- constant its source does not, or no longer uses a repository constant its source uses.
    -- Mathlib instances are compared loosely: a fuller import can pick another path through the
    -- instance diamonds, which Mathlib keeps definitionally equal.
    let hn := norm h
    if let some su := uses[hn.toString]? then
      let mut cu : Array Name := #[]
      for m in ms do
        if let some ci := env.find? m then
          let consts : NameSet :=
            if ci.isTheorem then (if m == h then (stripSorry ci.type).getUsedConstantsAsSet else {})
            else usedConsts ci true
          for u in consts.toList do
            let un := norm u
            -- matchers are shared between declarations of the same shape; their identity is noise
            let isMatcher := un.components.any fun c => c.toString.startsWith "match_"
            if un == hn || hn.isPrefixOf un || u == ``sorryAx || u == ``True || un.hasMacroScopes || isMatcher then continue
            if !cu.contains un then cu := cu.push un
      let mut extra : Array Name := #[]
      for u in cu do
        if !su.contains u.toString then
          if isInstanceCore env u && !inMod u then continue
          let prop ← (try
              match env.find? u with
              | some ci => forallTelescope ci.type fun _ body => isProp body
              | none => pure false
            catch _ => pure false)
          if !prop then extra := extra.push u
      let mut missing : Array Name := #[]
      for s in su.toList do
        let sn := s.toName
        if inMod sn && !cu.contains sn && !(isInstanceCore env sn && false) then
          let prop ← (try
              match env.find? sn with
              | some ci => forallTelescope ci.type fun _ body => isProp body
              | none => pure false
            catch _ => pure false)
          if !prop then missing := missing.push sn
      if !extra.isEmpty || !missing.isEmpty then
        drift := drift + 1
        let mut sugg : Array Name := #[]
        for e in extra do
          for s in su.toList do
            let sn := s.toName
            if lastComponent sn == lastComponent e && !cu.contains sn && !sugg.contains sn then
              sugg := sugg.push sn
        qualify := qualify ++ sugg
        lines := lines.push s!"DRIFT      {a}-{b}  {h}: extra {extra}; missing {missing}; source has {sugg}"
  for n in lost do lines := lines.push s!"UNATTACHED {n}"
  let declarations := (groups.filter fun (h, _, _, _) => !isNotationAux h).size
  return { declarations, needed := nNeeded, core := nCore, unneededLines, sorryOnlyLines, drift, lines,
           unneeded, qualify }

def readNames (path : System.FilePath) : IO (Array String) := do
  if !(← path.pathExists) then return #[]
  match Json.parse (← IO.FS.readFile path) with
  | .ok (Json.arr items) => return items.filterMap fun j => (j.getStr?).toOption
  | _ => return #[]

unsafe def run (modName root : Name) (dropOut : Option System.FilePath) : IO UInt32 := do
  initSearchPath (← findSysroot)
  let env ← importModules #[{module := modName}] {} (trustLevel := 1024) (loadExts := true)
  let ctx : Core.Context := { fileName := "<SpecAudit>", fileMap := default }
  let uses ← readUses ".lake/genspec/source-uses.json"
  let (r, _, _) ← (audit modName root uses).toIO ctx { env := env }
  IO.println s!"module {modName}, root {root}: {r.declarations} source declarations (notation commands excluded)"
  IO.println s!"  needed by the statement: {r.needed}; needed ignoring the types of sorries: {r.core}"
  IO.println s!"  unneeded declarations: {r.declarations - r.needed} ({r.unneededLines} lines); needed only to state a sorry: {r.needed - r.core} ({r.sorryOnlyLines} lines)"
  if uses.isEmpty then IO.println "  drift check skipped: no .lake/genspec/source-uses.json"
  else IO.println s!"  drifting declarations: {r.drift} (constants used here that the source does not use, proofs excluded)"
  for l in r.lines do IO.println s!"  {l}"
  if let some path := dropOut then
    let old ← readNames path
    let merged := (old ++ r.unneeded.map toString).toList.eraseDups
    IO.FS.writeFile path (Json.arr (merged.toArray.map Json.str)).pretty
    IO.println s!"  drop list {path}: {merged.length} name(s)"
    let qpath : System.FilePath := path.parent.getD "." / s!"{root}.qualify.json"
    let oldQ ← readNames qpath
    let mergedQ := (oldQ ++ r.qualify.map toString).toList.eraseDups
    if !mergedQ.isEmpty then
      IO.FS.writeFile qpath (Json.arr (mergedQ.toArray.map Json.str)).pretty
      IO.println s!"  qualify list {qpath}: {mergedQ.length} name(s)"
  return 0

end SpecAudit

unsafe def main (args : List String) : IO UInt32 := do
  enableInitializersExecution
  match args with
  | [m, root] => SpecAudit.run m.toName root.toName none
  | [m, root, out] => SpecAudit.run m.toName root.toName (some out)
  | _ => do IO.eprintln "usage: SpecAudit <module> <root> [drop.json]"; return 1
