/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import VersoManual
import Other.AlgebraicGeometry.SheafCycleClass

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

set_option pp.rawOnError true
set_option verso.code.warnLineLength 0

#doc (Manual) "Cycles and supported cohomology" =>

# Cycles are indexed by generic points

A codimension-$`p` cycle is a locally finite integer combination of scheme points of coheight
$`p`. Such a point is the generic point of an irreducible closed subset. The formalization uses
this generic-point representation rather than introducing a second type of subvarieties.

```lean
#check AlgebraicGeometry.CodimensionCycle
#check AlgebraicGeometry.CodimensionCycle.single
#check AlgebraicGeometry.ChowGroup
#check AlgebraicGeometry.RationalChowGroup
```

Rational equivalence is generated in the standard way: on an integral Noetherian closed subscheme
of codimension $`p-1`, take the divisor of a nonzero rational function and properly push that
divisor into $`X`. The Chow group is the quotient by the subgroup generated by these relations.
Compare the [Stacks Project definition of cycles](https://stacks.math.columbia.edu/tag/0FE2) and
its [construction of rational equivalence](https://stacks.math.columbia.edu/tag/02RW).

# From a point to a closed analytic support

For `x : X`, `cycleComponent X x` is the reduced closed subscheme on
$`\overline{\{x\}}`. Its complex points map into $`X(\mathbb C)`; the preimage of that closure is
the closed analytic support used below.

```lean
#check AlgebraicGeometry.cycleComponent
#check AlgebraicGeometry.cycleComponentι
#check AlgebraicGeometry.cycleComponentSupport
#check AlgebraicGeometry.isClosed_cycleComponentSupport
```

Smoothness is imposed on the ambient $`X`, not on the component. Singular components are therefore
part of the main construction, not an exceptional branch.

# The restriction-cone model of support

Let $`Z\subseteq X(\mathbb C)` be closed and let
$`j:U=X(\mathbb C)\setminus Z\hookrightarrow X(\mathbb C)`. The expected triangle is

$$`R\Gamma_Z(X,\mathbb Q_X)\longrightarrow R\Gamma(X,\mathbb Q_X)
  \longrightarrow R\Gamma(U,\mathbb Q_U)\xrightarrow{+1}.`

The code resolves the constant rational sheaf on $`U`, pushes that resolution forward along $`j`,
maps the ambient constant sheaf to it, and models the homotopy fibre by a mapping cone shifted by
$`-1`. The shift appears literally in the definition of `RationalCohomologyWithSupport`.

```lean
#check AlgebraicGeometry.ComplexPoint.rationalCohomologyWithSupportComplex
#check AlgebraicGeometry.ComplexPoint.RationalCohomologyWithSupport
#check AlgebraicGeometry.ComplexPoint.forgetSupport
```

Thus `forgetSupport` is the canonical map
$`H_Z^n(X;\mathbb Q)\to H^n(X;\mathbb Q)`, not a chosen comparison. See Goresky
[§§7.14--7.15](https://www.math.ias.edu/~goresky/pdf/all.pdf#page=30) for the support triangle and
relative interpretation, and the Stacks Project's
[cohomology-with-support construction](https://stacks.math.columbia.edu/tag/0A39) for its
derived-functor form.

# Additivity before quotienting by rational equivalence

Once the class of every component has been constructed, finite summation gives an additive map on
integral cycles. Tensoring the source with $`\mathbb Q` gives a rational-linear map on rational
cycles. The exact multiplicity formulas are proved, including negative and repeated coefficients.

```lean
#check AlgebraicGeometry.ComplexPoint.sheafCycleClassOnCycles
#check AlgebraicGeometry.ComplexPoint.sheafCycleClassOnCycles_single
#check AlgebraicGeometry.ComplexPoint.rationalSheafCycleClassOnCycles
#check AlgebraicGeometry.ComplexPoint.rationalSheafCycleClassOnCycles_tmul_single
```

The additive cycle-class map uses the wrapper `DimensionedSmoothProjectiveComplexVariety` to carry
the relative dimension required by the component construction. Its canonical constructor chooses
`dim X` and proves the dimension certificate from integrality and smoothness. The public algebraic
span likewise evaluates each component at this canonical dimension, so it does not depend on an
arbitrary dimension witness.

```lean
#check AlgebraicGeometry.ComplexPoint.DimensionedSmoothProjectiveComplexVariety.ofOver
#check AlgebraicGeometry.ComplexPoint.algebraicCycleClassSpan
```

The span is the supremum of the one-dimensional spans of the *actual terms*
`cycleComponentSheafClass structureMap x hx`. It is not defined by quantifying over a possible
generator of a supported image.

There is deliberately no claim here that the cycle map factors through `RationalChowGroup`.
That descent requires the separate theorem that principal divisors map to zero. Additivity alone
does not supply rational-equivalence invariance.
