/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Other.AlgebraicGeometry.CartierLocalForm
public import Mathlib.RingTheory.Localization.Away.Lemmas
public import Mathlib.RingTheory.Localization.Ideal

/-!
# Ideal generated by a codimension-one local equation
-/

@[expose] public noncomputable section

open CategoryTheory Order TopologicalSpace Opposite
open scoped BigOperators

namespace AlgebraicGeometry

variable {S : Scheme} [IsIntegral S] [IsNoetherian S] {c : S.CartierData}
  {i : c.ι} {x : S}

namespace Scheme.CartierData.LocalForm

variable (f : c.LocalForm i x) (hx : coheight x = 1)

/-- An order-one equation generates the maximal ideal of the codimension-one stalk. -/
theorem span_germ_equation_eq_maximalIdeal
    (hx : coheight x = 1) [IsDiscreteValuationRing (S.presheaf.stalk x)] :
    Ideal.span {S.presheaf.germ f.opens x f.mem f.equation} =
      IsLocalRing.maximalIdeal (S.presheaf.stalk x) := by
  let a : S.presheaf.stalk x := S.presheaf.germ f.opens x f.mem f.equation
  have ha0 : a ≠ 0 := by
    intro ha
    have hfield : S.germToFunctionField
        (h := ⟨⟨x, f.mem⟩⟩) f.opens f.equation = 0 := by
      rw [germToFunctionField_eq_algebraMap_germ f.mem]
      change algebraMap (S.presheaf.stalk x) S.functionField a = 0
      rw [ha]
      simp
    have hscheme : S.ord (S.germToFunctionField
        (h := ⟨⟨x, f.mem⟩⟩) f.opens f.equation) x = 0 := by
      rw [hfield]
      simp
    have := f.ord_equation
    omega
  have hfrac : Ring.ordFrac (S.presheaf.stalk x) (K := S.functionField)
      (algebraMap (S.presheaf.stalk x) S.functionField a) = WithZero.exp 1 := by
    change S.ordHom x hx (algebraMap (S.presheaf.stalk x) S.functionField a) = WithZero.exp 1
    rw [WithZero.exp_eq_coe_ofAdd]
    have hfield0 : S.germToFunctionField
        (h := ⟨⟨x, f.mem⟩⟩) f.opens f.equation ≠ 0 := by
      rw [germToFunctionField_eq_algebraMap_germ f.mem]
      exact (map_ne_zero_iff _ (IsFractionRing.injective (S.presheaf.stalk x)
        S.functionField)).mpr ha0
    have h := (Scheme.ord_eq_iff hx hfield0).mp f.ord_equation
    rw [germToFunctionField_eq_algebraMap_germ f.mem] at h
    simpa [a] using h
  obtain ⟨p, hp⟩ := IsDiscreteValuationRing.exists_irreducible (S.presheaf.stalk x)
  have hfracp : Ring.ordFrac (S.presheaf.stalk x) (K := S.functionField)
      (algebraMap (S.presheaf.stalk x) S.functionField p) = WithZero.exp 1 := by
    exact Ring.ordFrac_irreducible hp
  obtain ⟨u, hu⟩ := Ring.associated_of_ordFrac_eq
    (R := S.presheaf.stalk x) (K := S.functionField)
    (algebraMap (S.presheaf.stalk x) S.functionField a)
    (algebraMap (S.presheaf.stalk x) S.functionField p) (hfrac.trans hfracp.symm)
  have hassoc : Associated a p := by
    refine ⟨u, ?_⟩
    apply (FaithfulSMul.algebraMap_injective (S.presheaf.stalk x) S.functionField)
    rw [Units.smul_def, Algebra.smul_def] at hu
    simpa [Algebra.smul_def, mul_comm] using hu
  have hspan : Ideal.span {a} = IsLocalRing.maximalIdeal (S.presheaf.stalk x) := by
    rw [hp.maximalIdeal_eq]
    exact Ideal.span_singleton_eq_span_singleton.mpr hassoc
  simpa [a] using hspan

end Scheme.CartierData.LocalForm

section AwayGeneration

variable {R : Type*} [CommRing R] [IsNoetherianRing R]
  {P I : Ideal R} [hP : P.IsPrime]

/-- Equality of two ideals after localising at a prime spreads to a principal affine neighbourhood.
The element defining that neighbourhood can be chosen outside the prime. -/
theorem exists_away_eq_of_map_eq
    {T : Type*} [CommRing T] [Algebra R T]
    [IsLocalization P.primeCompl T]
    (hIP : I ≤ P)
    (h : P.map (algebraMap R T) = I.map (algebraMap R T)) :
    ∃ s : R, s ∉ P ∧
      P.map (algebraMap R (Localization.Away s)) =
        I.map (algebraMap R (Localization.Away s)) := by
  classical
  obtain ⟨g, _, hg⟩ :=
    Submodule.FG.exists_span_finset_card_eq_spanFinrank P.fg_of_isNoetherianRing
  have hg' : Ideal.span (g : Set R) = P := by
    rw [← Ideal.submodule_span_eq]
    exact hg
  have hgen : ∀ r ∈ g, ∃ m ∉ P, m * r ∈ I := by
    intro r hr
    have hrP : r ∈ P := by
      rw [← hg']
      exact Ideal.subset_span hr
    have hrmap : algebraMap R T r ∈ I.map (algebraMap R T) := by
      rw [← h]
      exact Ideal.mem_map_of_mem (algebraMap R T) hrP
    obtain ⟨m, hm, hmr⟩ :=
      (IsLocalization.algebraMap_mem_map_algebraMap_iff P.primeCompl T I r).mp hrmap
    exact ⟨m, Ideal.mem_primeCompl_iff.mp hm, hmr⟩
  choose m hmP hmI using hgen
  let n : R → R := fun r ↦ if hr : r ∈ g then m r hr else 1
  have hnP : ∀ r ∈ g, n r ∉ P := by
    intro r hr
    simp only [n, dif_pos hr]
    exact hmP r hr
  have hnI : ∀ r ∈ g, n r * r ∈ I := by
    intro r hr
    simp only [n, dif_pos hr]
    exact hmI r hr
  let s : R := ∏ r ∈ g, n r
  have hsP : s ∉ P := by
    intro hs
    change (∏ r ∈ g, n r) ∈ P at hs
    obtain ⟨r, hr, hrP⟩ := (Ideal.IsPrime.prod_mem_iff).mp hs
    exact hnP r hr hrP
  have hPI : P.map (algebraMap R (Localization.Away s)) ≤
      I.map (algebraMap R (Localization.Away s)) := by
    apply (Ideal.map_le_iff_le_comap).2
    rw [← hg']
    refine Ideal.span_le.2 fun r hr ↦ ?_
    apply (IsLocalization.algebraMap_mem_map_algebraMap_iff
      (Submonoid.powers s) (Localization.Away s) I r).2
    refine ⟨s, Submonoid.mem_powers s, ?_⟩
    obtain ⟨t, ht⟩ := Finset.dvd_prod_of_mem (fun r ↦ n r) hr
    change (∏ r ∈ g, n r) * r ∈ I
    rw [ht]
    simpa [mul_assoc, mul_comm, mul_left_comm] using I.mul_mem_left t (hnI r hr)
  exact ⟨s, hsP, le_antisymm hPI (Ideal.map_mono hIP)⟩

end AwayGeneration

namespace Scheme.CartierData.LocalForm

variable {S : Scheme} [IsIntegral S] [IsNoetherian S] {c : S.CartierData}
  {i : c.ι} {x : S}

/-- On a smaller principal affine neighbourhood, the local equation generates the reduced
codimension-one component ideal. -/
theorem exists_away_eq_component
    (f : c.LocalForm i x) (hx : coheight x = 1)
    [IsDiscreteValuationRing (S.presheaf.stalk x)] :
    ∃ s : Γ(S, f.opens),
      s ∉ (f.isAffineOpen.primeIdealOf ⟨x, f.mem⟩).asIdeal ∧
        (f.isAffineOpen.primeIdealOf ⟨x, f.mem⟩).asIdeal.map
            (algebraMap (Γ(S, f.opens)) (Localization.Away s)) =
          (Ideal.span {f.equation}).map
            (algebraMap (Γ(S, f.opens)) (Localization.Away s)) := by
  let _ : Algebra (Γ(S, f.opens)) (S.presheaf.stalk x) :=
    TopCat.Presheaf.algebra_section_stalk S.presheaf ⟨x, f.mem⟩
  let _ := f.isAffineOpen.isLocalization_stalk ⟨x, f.mem⟩
  let _ : IsNoetherianRing Γ(S, f.opens) :=
    IsLocallyNoetherian.component_noetherian ⟨f.opens, f.isAffineOpen⟩
  have heq : f.equation ∈ (f.isAffineOpen.primeIdealOf ⟨x, f.mem⟩).asIdeal := by
    by_contra hnot
    apply f.notMem_basicOpen x (subset_closure (Set.mem_singleton x))
    rw [Scheme.mem_basicOpen _ _ x f.mem]
    exact (f.isAffineOpen.isUnit_germ_iff_notMem ⟨x, f.mem⟩ f.equation).mpr hnot
  have hIP : Ideal.span ({f.equation} : Set Γ(S, f.opens)) ≤
      (f.isAffineOpen.primeIdealOf ⟨x, f.mem⟩).asIdeal := by
    exact (Ideal.span_singleton_le_iff_mem _).mpr heq
  have hmap :
      (f.isAffineOpen.primeIdealOf ⟨x, f.mem⟩).asIdeal.map
          (algebraMap (Γ(S, f.opens)) (S.presheaf.stalk x)) =
        (Ideal.span ({f.equation} : Set Γ(S, f.opens))).map
          (algebraMap (Γ(S, f.opens)) (S.presheaf.stalk x)) := by
    rw [IsLocalization.AtPrime.map_eq_maximalIdeal
      (f.isAffineOpen.primeIdealOf ⟨x, f.mem⟩).asIdeal (S.presheaf.stalk x)]
    rw [Ideal.map_span]
    rw [show (algebraMap (Γ(S, f.opens)) (S.presheaf.stalk x)) ''
          ({f.equation} : Set Γ(S, f.opens)) =
        {S.presheaf.germ f.opens x f.mem f.equation} by
      ext z
      constructor
      · rintro ⟨y, rfl, rfl⟩
        rfl
      · intro hz
        subst z
        refine ⟨f.equation, Set.mem_singleton _, ?_⟩
        change (algebraMap (Γ(S, f.opens)) (S.presheaf.stalk x)) f.equation =
          (S.presheaf.germ f.opens x f.mem).hom f.equation
        rw [RingHom.algebraMap_toAlgebra]]
    exact (f.span_germ_equation_eq_maximalIdeal hx).symm
  obtain ⟨s, hs, hsi⟩ := exists_away_eq_of_map_eq hIP hmap
  refine ⟨s, ?_, ?_⟩
  · exact hs
  · simpa using hsi

/-- The part of the reduced component removed by a principal affine shrink. -/
def exceptionalSet (f : c.LocalForm i x) (s : Γ(S, f.opens)) : Set S :=
  closure ({x} : Set S) \ S.basicOpen s

theorem exceptionalSet_isClosed (f : c.LocalForm i x) (s : Γ(S, f.opens)) :
    IsClosed (f.exceptionalSet s) := by
  exact isClosed_closure.sdiff (S.basicOpen s).isOpen

theorem exceptionalSet_subset (f : c.LocalForm i x) (s : Γ(S, f.opens)) :
    f.exceptionalSet s ⊆ closure ({x} : Set S) := by
  intro y hy
  exact hy.1

theorem x_not_mem_exceptionalSet (f : c.LocalForm i x) (s : Γ(S, f.opens))
    (hs : s ∉ (f.isAffineOpen.primeIdealOf ⟨x, f.mem⟩).asIdeal) :
    x ∉ f.exceptionalSet s := by
  intro hxB
  apply hxB.2
  exact (Scheme.mem_basicOpen _ _ x f.mem).mpr
    ((f.isAffineOpen.isUnit_germ_iff_notMem ⟨x, f.mem⟩ s).mpr hs)

/-- The principal shrink and its explicit closed exceptional subset. -/
theorem exists_away_eq_component_with_exceptional
    (f : c.LocalForm i x) (hx : coheight x = 1)
    [IsDiscreteValuationRing (S.presheaf.stalk x)] :
    ∃ s : Γ(S, f.opens),
      s ∉ (f.isAffineOpen.primeIdealOf ⟨x, f.mem⟩).asIdeal ∧
        (f.isAffineOpen.primeIdealOf ⟨x, f.mem⟩).asIdeal.map
            (algebraMap (Γ(S, f.opens)) (Localization.Away s)) =
          (Ideal.span {f.equation}).map
            (algebraMap (Γ(S, f.opens)) (Localization.Away s)) ∧
        IsClosed (f.exceptionalSet s) ∧
        x ∉ f.exceptionalSet s ∧
        f.exceptionalSet s ⊆ closure ({x} : Set S) := by
  obtain ⟨s, hs, hideal⟩ := f.exists_away_eq_component hx
  exact ⟨s, hs, hideal, f.exceptionalSet_isClosed s,
    f.x_not_mem_exceptionalSet s hs, f.exceptionalSet_subset s⟩

end Scheme.CartierData.LocalForm

end AlgebraicGeometry
