/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Other.AlgebraicGeometry.InvertibleSheafRationalSection

/-!
# The divisor of a rational section of an invertible sheaf

Let `L` be a sheaf of modules on an integral Noetherian scheme `S` which is generated by a
single section on each member of an open cover (`Scheme.Modules.TrivializingCover L`). Fixing
one member of the cover as a reference, the transition function from any member to the
reference member is a unit of the structure sheaf on the overlap, hence a nonzero rational
function `fᵢ`. These local equations are the coordinates of a single nonzero rational section
of `L`, and their orders of vanishing agree on overlaps because the transition functions
between two members are units there.

The main results are:

* `Scheme.CartierData.Represents`, the relation "the local equations of `c` are the coordinates
  of a rational section of `L`", stated through the transition functions;
* `Scheme.Modules.TrivializingCover.cartierData`, the Cartier data built from a trivializing
  cover, and `cartierData_represents`, the proof that it represents `L`.

Together with `Scheme.CartierData.divisor` this constructs the Weil divisor of a rational
section of an invertible sheaf, which is the first half of the decomposition of
`HasDivisorOfAlgebraicModel` described in `docs/DIVISOR_HANDOFF.md`.
-/

@[expose] public noncomputable section

open CategoryTheory Order TopologicalSpace

universe u

namespace AlgebraicGeometry

open Scheme.Modules

variable {S : Scheme.{u}} [IsIntegral S] [IsNoetherian S] {L : S.Modules}

/--
Cartier data `c` *represents* the sheaf of modules `L` when there are local generators of `L`
on the members of the cover of `c` whose transition functions are the ratios of the local
equations of `c`: if `u` is a unit of the structure sheaf with `u • gᵢ = gⱼ` on the overlap,
then `u · fⱼ = fᵢ` in the function field.

Equivalently, the local sections `fᵢ • gᵢ` glue to one nonzero rational section of `L`, and
`c.divisor` is the divisor of that section.
-/
def Scheme.CartierData.Represents (c : S.CartierData) (L : S.Modules) : Prop :=
  ∃ g : ∀ i : c.ι, Γ(L, c.opens i),
    (∀ i, Generates (g i)) ∧
    ∀ (i j : c.ι) (u : Γ(S, c.opens i ⊓ c.opens j)), IsUnit u →
      u • resSection L inf_le_left (g i) = resSection L inf_le_right (g j) →
      haveI := c.nonempty_inf i j
      S.germToFunctionField (c.opens i ⊓ c.opens j) u * c.fn j = c.fn i

namespace Scheme.Modules

omit [IsIntegral S] [IsNoetherian S] in
/-- Restricting an identity `a • s = t` to a smaller open. -/
lemma resSection_congr_smul {U V : S.Opens} (h : V ≤ U) {a : Γ(S, U)} {s t : Γ(L, U)}
    (he : a • s = t) :
    S.presheaf.map (homOfLE h).op a • resSection L h s = resSection L h t := by
  rw [← resSection_smul, he]

namespace TrivializingCover

variable (t : TrivializingCover L)

instance instNonemptyOpens (i : t.ι) : Nonempty (t.opens i) := t.nonempty i

/-- A distinguished member of the cover, used as the reference trivialization. -/
def base : t.ι := (t.covers (genericPoint S)).choose

/-- The overlap of a member of the cover with the reference member. -/
abbrev overlap (i : t.ι) : S.Opens := t.opens i ⊓ t.opens t.base

instance instNonemptyOverlap (i : t.ι) : Nonempty (t.overlap i) := S.nonempty_inf _ _

omit [IsNoetherian S] in
lemma exists_transitionUnit (i : t.ι) :
    ∃ u : Γ(S, t.overlap i), IsUnit u ∧
      u • resSection L (inf_le_left : t.overlap i ≤ t.opens i) (t.gen i) =
        resSection L (inf_le_right : t.overlap i ≤ t.opens t.base) (t.gen t.base) :=
  ((t.gen_generates i).restrict inf_le_left).exists_isUnit_smul_eq
    ((t.gen_generates t.base).restrict inf_le_right)

/-- The transition function from a member of the cover to the reference member. -/
def transitionUnit (i : t.ι) : Γ(S, t.overlap i) := (t.exists_transitionUnit i).choose

omit [IsNoetherian S] in
lemma transitionUnit_isUnit (i : t.ι) : IsUnit (t.transitionUnit i) :=
  (t.exists_transitionUnit i).choose_spec.1

omit [IsNoetherian S] in
lemma transitionUnit_smul (i : t.ι) :
    t.transitionUnit i • resSection L (inf_le_left : t.overlap i ≤ t.opens i) (t.gen i) =
      resSection L (inf_le_right : t.overlap i ≤ t.opens t.base) (t.gen t.base) :=
  (t.exists_transitionUnit i).choose_spec.2

/-- The local equation of the rational section on a member of the cover. -/
def fn (i : t.ι) : S.functionField :=
  S.germToFunctionField (t.overlap i) (t.transitionUnit i)

omit [IsNoetherian S] in
lemma isUnit_fn (i : t.ι) : IsUnit (t.fn i) := (t.transitionUnit_isUnit i).map _

omit [IsNoetherian S] in
lemma fn_ne_zero (i : t.ι) : t.fn i ≠ 0 := (t.isUnit_fn i).ne_zero

omit [IsNoetherian S] in
/-- Restricted form of the defining identity of the transition functions. -/
lemma transitionUnit_smul_res {W : S.Opens} (k : t.ι) (hW : W ≤ t.overlap k) :
    S.presheaf.map (homOfLE hW).op (t.transitionUnit k) •
        resSection L (hW.trans inf_le_left) (t.gen k) =
      resSection L (hW.trans inf_le_right) (t.gen t.base) := by
  have h := resSection_congr_smul (L := L) hW (t.transitionUnit_smul k)
  rwa [resSection_resSection, resSection_resSection] at h

omit [IsNoetherian S] in
/-- The germ of the transition function at the generic point is the local equation. -/
lemma germToFunctionField_transitionUnit_res {W : S.Opens} (k : t.ι) (hW : W ≤ t.overlap k)
    [Nonempty W] :
    S.germToFunctionField W (S.presheaf.map (homOfLE hW).op (t.transitionUnit k)) = t.fn k :=
  S.presheaf.germ_res_apply (homOfLE hW) _ _ _

omit [IsNoetherian S] in
/-- The transition function of `L` between two members of the cover is the ratio of the local
equations. -/
lemma germToFunctionField_mul_fn (i j : t.ι) (u : Γ(S, t.opens i ⊓ t.opens j)) (_hu : IsUnit u)
    (hue : u • resSection L inf_le_left (t.gen i) = resSection L inf_le_right (t.gen j)) :
    haveI := S.nonempty_inf (t.opens i) (t.opens j)
    S.germToFunctionField (t.opens i ⊓ t.opens j) u * t.fn j = t.fn i := by
  have hVne : Nonempty ((t.opens i ⊓ t.opens j : S.Opens)) := S.nonempty_inf _ _
  have hWne : Nonempty (((t.opens i ⊓ t.opens j) ⊓ t.opens t.base : S.Opens)) :=
    S.nonempty_inf _ _
  have hWV : ((t.opens i ⊓ t.opens j) ⊓ t.opens t.base : S.Opens) ≤ t.opens i ⊓ t.opens j :=
    inf_le_left
  have hWi : ((t.opens i ⊓ t.opens j) ⊓ t.opens t.base : S.Opens) ≤ t.overlap i :=
    le_inf (inf_le_left.trans inf_le_left) inf_le_right
  have hWj : ((t.opens i ⊓ t.opens j) ⊓ t.opens t.base : S.Opens) ≤ t.overlap j :=
    le_inf (inf_le_left.trans inf_le_right) inf_le_right
  have hi := t.transitionUnit_smul_res i hWi
  have hj := t.transitionUnit_smul_res j hWj
  have hv := resSection_congr_smul (L := L) hWV hue
  rw [resSection_resSection, resSection_resSection] at hv
  have hgen : Generates (resSection L (hWi.trans inf_le_left) (t.gen i)) :=
    (t.gen_generates i).restrict _
  have hmul :
      S.presheaf.map (homOfLE hWj).op (t.transitionUnit j) *
          S.presheaf.map (homOfLE hWV).op u =
        S.presheaf.map (homOfLE hWi).op (t.transitionUnit i) := by
    refine hgen.bijective.injective ?_
    show (_ * _) • _ = _ • _
    rw [mul_smul, hv, hj, hi]
  have hgerm := congrArg
    (S.germToFunctionField ((t.opens i ⊓ t.opens j) ⊓ t.opens t.base)) hmul
  rw [map_mul, t.germToFunctionField_transitionUnit_res j hWj,
    t.germToFunctionField_transitionUnit_res i hWi,
    S.presheaf.germ_res_apply (homOfLE hWV)] at hgerm
  rw [mul_comm]
  exact hgerm

/-- The local equations have equal orders of vanishing on overlaps. -/
lemma ord_eq (i j : t.ι) (x : S) (hi : x ∈ t.opens i) (hj : x ∈ t.opens j) :
    S.ord (t.fn i) x = S.ord (t.fn j) x := by
  have : Nonempty ((t.opens i ⊓ t.opens j : S.Opens)) := S.nonempty_inf _ _
  obtain ⟨u, hu, hue⟩ := ((t.gen_generates i).restrict inf_le_left).exists_isUnit_smul_eq
    ((t.gen_generates j).restrict (inf_le_right : t.opens i ⊓ t.opens j ≤ t.opens j))
  have hfi := t.germToFunctionField_mul_fn i j u hu hue
  have hune : IsUnit (S.germToFunctionField (t.opens i ⊓ t.opens j) u) :=
    hu.map (S.germToFunctionField (t.opens i ⊓ t.opens j)).hom
  rw [← hfi, Scheme.ord_mul hune.ne_zero (t.fn_ne_zero j),
    Scheme.ord_of_isUnit hu (show x ∈ (t.opens i ⊓ t.opens j : S.Opens) from ⟨hi, hj⟩), zero_add]

/-- The Cartier data of a trivializing cover: the local equations of a rational section of the
sheaf, taken with respect to the reference trivialization. -/
def cartierData : S.CartierData where
  ι := t.ι
  opens := t.opens
  nonempty := t.nonempty
  covers := t.covers
  fn := t.fn
  fn_ne_zero := t.fn_ne_zero
  ord_eq := t.ord_eq

/-- The constructed Cartier data represents the sheaf it came from. -/
theorem cartierData_represents : (t.cartierData).Represents L :=
  ⟨t.gen, t.gen_generates, fun i j u hu hue ↦ t.germToFunctionField_mul_fn i j u hu hue⟩

/-- The divisor of a rational section of a sheaf with a trivializing cover. -/
def divisor : CodimensionCycle S 1 := t.cartierData.divisor

/-- Every sheaf of modules with a trivializing cover is represented by Cartier data. -/
theorem exists_cartierData_represents (t : TrivializingCover L) :
    ∃ c : S.CartierData, c.Represents L := ⟨t.cartierData, t.cartierData_represents⟩

end TrivializingCover

end Scheme.Modules

end AlgebraicGeometry
