/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import HodgeConjecture.Definitions.AlgebraicGeometry.AlgebraicCycleClassSpan
import Other.AlgebraicGeometry.CodimensionCycle

import HodgeConjecture.Lemmas.AlgebraicGeometry.RationalCohomologyZero
import Other.AlgebraicGeometry.HodgeCodimensionZero
import Other.AlgebraicGeometry.SmoothAnalytificationConnected

/-!
# Comparing the two codimension-zero cycle-class constructions

The constructed codimension-zero algebraic cycle-class span is the line generated by the
component class of the generic point, and the comparison span is the line generated by
the degree-zero cohomological unit. Degree-zero rational cohomology is one dimensional because the
analytification is connected, so the two lines agree exactly when the generic-point component
class is nonzero.

Nonvanishing of that class is equivalent to nonvanishing of the normalized coclass section it is
built from, because every step of the normalization chain is injective: the two normalization
comparisons are isomorphisms, and forgetting support is a bijection because the generic component
is supported on the whole analytic space.

Thus it suffices to prove that the normalized coclass section is nonzero to establish the
codimension-zero case of the Hodge conjecture.
-/

@[expose] public noncomputable section

open CategoryTheory Order TopologicalSpace

namespace AlgebraicGeometry.ComplexPoint

open Point

variable (X : Over (Spec ↧ℂ)) [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom]

local instance : QuasiSeparatedSpace X.left :=
  quasiSeparatedSpace_of_quasiSeparated X.hom

/-! ### The constructed codimension-zero span is a single line -/

omit [Smooth X.hom] [IsProjective X.hom] in
/-- The codimension-zero coheight certificate of the generic point. -/
theorem coheight_genericPoint_eq_zero :
    coheight (genericPoint X.left) = ((0 : ℕ) : ℕ∞) := by
  rw [Nat.cast_zero]
  exact Order.IsMax.coheight_eq_zero isMax_top

/-- The constructed codimension-zero algebraic cycle-class span is the line generated by the
component class of the generic point: no other point of an integral scheme has coheight zero. -/
theorem algebraicCycleClassSpan_zero_eq_span_genericPoint :
    algebraicCycleClassSpan X 0 =
      Submodule.span ℚ {cycleComponentSheafClass X (genericPoint X.left)
        (d := dim X.left) (coheight_genericPoint_eq_zero X)} := by
  unfold algebraicCycleClassSpan
  refine le_antisymm (iSup_le fun x ↦ iSup_le fun hx ↦ ?_)
    (le_iSup_of_le (genericPoint X.left)
      (le_iSup_of_le (coheight_genericPoint_eq_zero X) le_rfl))
  obtain rfl := CodimensionCycle.eq_genericPoint_of_coheight_zero x (by simpa using hx)
  exact le_rfl

/-! ### Degree-zero cohomology is a line on a connected analytification -/

omit [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] in
/-- On a connected analytification a degree-zero rational cohomology class generates the whole
group precisely when it is nonzero. -/
theorem span_singleton_eq_top_iff_ne_zero [ConnectedSpace (ComplexPoint X)]
    (α : H^0(X; ℚ)) :
    Submodule.span ℚ {α} = ⊤ ↔ α ≠ 0 := by
  constructor
  · intro h hα
    rw [hα, Submodule.span_zero_singleton] at h
    exact rationalCohomologyUnit_ne_zero X
      ((Submodule.mem_bot ℚ).mp (h.ge Submodule.mem_top))
  · intro hα
    let e := rationalCohomologyClassLinearEquiv X
    obtain ⟨q, hq⟩ := e.surjective α
    have hq0 : q ≠ 0 := by
      rintro rfl
      exact hα (hq.symm.trans (map_zero _))
    refine top_unique fun β _ ↦ ?_
    obtain ⟨r, hr⟩ := e.surjective β
    have hβ : β = (r / q) • α := by
      rw [← hq, ← hr, ← map_smul]
      congr 1
      rw [smul_eq_mul, div_mul_cancel₀ _ hq0]
    rw [hβ]
    exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))

/-- On a connected analytification the two codimension-zero spans agree precisely when the
constructed generic-point component class is nonzero. -/
theorem algebraicCycleClassSpan_zero_eq_codimensionZeroCycleClassSpan_iff :
    algebraicCycleClassSpan X 0 = codimensionZeroCycleClassSpan X ↔
      cycleComponentSheafClass X (genericPoint X.left) (d := dim X.left)
        (coheight_genericPoint_eq_zero X) ≠ 0 := by
  let _ : ConnectedSpace (ComplexPoint X) := ComplexPoint.connectedSpace X
  rw [codimensionZeroCycleClassSpan_eq_span_unit, span_rationalCohomologyUnit_eq_top,
    algebraicCycleClassSpan_zero_eq_span_genericPoint]
  exact span_singleton_eq_top_iff_ne_zero X _

/-! ### The normalization chain is injective in codimension zero -/

/-- The component belonging to the generic point of an integral variety has the whole analytic
space as its support. -/
lemma cycleComponentSupport_genericPoint_eq_univ
    [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] :
    cycleComponentSupport X (genericPoint X.left) = Set.univ := by
  rw [cycleComponentSupport]
  change (@Point.underlying ℂ _ _ X) ⁻¹'
    (closure {genericPoint X.left} : Set X.left) = Set.univ
  rw [genericPoint_closure (α := X.left)]
  exact Set.preimage_univ



omit [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] in
/-- Forgetting support is injective whenever the support is the whole analytic space. -/
theorem forgetSupport_injective_of_eq_univ (Z : Set (ComplexPoint X))
    (hZ : Z = Set.univ) (n : ℤ) :
    Function.Injective (forgetSupport X Z n) := by
  subst hZ
  intro a b hab
  exact (forgetSupportEquivUniv X n).injective hab

/-- The generic-point component class vanishes exactly when the globally supported class it is
built from vanishes: support on the whole analytic space is forgotten injectively, and the
support-cone presentation is an isomorphism. -/
theorem cycleComponentSheafClass_genericPoint_eq_zero_iff_supportedInjectiveClass
    (d : ℕ) [SmoothOfRelativeDimension d X.hom] :
    cycleComponentSheafClass X (genericPoint X.left) (d := d)
        (coheight_genericPoint_eq_zero X) = 0 ↔
      cycleComponentSupportedInjectiveClass X (genericPoint X.left) (d := d)
        (coheight_genericPoint_eq_zero X) = 0 := by
  have hZ : cycleComponentSupport X (genericPoint X.left) = Set.univ :=
    cycleComponentSupport_genericPoint_eq_univ X
  rw [cycleComponentSheafClass_eq_forgetSupport]
  refine Iff.trans (map_eq_zero_iff _ (forgetSupport_injective_of_eq_univ X _ hZ _)) ?_
  rw [cycleComponentSheafSupportedClass]
  exact map_eq_zero_iff _ (AddEquiv.injective _)

/-- The generic-point component class vanishes exactly when the normalized coclass section it is
constructed from vanishes: the normalization comparison is an isomorphism. -/
theorem cycleComponentSheafClass_genericPoint_eq_zero_iff
    (d : ℕ) [SmoothOfRelativeDimension d X.hom] :
    cycleComponentSheafClass X (genericPoint X.left) (d := d)
        (coheight_genericPoint_eq_zero X) = 0 ↔
      cycleComponentSmoothSupportCoclassSection X (genericPoint X.left)
        (d := d) (coheight_genericPoint_eq_zero X) = 0 := by
  have hcoclass : (cycleComponentSupportedClassNormalizationIso X (genericPoint X.left)
        (d := d) (coheight_genericPoint_eq_zero X)).addCommGroupIsoToAddEquiv
      (cycleComponentSupportedInjectiveClass X (genericPoint X.left)
        (d := d) (coheight_genericPoint_eq_zero X)) =
      cycleComponentSmoothSupportCoclassSection X (genericPoint X.left)
        (d := d) (coheight_genericPoint_eq_zero X) :=
    cycleComponentSupportedInjectiveClass_normalization X (genericPoint X.left)
      (d := d) (coheight_genericPoint_eq_zero X)
  refine Iff.trans
    (cycleComponentSheafClass_genericPoint_eq_zero_iff_supportedInjectiveClass X d) ?_
  rw [← hcoclass]
  refine ⟨fun h ↦ ?_, fun h ↦ ?_⟩
  · rw [h]
    exact AddEquiv.map_zero _
  · exact AddEquiv.injective _ (h.trans (AddEquiv.map_zero _).symm)

/-- The comparison of the two codimension-zero span constructions, reduced to nonvanishing of the
one normalized coclass section the component class is built from. -/
theorem algebraicCycleClassSpan_zero_eq_codimensionZeroCycleClassSpan_of_coclassSection_ne_zero
    (hne : cycleComponentSmoothSupportCoclassSection X (genericPoint X.left)
      (d := dim X.left) (coheight_genericPoint_eq_zero X) ≠ 0) :
    algebraicCycleClassSpan X 0 = codimensionZeroCycleClassSpan X :=
  (algebraicCycleClassSpan_zero_eq_codimensionZeroCycleClassSpan_iff X).mpr
    fun h ↦ hne ((cycleComponentSheafClass_genericPoint_eq_zero_iff X (dim X.left)).mp h)

/-! ### The codimension-zero Hodge conjecture from the local nonvanishing -/

/-- The constructed codimension-zero algebraic cycle-class span is all of degree-zero rational
cohomology when the normalized coclass section is nonzero. -/
theorem algebraicCycleClassSpan_zero_eq_top_of_coclassSection_ne_zero
    (hne : cycleComponentSmoothSupportCoclassSection X (genericPoint X.left)
      (d := dim X.left) (coheight_genericPoint_eq_zero X) ≠ 0) :
    algebraicCycleClassSpan X 0 = ⊤ := by
  let hV : ConnectedSpace (ComplexPoint X) := ComplexPoint.connectedSpace X
  exact algebraicCycleClassSpan_zero_eq_top_of_connected X hV
    (algebraicCycleClassSpan_zero_eq_codimensionZeroCycleClassSpan_of_coclassSection_ne_zero X hne)

/-- The degree-zero Hodge classes are exactly the algebraic cycle-class span when the normalized
coclass section is nonzero. -/
theorem rationalHodgeClasses_zero_eq_algebraicCycleClassSpan_of_coclassSection_ne_zero
    (hne : cycleComponentSmoothSupportCoclassSection X (genericPoint X.left)
      (d := dim X.left) (coheight_genericPoint_eq_zero X) ≠ 0) :
    Hdg^0(ℚ; X) = algebraicCycleClassSpan X 0 := by
  let hV : ConnectedSpace (ComplexPoint X) := ComplexPoint.connectedSpace X
  exact rationalHodgeClasses_zero_eq_algebraicCycleClassSpan_of_connected X hV
    (algebraicCycleClassSpan_zero_eq_codimensionZeroCycleClassSpan_of_coclassSection_ne_zero X hne)

/-- The Hodge-conjecture inclusion in codimension zero follows from nonvanishing of the normalized
coclass section. -/
theorem rationalHodgeClasses_zero_le_algebraicCycleClassSpan_of_coclassSection_ne_zero
    (hne : cycleComponentSmoothSupportCoclassSection X (genericPoint X.left)
      (d := dim X.left) (coheight_genericPoint_eq_zero X) ≠ 0) :
    Hdg^0(ℚ; X) ≤ algebraicCycleClassSpan X 0 := by
  rw [rationalHodgeClasses_zero_eq_algebraicCycleClassSpan_of_coclassSection_ne_zero X hne]

/-- The Hodge-conjecture inclusion in every codimension for a smooth projective complex variety of
complex dimension zero, given nonvanishing of the normalized coclass section. -/
theorem rationalHodgeClasses_le_algebraicCycleClassSpan_of_dimension_eq_zero_of_coclassSection_ne_zero
    (hd : dim X.left = 0)
    (hne : cycleComponentSmoothSupportCoclassSection X (genericPoint X.left)
      (d := dim X.left) (coheight_genericPoint_eq_zero X) ≠ 0) (p : ℕ) :
    Hdg^p(ℚ; X) ≤ algebraicCycleClassSpan X p := by
  let _ : ConnectedSpace (ComplexPoint X) := ComplexPoint.connectedSpace X
  exact rationalHodgeClasses_le_algebraicCycleClassSpan_of_dimension_eq_zero X hd
    (algebraicCycleClassSpan_zero_eq_codimensionZeroCycleClassSpan_of_coclassSection_ne_zero
      X hne) p

end AlgebraicGeometry.ComplexPoint
