/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import HodgeConjecture.Definitions.AlgebraicGeometry.CycleClass

import HodgeConjecture.Definitions.AlgebraicGeometry.BettiSupportSingularHypercohomologyComparison
import Other.AlgebraicGeometry.CycleComponentPointPurity
import HodgeConjecture.Lemmas.AlgebraicGeometry.ProjectiveAnalytificationHausdorff
import HodgeConjecture.Lemmas.AlgebraicGeometry.ProjectiveAnalytificationParacompact

/-!
# Maximal-codimension component purity

The analytification of a maximal-codimension component is a point. Its rational singular
cohomology with support is generated by the chart-local coclass. The additive Betti comparison
transports this generator to rational constant-sheaf cohomology with support. Its image after
forgetting support therefore generates the complete supported image, which proves the guarded
component fundamental-class proposition in maximal codimension.

This does not prove Thom--Gysin purity for positive-dimensional supports or compatibility of the
Betti comparison with forgetting support.
-/

@[expose] public noncomputable section

open CategoryTheory Order TopologicalSpace

namespace AlgebraicGeometry.ComplexPoint

open Point

private lemma span_singleton_image_eq_span_range_of_span_eq_top
    {M N : Type*} [AddCommGroup M] [Module ℚ M] [AddCommGroup N] [Module ℚ N]
    (f : M →+ N) (x : M) (hx : Submodule.span ℚ {x} = ⊤) :
    Submodule.span ℚ {f x} = Submodule.span ℚ (Set.range f) := by
  refine le_antisymm (Submodule.span_mono fun y hy ↦ ⟨x, Set.mem_singleton_iff.mp hy ▸ rfl⟩)
    (Submodule.span_le.mpr ?_)
  rintro y ⟨z, rfl⟩
  obtain ⟨q, rfl⟩ := (Submodule.span_singleton_eq_top_iff ℚ x).mp hx z
  rw [map_rat_smul]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))

private lemma span_addEquiv_apply_eq_top
    {M N : Type*} [AddCommGroup M] [Module ℚ M] [AddCommGroup N] [Module ℚ N]
    (e : M ≃+ N) (x : M) (hx : Submodule.span ℚ {x} = ⊤) :
    Submodule.span ℚ {e x} = ⊤ := by
  refine top_unique fun y _ ↦ ?_
  obtain ⟨q, hq⟩ :=
    (Submodule.span_singleton_eq_top_iff ℚ x).mp hx (e.symm y)
  rw [← e.apply_symm_apply y, ← hq, map_rat_smul]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))

/-- A component of maximal codimension satisfies rational component cycle-class purity in
constant-sheaf cohomology. The supported generator is constructed in the proof and the public
conclusion records only the resulting equality of the fundamental-class line and supported
image. -/
theorem rationalComponentCycleClassPurity_of_coheight_eq_dimension
    (X : Over (Spec ↧ℂ)) [IsIntegral X.left] [Smooth X.hom]
    [IsProjective X.hom] (d : ℕ)
    [SmoothOfRelativeDimension d X.hom] (x : X.left) (hx : coheight x = d) :
    RationalComponentCycleClassPurity X d x := by
  unfold RationalComponentCycleClassPurity
  let : ∀ U : Opens (ComplexPoint X), ParacompactSpace U :=
    openParacompactSpace X
  let Z := cycleComponentSupport X x
  have hZ : IsClosed Z := isClosed_cycleComponentSupport X x
  let e : RationalCohomologyWithSupport X Z ((2 * d : ℕ) : ℤ) ≃+
      AlgebraicTopology.Singular.CohomologyWithSupport ℚ
        (TopCat.of (ComplexPoint X)) Z (2 * d) :=
    rationalCohomologyWithSupportAddEquivSingular X Z hZ (2 * d)
  let : Module ℚ (RationalCohomologyWithSupport X Z ((2 * d : ℕ) : ℤ)) :=
    e.module ℚ
  obtain ⟨β, hβ⟩ :=
    exists_singularComponentSupportedGenerator_of_coheight_eq_dimension X d x hx
  let γ : RationalCohomologyWithSupport X Z ((2 * d : ℕ) : ℤ) := e.symm β
  have hγ : Submodule.span ℚ {γ} = ⊤ := span_addEquiv_apply_eq_top e.symm β hβ
  let α := forgetSupport X Z ((2 * d : ℕ) : ℤ) γ
  have hα : IsRationalComponentCycleClass X d x α :=
    ⟨Submodule.subset_span ⟨γ, rfl⟩, span_singleton_image_eq_span_range_of_span_eq_top
      (forgetSupport X Z ((2 * d : ℕ) : ℤ)) γ hγ⟩
  simpa only [Nat.cast_mul, Nat.cast_ofNat] using
    (rationalComponentCycleClassLine_eq_span X d x α hα).trans hα.2

end AlgebraicGeometry.ComplexPoint
