/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Other.AlgebraicGeometry.ExplicitEllipticSurfaceCoordinateRing
public import Other.AlgebraicGeometry.ExplicitEllipticSurfaceOneForms

/-!
# Cotangent generation on the elliptic self-product charts

On each of the four affine product charts, the two pullbacks of the invariant
elliptic differential generate the cotangent module.  Consequently the wedge
of those two forms generates the degree-two de Rham forms.
-/

@[expose] public noncomputable section

open CategoryTheory CategoryTheory.Limits TopologicalSpace

namespace AlgebraicGeometry.ExplicitEllipticCandidate

open ComplexPoint

set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option maxHeartbeats 800000

attribute [local instance] regularSectionAlgebra

local instance surfaceCotangentSectionAlgebra (V : surface.Opens) :
    Algebra ℂ Γ(surface, V) :=
  regularSectionAlgebra (Over.mk surfaceToBase) V

local instance surfaceCotangentBaseAffine : IsAffine base :=
  inferInstanceAs (IsAffine (Spec (CommRingCat.of ℂ)))

local instance surfaceCotangentBaseTopAffine : IsAffine (⊤ : base.Opens).toScheme :=
  isAffineOpen_top base

/-- The section ring of every one of the four product charts is the pushout of
the section rings of its two elliptic factors. -/
theorem surfaceDifferentialChart_section_isPushout (ij : Fin 2 × Fin 2) :
    IsPushout
      (curveToBase.appLE ⊤ (chart (differentialChartIndex ij.1)) (by simp))
      (curveToBase.appLE ⊤ (chart (differentialChartIndex ij.2)) (by simp))
      ((pullback.fst curveToBase curveToBase).appLE
        (chart (differentialChartIndex ij.1))
        (surfaceDifferentialOpen ij) inf_le_left)
      ((pullback.snd curveToBase curveToBase).appLE
        (chart (differentialChartIndex ij.2))
        (surfaceDifferentialOpen ij) inf_le_right) := by
  let H : IsPullback (pullback.fst curveToBase curveToBase)
      (pullback.snd curveToBase curveToBase) curveToBase curveToBase := .of_hasPullback _ _
  have h := isIso_pushoutSection_of_isAffineOpen H
    (US := ⊤)
    (UT := chart (differentialChartIndex ij.2))
    (UX := chart (differentialChartIndex ij.1))
    (UY := surfaceDifferentialOpen ij)
    (by simp) (by simp) rfl
    (isAffineOpen_top base)
    (chart_isAffineOpen (differentialChartIndex ij.2))
    (chart_isAffineOpen (differentialChartIndex ij.1))
  exact (isIso_pushoutSection_iff H (by simp) (by simp) rfl).mp h

/-- Each affine elliptic cotangent module is generated by its chosen invariant
differential. -/
theorem indexedCurveDifferential_generates (i : Fin 2)
    (w : KaehlerDifferential ℂ Γ(curve, chart (differentialChartIndex i))) :
    ∃ a : Γ(curve, chart (differentialChartIndex i)),
      a • indexedCurveDifferential i = w := by
  fin_cases i
  · change ∃ a : Γ(curve, chart 2), a • curveZDifferential = w
    let a := curveZCotangentLinearEquiv.symm w
    refine ⟨a, ?_⟩
    change curveZCotangentLinearEquiv a = w
    exact curveZCotangentLinearEquiv.apply_symm_apply w
  · change ∃ a : Γ(curve, chart 1), a • curveYDifferential = w
    let a := curveYCotangentLinearEquiv.symm w
    refine ⟨a, ?_⟩
    rw [← curveYCotangentLinearEquiv_apply]
    exact curveYCotangentLinearEquiv.apply_symm_apply w

/-- Pullback of Kähler differentials is semilinear over pullback of functions. -/
theorem surfaceDifferentialPullback_smul'
    (f : surface ⟶ curve) (hbase : f ≫ curveToBase = surfaceToBase)
    (U : curve.Opens) (V : surface.Opens) (h : V ≤ f ⁻¹ᵁ U)
    (a : Γ(curve, U)) (w : KaehlerDifferential ℂ Γ(curve, U)) :
    surfaceDifferentialPullback f hbase U V h (a • w) =
      surfaceSectionPullback f hbase U V h a •
        surfaceDifferentialPullback f hbase U V h w := by
  let := (surfaceSectionPullback f hbase U V h).toRingHom.toAlgebra
  let : IsScalarTower ℂ Γ(curve, U) Γ(surface, V) :=
    IsScalarTower.of_algebraMap_eq'
      (surfaceSectionPullback f hbase U V h).comp_algebraMap.symm
  exact (KaehlerDifferential.map ℂ ℂ Γ(curve, U) Γ(surface, V)).map_smul a w

/-- Pullback carries the universal differential of a function to the universal
differential of its pullback. -/
theorem surfaceDifferentialPullback_D'
    (f : surface ⟶ curve) (hbase : f ≫ curveToBase = surfaceToBase)
    (U : curve.Opens) (V : surface.Opens) (h : V ≤ f ⁻¹ᵁ U)
    (b : Γ(curve, U)) :
    surfaceDifferentialPullback f hbase U V h
        (KaehlerDifferential.D ℂ Γ(curve, U) b) =
      KaehlerDifferential.D ℂ Γ(surface, V)
        (surfaceSectionPullback f hbase U V h b) := by
  simpa using surfaceDifferentialPullback_smul_D f hbase U V h 1 b

/-- The selected pulled invariant differential in the cotangent module of a
full product chart. -/
def surfaceChartPulledDifferential (factor : Fin 2) (ij : Fin 2 × Fin 2) :
    KaehlerDifferential ℂ Γ(surface, surfaceDifferentialOpen ij) :=
  Fin.cases
    (surfacePulledCurveDifferential
      (pullback.fst curveToBase curveToBase) rfl ij.1
      (surfaceDifferentialOpen ij) inf_le_left)
    (Fin.cases
      (surfacePulledCurveDifferential
        (pullback.snd curveToBase curveToBase) pullback.condition.symm ij.2
        (surfaceDifferentialOpen ij) inf_le_right)
      (fun i => i.elim0)) factor

/-- Differentiating a function pulled from the first factor gives a coefficient
multiple of the first invariant differential. -/
theorem exists_surfaceChart_D_fstPullback_eq_smul
    (ij : Fin 2 × Fin 2)
    (b : Γ(curve, chart (differentialChartIndex ij.1))) :
    ∃ a : Γ(surface, surfaceDifferentialOpen ij),
      a • surfaceChartPulledDifferential 0 ij =
        KaehlerDifferential.D ℂ Γ(surface, surfaceDifferentialOpen ij)
          (surfaceSectionPullback (pullback.fst curveToBase curveToBase) rfl
            (chart (differentialChartIndex ij.1)) (surfaceDifferentialOpen ij)
            inf_le_left b) := by
  obtain ⟨a, ha⟩ := indexedCurveDifferential_generates ij.1
    (KaehlerDifferential.D ℂ Γ(curve, chart (differentialChartIndex ij.1)) b)
  let f : surface ⟶ curve := by
    change pullback curveToBase curveToBase ⟶ curve
    exact pullback.fst curveToBase curveToBase
  have hf : f ≫ curveToBase = surfaceToBase := by rfl
  refine ⟨surfaceSectionPullback (pullback.fst curveToBase curveToBase) rfl
    (chart (differentialChartIndex ij.1)) (surfaceDifferentialOpen ij)
    inf_le_left a, ?_⟩
  calc
    _ = surfaceDifferentialPullback f hf
        (chart (differentialChartIndex ij.1)) (surfaceDifferentialOpen ij)
        inf_le_left (a • indexedCurveDifferential ij.1) := by
      simpa [f, surfaceChartPulledDifferential, surfacePulledCurveDifferential] using
        (surfaceDifferentialPullback_smul' f hf
          (chart (differentialChartIndex ij.1)) (surfaceDifferentialOpen ij)
          inf_le_left a (indexedCurveDifferential ij.1)).symm
    _ = surfaceDifferentialPullback f hf
        (chart (differentialChartIndex ij.1)) (surfaceDifferentialOpen ij)
        inf_le_left (KaehlerDifferential.D ℂ
          Γ(curve, chart (differentialChartIndex ij.1)) b) := congrArg _ ha
    _ = _ := by
      simpa [f] using surfaceDifferentialPullback_D' f hf
        (chart (differentialChartIndex ij.1)) (surfaceDifferentialOpen ij)
        inf_le_left b

/-- Differentiating a function pulled from the second factor gives a coefficient
multiple of the second invariant differential. -/
theorem exists_surfaceChart_D_sndPullback_eq_smul
    (ij : Fin 2 × Fin 2)
    (b : Γ(curve, chart (differentialChartIndex ij.2))) :
    ∃ a : Γ(surface, surfaceDifferentialOpen ij),
      a • surfaceChartPulledDifferential 1 ij =
        KaehlerDifferential.D ℂ Γ(surface, surfaceDifferentialOpen ij)
          (surfaceSectionPullback (pullback.snd curveToBase curveToBase)
            pullback.condition.symm (chart (differentialChartIndex ij.2))
            (surfaceDifferentialOpen ij) inf_le_right b) := by
  obtain ⟨a, ha⟩ := indexedCurveDifferential_generates ij.2
    (KaehlerDifferential.D ℂ Γ(curve, chart (differentialChartIndex ij.2)) b)
  let f : surface ⟶ curve := by
    change pullback curveToBase curveToBase ⟶ curve
    exact pullback.snd curveToBase curveToBase
  have hf : f ≫ curveToBase = surfaceToBase := by
    exact pullback.condition.symm
  refine ⟨surfaceSectionPullback (pullback.snd curveToBase curveToBase)
    pullback.condition.symm (chart (differentialChartIndex ij.2))
    (surfaceDifferentialOpen ij) inf_le_right a, ?_⟩
  change _ • surfacePulledCurveDifferential
      (pullback.snd curveToBase curveToBase) pullback.condition.symm ij.2
        (surfaceDifferentialOpen ij) inf_le_right = _
  calc
    _ = surfaceDifferentialPullback f hf
        (chart (differentialChartIndex ij.2)) (surfaceDifferentialOpen ij)
        inf_le_right (a • indexedCurveDifferential ij.2) := by
      simpa [f, surfaceChartPulledDifferential, surfacePulledCurveDifferential] using
        (surfaceDifferentialPullback_smul' f hf
          (chart (differentialChartIndex ij.2)) (surfaceDifferentialOpen ij)
          inf_le_right a (indexedCurveDifferential ij.2)).symm
    _ = surfaceDifferentialPullback f hf
        (chart (differentialChartIndex ij.2)) (surfaceDifferentialOpen ij)
        inf_le_right (KaehlerDifferential.D ℂ
          Γ(curve, chart (differentialChartIndex ij.2)) b) := congrArg _ ha
    _ = _ := by
      simpa [f] using surfaceDifferentialPullback_D' f hf
        (chart (differentialChartIndex ij.2)) (surfaceDifferentialOpen ij)
        inf_le_right b

/-- On every product chart, the two projection pullbacks of the invariant
elliptic differential generate the full cotangent module. -/
theorem exists_surfaceChart_cotangent_eq_linearCombination
    (ij : Fin 2 × Fin 2)
    (w : KaehlerDifferential ℂ Γ(surface, surfaceDifferentialOpen ij)) :
    ∃ a b : Γ(surface, surfaceDifferentialOpen ij),
      a • surfaceChartPulledDifferential 0 ij +
        b • surfaceChartPulledDifferential 1 ij = w := by
  let P : Subring Γ(surface, surfaceDifferentialOpen ij) :=
    { carrier := {x | ∃ a b : Γ(surface, surfaceDifferentialOpen ij),
          a • surfaceChartPulledDifferential 0 ij +
            b • surfaceChartPulledDifferential 1 ij =
              KaehlerDifferential.D ℂ Γ(surface, surfaceDifferentialOpen ij) x}
      zero_mem' := ⟨0, 0, by simp⟩
      one_mem' := ⟨0, 0, by simp⟩
      add_mem' := by
        rintro x y ⟨a, b, hab⟩ ⟨c, d, hcd⟩
        refine ⟨a + c, b + d, ?_⟩
        rw [add_smul, add_smul, map_add]
        rw [← hab, ← hcd]
        abel
      neg_mem' := by
        rintro x ⟨a, b, hab⟩
        refine ⟨-a, -b, ?_⟩
        rw [neg_smul, neg_smul, map_neg, ← hab]
        abel
      mul_mem' := by
        rintro x y ⟨a, b, hab⟩ ⟨c, d, hcd⟩
        refine ⟨x * c + y * a, x * d + y * b, ?_⟩
        rw [add_smul, add_smul, mul_smul, mul_smul, mul_smul, mul_smul,
          Derivation.leibniz, ← hab, ← hcd]
        simp only [smul_add]
        abel }
  have hP : P = ⊤ := by
    apply CommRingCat.subring_eq_top_of_isPushout
      (surfaceDifferentialChart_section_isPushout ij)
    · intro x
      obtain ⟨a, ha⟩ := exists_surfaceChart_D_fstPullback_eq_smul ij x
      have heq :
          surfaceSectionPullback (pullback.fst curveToBase curveToBase) rfl
              (chart (differentialChartIndex ij.1)) (surfaceDifferentialOpen ij)
              inf_le_left x =
            (pullback.fst curveToBase curveToBase).appLE
              (chart (differentialChartIndex ij.1)) (surfaceDifferentialOpen ij)
              inf_le_left x := by
        rfl
      exact ⟨a, 0, by simpa [P, heq] using ha⟩
    · intro x
      obtain ⟨b, hb⟩ := exists_surfaceChart_D_sndPullback_eq_smul ij x
      have heq :
          surfaceSectionPullback (pullback.snd curveToBase curveToBase)
              pullback.condition.symm (chart (differentialChartIndex ij.2))
              (surfaceDifferentialOpen ij) inf_le_right x =
            (pullback.snd curveToBase curveToBase).appLE
              (chart (differentialChartIndex ij.2)) (surfaceDifferentialOpen ij)
              inf_le_right x := by
        rfl
      exact ⟨0, b, by simpa [P, heq] using hb⟩
  have hD (x : Γ(surface, surfaceDifferentialOpen ij)) :
      ∃ a b : Γ(surface, surfaceDifferentialOpen ij),
        a • surfaceChartPulledDifferential 0 ij +
          b • surfaceChartPulledDifferential 1 ij =
            KaehlerDifferential.D ℂ Γ(surface, surfaceDifferentialOpen ij) x := by
    have hx : x ∈ P := by rw [hP]; trivial
    exact hx
  have hw : w ∈ Submodule.span Γ(surface, surfaceDifferentialOpen ij)
      (Set.range (KaehlerDifferential.D ℂ
        Γ(surface, surfaceDifferentialOpen ij))) := by
    rw [KaehlerDifferential.span_range_derivation]
    trivial
  let Q : KaehlerDifferential ℂ Γ(surface, surfaceDifferentialOpen ij) → Prop :=
    fun z ↦ ∃ a b : Γ(surface, surfaceDifferentialOpen ij),
      a • surfaceChartPulledDifferential 0 ij +
        b • surfaceChartPulledDifferential 1 ij = z
  refine Submodule.span_induction (p := fun z _ ↦ Q z) ?_ ?_ ?_ ?_ hw
  · rintro _ ⟨x, rfl⟩
    exact hD x
  · exact ⟨0, 0, by simp⟩
  · rintro x y _ _ ⟨a, b, hab⟩ ⟨c, d, hcd⟩
    refine ⟨a + c, b + d, ?_⟩
    rw [add_smul, add_smul]
    calc
      _ = (a • surfaceChartPulledDifferential 0 ij +
            b • surfaceChartPulledDifferential 1 ij) +
          (c • surfaceChartPulledDifferential 0 ij +
            d • surfaceChartPulledDifferential 1 ij) := by abel
      _ = x + y := by rw [hab, hcd]
  · rintro c x _ ⟨a, b, hab⟩
    exact ⟨c * a, c * b, by rw [mul_smul, mul_smul, ← smul_add, hab]⟩

end AlgebraicGeometry.ExplicitEllipticCandidate
