/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Other.AlgebraicGeometry.DivisorOfRationalSection
public import Other.TauCeti.SheafOfModules.Free
public import Other.TauCeti.SheafOfModules.LocalTriviality
public import Mathlib.AlgebraicGeometry.Modules.Sheaf

/-!
# Generating sections of a sheaf of modules and trivializing covers

An invertible sheaf is locally generated by a single section. This file records the
section-level form of that statement, which is what the divisor of a rational section is
defined from.

* `Scheme.Modules.Generates s` says that a section `s : Γ(L, U)` freely generates `L` on `U`:
  for every open `V ≤ U`, multiplication by the restriction of `s` is a bijection
  `Γ(X, V) → Γ(L, V)`.
* `Scheme.Modules.Generates.exists_isUnit_smul_eq`: two generating sections on the same open
  differ by a unit of the structure sheaf. This is the transition-function statement, and it is
  what makes the order of vanishing of a rational section independent of the trivialization.
* `Scheme.Modules.TrivializingCover L` bundles an open cover with a generating section on each
  member.

The comparison of this section-level interface with the sheaf-of-modules interface of
`TauCeti.SheafOfModules.IsInvertible` is stated as `HasGeneratingCover` in
`Other/AlgebraicGeometry/DivisorObligations.lean`; see `docs/DIVISOR_HANDOFF.md`.
-/

@[expose] public noncomputable section

open CategoryTheory Order TopologicalSpace Opposite

universe u

namespace AlgebraicGeometry.Scheme.Modules

variable {S : Scheme.{u}} {L : S.Modules}

/-- Restriction of a section of a sheaf of modules to a smaller open. -/
abbrev resSection (L : S.Modules) {U V : S.Opens} (h : V ≤ U) (s : Γ(L, U)) : Γ(L, V) :=
  L.presheaf.map (homOfLE h).op s

@[simp]
lemma resSection_rfl {U : S.Opens} (s : Γ(L, U)) : resSection L le_rfl s = s := by
  change L.presheaf.map (𝟙 (Opposite.op U)) s = s
  rw [L.presheaf.map_id]
  rfl

lemma resSection_resSection {U V W : S.Opens} (hVU : V ≤ U) (hWV : W ≤ V) (s : Γ(L, U)) :
    resSection L hWV (resSection L hVU s) = resSection L (hWV.trans hVU) s := by
  change (L.presheaf.map (homOfLE hVU).op ≫ L.presheaf.map (homOfLE hWV).op) s = _
  rw [← L.presheaf.map_comp]
  rfl

lemma resSection_smul {U V : S.Opens} (h : V ≤ U) (r : Γ(S, U)) (s : Γ(L, U)) :
    resSection L h (r • s) = S.presheaf.map (homOfLE h).op r • resSection L h s :=
  L.map_smul _ _ _

/-- A section `s : Γ(L, U)` generates `L` on `U`: on every smaller open, multiplication by the
restriction of `s` is a bijection from functions to sections. -/
def Generates {U : S.Opens} (s : Γ(L, U)) : Prop :=
  ∀ (V : S.Opens) (h : V ≤ U), Function.Bijective fun r : Γ(S, V) ↦ r • resSection L h s

namespace Generates

variable {U : S.Opens} {s : Γ(L, U)}

lemma bijective (hs : Generates s) : Function.Bijective fun r : Γ(S, U) ↦ r • s := by
  simpa using hs U le_rfl

/-- The restriction of a generating section generates on the smaller open. -/
lemma restrict (hs : Generates s) {V : S.Opens} (h : V ≤ U) :
    Generates (resSection L h s) := by
  intro W hW
  have := hs W (hW.trans h)
  rwa [← resSection_resSection h hW s] at this

/-- Every section over an open on which `s` generates is a multiple of `s`. -/
lemma exists_smul_eq (hs : Generates s) {V : S.Opens} (h : V ≤ U) (t : Γ(L, V)) :
    ∃ r : Γ(S, V), r • resSection L h s = t := (hs V h).surjective t

/-- The coefficient of a section with respect to a generating section is unique. -/
lemma smul_left_injective (hs : Generates s) {V : S.Opens} (h : V ≤ U) :
    Function.Injective fun r : Γ(S, V) ↦ r • resSection L h s := (hs V h).injective

/-- Two generating sections on the same open differ by a unit: this is the transition
function of the corresponding invertible sheaf. -/
lemma exists_isUnit_smul_eq (hs : Generates s) {t : Γ(L, U)} (ht : Generates t) :
    ∃ u : Γ(S, U), IsUnit u ∧ u • s = t := by
  obtain ⟨u, hu⟩ := hs.exists_smul_eq le_rfl t
  obtain ⟨v, hv⟩ := ht.exists_smul_eq le_rfl s
  rw [resSection_rfl] at hu hv
  have h1 : (v * u) • s = (1 : Γ(S, U)) • s := by rw [mul_smul, hu, hv, one_smul]
  have h2 : v * u = 1 := hs.bijective.injective h1
  exact ⟨u, ⟨⟨u, v, by rw [mul_comm]; exact h2, h2⟩, rfl⟩, hu⟩

end Generates

/-- The section of `L` over `U` corresponding to `1` under a trivialization of `L` on `U`. -/
def unitIsoSection {U : S.Opens}
    (e : SheafOfModules.unit (S.ringCatSheaf.over U) ≅ L.over U) : Γ(L, U) :=
  e.hom.val.app (op (Over.mk (𝟙 U))) (1 : Γ(S, U))

/-- The section corresponding to `1` under a trivialization generates. -/
theorem generates_unitIsoSection {U : S.Opens}
    (e : SheafOfModules.unit (S.ringCatSheaf.over U) ≅ L.over U) :
    Generates (unitIsoSection e) := by
  intro V h
  have hbij : Function.Bijective (e.hom.val.app (op (Over.mk (homOfLE h)))) :=
    ConcreteCategory.bijective_of_isIso
      ((SheafOfModules.evaluation (R := S.ringCatSheaf.over U) (op (Over.mk (homOfLE h)))).map
        e.hom)
  have hmu : Over.mk (homOfLE h) ⟶ Over.mk (𝟙 U) := Over.homMk (homOfLE h) (by simp)
  have hone : e.hom.val.app (op (Over.mk (homOfLE h))) (1 : Γ(S, V)) =
      resSection L h (unitIsoSection e) := by
    have hnat := PresheafOfModules.naturality_apply e.hom.val hmu.op (1 : Γ(S, U))
    have h1 : (SheafOfModules.unit (S.ringCatSheaf.over U)).val.map hmu.op (1 : Γ(S, U)) =
        (1 : Γ(S, V)) := PresheafOfModules.unit_map_one _ hmu.op
    rw [h1] at hnat
    exact hnat
  have hsmul : ∀ r : Γ(S, V), e.hom.val.app (op (Over.mk (homOfLE h))) r =
      r • resSection L h (unitIsoSection e) := by
    intro r
    have hlin := (e.hom.val.app (op (Over.mk (homOfLE h)))).hom.map_smul r (1 : Γ(S, V))
    rw [← hone]
    refine Eq.trans ?_ hlin
    congr 1
    exact (mul_one r).symm
  have hfun : (fun r : Γ(S, V) ↦ r • resSection L h (unitIsoSection e)) =
      ⇑(ConcreteCategory.hom (e.hom.val.app (op (Over.mk (homOfLE h))))) := by
    funext r
    exact (hsmul r).symm
  rw [hfun]
  exact hbij

/-- An open cover of a scheme together with a generating section of `L` on each member. -/
structure TrivializingCover (L : S.Modules) where
  /-- The index type of the cover. -/
  ι : Type u
  /-- The members of the cover. -/
  opens : ι → S.Opens
  /-- Every member is nonempty. -/
  nonempty (i : ι) : Nonempty (opens i)
  /-- The members cover the scheme. -/
  covers (x : S) : ∃ i, x ∈ opens i
  /-- The chosen local generator on each member. -/
  gen (i : ι) : Γ(L, opens i)
  /-- Each chosen local section generates. -/
  gen_generates (i : ι) : Generates (gen i)

/-- An invertible sheaf of modules on a scheme has a trivializing cover by nonempty opens with
a generating section on each member. -/
theorem nonempty_trivializingCover_of_isInvertible (L : S.Modules)
    (hL : _root_.TauCeti.SheafOfModules.IsInvertible.{u} L) : Nonempty (TrivializingCover L) := by
  have := hL
  let t := _root_.TauCeti.SheafOfModules.LocalTrivializations.ofIsInvertible L
  have hcov : IsOpenCover t.X := (Opens.coversTop_iff _ t.X).mp t.coversTop
  refine ⟨{
    ι := {i : t.I // Nonempty (t.X i)}
    opens := fun i ↦ t.X i.1
    nonempty := fun i ↦ i.2
    covers := fun x ↦ ?_
    gen := fun i ↦ unitIsoSection
      ((_root_.TauCeti.SheafOfModules.freePUnitIsoUnit _).symm ≪≫ t.iso i.1)
    gen_generates := fun i ↦ generates_unitIsoSection _ }⟩
  obtain ⟨i, hi⟩ := hcov.exists_mem x
  exact ⟨⟨i, ⟨⟨x, hi⟩⟩⟩, hi⟩

end AlgebraicGeometry.Scheme.Modules
