/-
Copyright 2026 The Formal Conjectures Authors.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Other.AlgebraicGeometry.ProjectiveChartIso
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Basic
public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.AlgebraicGeometry.Limits
public import HodgeConjecture.Definitions.AlgebraicGeometry.ProjectiveSpace

import HodgeConjecture.Mathlib.CategoryTheory.ConcreteCategory.Notation

/-!
# Projective space is smooth of relative dimension `N`

The standard charts `D₊(Xᵢ)` cover `Proj R[X₀, …, X_N]` and each is the spectrum of a polynomial
ring in `N` variables over `R`.  Since smoothness of relative dimension `N` is local at the
source, the structure morphism `Proj R[X₀, …, X_N] ⟶ Spec R` is smooth of relative dimension `N`.
-/

@[expose] public noncomputable section

open MvPolynomial CategoryTheory AlgebraicGeometry HomogeneousLocalization

namespace Other.ProjectiveChart

section Smooth

variable (R : Type*) [CommRing R] (N : ℕ)

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The irrelevant ideal of the standard grading is generated by the variables. -/
theorem irrelevant_le_span_X :
    (HomogeneousIdeal.irrelevant (homogeneousSubmodule (Fin (N + 1)) R)).toIdeal ≤
      Ideal.span (Set.range (X : Fin (N + 1) → MvPolynomial (Fin (N + 1)) R)) := by
  intro p hp
  have hmem : (homogeneousComponent 0 p : MvPolynomial (Fin (N + 1)) R) ∈
      homogeneousSubmodule (Fin (N + 1)) R 0 := homogeneousComponent_mem 0 p
  have h0 : (homogeneousComponent 0 p : MvPolynomial (Fin (N + 1)) R) ∈
      (HomogeneousIdeal.irrelevant (homogeneousSubmodule (Fin (N + 1)) R)).toIdeal :=
    MvPolynomial.homogeneousComponent_mem_of_mem
      (HomogeneousIdeal.irrelevant (homogeneousSubmodule (Fin (N + 1)) R)).isHomogeneous hp 0
  rw [HomogeneousIdeal.toIdeal_irrelevant, RingHom.mem_ker,
    GradedRing.projZeroRingHom_apply, DirectSum.decompose_of_mem_same _ hmem] at h0
  have hcoeff : coeff 0 p = 0 := by
    rw [homogeneousComponent_zero] at h0
    have h2 := congrArg (coeff 0) h0
    simpa using h2
  have : p ∈ idealOfVars (Fin (N + 1)) R ^ 1 := by
    rw [mem_pow_idealOfVars_iff]
    intro d hd
    rw [Nat.one_le_iff_ne_zero]
    intro hdeg
    apply (MvPolynomial.mem_support_iff.1 hd)
    rw [(Finsupp.degree_eq_zero_iff d).mp hdeg, hcoeff]
  simpa [pow_one, idealOfVars] using this

/-- The standard coordinate charts cover `Proj` of a polynomial ring. -/
theorem iSup_basicOpen_X_eq_top :
    ⨆ i : Fin (N + 1), Proj.basicOpen (homogeneousSubmodule (Fin (N + 1)) R) (X i) = ⊤ :=
  Proj.iSup_basicOpen_eq_top _ _ (irrelevant_le_span_X R N)

variable {N}

set_option linter.style.haveILetI false in
/-- **`Proj` of a polynomial ring in `N + 1` variables is smooth of relative dimension `N`.** -/
theorem smoothOfRelativeDimension_toSpecZero :
    SmoothOfRelativeDimension N
      (Proj.toSpecZero (homogeneousSubmodule (Fin (N + 1)) R)) := by
  have : MorphismProperty.RespectsIso (@SmoothOfRelativeDimension N) :=
    (smoothOfRelativeDimension_isStableUnderBaseChange (n := N)).respectsIso
  have : IsZariskiLocalAtSource (@SmoothOfRelativeDimension N) :=
    HasRingHomProperty.instIsZariskiLocalAtSource
      (P := @SmoothOfRelativeDimension N)
      (Q := RingHom.Locally (RingHom.IsStandardSmoothOfRelativeDimension N))
  rw [IsZariskiLocalAtSource.iff_of_iSup_eq_top
    (P := @SmoothOfRelativeDimension N)
    (fun i : Fin (N + 1) ↦ Proj.basicOpen (homogeneousSubmodule (Fin (N + 1)) R) (X i))
    (iSup_basicOpen_X_eq_top R N)]
  intro i
  rw [← MorphismProperty.cancel_left_of_respectsIso (P := @SmoothOfRelativeDimension N)
    (Proj.basicOpenIsoSpec (homogeneousSubmodule (Fin (N + 1)) R) (X i)
      (X_mem_one R i) Nat.one_pos).inv, ← Category.assoc,
    Proj.basicOpenIsoSpec_inv_ι, Proj.awayι_toSpecZero,
    HasRingHomProperty.Spec_iff (P := @SmoothOfRelativeDimension N)]
  exact RingHom.locally_of RingHom.isStandardSmoothOfRelativeDimension_respectsIso _
    (Other.ProjectiveChart.isStandardSmoothOfRelativeDimension_fromZeroRingHom R i)

end Smooth

section Base

open Limits

universe u v

variable (N : ℕ)

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The spectrum of the degree-zero part of the universal homogeneous coordinate ring is a
terminal scheme. -/
def specDegreeZeroIsTerminal :
    IsTerminal (Spec ↧(homogeneousSubmodule (Fin (N + 1)) (ULift.{u} ℤ) 0)) :=
  IsTerminal.ofIso specULiftZIsTerminal
    (Scheme.Spec.mapIso (cZeroEquiv (N := N) (ULift.{u} ℤ)).symm.toCommRingCatIso.op)

/-- The universal `Proj` model of projective `N`-space is smooth of relative dimension `N`
over the terminal scheme. -/
theorem smoothOfRelativeDimension_terminalFromProj :
    SmoothOfRelativeDimension N
      (terminal.from (Proj (homogeneousSubmodule (Fin (N + 1)) (ULift.{u} ℤ)))) := by
  have hresp : MorphismProperty.RespectsIso (@SmoothOfRelativeDimension N) :=
    (smoothOfRelativeDimension_isStableUnderBaseChange (n := N)).respectsIso
  have hiso := isIso_of_isTerminal (specDegreeZeroIsTerminal.{u} N)
    terminalIsTerminal (terminal.from _)
  rw [← terminal.comp_from
      (Proj.toSpecZero (homogeneousSubmodule (Fin (N + 1)) (ULift.{u} ℤ))),
    MorphismProperty.cancel_right_of_respectsIso (P := @SmoothOfRelativeDimension N)]
  exact smoothOfRelativeDimension_toSpecZero _

set_option linter.style.haveILetI false in
/-- **Projective `N`-space over an arbitrary base scheme is smooth of relative dimension `N`.**
This supplies the `SmoothOfRelativeDimension N` instance that the repository's holomorphic
structure sheaf, analytification functor and charts require on `ℙᴺ`. -/
theorem smoothOfRelativeDimension_projectiveSpaceToBase (S : Scheme.{u}) :
    SmoothOfRelativeDimension N (ProjectiveSpace.toBase (Fin (N + 1)) S) := by
  letI hst : MorphismProperty.IsStableUnderBaseChange (@SmoothOfRelativeDimension N) :=
    smoothOfRelativeDimension_isStableUnderBaseChange N
  letI hAlong : MorphismProperty.IsStableUnderBaseChangeAlong (@SmoothOfRelativeDimension N)
      (terminal.from S) := ⟨fun pb hg ↦ hst.of_isPullback pb hg⟩
  have h := smoothOfRelativeDimension_terminalFromProj.{u} N
  exact MorphismProperty.pullback_fst _ _ h

/-- Projective space, as an object over its base, is smooth of relative dimension `N`.  This is
the instance the repository's holomorphic structure sheaf and analytification functor need. -/
instance smoothOfRelativeDimension_projectiveSpaceOver (N : ℕ) (S : Scheme.{u}) :
    SmoothOfRelativeDimension N
      (Over.mk (ProjectiveSpace.toBase (Fin (N + 1)) S)).hom :=
  smoothOfRelativeDimension_projectiveSpaceToBase N S

end Base

end Other.ProjectiveChart
