import Other
import Lean.Util.CollectAxioms
import Lean.Elab.Command

/-!
Reproduce the axiom audit for the main handoff milestones with:

    lake env lean checks/AlgebraicHodgeHandoff.lean

The two requested final statements remain unproved; the checks below audit the
proved reductions, analytic comparisons, and explicit scheme constructions.
Each audit fails if a declaration transitively depends on any axiom beyond
`propext`, `Classical.choice`, and `Quot.sound`.
-/

open Lean Elab Command in
elab "audit_standard_axioms " n:ident : command => do
  let name ← liftCoreM <| Lean.Elab.realizeGlobalConstNoOverloadWithInfo n
  let axioms ← Lean.collectAxioms name
  let allowed := #[``propext, ``Classical.choice, ``Quot.sound]
  for ax in axioms do
    unless allowed.contains ax do
      throwError "{name} depends on unexpected axiom {ax}"
  logInfo m!"{name}: {axioms.toList}"

audit_standard_axioms AlgebraicGeometry.ComplexPoint.range_rationalSheafCycleClassOnCycles
audit_standard_axioms AlgebraicGeometry.ComplexPoint.algebraicCycleClassSpan_le_hodgeClasses_iff_filtered_lifts
audit_standard_axioms AlgebraicGeometry.ComplexPoint.algebraicCycleClassSpan_le_hodgeClasses_of_dimension_eq_zero
audit_standard_axioms AlgebraicGeometry.ComplexPoint.rationalExponentialClass_isHodge
audit_standard_axioms AlgebraicGeometry.ComplexPoint.isHodgeClass_one_iff
audit_standard_axioms AlgebraicGeometry.ComplexPoint.integralClass_isHodge_iff_exponential
audit_standard_axioms AlgebraicGeometry.ComplexPoint.analyticTransitionExtClass_eq_zero_iff
audit_standard_axioms AlgebraicGeometry.ComplexPoint.holomorphicTransitionUnitsClass_eq_zero_iff
audit_standard_axioms AlgebraicGeometry.ComplexPoint.rationalHolomorphicTransitionClass_changeTrivialization
audit_standard_axioms AlgebraicGeometry.ComplexPoint.holomorphicUnitLogarithmObstruction_eq_zero_iff
audit_standard_axioms AlgebraicGeometry.ComplexPoint.holomorphicUnitLogarithmObstruction_ne_zero_of_loop
audit_standard_axioms AlgebraicGeometry.ComplexPoint.holomorphicLogarithmTransition_class
audit_standard_axioms CategoryTheory.ShortComplex.comparisonCone_derived
audit_standard_axioms CategoryTheory.ShortComplex.comparisonTriangle_derived
audit_standard_axioms CategoryTheory.ShortComplex.comparisonExt_hom
audit_standard_axioms CategoryTheory.ShortComplex.comparisonExt
audit_standard_axioms Algebra.DeRham.kaehlerToForm_smul_D
audit_standard_axioms Algebra.DeRham.kaehlerToForm_map
audit_standard_axioms Algebra.DeRham.kaehlerWedge_smul_D_smul_D
audit_standard_axioms Algebra.DeRham.kaehlerWedge_map
audit_standard_axioms AlgebraicGeometry.ComplexPoint.contMDiffAt_evaluate
audit_standard_axioms AlgebraicGeometry.ComplexPoint.regularToHolomorphicAlgHom
audit_standard_axioms AlgebraicGeometry.ComplexPoint.regularFormToHolomorphicForm_restrict
audit_standard_axioms AlgebraicGeometry.ComplexPoint.regularFormToHolomorphicForm_differential
audit_standard_axioms AlgebraicGeometry.ComplexPoint.exponentialComparisonKernel_normalization
audit_standard_axioms AlgebraicGeometry.ComplexPoint.exponentialConnectingClass_comparison
audit_standard_axioms AlgebraicGeometry.ComplexPoint.exponentialConnectingClass_hypercohomology
audit_standard_axioms AlgebraicGeometry.ComplexPoint.rationalExponentialConnectingClass_scaled_deRham
audit_standard_axioms AlgebraicGeometry.ComplexPoint.rationalExponentialConnectingClass_eq_neg
audit_standard_axioms AlgebraicGeometry.ComplexPoint.rationalExponentialConnectingClass_isHodge
audit_standard_axioms AlgebraicGeometry.ComplexPoint.regularSectionPullback_restrict
audit_standard_axioms AlgebraicGeometry.ComplexPoint.regularSectionPullback_restrict_domain
audit_standard_axioms AlgebraicGeometry.ComplexPoint.holomorphicDeRham_toSheafify_injective
audit_standard_axioms AlgebraicGeometry.ComplexPoint.exists_not_isHodgeClass_iff
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceSegre_isClosedImmersion
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surface_isProjective
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveVariety
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceVariety
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveVariety_isIntegral
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceVariety_isIntegral
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveVariety_isProjective
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceVariety_isProjective
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveVariety_smooth
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceVariety_smooth
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveZDifferential_ne_zero
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveYDifferential_ne_zero
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveDifferential_overlap_on
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveDifferential_overlap
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveGlobalHolomorphicDifferential
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveGlobalHolomorphicDifferential_restrict_z
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveGlobalHolomorphicDifferential_restrict_y
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.evaluate_curveYCoordinate_infinity
audit_standard_axioms AlgebraicGeometry.ComplexPoint.exists_regularInLocalChart_fderiv_ne_zero
audit_standard_axioms AlgebraicGeometry.ComplexPoint.exists_generator_fderiv_ne_zero
audit_standard_axioms AlgebraicGeometry.ComplexPoint.holomorphicFormEvaluation_regular_mk_one
audit_standard_axioms AlgebraicGeometry.ComplexPoint.holomorphicFormEvaluation_regular_mk
audit_standard_axioms AlgebraicGeometry.ComplexPoint.holomorphicFormEvaluation_regular_kaehlerWedge_normalized
audit_standard_axioms AlgebraicGeometry.ComplexPoint.generator_fderiv_separates_tangent
audit_standard_axioms AlgebraicGeometry.ComplexPoint.wedgeCovectors_two_ne_zero_of_separates
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.fderiv_curveYCoordinateInLocalChart_zero_ne_zero
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.curveGlobalHolomorphicDifferential_ne_zero
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceDifferentialPullback_restrict_curve
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceDifferentialPullback_restrict
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceDifferentialPullback_overlap
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceGlobalHolomorphicTwoForm
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceGlobalHolomorphicTwoForm_restrict
audit_standard_axioms CommRingCat.subring_eq_top_of_isPushout
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceYChart_section_isPushout
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceYChart_isAffineOpen
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceYPolynomialMap_surjective
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceInfinity
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.evaluate_surfaceYCoordinate_infinity
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.fderiv_surfaceYCoordinateInLocalChart_one
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surface_u_derivatives_wedge_ne_zero
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceYHolomorphicTwoForm_evaluation
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceGlobalHolomorphicTwoForm_ne_zero
audit_standard_axioms AlgebraicGeometry.ComplexPoint.topHodgeFilteredComplexIsoSingle
audit_standard_axioms AlgebraicGeometry.ComplexPoint.topHolomorphicFormFilteredEquiv
audit_standard_axioms AlgebraicGeometry.ComplexPoint.topHolomorphicFormFilteredEquiv_ne_zero
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.dim_surface_eq_two
audit_standard_axioms AlgebraicGeometry.ExplicitEllipticCandidate.surfaceTopFilteredClass_ne_zero
