import Other.AlgebraicTopology.SingularSubdivisionCochainSheafComplex
#check AlgebraicTopology.Singular.HereditarilyParacompact.topOpenToGlobalSingularCochainSheafComplex_quasiIso_complex
#check AlgebraicTopology.Singular.topOpenToGlobalSingularCochainSheafComplex_quasiIso_complex
