import Other.AlgebraicGeometry.ExplicitEllipticGlobalOneForms
#check AlgebraicGeometry.ExplicitEllipticCandidate.exists_curveOneFormGlobalCoefficient
#check AlgebraicGeometry.ExplicitEllipticCandidate.curveGlobalOneForm_locally_functionMul
#check AlgebraicGeometry.ExplicitEllipticCandidate.curveGlobalHolomorphicDifferential_smul_injective
#check AlgebraicGeometry.ExplicitEllipticCandidate.existsUnique_curveGlobalOneForm_eq_smul
