import Other.AlgebraicGeometry.ExplicitEllipticGlobalOneForms
import Other.AlgebraicGeometry.ExplicitEllipticIntegrality

open AlgebraicGeometry
open AlgebraicGeometry.ExplicitEllipticCandidate

#synth ConnectedSpace (ComplexPoint curveAnalyticVariety)
