import Other.AlgebraicTopology.SingularProductDegreeOne
#check LinearMap.llcomp
#check LinearMap.llcomp_apply
#check LinearMap.compr₂
#check LinearMap.compRight
#check LinearMap.lsmul
#check LinearMap.flip
#check LinearMap.applyₗ
#check LinearMap.applyₗ_apply
#check LinearMap.llcomp
#check LinearMap.compl₂
#check LinearMap.mul
#check LinearMap.mul_apply
#check LinearMap.lmul
#check LinearMap.lsmul
#check LinearMap.flip
#check LinearMap.compr₂_apply
#check HomologicalComplex.Hom.comm
#check HomologicalComplex.Hom.comm'
#check SSet.chainComplexMap
#check SemiCartesianMonoidalCategory.fst
#check SemiCartesianMonoidalCategory.snd
#check HomologicalComplex.cyclesMk
#check HomologicalComplex.liftCycles
#check HomologicalComplex.homologyπ
#check ShortComplex.moduleCatHomologyClass
#check ShortComplex.moduleCatHomologyClass_surjective
